------------------------------------
-- DDL Statements for BUFFERPOOLS --
------------------------------------
CREATE BUFFERPOOL "BUFF8K" SIZE AUTOMATIC PAGESIZE 8192;
CREATE BUFFERPOOL "BUFF16K" SIZE AUTOMATIC PAGESIZE 16384;
CREATE BUFFERPOOL "BUFF32K" SIZE AUTOMATIC PAGESIZE 32768;
--------------------------
-- Mimic Storage groups --
--------------------------
ALTER STOGROUP "IBMSTOGROUP" DATA TAG NONE
SET AS DEFAULT;
------------------------------------
-- DDL Statements for TABLESPACES --
------------------------------------
CREATE REGULAR TABLESPACE "TAB8K" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 8192 MANAGED BY AUTOMATIC STORAGE USING STOGROUP "IBMSTOGROUP" AUTORESIZE YES INITIALSIZE 32 M MAXSIZE NONE EXTENTSIZE 32 PREFETCHSIZE AUTOMATIC BUFFERPOOL "BUFF8K" DATA TAG NONE OVERHEAD 7.500000 TRANSFERRATE 0.060000 DROPPED TABLE RECOVERY ON;
CREATE REGULAR TABLESPACE "TAB16K" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 16384 MANAGED BY AUTOMATIC STORAGE USING STOGROUP "IBMSTOGROUP" AUTORESIZE YES INITIALSIZE 32 M MAXSIZE NONE EXTENTSIZE 32 PREFETCHSIZE AUTOMATIC BUFFERPOOL "BUFF16K" DATA TAG NONE OVERHEAD 7.500000 TRANSFERRATE 0.060000 DROPPED TABLE RECOVERY ON;
CREATE TEMPORARY TABLESPACE "TEMPSYS8K" IN DATABASE PARTITION GROUP IBMTEMPGROUP PAGESIZE 8192 MANAGED BY AUTOMATIC STORAGE USING STOGROUP "IBMSTOGROUP" EXTENTSIZE 32 PREFETCHSIZE AUTOMATIC BUFFERPOOL "BUFF8K" OVERHEAD 7.500000 TRANSFERRATE 0.060000 FILE SYSTEM CACHING DROPPED TABLE RECOVERY OFF;
CREATE TEMPORARY TABLESPACE "TEMPSYS16K" IN DATABASE PARTITION GROUP IBMTEMPGROUP PAGESIZE 16384 MANAGED BY AUTOMATIC STORAGE USING STOGROUP "IBMSTOGROUP" EXTENTSIZE 32 PREFETCHSIZE AUTOMATIC BUFFERPOOL "BUFF16K" OVERHEAD 7.500000 TRANSFERRATE 0.060000 FILE SYSTEM CACHING DROPPED TABLE RECOVERY OFF;
CREATE TEMPORARY TABLESPACE "TEMPSYS32K" IN DATABASE PARTITION GROUP IBMTEMPGROUP PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE USING STOGROUP "IBMSTOGROUP" EXTENTSIZE 32 PREFETCHSIZE AUTOMATIC BUFFERPOOL "BUFF32K" OVERHEAD 7.500000 TRANSFERRATE 0.060000 FILE SYSTEM CACHING DROPPED TABLE RECOVERY OFF;
CREATE LARGE TABLESPACE "SYSTOOLSPACE" IN DATABASE PARTITION GROUP IBMCATGROUP PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE USING STOGROUP "IBMSTOGROUP" AUTORESIZE YES INITIALSIZE 32 M MAXSIZE NONE EXTENTSIZE 4 PREFETCHSIZE AUTOMATIC BUFFERPOOL "IBMDEFAULTBP" DATA TAG NONE OVERHEAD 7.500000 TRANSFERRATE 0.060000 DROPPED TABLE RECOVERY ON;
CREATE USER TEMPORARY TABLESPACE "SYSTOOLSTMPSPACE" IN DATABASE PARTITION GROUP IBMCATGROUP PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE USING STOGROUP "IBMSTOGROUP" EXTENTSIZE 4 PREFETCHSIZE AUTOMATIC BUFFERPOOL "IBMDEFAULTBP" OVERHEAD 7.500000 TRANSFERRATE 0.060000 FILE SYSTEM CACHING DROPPED TABLE RECOVERY OFF;
----------------------
-- Mimic tablespace --
----------------------
ALTER TABLESPACE "SYSCATSPACE" PREFETCHSIZE AUTOMATIC OVERHEAD 7.500000 AUTORESIZE YES MAXSIZE NONE TRANSFERRATE 0.060000;
ALTER TABLESPACE "SYSCATSPACE" USING STOGROUP "IBMSTOGROUP";
ALTER TABLESPACE "TEMPSPACE1" PREFETCHSIZE AUTOMATIC OVERHEAD 7.500000 FILE SYSTEM CACHING TRANSFERRATE 0.060000;
ALTER TABLESPACE "USERSPACE1" PREFETCHSIZE AUTOMATIC OVERHEAD 7.500000 AUTORESIZE YES MAXSIZE NONE TRANSFERRATE 0.060000 DATA TAG NONE;
ALTER TABLESPACE "USERSPACE1" USING STOGROUP "IBMSTOGROUP";
------------------------------------------------
-- DDL Statements for Roles
------------------------------------------------
CREATE ROLE "WCSOWNER_SELECT_ROLE";
CREATE ROLE "WCSOWNER_UPDATE_ROLE";
CREATE ROLE "CREATE_TABLE_ROLE";
CREATE ROLE "DMOWNER_EXECUTE_ROLE";
CREATE ROLE "DMOWNER_SELECT_ROLE";
CREATE ROLE "DMOWNER_UPDATE_ROLE";
CREATE ROLE "DM_SCM_ROLE";
CREATE ROLE "DM_SUPPORT_ROLE";
CREATE ROLE "SELECT_CATALOG_ROLE";
------------------------------------------------
-- DDL Statements for Schemas
------------------------------------------------
CREATE SCHEMA "COLOWNER" AUTHORIZATION "DB2ADMIN";
CREATE SCHEMA "DBA     " AUTHORIZATION "DBPCSA  ";
CREATE SCHEMA "DSWEB   " AUTHORIZATION "DB2ADMIN";
CREATE SCHEMA "OPM     " AUTHORIZATION "DB2ADMIN";
CREATE SCHEMA "DMOWNER " AUTHORIZATION "DB2ADMIN";
CREATE SCHEMA "VCW_DEMO" AUTHORIZATION "DB2ADMIN";
------------------------------------------------
-- DDL Statements for Schemas
------------------------------------------------
-- Running the DDL below will explicitly create a schema in the
-- new database that corresponds to an implicitly created schema
-- in the original database.
CREATE SCHEMA "NULLIDR1";
CREATE SCHEMA "NULLIDRA";
CREATE SCHEMA "DB2ADMIN";
CREATE SCHEMA "ADMINISTRATOR";
CREATE SCHEMA "CGTT    ";
CREATE SCHEMA "WCSOWNER";
---------------------------------------------------------------
-- DDL Statements for Distinct Types and/or Abstract Data Types
-- DDL Statements for Associative Array Types
-- DDL Statements for Row Types
-- DDL Statements for Cursor Types
---------------------------------------------------------------
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "DB2ADMIN"."BIGINTARRAY" AS BIGINT ARRAY [50];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "DB2ADMIN"."CHARARRAY" AS CHARACTER(10 OCTETS) ARRAY [VARCHAR(3 OCTETS)];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "DB2ADMIN"."STRING_ARRAY" AS VARCHAR(256 OCTETS) ARRAY [1000];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "DB2ADMIN"."INT_ARRAY" AS INTEGER ARRAY [1000];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "DB2ADMIN"."TIME_ARRAY" AS TIMESTAMP ARRAY [1000];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "DB2ADMIN"."BIGINT_ARRAY" AS BIGINT ARRAY [1000];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "DB2ADMIN"."DOUBLE_ARRAY" AS DOUBLE ARRAY [1000];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "DB2ADMIN"."SMALLINT_ARRAY" AS SMALLINT ARRAY [1000];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "COLOWNER"."STRING_ARRAY" AS VARCHAR(256 OCTETS) ARRAY [1000];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "COLOWNER"."INT_ARRAY" AS INTEGER ARRAY [1000];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "COLOWNER"."TIME_ARRAY" AS TIMESTAMP ARRAY [1000];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "COLOWNER"."BIGINT_ARRAY" AS BIGINT ARRAY [1000];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "COLOWNER"."DOUBLE_ARRAY" AS DOUBLE ARRAY [1000];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "COLOWNER"."SMALLINT_ARRAY" AS SMALLINT ARRAY [1000];
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE TYPE "DB2ADMIN"."STRINGARRAY" AS CHARACTER(1 OCTETS) ARRAY [100];