------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATCHAST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATCHAST" (
	"ATCHAST_ID" BIGINT NOT NULL,
	"STOREENT_ID" INTEGER NOT NULL WITH DEFAULT 0,
	"ATCHTGT_ID" BIGINT NOT NULL,
	"ATCHASTPATH" VARCHAR(256 OCTETS),
	"DIRECTORYPATH" VARCHAR(128 OCTETS),
	"MIMETYPE" VARCHAR(254 OCTETS),
	"MIMETYPEENCODING" VARCHAR(128 OCTETS),
	"TIMECREATED" TIMESTAMP,
	"TIMEUPDATED" TIMESTAMP,
	"IMAGE1" VARCHAR(254 OCTETS),
	"IMAGE2" VARCHAR(254 OCTETS),
	"OPTCOUNTER" SMALLINT,
	"UP_ATCHASTPATH" VARCHAR(256 OCTETS) GENERATED ALWAYS AS (UPPER(ATCHASTPATH))
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATCHAST"
ALTER TABLE "DB2ADMIN"."ATCHAST"
ADD PRIMARY KEY ("ATCHAST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHAST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000856" ON "DB2ADMIN"."ATCHAST" (
	"STOREENT_ID" ASC,
	"ATCHTGT_ID" ASC,
	"ATCHASTPATH" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHAST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000857" ON "DB2ADMIN"."ATCHAST" ("STOREENT_ID" ASC, "DIRECTORYPATH" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHAST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000867" ON "DB2ADMIN"."ATCHAST" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHAST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000868" ON "DB2ADMIN"."ATCHAST" ("ATCHTGT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHAST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00017" ON "DB2ADMIN"."ATCHAST" ("UP_ATCHASTPATH" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATCHASTLG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATCHASTLG" (
	"ATCHASTLG_ID" BIGINT NOT NULL,
	"ATCHAST_ID" BIGINT NOT NULL,
	"LANGUAGE_ID" INTEGER,
	"OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATCHASTLG"
ALTER TABLE "DB2ADMIN"."ATCHASTLG"
ADD PRIMARY KEY ("ATCHASTLG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHASTLG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000859" ON "DB2ADMIN"."ATCHASTLG" ("ATCHAST_ID" ASC, "LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHASTLG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000871" ON "DB2ADMIN"."ATCHASTLG" ("ATCHAST_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHASTLG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000872" ON "DB2ADMIN"."ATCHASTLG" ("LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATCHOBJTYP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATCHOBJTYP" (
	"ATCHOBJTYP_ID" INTEGER NOT NULL,
	"IDENTIFIER" CHAR(32 OCTETS) NOT NULL,
	"SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
	"DESCRIPTION" VARCHAR(254 OCTETS),
	"OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATCHOBJTYP"
ALTER TABLE "DB2ADMIN"."ATCHOBJTYP"
ADD PRIMARY KEY ("ATCHOBJTYP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHOBJTYP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000853" ON "DB2ADMIN"."ATCHOBJTYP" ("IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATCHREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATCHREL" (
	"ATCHREL_ID" BIGINT NOT NULL,
	"OBJECT_ID" CHAR(64 OCTETS) NOT NULL,
	"ATCHOBJTYP_ID" INTEGER NOT NULL,
	"ATCHTGT_ID" BIGINT NOT NULL,
	"ATCHRLUS_ID" INTEGER NOT NULL,
	"LASTUPDATE" TIMESTAMP,
	"SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
	"BIGINTOBJECT_ID" BIGINT,
	"OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATCHREL"
ALTER TABLE "DB2ADMIN"."ATCHREL"
ADD PRIMARY KEY ("ATCHREL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000860" ON "DB2ADMIN"."ATCHREL" (
	"ATCHOBJTYP_ID" ASC,
	"OBJECT_ID" ASC,
	"ATCHRLUS_ID" ASC,
	"ATCHTGT_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000873" ON "DB2ADMIN"."ATCHREL" ("ATCHOBJTYP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000874" ON "DB2ADMIN"."ATCHREL" ("ATCHTGT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000877" ON "DB2ADMIN"."ATCHREL" ("ATCHRLUS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001207" ON "DB2ADMIN"."ATCHREL" ("BIGINTOBJECT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATCHRELDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATCHRELDSC" (
	"ATCHRELDSC_ID" BIGINT NOT NULL,
	"ATCHREL_ID" BIGINT NOT NULL,
	"LANGUAGE_ID" INTEGER NOT NULL,
	"NAME" VARCHAR(128 OCTETS),
	"SHORTDESCRIPTION" VARCHAR(254 OCTETS),
	"LONGDESCRIPTION" VARCHAR(4000 OCTETS),
	"OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATCHRELDSC"
ALTER TABLE "DB2ADMIN"."ATCHRELDSC"
ADD PRIMARY KEY ("ATCHRELDSC_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHRELDSC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000861" ON "DB2ADMIN"."ATCHRELDSC" ("ATCHREL_ID" ASC, "LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHRELDSC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000875" ON "DB2ADMIN"."ATCHRELDSC" ("ATCHREL_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHRELDSC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000876" ON "DB2ADMIN"."ATCHRELDSC" ("LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATCHRLUS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATCHRLUS" (
	"ATCHRLUS_ID" INTEGER NOT NULL,
	"IDENTIFIER" VARCHAR(254 OCTETS),
	"IMAGE" VARCHAR(254 OCTETS),
	"SEQUENCE" DOUBLE,
	"OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATCHRLUS"
ALTER TABLE "DB2ADMIN"."ATCHRLUS"
ADD PRIMARY KEY ("ATCHRLUS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHRLUS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000878" ON "DB2ADMIN"."ATCHRLUS" ("IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATCHRLUSDS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATCHRLUSDS" (
	"ATCHRLUSDS_ID" INTEGER NOT NULL,
	"ATCHRLUS_ID" INTEGER NOT NULL,
	"LANGUAGE_ID" INTEGER NOT NULL,
	"NAME" VARCHAR(128 OCTETS),
	"SHORTDESCRIPTION" VARCHAR(254 OCTETS),
	"LONGDESCRIPTION" VARCHAR(4000 OCTETS),
	"OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATCHRLUSDS"
ALTER TABLE "DB2ADMIN"."ATCHRLUSDS"
ADD PRIMARY KEY ("ATCHRLUSDS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHRLUSDS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000879" ON "DB2ADMIN"."ATCHRLUSDS" ("ATCHRLUS_ID" ASC, "LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATCHTGT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATCHTGT" (
	"ATCHTGT_ID" BIGINT NOT NULL,
	"STOREENT_ID" INTEGER NOT NULL WITH DEFAULT 0,
	"MEMBER_ID" BIGINT NOT NULL,
	"IDENTIFIER" VARCHAR(128 OCTETS) NOT NULL,
	"ATTACHUSG_ID" CHAR(64 OCTETS),
	"MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
	"FIELD1" BIGINT,
	"FIELD2" DOUBLE,
	"FIELD3" VARCHAR(254 OCTETS),
	"FIELD4" VARCHAR(254 OCTETS),
	"OPTCOUNTER" SMALLINT,
	"UP_IDENTIFIER" VARCHAR(128 OCTETS) GENERATED ALWAYS AS (UPPER(IDENTIFIER))
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATCHTGT"
ALTER TABLE "DB2ADMIN"."ATCHTGT"
ADD PRIMARY KEY ("ATCHTGT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHTGT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000854" ON "DB2ADMIN"."ATCHTGT" (
	"STOREENT_ID" ASC,
	"MEMBER_ID" ASC,
	"IDENTIFIER" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHTGT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000862" ON "DB2ADMIN"."ATCHTGT" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHTGT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000863" ON "DB2ADMIN"."ATCHTGT" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHTGT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000864" ON "DB2ADMIN"."ATCHTGT" ("ATTACHUSG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHTGT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00018" ON "DB2ADMIN"."ATCHTGT" ("UP_IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATCHTGTDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATCHTGTDSC" (
	"ATCHTGTDSC_ID" BIGINT NOT NULL,
	"ATCHTGT_ID" BIGINT NOT NULL,
	"LANGUAGE_ID" INTEGER NOT NULL,
	"NAME" VARCHAR(128 OCTETS),
	"SHORTDESCRIPTION" VARCHAR(254 OCTETS),
	"LONGDESCRIPTION" VARCHAR(4000 OCTETS),
	"OPTCOUNTER" SMALLINT,
	"UP_NAME" VARCHAR(128 OCTETS) GENERATED ALWAYS AS (UPPER(NAME))
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATCHTGTDSC"
ALTER TABLE "DB2ADMIN"."ATCHTGTDSC"
ADD PRIMARY KEY ("ATCHTGTDSC_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHTGTDSC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000855" ON "DB2ADMIN"."ATCHTGTDSC" ("ATCHTGT_ID" ASC, "LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHTGTDSC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000865" ON "DB2ADMIN"."ATCHTGTDSC" ("ATCHTGT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHTGTDSC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000866" ON "DB2ADMIN"."ATCHTGTDSC" ("LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHTGTDSC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001208" ON "DB2ADMIN"."ATCHTGTDSC" ("NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATCHTGTDSC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00019" ON "DB2ADMIN"."ATCHTGTDSC" ("UP_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTACHMENT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTACHMENT" (
	"ATTACHMENT_ID" BIGINT NOT NULL,
	"ATTACHMENTURL" VARCHAR(254 OCTETS) NOT NULL,
	"MEMBER_ID" BIGINT NOT NULL,
	"ATTACHUSG_ID" CHAR(64 OCTETS),
	"MIMETYPE" VARCHAR(254 OCTETS),
	"MIMETYPEENCODING" VARCHAR(128 OCTETS),
	"TIMECREATED" TIMESTAMP,
	"TIMEUPDATED" TIMESTAMP,
	"MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
	"DESCRIPTION" VARCHAR(254 OCTETS),
	"FILENAME" VARCHAR(254 OCTETS),
	"FILESIZE" BIGINT,
	"CREATEMETHOD" INTEGER WITH DEFAULT 0,
	"IMAGE1" VARCHAR(254 OCTETS),
	"IMAGE2" VARCHAR(254 OCTETS),
	"CONTENT" BLOB(10000000) LOGGED NOT COMPACT,
	"RESERVED" VARCHAR(254 OCTETS),
	"OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTACHMENT"
ALTER TABLE "DB2ADMIN"."ATTACHMENT"
ADD PRIMARY KEY ("ATTACHMENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTACHMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000017" ON "DB2ADMIN"."ATTACHMENT" ("ATTACHMENTURL" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTACHMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000290" ON "DB2ADMIN"."ATTACHMENT" ("ATTACHUSG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTACHMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000452" ON "DB2ADMIN"."ATTACHMENT" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTACHUSG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTACHUSG" (
	"ATTACHUSG_ID" CHAR(64 OCTETS) NOT NULL,
	"OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTACHUSG"
ALTER TABLE "DB2ADMIN"."ATTACHUSG"
ADD PRIMARY KEY ("ATTACHUSG_ID");
---