------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMBITEMS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMBITEMS" (
    "CBMRFNBR" INTEGER NOT NULL,
    "CBTRFNBR" INTEGER,
    "CBINTVALUE" INTEGER,
    "CBCURVALUE" DECIMAL(20, 5),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMBITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000074" ON "DB2ADMIN"."CMBITEMS" ("CBMRFNBR" ASC, "CBTRFNBR" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMDREG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMDREG" (
    "STOREENT_ID" INTEGER NOT NULL,
    "INTERFACENAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "CLASSNAME" VARCHAR(254 OCTETS),
    "PROPERTIES" VARCHAR(254 OCTETS),
    "LASTUPDATE" TIMESTAMP,
    "TARGET" CHAR(16 OCTETS) WITH DEFAULT 'Local',
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMDREG"
ALTER TABLE "DB2ADMIN"."CMDREG"
ADD PRIMARY KEY ("STOREENT_ID", "INTERFACENAME");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMFILE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMFILE" (
    "CMFILE_ID" BIGINT NOT NULL,
    "CMFILEPATH" VARCHAR(254 OCTETS) NOT NULL,
    "PROMOTE_FS" SMALLINT NOT NULL WITH DEFAULT 0,
    "UPLOAD_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT,
    "PROMOTE_TIMESTAMP" TIMESTAMP,
    "ASSOCIATED" SMALLINT NOT NULL WITH DEFAULT 0,
    "STORAGE_TYPE" SMALLINT NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "CMFILEDIR_ID" BIGINT NOT NULL,
    "FILESIZE" BIGINT WITH DEFAULT 0,
    "PUBLISHED" SMALLINT NOT NULL WITH DEFAULT 0,
    "UP_CMFILEPATH" VARCHAR(254 OCTETS) GENERATED ALWAYS AS (UPPER(CMFILEPATH))
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMFILE"
ALTER TABLE "DB2ADMIN"."CMFILE"
ADD PRIMARY KEY ("CMFILE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFILE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000897" ON "DB2ADMIN"."CMFILE" ("CMFILEPATH" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFILE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000934" ON "DB2ADMIN"."CMFILE" ("CMFILEDIR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFILE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00024" ON "DB2ADMIN"."CMFILE" ("UP_CMFILEPATH" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMFILEDIR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMFILEDIR" (
    "CMFILEDIR_ID" BIGINT NOT NULL,
    "CMFILEDIR_PARENT" BIGINT,
    "IDENTIFIER" VARCHAR(100 OCTETS) NOT NULL,
    "DISPLAYNAME" VARCHAR(100 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMFILEDIR"
ALTER TABLE "DB2ADMIN"."CMFILEDIR"
ADD PRIMARY KEY ("CMFILEDIR_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFILEDIR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000931" ON "DB2ADMIN"."CMFILEDIR" ("CMFILEDIR_PARENT" ASC, "IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMFTASK"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMFTASK" (
    "CMFTASK_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(254 OCTETS),
    "USAGE" INTEGER,
    "DUEDATE" TIMESTAMP,
    "COMPLETEDATE" TIMESTAMP,
    "STATUS" INTEGER NOT NULL WITH DEFAULT 0,
    "TEMPLATETYPE" INTEGER NOT NULL WITH DEFAULT 0,
    "TYPE" INTEGER NOT NULL WITH DEFAULT 1,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMFTASK"
ALTER TABLE "DB2ADMIN"."CMFTASK"
ADD PRIMARY KEY ("CMFTASK_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFTASK"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000885" ON "DB2ADMIN"."CMFTASK" ("IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFTASK"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000886" ON "DB2ADMIN"."CMFTASK" ("STATUS" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFTASK"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000887" ON "DB2ADMIN"."CMFTASK" ("TYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMFTASKDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMFTASKDSC" (
    "CMFTASK_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS),
    "DESCRIPTION" VARCHAR(4000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMFTASKDSC"
ALTER TABLE "DB2ADMIN"."CMFTASKDSC"
ADD PRIMARY KEY ("CMFTASK_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMFTASKGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMFTASKGRP" (
    "CMFTASKGRP_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(254 OCTETS),
    "STATUS" INTEGER NOT NULL WITH DEFAULT 0,
    "APPROVEDATE" TIMESTAMP,
    "DUEDATE" TIMESTAMP,
    "PROMOTIONDATE" TIMESTAMP,
    "PERSISTENTYPE" INTEGER NOT NULL WITH DEFAULT 0,
    "TEMPLATETYPE" INTEGER NOT NULL WITH DEFAULT 0,
    "QUICKPUBLISHTYPE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT,
    "COMMITDATE" TIMESTAMP
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMFTASKGRP"
ALTER TABLE "DB2ADMIN"."CMFTASKGRP"
ADD PRIMARY KEY ("CMFTASKGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFTASKGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000882" ON "DB2ADMIN"."CMFTASKGRP" ("IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFTASKGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000883" ON "DB2ADMIN"."CMFTASKGRP" ("STATUS" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFTASKGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000884" ON "DB2ADMIN"."CMFTASKGRP" ("TEMPLATETYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMFTGCMT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMFTGCMT" (
    "CMFTGCMT_ID" BIGINT NOT NULL,
    "CMFTASKGRP_ID" BIGINT NOT NULL,
    "POSTEDDATE" TIMESTAMP,
    "MEMBER_ID" BIGINT NOT NULL,
    "COMMENTS" VARCHAR(4000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMFTGCMT"
ALTER TABLE "DB2ADMIN"."CMFTGCMT"
ADD PRIMARY KEY ("CMFTGCMT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFTGCMT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000890" ON "DB2ADMIN"."CMFTGCMT" ("CMFTASKGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFTGCMT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000891" ON "DB2ADMIN"."CMFTGCMT" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMFTGDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMFTGDSC" (
    "CMFTASKGRP_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS),
    "DESCRIPTION" VARCHAR(4000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMFTGDSC"
ALTER TABLE "DB2ADMIN"."CMFTGDSC"
ADD PRIMARY KEY ("CMFTASKGRP_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMFTGTSKREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMFTGTSKREL" (
    "CMFTASK_ID" BIGINT NOT NULL,
    "CMFTASKGRP_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMFTGTSKREL"
ALTER TABLE "DB2ADMIN"."CMFTGTSKREL"
ADD PRIMARY KEY ("CMFTASK_ID", "CMFTASKGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFTGTSKREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001441" ON "DB2ADMIN"."CMFTGTSKREL" ("CMFTASKGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMFTSKMBREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMFTSKMBREL" (
    "CMFTASK_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMFTSKMBREL"
ALTER TABLE "DB2ADMIN"."CMFTSKMBREL"
ADD PRIMARY KEY ("CMFTASK_ID", "MEMBER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFTSKMBREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000888" ON "DB2ADMIN"."CMFTSKMBREL" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMFWKSPC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMFWKSPC" (
    "CMFWKSPC_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(254 OCTETS),
    "STATUS" INTEGER NOT NULL WITH DEFAULT 1,
    "MEMBER_ID" BIGINT NOT NULL,
    "PERSISTENTYPE" INTEGER NOT NULL WITH DEFAULT 0,
    "LOCKINGPOLICY" INTEGER NOT NULL WITH DEFAULT 0,
    "PROMOTIONPOLICY" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMFWKSPC"
ALTER TABLE "DB2ADMIN"."CMFWKSPC"
ADD PRIMARY KEY ("CMFWKSPC_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFWKSPC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000880" ON "DB2ADMIN"."CMFWKSPC" ("IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFWKSPC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000881" ON "DB2ADMIN"."CMFWKSPC" ("STATUS" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFWKSPC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000889" ON "DB2ADMIN"."CMFWKSPC" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMFWKSPCDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMFWKSPCDSC" (
    "CMFWKSPC_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS),
    "DESCRIPTION" VARCHAR(4000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMFWKSPCDSC"
ALTER TABLE "DB2ADMIN"."CMFWKSPCDSC"
ADD PRIMARY KEY ("CMFWKSPC_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMFWSTGREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMFWSTGREL" (
    "CMFWKSPC_ID" BIGINT NOT NULL,
    "CMFTASKGRP_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMFWSTGREL"
ALTER TABLE "DB2ADMIN"."CMFWSTGREL"
ADD PRIMARY KEY ("CMFWKSPC_ID", "CMFTASKGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMFWSTGREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001442" ON "DB2ADMIN"."CMFWSTGREL" ("CMFTASKGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMLARGEFILE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMLARGEFILE" (
    "CMFILE_ID" BIGINT NOT NULL,
    "CONTENT_WORKSPACE" CHAR(25 OCTETS),
    "CMFILE" BLOB(300000000) LOGGED NOT COMPACT,
    "CONTENT_OLD_WKSP" CHAR(25 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMLARGEFILE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000429" ON "DB2ADMIN"."CMLARGEFILE" ("CMFILE_ID" ASC, "CONTENT_WORKSPACE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMMETADATA"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMMETADATA" (
    "CMCONTAINER_ID" INTEGER NOT NULL,
    "CMRESMGR_ID" INTEGER NOT NULL,
    "BOKEY1" BIGINT NOT NULL,
    "BOKEY2" BIGINT NOT NULL,
    "BOKEY3" BIGINT NOT NULL,
    "BOKEY4" BIGINT NOT NULL,
    "ACTION" CHAR(1 OCTETS) NOT NULL,
    "CMTIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT,
    "WORKSPACE" CHAR(25 OCTETS),
    "TASKGRP" CHAR(25 OCTETS),
    "TASK" CHAR(25 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "MEMBER_ID" BIGINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMMETADATA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000835" ON "DB2ADMIN"."CMMETADATA" (
    "CMCONTAINER_ID" ASC,
    "CMRESMGR_ID" ASC,
    "BOKEY1" ASC,
    "BOKEY2" ASC,
    "BOKEY3" ASC,
    "BOKEY4" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMSMALLFILE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMSMALLFILE" (
    "CMFILE_ID" BIGINT NOT NULL,
    "CONTENT_WORKSPACE" CHAR(25 OCTETS),
    "CMFILE" BLOB(32000) LOGGED NOT COMPACT,
    "CONTENT_OLD_WKSP" CHAR(25 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMSMALLFILE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000428" ON "DB2ADMIN"."CMSMALLFILE" ("CMFILE_ID" ASC, "CONTENT_WORKSPACE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMWORKSPACE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMWORKSPACE" (
    "WORKSPACE" CHAR(25 OCTETS) NOT NULL,
    "LOCKING_POLICY" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMWORKSPACE"
ALTER TABLE "DB2ADMIN"."CMWORKSPACE"
ADD PRIMARY KEY ("WORKSPACE");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CMWSSCHEMA"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CMWSSCHEMA" (
    "CMWSSCHEMA_ID" INTEGER NOT NULL,
    "BASESCHEMA" CHAR(30 OCTETS) NOT NULL,
    "WRITESCHEMA" CHAR(30 OCTETS) NOT NULL,
    "READSCHEMA" CHAR(30 OCTETS) NOT NULL,
    "WORKSPACE" CHAR(25 OCTETS),
    "ALLOCATED" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "SYNCREQUIRED" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CMWSSCHEMA"
ALTER TABLE "DB2ADMIN"."CMWSSCHEMA"
ADD PRIMARY KEY ("CMWSSCHEMA_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CMWSSCHEMA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000834" ON "DB2ADMIN"."CMWSSCHEMA" ("WORKSPACE" ASC, "ALLOCATED" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CNTRDISPLY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CNTRDISPLY" (
    "DEVICEFMT_ID" INTEGER NOT NULL,
    "CNTRDISPLY_ID" BIGINT NOT NULL,
    "CONTRACT_ID" BIGINT,
    "PARTROLE_ID" INTEGER,
    "DISPLAYPAGENAME" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CNTRDISPLY"
ALTER TABLE "DB2ADMIN"."CNTRDISPLY"
ADD PRIMARY KEY ("CNTRDISPLY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CNTRDISPLY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000075" ON "DB2ADMIN"."CNTRDISPLY" (
    "CONTRACT_ID" ASC,
    "DEVICEFMT_ID" ASC,
    "PARTROLE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CNTRNAME"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CNTRNAME" (
    "NAME" VARCHAR(200 OCTETS) NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "ORIGIN" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CNTRNAME"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000076" ON "DB2ADMIN"."CNTRNAME" ("NAME" ASC, "MEMBER_ID" ASC, "ORIGIN" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CNTRNAME"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000537" ON "DB2ADMIN"."CNTRNAME" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CNTRSTORE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CNTRSTORE" (
    "CONTRACT_ID" BIGINT NOT NULL,
    "STOREXML" CLOB(1000000 OCTETS) LOGGED NOT COMPACT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CNTRSTORE"
ALTER TABLE "DB2ADMIN"."CNTRSTORE"
ADD PRIMARY KEY ("CONTRACT_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."COLLABWS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."COLLABWS" (
    "COLLABWS_ID" CHAR(32 OCTETS) NOT NULL,
    "PROCTYPE" VARCHAR(64 OCTETS),
    "PROCID" VARCHAR(64 OCTETS),
    "CREATORLOGONID" VARCHAR(254 OCTETS) NOT NULL,
    "NAME" VARCHAR(254 OCTETS),
    "DESCRIPTION" VARCHAR(1000 OCTETS),
    "TEMPLATE" VARCHAR(64 OCTETS),
    "TIMECREATED" TIMESTAMP,
    "ACCOUNT_ID" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."COLLABWS"
ALTER TABLE "DB2ADMIN"."COLLABWS"
ADD PRIMARY KEY ("COLLABWS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."COLLABWS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000538" ON "DB2ADMIN"."COLLABWS" ("ACCOUNT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."COLLATERAL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."COLLATERAL" (
    "COLLATERAL_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "COLLTYPE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(256 OCTETS),
    "URL" VARCHAR(1024 OCTETS),
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "UP_NAME" VARCHAR(256 OCTETS) GENERATED ALWAYS AS (UPPER(NAME)),
    "BEHAVIOR" SMALLINT NOT NULL WITH DEFAULT 0,
    "UIDISPLAYABLE" SMALLINT,
    "MANAGINGTOOL" SMALLINT,
    "OVRMKTLIMIT" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."COLLATERAL"
ALTER TABLE "DB2ADMIN"."COLLATERAL"
ADD PRIMARY KEY ("COLLATERAL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."COLLATERAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000077" ON "DB2ADMIN"."COLLATERAL" ("NAME" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."COLLATERAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000312" ON "DB2ADMIN"."COLLATERAL" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."COLLATERAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00008" ON "DB2ADMIN"."COLLATERAL" ("UP_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."COLLDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."COLLDESC" (
    "COLLATERAL_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "LOCATION" VARCHAR(254 OCTETS),
    "MARKETINGTEXT" VARCHAR(4000 OCTETS),
    "LONGMKTGTEXT" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."COLLDESC"
ALTER TABLE "DB2ADMIN"."COLLDESC"
ADD PRIMARY KEY ("LANGUAGE_ID", "COLLATERAL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."COLLDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001249" ON "DB2ADMIN"."COLLDESC" ("COLLATERAL_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."COLLTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."COLLTYPE" (
    "COLLTYPE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."COLLTYPE"
ALTER TABLE "DB2ADMIN"."COLLTYPE"
ADD PRIMARY KEY ("COLLTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CONTRACT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CONTRACT" (
    "CONTRACT_ID" BIGINT NOT NULL,
    "MAJORVERSION" INTEGER NOT NULL WITH DEFAULT 1,
    "MINORVERSION" INTEGER NOT NULL WITH DEFAULT 0,
    "NAME" VARCHAR(200 OCTETS) NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "ORIGIN" INTEGER NOT NULL WITH DEFAULT 0,
    "STATE" INTEGER NOT NULL WITH DEFAULT 0,
    "USAGE" INTEGER NOT NULL WITH DEFAULT 0,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "COMMENTS" VARCHAR(4000 OCTETS),
    "TIMECREATED" TIMESTAMP,
    "TIMEUPDATED" TIMESTAMP,
    "TIMEAPPROVED" TIMESTAMP,
    "TIMEACTIVATED" TIMESTAMP,
    "TIMEDEPLOYED" TIMESTAMP,
    "FAMILY_ID" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CONTRACT"
ALTER TABLE "DB2ADMIN"."CONTRACT"
ADD PRIMARY KEY ("CONTRACT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CONTRACT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000078" ON "DB2ADMIN"."CONTRACT" (
    "NAME" ASC,
    "MEMBER_ID" ASC,
    "MAJORVERSION" ASC,
    "MINORVERSION" ASC,
    "ORIGIN" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CONTRACT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000539" ON "DB2ADMIN"."CONTRACT" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CONTRACT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001510" ON "DB2ADMIN"."CONTRACT" ("FAMILY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CONTRLRULE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CONTRLRULE" (
    "RULE_ID" BIGINT NOT NULL,
    "OWNER_ID" BIGINT NOT NULL,
    "CLASS_ID" BIGINT NOT NULL,
    "ADMIN_ID" BIGINT,
    "RULETYPE" CHAR(4 OCTETS) NOT NULL,
    "RULENAME" CHAR(30 OCTETS) NOT NULL,
    "RULEDESC" VARCHAR(254 OCTETS),
    "MINQUANT" DOUBLE,
    "MINVALUE" DECIMAL(20, 5),
    "RULETEXT" VARCHAR(4000 OCTETS),
    "FIELD1" BIGINT,
    "FIELD2" DECIMAL(20, 5),
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CONTRLRULE"
ALTER TABLE "DB2ADMIN"."CONTRLRULE"
ADD PRIMARY KEY ("RULE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CONTRLRULE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000080" ON "DB2ADMIN"."CONTRLRULE" ("RULENAME" ASC, "OWNER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CONTRLRULE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000081" ON "DB2ADMIN"."CONTRLRULE" ("RULETYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CONTRLRULE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000540" ON "DB2ADMIN"."CONTRLRULE" ("ADMIN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CONTRLRULE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000541" ON "DB2ADMIN"."CONTRLRULE" ("OWNER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CONTRLRULE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001250" ON "DB2ADMIN"."CONTRLRULE" ("CLASS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."COUNTCODE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."COUNTCODE" (
    "PRODUCTVENDOR" VARCHAR(64 OCTETS) NOT NULL,
    "COUNTRYABBR" CHAR(5 OCTETS) NOT NULL,
    "COUNTRYCODE" CHAR(5 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."COUNTCODE"
ALTER TABLE "DB2ADMIN"."COUNTCODE"
ADD PRIMARY KEY ("PRODUCTVENDOR", "COUNTRYABBR");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."COUNTRY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."COUNTRY" (
    "COUNTRYABBR" CHAR(5 OCTETS) NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS),
    "CALLINGCODE" VARCHAR(16 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."COUNTRY"
ALTER TABLE "DB2ADMIN"."COUNTRY"
ADD PRIMARY KEY ("COUNTRYABBR", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."COUNTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000342" ON "DB2ADMIN"."COUNTRY" ("LANGUAGE_ID" ASC, "NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."COUNTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000343" ON "DB2ADMIN"."COUNTRY" ("NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPEMAILMAP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPEMAILMAP" (
    "CPWALLET_ID" BIGINT NOT NULL,
    "SHOPPEREMAILID" CHAR(64 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPEMAILMAP"
ALTER TABLE "DB2ADMIN"."CPEMAILMAP"
ADD PRIMARY KEY ("CPWALLET_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPEMAILMAP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000276" ON "DB2ADMIN"."CPEMAILMAP" ("SHOPPEREMAILID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPENDORDER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPENDORDER" (
    "STOREENT_ID" INTEGER NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPENDORDER"
ALTER TABLE "DB2ADMIN"."CPENDORDER"
ADD PRIMARY KEY ("ORDERS_ID", "MEMBER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPENDORDER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I168207" ON "DB2ADMIN"."CPENDORDER" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPENDORDER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000542" ON "DB2ADMIN"."CPENDORDER" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPGNLOG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPGNLOG" (
    "USRTRAFFIC_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "MPE_ID" INTEGER NOT NULL,
    "MPETYPE_ID" INTEGER,
    "MPENAME" VARCHAR(64 OCTETS),
    "INITIATIVE_ID" INTEGER NOT NULL,
    "MPETYPENAME" VARCHAR(64 OCTETS),
    "CAMPAIGN_ID" INTEGER,
    "SHOPSEGMENTS" VARCHAR(254 OCTETS),
    "RESULTS" VARCHAR(254 OCTETS),
    "INITIATIVENAME" VARCHAR(64 OCTETS),
    "CAMPAIGNNAME" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPGNLOG"
ALTER TABLE "DB2ADMIN"."CPGNLOG"
ADD PRIMARY KEY ("USRTRAFFIC_ID", "MPE_ID", "INITIATIVE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPGNSTATS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPGNSTATS" (
    "INITIATIVE_ID" INTEGER NOT NULL,
    "MPE_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "MPENAME" VARCHAR(64 OCTETS),
    "MPETYPE_ID" INTEGER,
    "INITIATIVENAME" VARCHAR(64 OCTETS),
    "VIEWS" INTEGER,
    "CLICKS" INTEGER,
    "MPETYPENAME" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPGNSTATS"
ALTER TABLE "DB2ADMIN"."CPGNSTATS"
ADD PRIMARY KEY ("INITIATIVE_ID", "MPE_ID", "STOREENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPGNSTATS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000315" ON "DB2ADMIN"."CPGNSTATS" ("MPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPITMAP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPITMAP" (
    "CPWALLET_ID" BIGINT NOT NULL,
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "DISCAMT" DECIMAL(20, 5) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPITMAP"
ALTER TABLE "DB2ADMIN"."CPITMAP"
ADD PRIMARY KEY ("CPWALLET_ID", "ORDERITEMS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPITMAP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000280" ON "DB2ADMIN"."CPITMAP" ("ORDERITEMS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPOFFER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPOFFER" (
    "CPPMN_ID" INTEGER NOT NULL,
    "USERS_ID" BIGINT NOT NULL,
    "STATE" CHAR(4 OCTETS) NOT NULL,
    "FIRSTTIMESEEN" TIMESTAMP,
    "FIELD1" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPOFFER"
ALTER TABLE "DB2ADMIN"."CPOFFER"
ADD PRIMARY KEY ("CPPMN_ID", "USERS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPOFFER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000545" ON "DB2ADMIN"."CPOFFER" ("USERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPPMN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPPMN" (
    "CPPMN_ID" INTEGER NOT NULL,
    "CPPMNVAL_ID" INTEGER,
    "STOREENT_ID" INTEGER NOT NULL,
    "INITIATIVE_ID" INTEGER,
    "SETCCURR" CHAR(3 OCTETS),
    "TOTALNUMOFFER" INTEGER NOT NULL,
    "NUMOFFERED" INTEGER NOT NULL,
    "EARLYBIRDLIMIT" INTEGER,
    "CREATIONTIME" TIMESTAMP,
    "PURCHASECONDTYPE" CHAR(4 OCTETS) NOT NULL,
    "NUMSEENALLOWED" INTEGER NOT NULL,
    "FIELD1" VARCHAR(64 OCTETS),
    "PROMODISPTYPE" CHAR(4 OCTETS) NOT NULL,
    "NUMUSEALLOWED" INTEGER NOT NULL,
    "STATUS" CHAR(1 OCTETS) NOT NULL,
    "CPPMNNAME" CHAR(64 OCTETS) NOT NULL,
    "CPPMNDESC" CHAR(254 OCTETS),
    "STARTDATE" TIMESTAMP NOT NULL,
    "ENDDATE" TIMESTAMP,
    "NUMACPALLOWED" INTEGER NOT NULL WITH DEFAULT 1,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPPMN"
ALTER TABLE "DB2ADMIN"."CPPMN"
ADD PRIMARY KEY ("CPPMN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPPMN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000289" ON "DB2ADMIN"."CPPMN" ("CPPMNNAME" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPPMN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000302" ON "DB2ADMIN"."CPPMN" ("ENDDATE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPPMN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000546" ON "DB2ADMIN"."CPPMN" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPPMN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001251" ON "DB2ADMIN"."CPPMN" ("INITIATIVE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPPMNACC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPPMNACC" (
    "CPPMN_ID" INTEGER NOT NULL,
    "SHOPPEREMAILID" CHAR(64 OCTETS) NOT NULL,
    "NUMACCEPTED" INTEGER NOT NULL WITH DEFAULT 0,
    "NUMREDEEMED" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPPMNACC"
ALTER TABLE "DB2ADMIN"."CPPMNACC"
ADD PRIMARY KEY ("CPPMN_ID", "SHOPPEREMAILID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPPMNACC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000277" ON "DB2ADMIN"."CPPMNACC" ("SHOPPEREMAILID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPPMNCAT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPPMNCAT" (
    "CATALOG_ID" BIGINT NOT NULL,
    "CATGROUP_ID" BIGINT NOT NULL,
    "CPPMN_ID" INTEGER NOT NULL,
    "QTYMEASURE" CHAR(16 OCTETS) NOT NULL,
    "MINQTY" DOUBLE,
    "MAXQTY" DOUBLE,
    "MINVALUE" DECIMAL(20, 5),
    "MAXVALUE" DECIMAL(20, 5),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPPMNCAT"
ALTER TABLE "DB2ADMIN"."CPPMNCAT"
ADD PRIMARY KEY ("CPPMN_ID", "CATALOG_ID", "CATGROUP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPPMNCAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000287" ON "DB2ADMIN"."CPPMNCAT" ("CATALOG_ID" ASC, "CATGROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPPMNCAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000547" ON "DB2ADMIN"."CPPMNCAT" ("CATGROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPPMNDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPPMNDESC" (
    "CPPMN_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "THUMBNAILPATH" VARCHAR(254 OCTETS),
    "FULLIMAGEPATH" VARCHAR(254 OCTETS),
    "SHORTDESC" VARCHAR(64 OCTETS),
    "LONGDESC" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPPMNDESC"
ALTER TABLE "DB2ADMIN"."CPPMNDESC"
ADD PRIMARY KEY ("CPPMN_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPPMNDISC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPPMNDISC" (
    "CPPMNDISC_ID" INTEGER NOT NULL,
    "CPPMN_ID" INTEGER NOT NULL,
    "CALCODE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPPMNDISC"
ALTER TABLE "DB2ADMIN"."CPPMNDISC"
ADD PRIMARY KEY ("CPPMNDISC_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPPMNDISC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000548" ON "DB2ADMIN"."CPPMNDISC" ("CALCODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPPMNDISC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001252" ON "DB2ADMIN"."CPPMNDISC" ("CPPMN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPPMNORD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPPMNORD" (
    "CPPMN_ID" INTEGER NOT NULL,
    "ORDERMIN" DECIMAL(20, 5) NOT NULL,
    "ORDERMAX" DECIMAL(20, 5),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPPMNORD"
ALTER TABLE "DB2ADMIN"."CPPMNORD"
ADD PRIMARY KEY ("CPPMN_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPPMNPROD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPPMNPROD" (
    "CPPMN_ID" INTEGER NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "QTYMEASURE" CHAR(16 OCTETS) NOT NULL,
    "QUANTITY" DOUBLE NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPPMNPROD"
ALTER TABLE "DB2ADMIN"."CPPMNPROD"
ADD PRIMARY KEY ("CPPMN_ID", "CATENTRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPPMNPROD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000282" ON "DB2ADMIN"."CPPMNPROD" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPPMNVAL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPPMNVAL" (
    "CPPMNVAL_ID" INTEGER NOT NULL,
    "STARTTIME" TIMESTAMP,
    "ENDTIME" TIMESTAMP,
    "DAY" CHAR(72 OCTETS),
    "WEEK" CHAR(40 OCTETS),
    "MONTH" CHAR(32 OCTETS),
    "VALIDITYTYPE" CHAR(1 OCTETS),
    "FIELD1" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPPMNVAL"
ALTER TABLE "DB2ADMIN"."CPPMNVAL"
ADD PRIMARY KEY ("CPPMNVAL_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CPWALLET"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CPWALLET" (
    "CPWALLET_ID" BIGINT NOT NULL,
    "CPPMN_ID" INTEGER NOT NULL,
    "USERS_ID" BIGINT NOT NULL,
    "NUMUSE" INTEGER NOT NULL,
    "STATE" CHAR(4 OCTETS) NOT NULL,
    "ACCEPTFROMTYPE" CHAR(4 OCTETS) NOT NULL,
    "TIMEACCEPT" TIMESTAMP,
    "FIELD1" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CPWALLET"
ALTER TABLE "DB2ADMIN"."CPWALLET"
ADD PRIMARY KEY ("CPWALLET_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPWALLET"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000283" ON "DB2ADMIN"."CPWALLET" ("USERS_ID" ASC, "STATE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CPWALLET"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000284" ON "DB2ADMIN"."CPWALLET" ("CPPMN_ID" ASC, "USERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CREDITLINE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CREDITLINE" (
    "CREDITLINE_ID" BIGINT NOT NULL,
    "SETCCURR" CHAR(3 OCTETS),
    "ACCOUNT_ID" BIGINT,
    "STATE" INTEGER WITH DEFAULT 0,
    "TIMECREATED" TIMESTAMP,
    "TIMEUPDATED" TIMESTAMP,
    "CREDITLIMIT" DECIMAL(20, 5),
    "DECIMALFIELD1" DECIMAL(20, 5),
    "DECIMALFIELD2" DECIMAL(20, 5),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CREDITLINE"
ALTER TABLE "DB2ADMIN"."CREDITLINE"
ADD PRIMARY KEY ("CREDITLINE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CREDITLINE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000549" ON "DB2ADMIN"."CREDITLINE" ("ACCOUNT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CRULESCALE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CRULESCALE" (
    "CALSCALE_ID" INTEGER NOT NULL,
    "CALRULE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CRULESCALE"
ALTER TABLE "DB2ADMIN"."CRULESCALE"
ADD PRIMARY KEY ("CALRULE_ID", "CALSCALE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CRULESCALE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000550" ON "DB2ADMIN"."CRULESCALE" ("CALSCALE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CSEDITATT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CSEDITATT" (
    "CSEDITATT_ID" INTEGER NOT NULL,
    "TRANSPORT_ID" INTEGER NOT NULL,
    "STORE_ID" INTEGER,
    "PROFILE_ID" INTEGER,
    "INSTANCE_NUM" INTEGER NOT NULL,
    "CUSTOMIZABLE" INTEGER NOT NULL,
    "CONNSPECATTNAME" VARCHAR(254 OCTETS) NOT NULL,
    "CONNSPECATTVALUE" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CSEDITATT"
ALTER TABLE "DB2ADMIN"."CSEDITATT"
ADD PRIMARY KEY ("CSEDITATT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CSEDITATT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000082" ON "DB2ADMIN"."CSEDITATT" (
    "TRANSPORT_ID" ASC,
    "STORE_ID" ASC,
    "PROFILE_ID" ASC,
    "CONNSPECATTNAME" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CSEDITATT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001253" ON "DB2ADMIN"."CSEDITATT" ("PROFILE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CTXDATA"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CTXDATA" (
    "ACTIVITY_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(128 OCTETS) NOT NULL,
    "SERVALUE" VARCHAR(2048 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CTXDATA"
ALTER TABLE "DB2ADMIN"."CTXDATA"
ADD PRIMARY KEY ("ACTIVITY_ID", "NAME");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CTXDATA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000841" ON "DB2ADMIN"."CTXDATA" ("ACTIVITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CTXMGMT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CTXMGMT" (
    "ACTIVITY_ID" BIGINT NOT NULL,
    "CALLER_ID" BIGINT,
    "STARTTIME" TIMESTAMP,
    "ENDTIME" TIMESTAMP,
    "STATUS" CHAR(1 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "STORE_ID" INTEGER,
    "RUNAS_ID" BIGINT,
    "LASTACCESSTIME" TIMESTAMP
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CTXMGMT"
ALTER TABLE "DB2ADMIN"."CTXMGMT"
ADD PRIMARY KEY ("ACTIVITY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CTXMGMT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000831" ON "DB2ADMIN"."CTXMGMT" ("CALLER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CTXMGMT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000895" ON "DB2ADMIN"."CTXMGMT" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CTXMGMT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000896" ON "DB2ADMIN"."CTXMGMT" ("RUNAS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CTXMGMT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001299" ON "DB2ADMIN"."CTXMGMT" ("LASTACCESSTIME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CTXMGMT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001545" ON "DB2ADMIN"."CTXMGMT" (
    "CALLER_ID" ASC,
    "RUNAS_ID" ASC,
    "STORE_ID" ASC,
    "STATUS" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CURCONVERT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CURCONVERT" (
    "STOREENT_ID" INTEGER NOT NULL,
    "FROMCURR" CHAR(3 OCTETS) NOT NULL,
    "TOCURR" CHAR(3 OCTETS) NOT NULL,
    "FACTOR" DECIMAL(31, 20) NOT NULL WITH DEFAULT 1,
    "MULTIPLYORDIVIDE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'M',
    "BIDIRECTIONAL" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N',
    "UPDATABLE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'Y',
    "CURCONVERT_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CURCONVERT"
ALTER TABLE "DB2ADMIN"."CURCONVERT"
ADD PRIMARY KEY ("CURCONVERT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CURCONVERT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000083" ON "DB2ADMIN"."CURCONVERT" (
    "FROMCURR" ASC,
    "TOCURR" ASC,
    "STOREENT_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CURCONVERT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000551" ON "DB2ADMIN"."CURCONVERT" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CURCVLIST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CURCVLIST" (
    "STOREENT_ID" INTEGER NOT NULL,
    "CURRSTR" CHAR(3 OCTETS) NOT NULL,
    "COUNTERVALUECURR" CHAR(3 OCTETS) NOT NULL,
    "DISPLAYSEQ" DOUBLE NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CURCVLIST"
ALTER TABLE "DB2ADMIN"."CURCVLIST"
ADD PRIMARY KEY (
        "COUNTERVALUECURR",
        "CURRSTR",
        "STOREENT_ID",
        "DISPLAYSEQ"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."CURCVLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000552" ON "DB2ADMIN"."CURCVLIST" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CURFMTDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CURFMTDESC" (
    "STOREENT_ID" INTEGER NOT NULL,
    "NUMBRUSG_ID" INTEGER NOT NULL WITH DEFAULT -1,
    "SETCCURR" CHAR(3 OCTETS) NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CURRENCYSYMBOL" VARCHAR(254 OCTETS),
    "CUSTOMIZEDCURRSTR" VARCHAR(254 OCTETS),
    "CURRENCYPREFIXPOS" VARCHAR(254 OCTETS),
    "CURRENCYSUFFIXPOS" VARCHAR(254 OCTETS),
    "DISPLAYLOCALE" CHAR(16 OCTETS),
    "CURRENCYPREFIXNEG" VARCHAR(254 OCTETS),
    "CURRENCYSUFFIXNEG" VARCHAR(254 OCTETS),
    "RADIXPOINT" CHAR(1 OCTETS),
    "GROUPINGCHAR" CHAR(1 OCTETS),
    "NUMBERPATTERN" VARCHAR(254 OCTETS),
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CURFMTDESC"
ALTER TABLE "DB2ADMIN"."CURFMTDESC"
ADD PRIMARY KEY (
        "NUMBRUSG_ID",
        "STOREENT_ID",
        "SETCCURR",
        "LANGUAGE_ID"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."CURFMTDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001254" ON "DB2ADMIN"."CURFMTDESC" (
    "STOREENT_ID" ASC,
    "SETCCURR" ASC,
    "NUMBRUSG_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CURFORMAT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CURFORMAT" (
    "STOREENT_ID" INTEGER NOT NULL,
    "SETCCURR" CHAR(3 OCTETS) NOT NULL,
    "ROUNDINGMULTIPLE" INTEGER NOT NULL WITH DEFAULT 1,
    "NUMBRUSG_ID" INTEGER NOT NULL WITH DEFAULT -1,
    "ROUNDINGMETHOD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'R',
    "DECIMALPLACES" INTEGER NOT NULL WITH DEFAULT 2,
    "MINAPPROVEAMOUNT" DECIMAL(20, 5),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CURFORMAT"
ALTER TABLE "DB2ADMIN"."CURFORMAT"
ADD PRIMARY KEY ("STOREENT_ID", "SETCCURR", "NUMBRUSG_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CURLIST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CURLIST" (
    "STOREENT_ID" INTEGER NOT NULL,
    "CURRSTR" CHAR(3 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CURLIST"
ALTER TABLE "DB2ADMIN"."CURLIST"
ADD PRIMARY KEY ("CURRSTR", "STOREENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CURLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000553" ON "DB2ADMIN"."CURLIST" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CURMSGID"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CURMSGID" ("CURID" INTEGER, "OPTCOUNTER" SMALLINT) IN "USERSPACE1" ORGANIZE BY ROW;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CWMEMBER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CWMEMBER" (
    "COLLABWS_ID" CHAR(32 OCTETS) NOT NULL,
    "LOGONID" VARCHAR(254 OCTETS) NOT NULL,
    "ROLE" VARCHAR(32 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CWMEMBER"
ALTER TABLE "DB2ADMIN"."CWMEMBER"
ADD PRIMARY KEY ("COLLABWS_ID", "LOGONID");
---