------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACACGPDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACACGPDESC" (
    "ACACTGRP_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(700 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(700 OCTETS),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACACGPDESC"
ALTER TABLE "DB2ADMIN"."ACACGPDESC"
ADD PRIMARY KEY ("ACACTGRP_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACACTACTGP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACACTACTGP" (
    "ACACTGRP_ID" INTEGER NOT NULL,
    "ACACTION_ID" INTEGER NOT NULL,
    "FIELD1" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACACTACTGP"
ALTER TABLE "DB2ADMIN"."ACACTACTGP"
ADD PRIMARY KEY ("ACACTGRP_ID", "ACACTION_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACACTACTGP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000426" ON "DB2ADMIN"."ACACTACTGP" ("ACACTION_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACACTDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACACTDESC" (
    "ACACTION_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(700 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(700 OCTETS),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACACTDESC"
ALTER TABLE "DB2ADMIN"."ACACTDESC"
ADD PRIMARY KEY ("ACACTION_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACACTGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACACTGRP" (
    "ACACTGRP_ID" INTEGER NOT NULL,
    "GROUPNAME" VARCHAR(128 OCTETS) NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "FIELD1" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACACTGRP"
ALTER TABLE "DB2ADMIN"."ACACTGRP"
ADD PRIMARY KEY ("ACACTGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACACTGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000001" ON "DB2ADMIN"."ACACTGRP" ("GROUPNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACACTGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000427" ON "DB2ADMIN"."ACACTGRP" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACACTION"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACACTION" (
    "ACACTION_ID" INTEGER NOT NULL,
    "ACTION" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACACTION"
ALTER TABLE "DB2ADMIN"."ACACTION"
ADD PRIMARY KEY ("ACACTION_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACACTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000002" ON "DB2ADMIN"."ACACTION" ("ACTION" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACATTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACATTR" (
    "ACATTR_ID" BIGINT NOT NULL,
    "ATTRNAME" VARCHAR(128 OCTETS) NOT NULL,
    "DATATYPE" INTEGER NOT NULL,
    "FIELD1" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACATTR"
ALTER TABLE "DB2ADMIN"."ACATTR"
ADD PRIMARY KEY ("ACATTR_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000003" ON "DB2ADMIN"."ACATTR" ("ATTRNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACATTRDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACATTRDESC" (
    "ACATTR_ID" BIGINT NOT NULL,
    "DISPLAYNAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACATTRDESC"
ALTER TABLE "DB2ADMIN"."ACATTRDESC"
ADD PRIMARY KEY ("ACATTR_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACCCMDGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACCCMDGRP" (
    "ACCCMDGRP_ID" INTEGER NOT NULL,
    "MBRGRP_ID" BIGINT NOT NULL,
    "ACCCMDTYPE_ID" CHAR(32 OCTETS) NOT NULL,
    "INTERFACENAME" VARCHAR(254 OCTETS),
    "VIEWNAME" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACCCMDGRP"
ALTER TABLE "DB2ADMIN"."ACCCMDGRP"
ADD PRIMARY KEY ("ACCCMDGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACCCMDGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000004" ON "DB2ADMIN"."ACCCMDGRP" (
    "MBRGRP_ID" ASC,
    "INTERFACENAME" ASC,
    "VIEWNAME" ASC,
    "ACCCMDTYPE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACCCMDTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACCCMDTYPE" (
    "ACCCMDTYPE_ID" CHAR(32 OCTETS) NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACCCMDTYPE"
ALTER TABLE "DB2ADMIN"."ACCCMDTYPE"
ADD PRIMARY KEY ("ACCCMDTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACCCUSTEXC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACCCUSTEXC" (
    "ACCCMDGRP_ID" INTEGER NOT NULL,
    "OWNER_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACCCUSTEXC"
ALTER TABLE "DB2ADMIN"."ACCCUSTEXC"
ADD PRIMARY KEY ("OWNER_ID", "ACCCMDGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACCCUSTEXC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001234" ON "DB2ADMIN"."ACCCUSTEXC" ("ACCCMDGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACCLOGMAIN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACCLOGMAIN" (
    "ACCLOGMAIN_ID" BIGINT NOT NULL,
    "THREADID" VARCHAR(32 OCTETS),
    "HOSTNAME" VARCHAR(64 OCTETS),
    "STOREENT_ID" INTEGER NOT NULL,
    "USERS_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACCLOGMAIN"
ALTER TABLE "DB2ADMIN"."ACCLOGMAIN"
ADD PRIMARY KEY ("ACCLOGMAIN_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACCLOGSUB"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACCLOGSUB" (
    "ACCLOGSUB_ID" BIGINT NOT NULL,
    "ACCLOGMAIN_ID" BIGINT NOT NULL,
    "LOGTIME" TIMESTAMP,
    "ACTION" VARCHAR(254 OCTETS),
    "RESULT" VARCHAR(254 OCTETS),
    "RESOURCES" VARCHAR(254 OCTETS),
    "USERS_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACCLOGSUB"
ALTER TABLE "DB2ADMIN"."ACCLOGSUB"
ADD PRIMARY KEY ("ACCLOGSUB_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACCMBRGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACCMBRGRP" (
    "MBRGRP_ID" BIGINT NOT NULL,
    "USERS_ID" BIGINT NOT NULL,
    "OWNER_ID" BIGINT NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACCMBRGRP"
ALTER TABLE "DB2ADMIN"."ACCMBRGRP"
ADD PRIMARY KEY ("USERS_ID", "MBRGRP_ID", "OWNER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACCMBRGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000432" ON "DB2ADMIN"."ACCMBRGRP" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACCMBRGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000433" ON "DB2ADMIN"."ACCMBRGRP" ("OWNER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACCOUNT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACCOUNT" (
    "ACCOUNT_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(200 OCTETS) NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "STORE_ID" INTEGER,
    "STATE" INTEGER NOT NULL WITH DEFAULT 0,
    "CURRENCY" CHAR(3 OCTETS),
    "DEFAULTCONTRACT" INTEGER NOT NULL WITH DEFAULT 0,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "COMMENTS" VARCHAR(4000 OCTETS),
    "TIMECREATED" TIMESTAMP,
    "TIMEUPDATED" TIMESTAMP,
    "TIMEAPPROVED" TIMESTAMP,
    "TIMEACTIVATED" TIMESTAMP,
    "OPTCOUNTER" SMALLINT,
    "PRCPLCYPREF" VARCHAR(32 OCTETS),
    "USEPRCPLCYPREF" SMALLINT,
    "UP_NAME" VARCHAR(200 OCTETS) GENERATED ALWAYS AS (UPPER(NAME))
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACCOUNT"
ALTER TABLE "DB2ADMIN"."ACCOUNT"
ADD PRIMARY KEY ("ACCOUNT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACCOUNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000005" ON "DB2ADMIN"."ACCOUNT" ("NAME" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACCOUNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000434" ON "DB2ADMIN"."ACCOUNT" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACCOUNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000435" ON "DB2ADMIN"."ACCOUNT" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACCOUNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00027" ON "DB2ADMIN"."ACCOUNT" ("UP_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACORGPOL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACORGPOL" (
    "ACPOLICY_ID" INTEGER NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACORGPOL"
ALTER TABLE "DB2ADMIN"."ACORGPOL"
ADD PRIMARY KEY ("ACPOLICY_ID", "MEMBER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACORGPOL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000436" ON "DB2ADMIN"."ACORGPOL" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACPLGPDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACPLGPDESC" (
    "ACPOLGRP_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(700 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(700 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACPLGPDESC"
ALTER TABLE "DB2ADMIN"."ACPLGPDESC"
ADD PRIMARY KEY ("ACPOLGRP_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACPLGPSUBS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACPLGPSUBS" (
    "ACPOLGRP_ID" INTEGER NOT NULL,
    "ORGENTITY_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACPLGPSUBS"
ALTER TABLE "DB2ADMIN"."ACPLGPSUBS"
ADD PRIMARY KEY ("ORGENTITY_ID", "ACPOLGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACPLGPSUBS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000437" ON "DB2ADMIN"."ACPLGPSUBS" ("ACPOLGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACPOLDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACPOLDESC" (
    "ACPOLICY_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(700 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(700 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACPOLDESC"
ALTER TABLE "DB2ADMIN"."ACPOLDESC"
ADD PRIMARY KEY ("ACPOLICY_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACPOLGPPOL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACPOLGPPOL" (
    "ACPOLICY_ID" INTEGER NOT NULL,
    "ACPOLGRP_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACPOLGPPOL"
ALTER TABLE "DB2ADMIN"."ACPOLGPPOL"
ADD PRIMARY KEY ("ACPOLICY_ID", "ACPOLGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACPOLGPPOL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000438" ON "DB2ADMIN"."ACPOLGPPOL" ("ACPOLGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACPOLGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACPOLGRP" (
    "ACPOLGRP_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(128 OCTETS) NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACPOLGRP"
ALTER TABLE "DB2ADMIN"."ACPOLGRP"
ADD PRIMARY KEY ("ACPOLGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACPOLGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000306" ON "DB2ADMIN"."ACPOLGRP" ("NAME" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACPOLGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000439" ON "DB2ADMIN"."ACPOLGRP" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACPOLICY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACPOLICY" (
    "ACPOLICY_ID" INTEGER NOT NULL,
    "POLICYNAME" VARCHAR(128 OCTETS) NOT NULL,
    "ACRELGRP_ID" INTEGER,
    "ACACTGRP_ID" INTEGER NOT NULL,
    "ACRESGRP_ID" INTEGER NOT NULL,
    "ACRELATION_ID" INTEGER,
    "POLICYTYPE" INTEGER,
    "FIELD1" VARCHAR(128 OCTETS),
    "MBRGRP_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACPOLICY"
ALTER TABLE "DB2ADMIN"."ACPOLICY"
ADD PRIMARY KEY ("ACPOLICY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACPOLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000006" ON "DB2ADMIN"."ACPOLICY" ("POLICYNAME" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACPOLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000316" ON "DB2ADMIN"."ACPOLICY" ("ACRESGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACPOLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000317" ON "DB2ADMIN"."ACPOLICY" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACPOLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000318" ON "DB2ADMIN"."ACPOLICY" ("ACRELATION_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACPOLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000319" ON "DB2ADMIN"."ACPOLICY" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACPOLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000320" ON "DB2ADMIN"."ACPOLICY" ("ACACTGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACPOLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000440" ON "DB2ADMIN"."ACPOLICY" ("ACRELGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACPOLSUBGP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACPOLSUBGP" (
    "CHILD_ID" INTEGER NOT NULL,
    "PARENT_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACPOLSUBGP"
ALTER TABLE "DB2ADMIN"."ACPOLSUBGP"
ADD PRIMARY KEY ("CHILD_ID", "PARENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACPOLSUBGP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000441" ON "DB2ADMIN"."ACPOLSUBGP" ("PARENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRELATION"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRELATION" (
    "ACRELATION_ID" INTEGER NOT NULL,
    "RELATIONNAME" VARCHAR(128 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRELATION"
ALTER TABLE "DB2ADMIN"."ACRELATION"
ADD PRIMARY KEY ("ACRELATION_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRELATION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000007" ON "DB2ADMIN"."ACRELATION" ("RELATIONNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRELDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRELDESC" (
    "ACRELATION_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRELDESC"
ALTER TABLE "DB2ADMIN"."ACRELDESC"
ADD PRIMARY KEY ("ACRELATION_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRELGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRELGRP" (
    "ACRELGRP_ID" INTEGER NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "GRPNAME" VARCHAR(200 OCTETS) NOT NULL,
    "CONDITIONS" VARCHAR(2500 OCTETS),
    "FIELD1" VARCHAR(64 OCTETS),
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRELGRP"
ALTER TABLE "DB2ADMIN"."ACRELGRP"
ADD PRIMARY KEY ("ACRELGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRELGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000008" ON "DB2ADMIN"."ACRELGRP" ("GRPNAME" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRELGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000442" ON "DB2ADMIN"."ACRELGRP" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRESACT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRESACT" (
    "ACRESCGRY_ID" INTEGER NOT NULL,
    "ACACTION_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRESACT"
ALTER TABLE "DB2ADMIN"."ACRESACT"
ADD PRIMARY KEY ("ACRESCGRY_ID", "ACACTION_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRESACT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000443" ON "DB2ADMIN"."ACRESACT" ("ACACTION_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRESATREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRESATREL" (
    "ACATTR_ID" BIGINT NOT NULL,
    "ACRESCGRY_ID" INTEGER NOT NULL,
    "ATTRTBLNAME" VARCHAR(64 OCTETS) NOT NULL,
    "ATTRCOLNAME" VARCHAR(64 OCTETS) NOT NULL,
    "RESKEYCOLNAME" VARCHAR(64 OCTETS) NOT NULL,
    "FIELD1" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRESATREL"
ALTER TABLE "DB2ADMIN"."ACRESATREL"
ADD PRIMARY KEY ("ACATTR_ID", "ACRESCGRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRESATREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000444" ON "DB2ADMIN"."ACRESATREL" ("ACRESCGRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRESCGRY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRESCGRY" (
    "ACRESCGRY_ID" INTEGER NOT NULL,
    "RESPRIMARYTABLE" VARCHAR(64 OCTETS),
    "RESOWNERTABLE" VARCHAR(64 OCTETS),
    "RESOWNERCOL" VARCHAR(64 OCTETS),
    "RESKEYOWNCOL" VARCHAR(64 OCTETS),
    "FIELD1" VARCHAR(128 OCTETS),
    "RESCLASSNAME" VARCHAR(254 OCTETS) NOT NULL,
    "RESJOINKEY" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRESCGRY"
ALTER TABLE "DB2ADMIN"."ACRESCGRY"
ADD PRIMARY KEY ("ACRESCGRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRESCGRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000009" ON "DB2ADMIN"."ACRESCGRY" ("RESCLASSNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRESGPDES"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRESGPDES" (
    "ACRESGRP_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(700 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(700 OCTETS),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRESGPDES"
ALTER TABLE "DB2ADMIN"."ACRESGPDES"
ADD PRIMARY KEY ("ACRESGRP_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRESGPRES"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRESGPRES" (
    "ACRESGRP_ID" INTEGER NOT NULL,
    "ACRESCGRY_ID" INTEGER NOT NULL,
    "FIELD1" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRESGPRES"
ALTER TABLE "DB2ADMIN"."ACRESGPRES"
ADD PRIMARY KEY ("ACRESGRP_ID", "ACRESCGRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRESGPRES"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000445" ON "DB2ADMIN"."ACRESGPRES" ("ACRESCGRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRESGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRESGRP" (
    "ACRESGRP_ID" INTEGER NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "GRPNAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "CONDITIONS" VARCHAR(2500 OCTETS),
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRESGRP"
ALTER TABLE "DB2ADMIN"."ACRESGRP"
ADD PRIMARY KEY ("ACRESGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRESGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000010" ON "DB2ADMIN"."ACRESGRP" ("GRPNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRESGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000446" ON "DB2ADMIN"."ACRESGRP" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRESMEMRL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRESMEMRL" (
    "RESOURCEID" BIGINT,
    "ACRESMEMRL_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "ACRELATION_ID" INTEGER NOT NULL,
    "ACRESCGRY_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRESMEMRL"
ALTER TABLE "DB2ADMIN"."ACRESMEMRL"
ADD PRIMARY KEY ("ACRESMEMRL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRESMEMRL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000011" ON "DB2ADMIN"."ACRESMEMRL" (
    "MEMBER_ID" ASC,
    "RESOURCEID" ASC,
    "ACRELATION_ID" ASC,
    "ACRESCGRY_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRESMEMRL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000012" ON "DB2ADMIN"."ACRESMEMRL" (
    "RESOURCEID" ASC,
    "ACRELATION_ID" ASC,
    "ACRESCGRY_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRESMEMRL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000447" ON "DB2ADMIN"."ACRESMEMRL" ("ACRESCGRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRESPRIM"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRESPRIM" (
    "ACRESCGRY_ID" INTEGER NOT NULL,
    "RESPRIMARYCOL" VARCHAR(64 OCTETS) NOT NULL,
    "FIELD1" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRESPRIM"
ALTER TABLE "DB2ADMIN"."ACRESPRIM"
ADD PRIMARY KEY ("ACRESCGRY_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRESREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRESREL" (
    "ACRELATION_ID" INTEGER NOT NULL,
    "ACRESCGRY_ID" INTEGER NOT NULL,
    "RESRELTABLE" VARCHAR(64 OCTETS) NOT NULL,
    "RESRELMEMCOL" VARCHAR(64 OCTETS) NOT NULL,
    "RESRELKEYCOL" VARCHAR(64 OCTETS),
    "RESRELCOL" VARCHAR(64 OCTETS),
    "RESJOINCOL" VARCHAR(64 OCTETS),
    "FIELD1" VARCHAR(128 OCTETS),
    "RESOURCETYPE" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRESREL"
ALTER TABLE "DB2ADMIN"."ACRESREL"
ADD PRIMARY KEY ("ACRELATION_ID", "ACRESCGRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRESREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000448" ON "DB2ADMIN"."ACRESREL" ("ACRESCGRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRLGPDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRLGPDESC" (
    "ACRELGRP_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(128 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRLGPDESC"
ALTER TABLE "DB2ADMIN"."ACRLGPDESC"
ADD PRIMARY KEY ("ACRELGRP_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ACRSCGDES"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ACRSCGDES" (
    "LANGUAGE_ID" INTEGER NOT NULL,
    "ACRESCGRY_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(700 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(700 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ACRSCGDES"
ALTER TABLE "DB2ADMIN"."ACRSCGDES"
ADD PRIMARY KEY ("LANGUAGE_ID", "ACRESCGRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ACRSCGDES"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000449" ON "DB2ADMIN"."ACRSCGDES" ("ACRESCGRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
---