------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ADDRBOOK"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ADDRBOOK" (
    "ADDRBOOK_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "TYPE" CHAR(1 OCTETS),
    "DISPLAYNAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ADDRBOOK"
ALTER TABLE "DB2ADMIN"."ADDRBOOK"
ADD PRIMARY KEY ("ADDRBOOK_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ADDRBOOK"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000013" ON "DB2ADMIN"."ADDRBOOK" ("ADDRBOOK_ID" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ADDRBOOK"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000014" ON "DB2ADMIN"."ADDRBOOK" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ADDRESS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ADDRESS" (
    "ADDRESS_ID" BIGINT NOT NULL,
    "ADDRESSTYPE" CHAR(5 OCTETS),
    "MEMBER_ID" BIGINT NOT NULL,
    "ADDRBOOK_ID" BIGINT NOT NULL,
    "ORGUNITNAME" VARCHAR(128 OCTETS),
    "FIELD3" VARCHAR(64 OCTETS),
    "BILLINGCODE" VARCHAR(17 OCTETS),
    "BILLINGCODETYPE" CHAR(2 OCTETS),
    "STATUS" CHAR(1 OCTETS),
    "ORGNAME" VARCHAR(128 OCTETS),
    "ISPRIMARY" INTEGER,
    "LASTNAME" VARCHAR(128 OCTETS),
    "PERSONTITLE" VARCHAR(50 OCTETS),
    "FIRSTNAME" VARCHAR(128 OCTETS),
    "MIDDLENAME" VARCHAR(128 OCTETS),
    "BUSINESSTITLE" VARCHAR(128 OCTETS),
    "PHONE1" VARCHAR(32 OCTETS),
    "FAX1" VARCHAR(32 OCTETS),
    "PHONE2" VARCHAR(32 OCTETS),
    "ADDRESS1" VARCHAR(256 OCTETS),
    "FAX2" VARCHAR(32 OCTETS),
    "NICKNAME" VARCHAR(254 OCTETS) NOT NULL,
    "ADDRESS2" VARCHAR(128 OCTETS),
    "ADDRESS3" VARCHAR(128 OCTETS),
    "CITY" VARCHAR(128 OCTETS),
    "STATE" VARCHAR(128 OCTETS),
    "COUNTRY" VARCHAR(128 OCTETS),
    "ZIPCODE" VARCHAR(40 OCTETS),
    "EMAIL1" VARCHAR(256 OCTETS),
    "EMAIL2" VARCHAR(256 OCTETS),
    "PHONE1TYPE" CHAR(3 OCTETS),
    "PHONE2TYPE" CHAR(3 OCTETS),
    "PUBLISHPHONE1" INTEGER,
    "PUBLISHPHONE2" INTEGER,
    "BESTCALLINGTIME" CHAR(1 OCTETS),
    "PACKAGESUPPRESSION" INTEGER,
    "LASTCREATE" TIMESTAMP,
    "OFFICEADDRESS" VARCHAR(128 OCTETS),
    "SELFADDRESS" INTEGER NOT NULL WITH DEFAULT 0,
    "FIELD1" VARCHAR(64 OCTETS),
    "FIELD2" VARCHAR(64 OCTETS),
    "TAXGEOCODE" VARCHAR(254 OCTETS),
    "SHIPPINGGEOCODE" VARCHAR(254 OCTETS),
    "MOBILEPHONE1" VARCHAR(32 OCTETS),
    "MOBILEPHONE1CNTRY" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ADDRESS"
ALTER TABLE "DB2ADMIN"."ADDRESS"
ADD PRIMARY KEY ("ADDRESS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ADDRESS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000015" ON "DB2ADMIN"."ADDRESS" (
    "ADDRBOOK_ID" ASC,
    "ADDRESSTYPE" ASC,
    "ISPRIMARY" ASC,
    "STATUS" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ADDRESS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000016" ON "DB2ADMIN"."ADDRESS" (
    "MEMBER_ID" ASC,
    "STATUS" ASC,
    "SELFADDRESS" ASC,
    "ADDRESSTYPE" ASC,
    "ISPRIMARY" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ADDRESS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000346" ON "DB2ADMIN"."ADDRESS" ("LASTNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ADDRESS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001521" ON "DB2ADMIN"."ADDRESS" ("EMAIL1" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ALCHARGE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ALCHARGE" (
    "ALCHRFNBR" INTEGER NOT NULL,
    "ALCHORRFNBR" INTEGER,
    "ALCHOIRFNBR" INTEGER,
    "ALCHTYPE" CHAR(4 OCTETS) NOT NULL,
    "ALCHAMT" DECIMAL(20, 5),
    "ALCHCUR" CHAR(10 OCTETS),
    "ALCHPERT" DECIMAL(20, 5),
    "ALCHCALCODE" CHAR(2 OCTETS),
    "ALCHDES" VARCHAR(80 OCTETS),
    "ALCHFIELD1" VARCHAR(30 OCTETS),
    "ALCHFIELD2" VARCHAR(30 OCTETS),
    "ALCHFIELD3" VARCHAR(30 OCTETS),
    "ORDERS_ID" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ALCHARGE"
ALTER TABLE "DB2ADMIN"."ALCHARGE"
ADD PRIMARY KEY ("ALCHRFNBR");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ALCHARGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000450" ON "DB2ADMIN"."ALCHARGE" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."APPLY_INIT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."APPLY_INIT" (
    "SEGMENTATION_ID" INTEGER NOT NULL,
    "INITIATIVE_ID" INTEGER NOT NULL,
    "SEGMENT_INDEX" INTEGER NOT NULL,
    "SCORE" DOUBLE,
    "CONFIDENCE" DOUBLE,
    "SCORE2" DOUBLE,
    "SEGMENT_INDEX2" INTEGER,
    "LAST_UPDATED" TIMESTAMP NOT NULL WITH DEFAULT,
    "LAST_UPDATED_ID" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."APPLY_INIT"
ALTER TABLE "DB2ADMIN"."APPLY_INIT"
ADD PRIMARY KEY ("SEGMENTATION_ID", "INITIATIVE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."APPLY_MEMBER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."APPLY_MEMBER" (
    "SEGMENTATION_ID" INTEGER NOT NULL,
    "SEGMENT_INDEX" INTEGER NOT NULL,
    "SCORE" DOUBLE NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "SUB_ID" BIGINT NOT NULL,
    "TYPE_ID" INTEGER NOT NULL,
    "CONFIDENCE" DOUBLE,
    "SCORE2" DOUBLE,
    "SEGMENT_INDEX2" INTEGER,
    "LAST_UPDATED" TIMESTAMP NOT NULL WITH DEFAULT,
    "LAST_UPDATED_ID" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."APPLY_MEMBER"
ALTER TABLE "DB2ADMIN"."APPLY_MEMBER"
ADD PRIMARY KEY ("MEMBER_ID", "SUB_ID", "SEGMENTATION_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."APPLY_MEMBER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000272" ON "DB2ADMIN"."APPLY_MEMBER" (
    "SEGMENTATION_ID" ASC,
    "SEGMENT_INDEX" ASC,
    "SCORE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."APPLY_RESULT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."APPLY_RESULT" (
    "SEGMENTATION_ID" INTEGER NOT NULL,
    "RESULT_ID" BIGINT NOT NULL,
    "TYPE_ID" INTEGER NOT NULL,
    "SEGMENT_INDEX" INTEGER NOT NULL,
    "SCORE" DOUBLE NOT NULL,
    "CONFIDENCE" DOUBLE,
    "SCORE2" DOUBLE,
    "SEGMENT_INDEX2" INTEGER,
    "LAST_UPDATED" TIMESTAMP NOT NULL WITH DEFAULT,
    "LAST_UPDATED_ID" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."APPLY_RESULT"
ALTER TABLE "DB2ADMIN"."APPLY_RESULT"
ADD PRIMARY KEY ("SEGMENTATION_ID", "RESULT_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."APRVSTATUS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."APRVSTATUS" (
    "APRVSTATUS_ID" BIGINT NOT NULL,
    "FLOW_ID" BIGINT NOT NULL,
    "SUBMITTER_ID" BIGINT NOT NULL,
    "APPROVER_ID" BIGINT,
    "FLOWTYPE_ID" BIGINT NOT NULL,
    "ENTITY_ID" BIGINT NOT NULL,
    "MBRGRP_ID" BIGINT NOT NULL,
    "FLSTATEDCT_ID" BIGINT NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "SUBMITTIME" TIMESTAMP,
    "ACTIONTIME" TIMESTAMP,
    "COMMENTS" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."APRVSTATUS"
ALTER TABLE "DB2ADMIN"."APRVSTATUS"
ADD PRIMARY KEY ("APRVSTATUS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."APRVSTATUS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I9221181" ON "DB2ADMIN"."APRVSTATUS" (
    "APPROVER_ID" ASC,
    "STATUS" ASC,
    "SUBMITTER_ID" ASC,
    "FLOWTYPE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."APRVSTATUS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I9221180" ON "DB2ADMIN"."APRVSTATUS" (
    "SUBMITTER_ID" ASC,
    "APPROVER_ID" ASC,
    "FLOWTYPE_ID" ASC,
    "STATUS" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."APRVSTATUS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I922110" ON "DB2ADMIN"."APRVSTATUS" ("FLOW_ID" ASC, "ENTITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."APRVSTATUS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000451" ON "DB2ADMIN"."APRVSTATUS" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
---