------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CACHEIVL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CACHEIVL" (
    "TEMPLATE" VARCHAR(1024 OCTETS),
    "DATAID" VARCHAR(2960 OCTETS),
    "INSERTTIME" TIMESTAMP NOT NULL WITH DEFAULT,
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CACHEIVL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000299" ON "DB2ADMIN"."CACHEIVL" ("INSERTTIME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALADJUST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALADJUST" (
    "CALADJUST_ID" BIGINT NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "CALUSAGE_ID" INTEGER NOT NULL,
    "SHIPMODE_ID" INTEGER,
    "SERVICEREP_ID" BIGINT NOT NULL,
    "PARMTYPE" INTEGER NOT NULL WITH DEFAULT 0,
    "PARMAMT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "BASECOST" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALADJUST"
ALTER TABLE "DB2ADMIN"."CALADJUST"
ADD PRIMARY KEY ("CALADJUST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALADJUST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000958" ON "DB2ADMIN"."CALADJUST" (
    "ORDERS_ID" ASC,
    "CALUSAGE_ID" ASC,
    "SHIPMODE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALADJUST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000959" ON "DB2ADMIN"."CALADJUST" ("SHIPMODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALADJUST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000960" ON "DB2ADMIN"."CALADJUST" ("SERVICEREP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALADJUST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000961" ON "DB2ADMIN"."CALADJUST" ("CALUSAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALCODE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALCODE" (
    "CALCODE_ID" INTEGER NOT NULL,
    "CODE" CHAR(128 OCTETS) NOT NULL,
    "CALUSAGE_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "GROUPBY" INTEGER NOT NULL WITH DEFAULT 0,
    "TXCDCLASS_ID" INTEGER,
    "PUBLISHED" INTEGER NOT NULL WITH DEFAULT 0,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "COMBINATION" INTEGER,
    "LASTUPDATE" TIMESTAMP,
    "CALMETHOD_ID" INTEGER NOT NULL,
    "CALMETHOD_ID_APP" INTEGER NOT NULL,
    "CALMETHOD_ID_QFY" INTEGER NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "DISPLAYLEVEL" INTEGER NOT NULL WITH DEFAULT 0,
    "STARTDATE" TIMESTAMP,
    "ENDDATE" TIMESTAMP,
    "FLAGS" INTEGER NOT NULL WITH DEFAULT 0,
    "PRECEDENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALCODE"
ALTER TABLE "DB2ADMIN"."CALCODE"
ADD PRIMARY KEY ("CALCODE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000054" ON "DB2ADMIN"."CALCODE" (
    "CALUSAGE_ID" ASC,
    "CODE" ASC,
    "STOREENT_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000495" ON "DB2ADMIN"."CALCODE" ("CALMETHOD_ID_APP" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000496" ON "DB2ADMIN"."CALCODE" ("CALMETHOD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000497" ON "DB2ADMIN"."CALCODE" ("CALMETHOD_ID_QFY" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000498" ON "DB2ADMIN"."CALCODE" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001247" ON "DB2ADMIN"."CALCODE" ("TXCDCLASS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALCODEDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALCODEDSC" (
    "CALCODE_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "LONGDESCRIPTION" VARCHAR(4000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALCODEDSC"
ALTER TABLE "DB2ADMIN"."CALCODEDSC"
ADD PRIMARY KEY ("CALCODE_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALCODEMGP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALCODEMGP" (
    "CALCODE_ID" INTEGER NOT NULL,
    "MBRGRP_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALCODEMGP"
ALTER TABLE "DB2ADMIN"."CALCODEMGP"
ADD PRIMARY KEY ("CALCODE_ID", "MBRGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALCODEMGP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000499" ON "DB2ADMIN"."CALCODEMGP" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALCODTXEX"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALCODTXEX" (
    "CALCODE_ID" INTEGER NOT NULL,
    "TAXCGRY_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALCODTXEX"
ALTER TABLE "DB2ADMIN"."CALCODTXEX"
ADD PRIMARY KEY ("CALCODE_ID", "TAXCGRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALCODTXEX"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000500" ON "DB2ADMIN"."CALCODTXEX" ("TAXCGRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALMETHOD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALMETHOD" (
    "CALMETHOD_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "CALUSAGE_ID" INTEGER NOT NULL,
    "TASKNAME" VARCHAR(254 OCTETS),
    "DESCRIPTION" VARCHAR(508 OCTETS),
    "SUBCLASS" INTEGER,
    "NAME" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALMETHOD"
ALTER TABLE "DB2ADMIN"."CALMETHOD"
ADD PRIMARY KEY ("CALMETHOD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALMETHOD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000055" ON "DB2ADMIN"."CALMETHOD" (
    "SUBCLASS" ASC,
    "CALUSAGE_ID" ASC,
    "STOREENT_ID" ASC,
    "NAME" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALMETHOD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000501" ON "DB2ADMIN"."CALMETHOD" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALMETHOD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000502" ON "DB2ADMIN"."CALMETHOD" ("CALUSAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALRANGE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALRANGE" (
    "CALRANGE_ID" INTEGER NOT NULL,
    "CALSCALE_ID" INTEGER,
    "CALMETHOD_ID" INTEGER NOT NULL,
    "RANGESTART" DECIMAL(20, 5),
    "CUMULATIVE" INTEGER NOT NULL WITH DEFAULT 0,
    "FIELD1" DECIMAL(20, 5),
    "FIELD2" DECIMAL(20, 5),
    "FIELD3" VARCHAR(254 OCTETS),
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALRANGE"
ALTER TABLE "DB2ADMIN"."CALRANGE"
ADD PRIMARY KEY ("CALRANGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALRANGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000056" ON "DB2ADMIN"."CALRANGE" ("CALSCALE_ID" ASC, "RANGESTART" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALRANGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000503" ON "DB2ADMIN"."CALRANGE" ("CALMETHOD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALRLOOKUP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALRLOOKUP" (
    "CALRLOOKUP_ID" INTEGER NOT NULL,
    "SETCCURR" CHAR(3 OCTETS),
    "CALRANGE_ID" INTEGER NOT NULL,
    "VALUE" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALRLOOKUP"
ALTER TABLE "DB2ADMIN"."CALRLOOKUP"
ADD PRIMARY KEY ("CALRLOOKUP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALRLOOKUP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000057" ON "DB2ADMIN"."CALRLOOKUP" ("CALRANGE_ID" ASC, "SETCCURR" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALRULE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALRULE" (
    "CALRULE_ID" INTEGER NOT NULL,
    "CALCODE_ID" INTEGER NOT NULL,
    "STARTDATE" TIMESTAMP,
    "TAXCGRY_ID" INTEGER,
    "ENDDATE" TIMESTAMP,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "COMBINATION" INTEGER NOT NULL WITH DEFAULT 2,
    "CALMETHOD_ID" INTEGER NOT NULL,
    "CALMETHOD_ID_QFY" INTEGER NOT NULL,
    "FIELD1" DECIMAL(20, 5),
    "FIELD2" VARCHAR(254 OCTETS),
    "FLAGS" INTEGER NOT NULL WITH DEFAULT 0,
    "IDENTIFIER" INTEGER NOT NULL WITH DEFAULT 1,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALRULE"
ALTER TABLE "DB2ADMIN"."CALRULE"
ADD PRIMARY KEY ("CALRULE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALRULE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000058" ON "DB2ADMIN"."CALRULE" ("CALCODE_ID" ASC, "IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALRULE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000504" ON "DB2ADMIN"."CALRULE" ("TAXCGRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALRULE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000505" ON "DB2ADMIN"."CALRULE" ("CALMETHOD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALRULE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000506" ON "DB2ADMIN"."CALRULE" ("CALMETHOD_ID_QFY" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALRULEMGP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALRULEMGP" (
    "CALRULE_ID" INTEGER NOT NULL,
    "MBRGRP_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALRULEMGP"
ALTER TABLE "DB2ADMIN"."CALRULEMGP"
ADD PRIMARY KEY ("MBRGRP_ID", "CALRULE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALRULEMGP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000507" ON "DB2ADMIN"."CALRULEMGP" ("CALRULE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALSCALE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALSCALE" (
    "CALSCALE_ID" INTEGER NOT NULL,
    "QTYUNIT_ID" CHAR(16 OCTETS),
    "CODE" CHAR(30 OCTETS),
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "STOREENT_ID" INTEGER NOT NULL,
    "CALUSAGE_ID" INTEGER NOT NULL,
    "SETCCURR" CHAR(3 OCTETS),
    "CALMETHOD_ID" INTEGER NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALSCALE"
ALTER TABLE "DB2ADMIN"."CALSCALE"
ADD PRIMARY KEY ("CALSCALE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALSCALE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000059" ON "DB2ADMIN"."CALSCALE" (
    "CALUSAGE_ID" ASC,
    "CODE" ASC,
    "STOREENT_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALSCALE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000508" ON "DB2ADMIN"."CALSCALE" ("CALMETHOD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALSCALE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000509" ON "DB2ADMIN"."CALSCALE" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALSCALEDS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALSCALEDS" (
    "CALSCALE_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALSCALEDS"
ALTER TABLE "DB2ADMIN"."CALSCALEDS"
ADD PRIMARY KEY ("LANGUAGE_ID", "CALSCALE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CALSCALEDS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000510" ON "DB2ADMIN"."CALSCALEDS" ("CALSCALE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CALUSAGE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CALUSAGE" (
    "CALUSAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "STRELTYPNAMECFG" VARCHAR(60 OCTETS),
    "STRELTYPNAMERT" VARCHAR(60 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CALUSAGE"
ALTER TABLE "DB2ADMIN"."CALUSAGE"
ADD PRIMARY KEY ("CALUSAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CAMPAIGN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CAMPAIGN" (
    "CAMPAIGN_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(64 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "TYPE" INTEGER,
    "STATUS" CHAR(1 OCTETS),
    "FIELD1" VARCHAR(254 OCTETS),
    "LASTUPDATE" TIMESTAMP NOT NULL,
    "LASTUPDATEDBY" VARCHAR(254 OCTETS) NOT NULL,
    "OWNER" VARCHAR(64 OCTETS),
    "OBJECTIVE" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CAMPAIGN"
ALTER TABLE "DB2ADMIN"."CAMPAIGN"
ADD PRIMARY KEY ("CAMPAIGN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CAMPAIGN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000060" ON "DB2ADMIN"."CAMPAIGN" ("NAME" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CAMPAIGN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000511" ON "DB2ADMIN"."CAMPAIGN" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATALOG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATALOG" (
    "CATALOG_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "TPCLEVEL" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATALOG"
ALTER TABLE "DB2ADMIN"."CATALOG"
ADD PRIMARY KEY ("CATALOG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATALOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000061" ON "DB2ADMIN"."CATALOG" ("MEMBER_ID" ASC, "IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATALOGDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATALOGDSC" (
    "CATALOG_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "SHORTDESCRIPTION" VARCHAR(254 OCTETS),
    "LONGDESCRIPTION" VARCHAR(4000 OCTETS),
    "THUMBNAIL" VARCHAR(254 OCTETS),
    "FULLIMAGE" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATALOGDSC"
ALTER TABLE "DB2ADMIN"."CATALOGDSC"
ADD PRIMARY KEY ("LANGUAGE_ID", "CATALOG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATALOGDSC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000512" ON "DB2ADMIN"."CATALOGDSC" ("CATALOG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATCLSFCOD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATCLSFCOD" (
    "CATENTRY_ID" BIGINT NOT NULL,
    "DOMAIN" CHAR(32 OCTETS) NOT NULL,
    "CODE" CHAR(16 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATCLSFCOD"
ALTER TABLE "DB2ADMIN"."CATCLSFCOD"
ADD PRIMARY KEY ("CATENTRY_ID", "DOMAIN");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATCNTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATCNTR" (
    "CATALOG_ID" BIGINT NOT NULL,
    "CONTRACT_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATCNTR"
ALTER TABLE "DB2ADMIN"."CATCNTR"
ADD PRIMARY KEY ("CONTRACT_ID", "CATALOG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATCNTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000513" ON "DB2ADMIN"."CATCNTR" ("CATALOG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATCONFINF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATCONFINF" (
    "CATENTRY_ID" BIGINT NOT NULL,
    "URL" VARCHAR(254 OCTETS),
    "REFERENCE" VARCHAR(4000 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" DOUBLE,
    "FIELD3" VARCHAR(254 OCTETS),
    "FIELD4" VARCHAR(254 OCTETS),
    "FIELD5" TIMESTAMP,
    "OPTCOUNTER" SMALLINT,
    "CONFIGURATION" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "CONFIGURABLE" SMALLINT WITH DEFAULT 1
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATCONFINF"
ALTER TABLE "DB2ADMIN"."CATCONFINF"
ADD PRIMARY KEY ("CATENTRY_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATENCALCD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATENCALCD" (
    "STORE_ID" INTEGER NOT NULL,
    "CATENCALCD_ID" BIGINT NOT NULL,
    "TRADING_ID" BIGINT,
    "CATENTRY_ID" BIGINT,
    "CALCODE_ID" INTEGER,
    "OPTCOUNTER" SMALLINT,
    "CALFLAGS" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATENCALCD"
ALTER TABLE "DB2ADMIN"."CATENCALCD"
ADD PRIMARY KEY ("CATENCALCD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENCALCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000062" ON "DB2ADMIN"."CATENCALCD" (
    "STORE_ID" ASC,
    "CATENTRY_ID" ASC,
    "CALCODE_ID" ASC,
    "TRADING_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENCALCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000514" ON "DB2ADMIN"."CATENCALCD" ("CALCODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENCALCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000515" ON "DB2ADMIN"."CATENCALCD" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENCALCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000516" ON "DB2ADMIN"."CATENCALCD" ("TRADING_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATENTATTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATENTATTR" (
    "CATENTATTR_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "VALUE" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATENTATTR"
ALTER TABLE "DB2ADMIN"."CATENTATTR"
ADD PRIMARY KEY ("CATENTATTR_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000063" ON "DB2ADMIN"."CATENTATTR" (
    "CATENTRY_ID" ASC,
    "LANGUAGE_ID" ASC,
    "NAME" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATENTDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATENTDESC" (
    "CATENTRY_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "NAME" CHAR(128 OCTETS),
    "SHORTDESCRIPTION" VARCHAR(254 OCTETS),
    "LONGDESCRIPTION" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "THUMBNAIL" VARCHAR(254 OCTETS),
    "AUXDESCRIPTION1" VARCHAR(4000 OCTETS),
    "FULLIMAGE" VARCHAR(254 OCTETS),
    "AUXDESCRIPTION2" VARCHAR(4000 OCTETS),
    "XMLDETAIL" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "AVAILABLE" INTEGER NOT NULL,
    "PUBLISHED" INTEGER NOT NULL,
    "AVAILABILITYDATE" TIMESTAMP,
    "KEYWORD" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "UP_NAME" CHAR(128 OCTETS) GENERATED ALWAYS AS (UPPER(NAME))
) IN "TAB16K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATENTDESC"
ALTER TABLE "DB2ADMIN"."CATENTDESC"
ADD PRIMARY KEY ("CATENTRY_ID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000304" ON "DB2ADMIN"."CATENTDESC" (
    "LANGUAGE_ID" ASC,
    "CATENTRY_ID" ASC,
    "NAME" ASC,
    "PUBLISHED" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001196" ON "DB2ADMIN"."CATENTDESC" (
    "NAME" ASC,
    "LANGUAGE_ID" ASC,
    "PUBLISHED" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001248" ON "DB2ADMIN"."CATENTDESC" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00002" ON "DB2ADMIN"."CATENTDESC" ("UP_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATENTREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATENTREL" (
    "CATENTRY_ID_PARENT" BIGINT NOT NULL,
    "CATRELTYPE_ID" CHAR(32 OCTETS) NOT NULL,
    "CATENTRY_ID_CHILD" BIGINT NOT NULL,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "QUANTITY" DOUBLE,
    "GROUPNAME" VARCHAR(254 OCTETS),
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" INTEGER,
    "FIELD3" DECIMAL(20, 5),
    "OID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "MANDATORY" CHAR(3 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATENTREL"
ALTER TABLE "DB2ADMIN"."CATENTREL"
ADD PRIMARY KEY (
        "CATRELTYPE_ID",
        "CATENTRY_ID_PARENT",
        "CATENTRY_ID_CHILD"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000365" ON "DB2ADMIN"."CATENTREL" ("CATENTRY_ID_CHILD" ASC, "CATRELTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000517" ON "DB2ADMIN"."CATENTREL" ("CATENTRY_ID_PARENT" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATENTRY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATENTRY" (
    "CATENTRY_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "ITEMSPC_ID" BIGINT,
    "CATENTTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "PARTNUMBER" VARCHAR(64 OCTETS) NOT NULL,
    "MFPARTNUMBER" VARCHAR(64 OCTETS),
    "MFNAME" VARCHAR(64 OCTETS),
    "MARKFORDELETE" INTEGER NOT NULL,
    "URL" VARCHAR(254 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" INTEGER,
    "LASTUPDATE" TIMESTAMP,
    "FIELD3" DECIMAL(20, 5),
    "ONSPECIAL" INTEGER,
    "ONAUCTION" INTEGER,
    "FIELD4" VARCHAR(254 OCTETS),
    "FIELD5" VARCHAR(254 OCTETS),
    "BUYABLE" INTEGER,
    "OID" VARCHAR(64 OCTETS),
    "BASEITEM_ID" BIGINT,
    "STATE" CHAR(1 OCTETS) WITH DEFAULT '1',
    "STARTDATE" TIMESTAMP,
    "ENDDATE" TIMESTAMP,
    "RANK" DOUBLE,
    "OPTCOUNTER" SMALLINT,
    "AVAILABILITYDATE" TIMESTAMP,
    "LASTORDERDATE" TIMESTAMP,
    "ENDOFSERVICEDATE" TIMESTAMP,
    "DISCONTINUEDATE" TIMESTAMP,
    "UP_MFNAME" VARCHAR(64 OCTETS) GENERATED ALWAYS AS (UPPER(MFNAME)),
    "UP_MFPARTNUMBER" VARCHAR(64 OCTETS) GENERATED ALWAYS AS (UPPER(MFPARTNUMBER)),
    "UP_PARTNUMBER" VARCHAR(64 OCTETS) GENERATED ALWAYS AS (UPPER(PARTNUMBER))
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATENTRY"
ALTER TABLE "DB2ADMIN"."CATENTRY"
ADD PRIMARY KEY ("CATENTRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000064" ON "DB2ADMIN"."CATENTRY" ("PARTNUMBER" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000065" ON "DB2ADMIN"."CATENTRY" ("CATENTRY_ID" ASC, "MARKFORDELETE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I263121" ON "DB2ADMIN"."CATENTRY" ("ITEMSPC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I263122" ON "DB2ADMIN"."CATENTRY" ("BASEITEM_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I263103" ON "DB2ADMIN"."CATENTRY" ("CATENTRY_ID" ASC, "CATENTTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000305" ON "DB2ADMIN"."CATENTRY" (
    "BUYABLE" ASC,
    "CATENTRY_ID" ASC,
    "CATENTTYPE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000375" ON "DB2ADMIN"."CATENTRY" ("RANK" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000518" ON "DB2ADMIN"."CATENTRY" ("CATENTTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000519" ON "DB2ADMIN"."CATENTRY" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00003" ON "DB2ADMIN"."CATENTRY" ("UP_PARTNUMBER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00020" ON "DB2ADMIN"."CATENTRY" ("UP_MFNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00021" ON "DB2ADMIN"."CATENTRY" ("UP_MFPARTNUMBER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATENTRYATTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATENTRYATTR" (
    "CATENTRY_ID" BIGINT NOT NULL,
    "ATTR_ID" BIGINT NOT NULL,
    "ATTRVAL_ID" BIGINT NOT NULL WITH DEFAULT 0,
    "USAGE" CHAR(1 OCTETS) NOT NULL,
    "SEQUENCE" DOUBLE,
    "FIELD1" INTEGER,
    "FIELD2" INTEGER,
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATENTRYATTR"
ALTER TABLE "DB2ADMIN"."CATENTRYATTR"
ADD PRIMARY KEY ("CATENTRY_ID", "ATTR_ID", "ATTRVAL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRYATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001202" ON "DB2ADMIN"."CATENTRYATTR" ("CATENTRY_ID" ASC, "USAGE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRYATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001463" ON "DB2ADMIN"."CATENTRYATTR" ("ATTR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTRYATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001462" ON "DB2ADMIN"."CATENTRYATTR" ("ATTRVAL_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATENTSHIP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATENTSHIP" (
    "CATENTRY_ID" BIGINT NOT NULL,
    "WEIGHT" DOUBLE,
    "WEIGHTMEASURE" CHAR(16 OCTETS),
    "LENGTH" DOUBLE,
    "WIDTH" DOUBLE,
    "HEIGHT" DOUBLE,
    "SIZEMEASURE" CHAR(16 OCTETS),
    "NOMINALQUANTITY" DOUBLE NOT NULL WITH DEFAULT 1.0,
    "QUANTITYMULTIPLE" DOUBLE NOT NULL WITH DEFAULT 1.0,
    "QUANTITYMEASURE" CHAR(16 OCTETS) NOT NULL WITH DEFAULT 'C62',
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATENTSHIP"
ALTER TABLE "DB2ADMIN"."CATENTSHIP"
ADD PRIMARY KEY ("CATENTRY_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATENTTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATENTTYPE" (
    "CATENTTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATENTTYPE"
ALTER TABLE "DB2ADMIN"."CATENTTYPE"
ADD PRIMARY KEY ("CATENTTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATGPCALCD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATGPCALCD" (
    "STORE_ID" INTEGER NOT NULL,
    "CATGPCALCD_ID" BIGINT NOT NULL,
    "TRADING_ID" BIGINT,
    "CATGROUP_ID" BIGINT NOT NULL,
    "CALCODE_ID" INTEGER,
    "OPTCOUNTER" SMALLINT,
    "CALFLAGS" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATGPCALCD"
ALTER TABLE "DB2ADMIN"."CATGPCALCD"
ADD PRIMARY KEY ("CATGPCALCD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGPCALCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000066" ON "DB2ADMIN"."CATGPCALCD" (
    "STORE_ID" ASC,
    "CATGROUP_ID" ASC,
    "CALCODE_ID" ASC,
    "TRADING_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGPCALCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000520" ON "DB2ADMIN"."CATGPCALCD" ("CALCODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGPCALCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000521" ON "DB2ADMIN"."CATGPCALCD" ("CATGROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGPCALCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000522" ON "DB2ADMIN"."CATGPCALCD" ("TRADING_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATGPENREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATGPENREL" (
    "CATGROUP_ID" BIGINT NOT NULL,
    "CATALOG_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "RULE" VARCHAR(254 OCTETS),
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "LASTUPDATE" TIMESTAMP,
    "OPTCOUNTER" SMALLINT,
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" INTEGER,
    "FIELD3" DECIMAL(20, 5)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATGPENREL"
ALTER TABLE "DB2ADMIN"."CATGPENREL"
ADD PRIMARY KEY ("CATGROUP_ID", "CATENTRY_ID", "CATALOG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGPENREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000523" ON "DB2ADMIN"."CATGPENREL" ("CATALOG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGPENREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000524" ON "DB2ADMIN"."CATGPENREL" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGPENREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001546" ON "DB2ADMIN"."CATGPENREL" (
    "CATGROUP_ID" ASC,
    "CATALOG_ID" ASC,
    "CATENTRY_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATGROUP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATGROUP" (
    "CATGROUP_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(254 OCTETS),
    "MARKFORDELETE" INTEGER NOT NULL,
    "LASTUPDATE" TIMESTAMP,
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "OID" VARCHAR(64 OCTETS),
    "RANK" DOUBLE,
    "OPTCOUNTER" SMALLINT,
    "UP_IDENTIFIER" VARCHAR(254 OCTETS) GENERATED ALWAYS AS (UPPER(IDENTIFIER)),
    "DYNAMIC" INTEGER WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATGROUP"
ALTER TABLE "DB2ADMIN"."CATGROUP"
ADD PRIMARY KEY ("CATGROUP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGROUP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000067" ON "DB2ADMIN"."CATGROUP" ("IDENTIFIER" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGROUP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000376" ON "DB2ADMIN"."CATGROUP" ("RANK" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGROUP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000525" ON "DB2ADMIN"."CATGROUP" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGROUP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00001" ON "DB2ADMIN"."CATGROUP" ("UP_IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATGRPATTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATGRPATTR" (
    "CATGRPATTR_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CATGROUP_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OID" CHAR(32 OCTETS),
    "SEQUENCE" DOUBLE,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATGRPATTR"
ALTER TABLE "DB2ADMIN"."CATGRPATTR"
ADD PRIMARY KEY ("LANGUAGE_ID", "CATGRPATTR_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000068" ON "DB2ADMIN"."CATGRPATTR" (
    "CATGROUP_ID" ASC,
    "LANGUAGE_ID" ASC,
    "NAME" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATGRPDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATGRPDESC" (
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CATGROUP_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "SHORTDESCRIPTION" VARCHAR(254 OCTETS),
    "LONGDESCRIPTION" VARCHAR(4000 OCTETS),
    "THUMBNAIL" VARCHAR(254 OCTETS),
    "FULLIMAGE" VARCHAR(254 OCTETS),
    "PUBLISHED" INTEGER NOT NULL,
    "DISPLAY" VARCHAR(254 OCTETS),
    "KEYWORD" VARCHAR(254 OCTETS),
    "NOTE" VARCHAR(4000 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "UP_NAME" CHAR(254 OCTETS) GENERATED ALWAYS AS (UPPER(NAME)),
    "UP_SHORTDESC" CHAR(254 OCTETS) GENERATED ALWAYS AS (UPPER(SHORTDESCRIPTION))
) IN "TAB16K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATGRPDESC"
ALTER TABLE "DB2ADMIN"."CATGRPDESC"
ADD PRIMARY KEY ("CATGROUP_ID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00022" ON "DB2ADMIN"."CATGRPDESC" ("UP_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00023" ON "DB2ADMIN"."CATGRPDESC" ("UP_SHORTDESC" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATGRPPS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATGRPPS" (
    "CATALOG_ID" BIGINT NOT NULL,
    "CATGROUP_ID" BIGINT NOT NULL,
    "PRODUCTSET_ID" INTEGER NOT NULL,
    "USAGE" CHAR(1 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATGRPPS"
ALTER TABLE "DB2ADMIN"."CATGRPPS"
ADD PRIMARY KEY (
        "CATALOG_ID",
        "CATGROUP_ID",
        "PRODUCTSET_ID"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPPS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000291" ON "DB2ADMIN"."CATGRPPS" (
    "CATALOG_ID" ASC,
    "CATGROUP_ID" ASC,
    "USAGE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPPS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000292" ON "DB2ADMIN"."CATGRPPS" ("PRODUCTSET_ID" ASC, "USAGE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPPS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000526" ON "DB2ADMIN"."CATGRPPS" ("CATGROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATGRPREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATGRPREL" (
    "CATGROUP_ID_PARENT" BIGINT NOT NULL,
    "CATGROUP_ID_CHILD" BIGINT NOT NULL,
    "CATALOG_ID" BIGINT NOT NULL,
    "RULE" VARCHAR(254 OCTETS),
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "LASTUPDATE" TIMESTAMP,
    "CATALOG_ID_LINK" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATGRPREL"
ALTER TABLE "DB2ADMIN"."CATGRPREL"
ADD PRIMARY KEY (
        "CATGROUP_ID_CHILD",
        "CATGROUP_ID_PARENT",
        "CATALOG_ID"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000294" ON "DB2ADMIN"."CATGRPREL" ("CATALOG_ID_LINK" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000527" ON "DB2ADMIN"."CATGRPREL" ("CATALOG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000528" ON "DB2ADMIN"."CATGRPREL" ("CATGROUP_ID_PARENT" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IDXCACHEIVL_CATGRPREL1" ON "DB2ADMIN"."CATGRPREL" ("CATGROUP_ID_CHILD" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IDXCACHEIVL_CATGRPREL2" ON "DB2ADMIN"."CATGRPREL" ("CATALOG_ID" ASC, "CATGROUP_ID_CHILD" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATGRPTPC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATGRPTPC" (
    "CATALOG_ID" BIGINT NOT NULL,
    "CATGROUP_ID" BIGINT NOT NULL WITH DEFAULT 0,
    "TRADEPOSCN_ID" BIGINT NOT NULL,
    "STORE_ID" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATGRPTPC"
ALTER TABLE "DB2ADMIN"."CATGRPTPC"
ADD PRIMARY KEY (
        "CATALOG_ID",
        "CATGROUP_ID",
        "TRADEPOSCN_ID",
        "STORE_ID"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPTPC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000529" ON "DB2ADMIN"."CATGRPTPC" ("TRADEPOSCN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPTPC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000530" ON "DB2ADMIN"."CATGRPTPC" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPTPC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000531" ON "DB2ADMIN"."CATGRPTPC" ("CATGROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATRELTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATRELTYPE" (
    "CATRELTYPE_ID" CHAR(32 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" DECIMAL(20, 5),
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATRELTYPE"
ALTER TABLE "DB2ADMIN"."CATRELTYPE"
ADD PRIMARY KEY ("CATRELTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATTOGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATTOGRP" (
    "CATALOG_ID" BIGINT NOT NULL,
    "CATGROUP_ID" BIGINT NOT NULL,
    "LASTUPDATE" TIMESTAMP,
    "SEQUENCE" DOUBLE,
    "CATALOG_ID_LINK" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATTOGRP"
ALTER TABLE "DB2ADMIN"."CATTOGRP"
ADD PRIMARY KEY ("CATALOG_ID", "CATGROUP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATTOGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000373" ON "DB2ADMIN"."CATTOGRP" ("CATALOG_ID_LINK" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATTOGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000532" ON "DB2ADMIN"."CATTOGRP" ("CATGROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CCCHECK"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CCCHECK" (
    "CCRFNBR" INTEGER NOT NULL,
    "CCTYPE" VARCHAR(40 OCTETS) NOT NULL,
    "CCLENGTH" INTEGER NOT NULL,
    "CCPREFIX" CHAR(16 OCTETS) NOT NULL,
    "CCALGTASKRN" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CCCHECK"
ALTER TABLE "DB2ADMIN"."CCCHECK"
ADD PRIMARY KEY ("CCRFNBR");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CCCHECK"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000069" ON "DB2ADMIN"."CCCHECK" (
    "CCTYPE" ASC,
    "CCLENGTH" ASC,
    "CCPREFIX" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CCOMMENT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CCOMMENT" (
    "CCOMMENT_ID" BIGINT NOT NULL,
    "CUSTOMERID" BIGINT NOT NULL,
    "TARGETID" BIGINT NOT NULL,
    "AUTHDOMAIN" BIGINT NOT NULL,
    "CREATEDBY" BIGINT NOT NULL,
    "LASTUPDATEDBY" BIGINT NOT NULL,
    "CREATETIMESTAMP" TIMESTAMP NOT NULL,
    "LASTUPDATETSTMP" TIMESTAMP NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS),
    "COMMENTDETAIL" VARCHAR(2000 OCTETS) NOT NULL
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CCOMMENT"
ALTER TABLE "DB2ADMIN"."CCOMMENT"
ADD PRIMARY KEY ("CCOMMENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CCOMMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000911" ON "DB2ADMIN"."CCOMMENT" ("CUSTOMERID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CCOMMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000912" ON "DB2ADMIN"."CCOMMENT" ("TARGETID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CCOMMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000913" ON "DB2ADMIN"."CCOMMENT" ("AUTHDOMAIN" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CCOMMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000914" ON "DB2ADMIN"."CCOMMENT" ("CREATEDBY" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CCOMMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000915" ON "DB2ADMIN"."CCOMMENT" ("LASTUPDATEDBY" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CCOMMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000916" ON "DB2ADMIN"."CCOMMENT" ("LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CERT_X509"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CERT_X509" (
    "CTSERNUM" CHAR(254 OCTETS) NOT NULL,
    "USERS_ID" BIGINT NOT NULL,
    "CTISSORGNM" CHAR(200 OCTETS) NOT NULL,
    "CTSBJCMNM" CHAR(254 OCTETS) NOT NULL,
    "CTSBJORGNM" CHAR(254 OCTETS) NOT NULL,
    "CTSBJEM" CHAR(254 OCTETS),
    "CTREQID" CHAR(254 OCTETS),
    "CTSTATUS" CHAR(4 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CERT_X509"
ALTER TABLE "DB2ADMIN"."CERT_X509"
ADD PRIMARY KEY ("USERS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CERT_X509"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000070" ON "DB2ADMIN"."CERT_X509" (
    "CTSERNUM" ASC,
    "CTISSORGNM" ASC,
    "CTSBJORGNM" ASC,
    "CTSBJCMNM" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CHARGETYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CHARGETYPE" (
    "CHARGETYPE_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "DISPLAYAGGREGATED" CHAR(1 OCTETS) NOT NULL,
    "CODE" CHAR(10 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CHARGETYPE"
ALTER TABLE "DB2ADMIN"."CHARGETYPE"
ADD PRIMARY KEY ("CHARGETYPE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CHARGETYPE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000071" ON "DB2ADMIN"."CHARGETYPE" ("STOREENT_ID" ASC, "CODE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CHKARRANG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CHKARRANG" (
    "CHKCMD_ID" INTEGER NOT NULL,
    "SCHCMD_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CHKARRANG"
ALTER TABLE "DB2ADMIN"."CHKARRANG"
ADD PRIMARY KEY ("CHKCMD_ID", "SCHCMD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CHKARRANG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000533" ON "DB2ADMIN"."CHKARRANG" ("SCHCMD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CHKCMD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CHKCMD" (
    "CHKCMD_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER,
    "DISPLAYNAME" VARCHAR(254 OCTETS),
    "INTERFACENAME" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CHKCMD"
ALTER TABLE "DB2ADMIN"."CHKCMD"
ADD PRIMARY KEY ("CHKCMD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CHKCMD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000534" ON "DB2ADMIN"."CHKCMD" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CHRGTYPDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CHRGTYPDSC" (
    "CHARGETYPE_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CHRGTYPDSC"
ALTER TABLE "DB2ADMIN"."CHRGTYPDSC"
ADD PRIMARY KEY ("CHARGETYPE_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CIITEMLIST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CIITEMLIST" (
    "IITEMLIST_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CIITEMLIST"
ALTER TABLE "DB2ADMIN"."CIITEMLIST"
ADD PRIMARY KEY ("IITEMLIST_ID", "MEMBER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CIITEMLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000535" ON "DB2ADMIN"."CIITEMLIST" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CLASIFCODE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CLASIFCODE" (
    "CLASIFCODE_ID" BIGINT NOT NULL,
    "DOMAIN" CHAR(32 OCTETS) NOT NULL,
    "CODE" CHAR(16 OCTETS) NOT NULL,
    "PARENTCODE" CHAR(16 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CLASIFCODE"
ALTER TABLE "DB2ADMIN"."CLASIFCODE"
ADD PRIMARY KEY ("CLASIFCODE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CLASIFCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000072" ON "DB2ADMIN"."CLASIFCODE" ("CODE" ASC, "DOMAIN" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CLCDPROMO"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CLCDPROMO" (
    "PX_PROMOTION_ID" INTEGER NOT NULL,
    "CALCODE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CLCDPROMO"
ALTER TABLE "DB2ADMIN"."CLCDPROMO"
ADD PRIMARY KEY ("PX_PROMOTION_ID", "CALCODE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CLCDPROMO"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000410" ON "DB2ADMIN"."CLCDPROMO" ("PX_PROMOTION_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CLCDPROMO"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000411" ON "DB2ADMIN"."CLCDPROMO" ("CALCODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CLEANCONF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CLEANCONF" (
    "OBJECTNAME" CHAR(40 OCTETS) NOT NULL,
    "TYPE" CHAR(40 OCTETS) NOT NULL,
    "STATEMENT" VARCHAR(4000 OCTETS) NOT NULL,
    "NAMEARG" CHAR(10 OCTETS) NOT NULL,
    "SEQUENCE" INTEGER NOT NULL,
    "DAYSARG" CHAR(10 OCTETS) NOT NULL,
    "STATEMENTTYPE" VARCHAR(120 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CLEANCONF"
ALTER TABLE "DB2ADMIN"."CLEANCONF"
ADD PRIMARY KEY ("OBJECTNAME", "TYPE", "SEQUENCE");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CLSFCODEDS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CLSFCODEDS" (
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CLASIFCODE_ID" BIGINT NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CLSFCODEDS"
ALTER TABLE "DB2ADMIN"."CLSFCODEDS"
ADD PRIMARY KEY ("LANGUAGE_ID", "CLASIFCODE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CLSFCODEDS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000536" ON "DB2ADMIN"."CLSFCODEDS" ("CLASIFCODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
---