------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ECEOUT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ECEOUT" (
    "ECREFNUM" INTEGER NOT NULL,
    "STORE_ID" INTEGER NOT NULL,
    "ECTYPE" CHAR(30 OCTETS) NOT NULL,
    "ECREQNUM" INTEGER NOT NULL,
    "ECSTAT" INTEGER,
    "ECFIELD1" VARCHAR(255 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ECEOUT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000096" ON "DB2ADMIN"."ECEOUT" ("ECREFNUM" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ECEOUT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000097" ON "DB2ADMIN"."ECEOUT" ("ECTYPE" ASC, "ECREQNUM" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ECEOUT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000562" ON "DB2ADMIN"."ECEOUT" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ECETMPT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ECETMPT" (
    "ECRFNBR" INTEGER NOT NULL,
    "ECDOCTYP" CHAR(8 OCTETS),
    "ECDOCVER" CHAR(2 OCTETS),
    "ECRECTYP" CHAR(10 OCTETS),
    "ECRECVER" CHAR(2 OCTETS),
    "ECCOMMANDNAME" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ECETMPT"
ALTER TABLE "DB2ADMIN"."ECETMPT"
ADD PRIMARY KEY ("ECRFNBR");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ECETMPT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000098" ON "DB2ADMIN"."ECETMPT" (
    "ECDOCTYP" ASC,
    "ECDOCVER" ASC,
    "ECRECTYP" ASC,
    "ECRECVER" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ECTPTITM"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ECTPTITM" (
    "ECITMRFNBR" INTEGER NOT NULL,
    "ECRFNBR" INTEGER,
    "ECSEQNO" INTEGER,
    "ECNAME" VARCHAR(64 OCTETS),
    "ECSIZE" INTEGER,
    "ECISTAG" CHAR(1 OCTETS),
    "ECFLDDT" CHAR(1 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ECTPTITM"
ALTER TABLE "DB2ADMIN"."ECTPTITM"
ADD PRIMARY KEY ("ECITMRFNBR");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ECTPTITM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000099" ON "DB2ADMIN"."ECTPTITM" ("ECSEQNO" ASC, "ECRFNBR" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EDPATMPAY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EDPATMPAY" (
    "EDPATMPAY_ID" BIGINT NOT NULL,
    "EDPPAYINST_ID" BIGINT,
    "TOTALAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "VALIDATIONAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "RESERVATIONAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "FINALIZATIONAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "VALIDATINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "RESERVINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "FINALIZINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "BACKENDPAYMENTID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "FIELD1" DECIMAL(20, 5),
    "FIELD2" DECIMAL(20, 5),
    "FIELD3" VARCHAR(254 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EDPATMPAY"
ALTER TABLE "DB2ADMIN"."EDPATMPAY"
ADD PRIMARY KEY ("EDPATMPAY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EDPATMPAY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000846" ON "DB2ADMIN"."EDPATMPAY" ("EDPPAYINST_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EDPATMREF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EDPATMREF" (
    "EDPATMREF_ID" BIGINT NOT NULL,
    "EDPREFINST_ID" BIGINT,
    "TOTALAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "REFUNDINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "BACKENDREFUNDID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "FIELD1" DECIMAL(20, 5),
    "FIELD2" DECIMAL(20, 5),
    "FIELD3" VARCHAR(254 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EDPATMREF"
ALTER TABLE "DB2ADMIN"."EDPATMREF"
ADD PRIMARY KEY ("EDPATMREF_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EDPATMREF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000851" ON "DB2ADMIN"."EDPATMREF" ("EDPREFINST_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EDPORDER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EDPORDER" (
    "EDPORDER_ID" BIGINT NOT NULL,
    "ORDER_ID" BIGINT,
    "STORE_ID" INTEGER,
    "INITIALAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "TOTALAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "CURRENCY" CHAR(3 OCTETS) NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "BLOCKED" INTEGER NOT NULL WITH DEFAULT 0,
    "BGJOBSTATUS" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EDPORDER"
ALTER TABLE "DB2ADMIN"."EDPORDER"
ADD PRIMARY KEY ("EDPORDER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EDPORDER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000843" ON "DB2ADMIN"."EDPORDER" ("STORE_ID" ASC, "ORDER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EDPPAYHIST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EDPPAYHIST" (
    "EDPPAYHIST_ID" BIGINT NOT NULL,
    "ORDER_ID" BIGINT,
    "RMA_ID" BIGINT,
    "STORE_ID" INTEGER,
    "HISTTIMESTAMP" TIMESTAMP NOT NULL,
    "AMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "OPERATIONNAME" VARCHAR(64 OCTETS) NOT NULL,
    "OPERATIONRESULT" VARCHAR(64 OCTETS) NOT NULL,
    "READABLESTATUS" VARCHAR(64 OCTETS) NOT NULL,
    "RECORDTYPE" VARCHAR(64 OCTETS) NOT NULL,
    "BACKENDPIID" VARCHAR(64 OCTETS),
    "BACKENDPAYMENTID" VARCHAR(64 OCTETS),
    "ACCOUNT" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "EDPPAYINST_ID" BIGINT,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EDPPAYHIST"
ALTER TABLE "DB2ADMIN"."EDPPAYHIST"
ADD PRIMARY KEY ("EDPPAYHIST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EDPPAYHIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000850" ON "DB2ADMIN"."EDPPAYHIST" ("ORDER_ID" ASC, "STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EDPPAYHIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000910" ON "DB2ADMIN"."EDPPAYHIST" ("EDPPAYINST_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EDPPAYINST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EDPPAYINST" (
    "EDPPAYINST_ID" BIGINT NOT NULL,
    "EDPORDER_ID" BIGINT,
    "AMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "SEQUENCENUMBER" INTEGER NOT NULL,
    "PRIORITY" INTEGER NOT NULL,
    "HUMANEDITABLE" INTEGER NOT NULL,
    "SYSTEMEDITABLE" INTEGER NOT NULL,
    "MAXAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT -1.00000,
    "MINAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "DEPRECATED" INTEGER NOT NULL WITH DEFAULT 0,
    "DIRTY" INTEGER NOT NULL WITH DEFAULT 0,
    "REFUNDALLOWED" INTEGER NOT NULL WITH DEFAULT 1,
    "PENDING" INTEGER NOT NULL WITH DEFAULT 0,
    "PAYMENTRULE" VARCHAR(64 OCTETS) NOT NULL,
    "PAYMENTMETHOD" VARCHAR(64 OCTETS) NOT NULL,
    "PAYMENTSYSTEM" VARCHAR(64 OCTETS) NOT NULL,
    "BACKENDPIID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "PAYCONFIGGROUP" VARCHAR(64 OCTETS) NOT NULL,
    "POLICY_ID" BIGINT NOT NULL,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EDPPAYINST"
ALTER TABLE "DB2ADMIN"."EDPPAYINST"
ADD PRIMARY KEY ("EDPPAYINST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EDPPAYINST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000844" ON "DB2ADMIN"."EDPPAYINST" ("EDPORDER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EDPPAYINST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000845" ON "DB2ADMIN"."EDPPAYINST" ("BACKENDPIID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EDPREFINST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EDPREFINST" (
    "EDPREFINST_ID" BIGINT NOT NULL,
    "EDPRMA_ID" BIGINT,
    "AMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "SEQUENCENUMBER" INTEGER NOT NULL,
    "PRIORITY" INTEGER NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "DEPRECATED" INTEGER NOT NULL WITH DEFAULT 0,
    "DIRTY" INTEGER NOT NULL WITH DEFAULT 0,
    "PENDING" INTEGER NOT NULL WITH DEFAULT 0,
    "PAYMENTSYSTEM" VARCHAR(64 OCTETS) NOT NULL,
    "REFUNDMETHOD" VARCHAR(64 OCTETS) NOT NULL,
    "BACKENDRIID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "POLICY_ID" BIGINT NOT NULL,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EDPREFINST"
ALTER TABLE "DB2ADMIN"."EDPREFINST"
ADD PRIMARY KEY ("EDPREFINST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EDPREFINST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000849" ON "DB2ADMIN"."EDPREFINST" ("EDPRMA_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EDPRELEASE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EDPRELEASE" (
    "EDPRELEASE_ID" BIGINT NOT NULL,
    "EDPORDER_ID" BIGINT,
    "RELEASE_ID" BIGINT NOT NULL,
    "TOTALAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "RESERVATIONAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "FINALIZATIONAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "RESERVINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "FINALIZINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "REQUESTFINALAMT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "FIELD1" DECIMAL(20, 5),
    "FIELD2" DECIMAL(20, 5),
    "FIELD3" VARCHAR(254 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EDPRELEASE"
ALTER TABLE "DB2ADMIN"."EDPRELEASE"
ADD PRIMARY KEY ("EDPRELEASE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EDPRELEASE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000847" ON "DB2ADMIN"."EDPRELEASE" ("EDPORDER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EDPRELHIST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EDPRELHIST" (
    "EDPPAYHIST_ID" BIGINT NOT NULL,
    "ORDER_ID" BIGINT NOT NULL,
    "RELEASE_ID" BIGINT NOT NULL,
    "STORE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EDPRELHIST"
ALTER TABLE "DB2ADMIN"."EDPRELHIST"
ADD PRIMARY KEY (
        "EDPPAYHIST_ID",
        "ORDER_ID",
        "RELEASE_ID",
        "STORE_ID"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."EDPRELHIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000852" ON "DB2ADMIN"."EDPRELHIST" (
    "ORDER_ID" ASC,
    "RELEASE_ID" ASC,
    "STORE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EDPRMA"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EDPRMA" (
    "EDPRMA_ID" BIGINT NOT NULL,
    "RMA_ID" BIGINT,
    "STORE_ID" INTEGER NOT NULL,
    "AMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "CURRENCY" CHAR(3 OCTETS) NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "BLOCKED" INTEGER NOT NULL WITH DEFAULT 0,
    "BGJOBSTATUS" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EDPRMA"
ALTER TABLE "DB2ADMIN"."EDPRMA"
ADD PRIMARY KEY ("EDPRMA_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EDPRMA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000848" ON "DB2ADMIN"."EDPRMA" ("STORE_ID" ASC, "RMA_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLBADADDR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLBADADDR" (
    "USERS_ID" BIGINT NOT NULL,
    "EMAIL1BAD" SMALLINT NOT NULL,
    "EMAIL2BAD" SMALLINT NOT NULL,
    "REASONCODE1" SMALLINT,
    "REASONCODE2" SMALLINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLBADADDR"
ALTER TABLE "DB2ADMIN"."EMLBADADDR"
ADD PRIMARY KEY ("USERS_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLBOUNCED"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLBOUNCED" (
    "EMLPROMO_ID" INTEGER NOT NULL,
    "USERS_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "STATUSCODE" VARCHAR(10 OCTETS),
    "LASTBOUNCE" TIMESTAMP,
    "LASTRETRY" TIMESTAMP,
    "RETRYCOUNT" SMALLINT,
    "MAXRETRYHIT" SMALLINT,
    "EMLADDRINDEX" SMALLINT NOT NULL,
    "EMAILADDRESS" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLBOUNCED"
ALTER TABLE "DB2ADMIN"."EMLBOUNCED"
ADD PRIMARY KEY ("EMLPROMO_ID", "USERS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLBOUNCED"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000378" ON "DB2ADMIN"."EMLBOUNCED" ("USERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLBOUNCED"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000379" ON "DB2ADMIN"."EMLBOUNCED" ("EMLPROMO_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLBOUNCED"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000380" ON "DB2ADMIN"."EMLBOUNCED" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLCAMPREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLCAMPREL" (
    "EMLPROMO_ID" INTEGER NOT NULL,
    "CAMPAIGN_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLCAMPREL"
ALTER TABLE "DB2ADMIN"."EMLCAMPREL"
ADD PRIMARY KEY ("EMLPROMO_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLCAMPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000377" ON "DB2ADMIN"."EMLCAMPREL" ("CAMPAIGN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLCFG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLCFG" (
    "EMLCFG_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(40 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "TYPE" INTEGER NOT NULL,
    "HOST" VARCHAR(254 OCTETS) NOT NULL,
    "TIME" INTEGER NOT NULL,
    "EMLSERVER" VARCHAR(254 OCTETS) NOT NULL,
    "ACCOUNT" VARCHAR(254 OCTETS) NOT NULL,
    "PORT" INTEGER NOT NULL,
    "PASSWORD" CHAR(128 OCTETS) FOR BIT DATA,
    "STOREENT_ID" INTEGER NOT NULL,
    "ADDRESS" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLCFG"
ALTER TABLE "DB2ADMIN"."EMLCFG"
ADD PRIMARY KEY ("EMLCFG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLCFG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000274" ON "DB2ADMIN"."EMLCFG" ("STOREENT_ID" ASC, "TYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLCONTENT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLCONTENT" (
    "EMLCONTENT_ID" INTEGER NOT NULL,
    "LASTMODIFY" TIMESTAMP,
    "RECORDOPEN" SMALLINT,
    "EMLSUBJECT" VARCHAR(254 OCTETS) NOT NULL,
    "EMLBODY" CLOB(10000000 OCTETS) LOGGED NOT COMPACT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLCONTENT"
ALTER TABLE "DB2ADMIN"."EMLCONTENT"
ADD PRIMARY KEY ("EMLCONTENT_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLGRPREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLGRPREL" (
    "MBRGRP_ID" BIGINT NOT NULL,
    "EMLPROMO_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLGRPREL"
ALTER TABLE "DB2ADMIN"."EMLGRPREL"
ADD PRIMARY KEY ("EMLPROMO_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLGRPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000563" ON "DB2ADMIN"."EMLGRPREL" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLMCREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLMCREL" (
    "EMLMSG_ID" INTEGER NOT NULL,
    "EMLCONTENT_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLMCREL"
ALTER TABLE "DB2ADMIN"."EMLMCREL"
ADD PRIMARY KEY ("EMLMSG_ID", "EMLCONTENT_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLMSG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLMSG" (
    "EMLMSG_ID" INTEGER NOT NULL,
    "JSPPATH" VARCHAR(254 OCTETS),
    "PROPERTYFILE" VARCHAR(254 OCTETS) NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "STOREENT_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "STATUS" SMALLINT NOT NULL WITH DEFAULT 1,
    "EMLBODYTYPE" SMALLINT NOT NULL WITH DEFAULT 0,
    "UP_NAME" VARCHAR(254 OCTETS) GENERATED ALWAYS AS (UPPER(NAME)),
    "UP_DESCRIPTION" VARCHAR(254 OCTETS) GENERATED ALWAYS AS (UPPER(DESCRIPTION))
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLMSG"
ALTER TABLE "DB2ADMIN"."EMLMSG"
ADD PRIMARY KEY ("EMLMSG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000288" ON "DB2ADMIN"."EMLMSG" ("STOREENT_ID" ASC, "NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00004" ON "DB2ADMIN"."EMLMSG" ("UP_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00005" ON "DB2ADMIN"."EMLMSG" ("UP_DESCRIPTION" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLPOLICY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLPOLICY" (
    "EMLPOLICY_ID" INTEGER NOT NULL,
    "NUMRETRIES" SMALLINT NOT NULL,
    "INTERVAL" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLPOLICY"
ALTER TABLE "DB2ADMIN"."EMLPOLICY"
ADD PRIMARY KEY ("EMLPOLICY_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLPROMO"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLPROMO" (
    "EMLPROMO_ID" INTEGER NOT NULL,
    "STATUS" INTEGER NOT NULL WITH DEFAULT 0,
    "MODIFIEDBY" VARCHAR(254 OCTETS),
    "MODDATE" TIMESTAMP,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "EMLMSG_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "SCCJOBREFNUM" BIGINT NOT NULL,
    "REPLYTO" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLPROMO"
ALTER TABLE "DB2ADMIN"."EMLPROMO"
ADD PRIMARY KEY ("EMLPROMO_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLPROMO"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000339" ON "DB2ADMIN"."EMLPROMO" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLPROMO"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000564" ON "DB2ADMIN"."EMLPROMO" ("EMLMSG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLPROMO"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000565" ON "DB2ADMIN"."EMLPROMO" ("SCCJOBREFNUM" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLRCPTS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLRCPTS" (
    "EMLPROMO_ID" INTEGER NOT NULL,
    "COUNT" INTEGER NOT NULL,
    "RECIPIENTS" CLOB(10000000 OCTETS) LOGGED NOT COMPACT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLRCPTS"
ALTER TABLE "DB2ADMIN"."EMLRCPTS"
ADD PRIMARY KEY ("EMLPROMO_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLRPTEVTS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLRPTEVTS" (
    "USERS_ID" BIGINT NOT NULL,
    "EMLPROMO_ID" INTEGER NOT NULL,
    "OPENED" TIMESTAMP,
    "CLICKED" TIMESTAMP,
    "BOUNCED" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLRPTEVTS"
ALTER TABLE "DB2ADMIN"."EMLRPTEVTS"
ADD PRIMARY KEY ("USERS_ID", "EMLPROMO_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLRPTEVTS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000566" ON "DB2ADMIN"."EMLRPTEVTS" ("EMLPROMO_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLSTRPLCY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLSTRPLCY" (
    "EMLPOLICY_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLSTRPLCY"
ALTER TABLE "DB2ADMIN"."EMLSTRPLCY"
ADD PRIMARY KEY ("EMLPOLICY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLSTRPLCY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000383" ON "DB2ADMIN"."EMLSTRPLCY" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMLUSRRECV"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMLUSRRECV" (
    "USERS_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "RECEIVEEML" INTEGER NOT NULL WITH DEFAULT 0,
    "RECEIVESMS" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMLUSRRECV"
ALTER TABLE "DB2ADMIN"."EMLUSRRECV"
ADD PRIMARY KEY ("USERS_ID", "STOREENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMLUSRRECV"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000567" ON "DB2ADMIN"."EMLUSRRECV" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EMSPOT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EMSPOT" (
    "EMSPOT_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(256 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "SUPPORTEDTYPES" VARCHAR(20 OCTETS),
    "LASTUPDATE" TIMESTAMP,
    "LASTUPDATEDBY" VARCHAR(254 OCTETS),
    "DEFAULTRULE" VARCHAR(4000 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "USAGETYPE" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT 'MARKETING',
    "UP_NAME" VARCHAR(256 OCTETS) GENERATED ALWAYS AS (UPPER(NAME)),
    "UP_DESCRIPTION" VARCHAR(254 OCTETS) GENERATED ALWAYS AS (UPPER(DESCRIPTION)),
    "UIDISPLAYABLE" SMALLINT,
    "MANAGINGTOOL" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EMSPOT"
ALTER TABLE "DB2ADMIN"."EMSPOT"
ADD PRIMARY KEY ("EMSPOT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMSPOT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000100" ON "DB2ADMIN"."EMSPOT" (
    "NAME" ASC,
    "STOREENT_ID" ASC,
    "USAGETYPE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMSPOT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000568" ON "DB2ADMIN"."EMSPOT" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMSPOT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00006" ON "DB2ADMIN"."EMSPOT" ("UP_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EMSPOT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00007" ON "DB2ADMIN"."EMSPOT" ("UP_DESCRIPTION" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ESMAPOBJ"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ESMAPOBJ" (
    "ESMAPOBJ_ID" INTEGER NOT NULL,
    "ESMAPTYP_ID" INTEGER NOT NULL,
    "OBJECT_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ESMAPOBJ"
ALTER TABLE "DB2ADMIN"."ESMAPOBJ"
ADD PRIMARY KEY ("ESMAPOBJ_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ESMAPOBJ"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000833" ON "DB2ADMIN"."ESMAPOBJ" ("ESMAPTYP_ID" ASC, "OBJECT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ESMAPTYP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ESMAPTYP" (
    "ESMAPTYP_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(20 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(100 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ESMAPTYP"
ALTER TABLE "DB2ADMIN"."ESMAPTYP"
ADD PRIMARY KEY ("ESMAPTYP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ESMAPTYP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000832" ON "DB2ADMIN"."ESMAPTYP" ("NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXCHORDERS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXCHORDERS" (
    "EX_ORD_ID" BIGINT NOT NULL,
    "RMA_ID" BIGINT NOT NULL,
    "CROSS_SHIP" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N',
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EXCHORDERS"
ALTER TABLE "DB2ADMIN"."EXCHORDERS"
ADD PRIMARY KEY ("EX_ORD_ID", "RMA_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXCHORDERS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001257" ON "DB2ADMIN"."EXCHORDERS" ("RMA_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPERIMENT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPERIMENT" (
    "EXPERIMENT_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(64 OCTETS) NOT NULL,
    "LASTUPDATE" TIMESTAMP NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "EXPTYPE_ID" INTEGER NOT NULL,
    "PRIORITY" SMALLINT NOT NULL WITH DEFAULT 1,
    "EXPIRECOUNT" INTEGER,
    "STARTDATE" TIMESTAMP NOT NULL,
    "ENDDATE" TIMESTAMP,
    "RESULTSCOPE" CHAR(1 OCTETS) NOT NULL,
    "PREFERREDELEMENT" SMALLINT,
    "STATUS" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'A',
    "FIELD1" INTEGER,
    "FIELD2" BIGINT,
    "FIELD3" DECIMAL(20, 5),
    "FIELD4" VARCHAR(254 OCTETS),
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "LASTUPDATEDBY" VARCHAR(254 OCTETS) NOT NULL,
    "RULEXML" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EXPERIMENT"
ALTER TABLE "DB2ADMIN"."EXPERIMENT"
ADD PRIMARY KEY ("EXPERIMENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXPERIMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001500" ON "DB2ADMIN"."EXPERIMENT" ("NAME" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXPERIMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001501" ON "DB2ADMIN"."EXPERIMENT" ("STOREENT_ID" ASC, "STATUS" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPLOG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPLOG" (
    "EXPLOG_ID" BIGINT NOT NULL,
    "EXPERIMENT_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "SESSIONID" CHAR(64 OCTETS) NOT NULL,
    "CREATED" TIMESTAMP NOT NULL,
    "TESTELEMENT_ID" INTEGER NOT NULL,
    "RESULTTYPE" CHAR(1 OCTETS),
    "CLICKED" CHAR(1 OCTETS) WITH DEFAULT '0',
    "RESULTS" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EXPLOG"
ALTER TABLE "DB2ADMIN"."EXPLOG"
ADD PRIMARY KEY ("EXPLOG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXPLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001502" ON "DB2ADMIN"."EXPLOG" ("SESSIONID" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPRESULT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPRESULT" (
    "EXPERIMENT_ID" INTEGER NOT NULL,
    "SESSION_ID" VARCHAR(64 OCTETS) NOT NULL,
    "USERS_ID" BIGINT NOT NULL,
    "RESULTNUMBER" SMALLINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EXPRESULT"
ALTER TABLE "DB2ADMIN"."EXPRESULT"
ADD PRIMARY KEY ("EXPERIMENT_ID", "SESSION_ID", "USERS_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPSTATS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPSTATS" (
    "EXPERIMENT_ID" INTEGER NOT NULL,
    "TESTELEMENT_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(64 OCTETS),
    "EXPTYPE_ID" INTEGER,
    "CONTROLELEMENT" CHAR(1 OCTETS) NOT NULL,
    "DISPLAYS" INTEGER WITH DEFAULT 0,
    "CLICKS" INTEGER WITH DEFAULT 0,
    "DISPLAYORDERS" INTEGER WITH DEFAULT 0,
    "DISPLAYREVENUE" DECIMAL(20, 5) WITH DEFAULT 0,
    "CLICKORDERS" INTEGER WITH DEFAULT 0,
    "CLICKREVENUE" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "CURRENCY" CHAR(3 OCTETS),
    "FREQUENCY" VARCHAR(10 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" BIGINT,
    "FIELD3" DECIMAL(20, 5),
    "FIELD4" VARCHAR(254 OCTETS),
    "TESTELEMENTNAME" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EXPSTATS"
ALTER TABLE "DB2ADMIN"."EXPSTATS"
ADD PRIMARY KEY (
        "EXPERIMENT_ID",
        "TESTELEMENT_ID",
        "STOREENT_ID"
    );
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPTYPE" (
    "EXPTYPE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(64 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "IMPLCLS" VARCHAR(254 OCTETS) NOT NULL,
    "OBJCLS" VARCHAR(254 OCTETS) NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EXPTYPE"
ALTER TABLE "DB2ADMIN"."EXPTYPE"
ADD PRIMARY KEY ("EXPTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FFMCENTDS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FFMCENTDS" (
    "FFMCENTER_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "STADDRESS_ID" INTEGER,
    "DESCRIPTION" VARCHAR(4000 OCTETS),
    "DISPLAYNAME" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FFMCENTDS"
ALTER TABLE "DB2ADMIN"."FFMCENTDS"
ADD PRIMARY KEY ("FFMCENTER_ID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FFMCENTDS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000570" ON "DB2ADMIN"."FFMCENTDS" ("STADDRESS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FFMCENTER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FFMCENTER" (
    "FFMCENTER_ID" INTEGER NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(254 OCTETS),
    "DEFAULTSHIPOFFSET" INTEGER NOT NULL WITH DEFAULT 86400,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "EXTFFMSTORENUM" VARCHAR(128 OCTETS),
    "INVENTORYOPFLAGS" INTEGER NOT NULL WITH DEFAULT 0,
    "MAXNUMPICK" SMALLINT NOT NULL WITH DEFAULT 25,
    "PICKDELAYINMIN" SMALLINT NOT NULL WITH DEFAULT 5,
    "OPTCOUNTER" SMALLINT,
    "DROPSHIP" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N'
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FFMCENTER"
ALTER TABLE "DB2ADMIN"."FFMCENTER"
ADD PRIMARY KEY ("FFMCENTER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FFMCENTER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000101" ON "DB2ADMIN"."FFMCENTER" ("MEMBER_ID" ASC, "NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FILEUPLOAD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FILEUPLOAD" (
    "FILEUPLOAD_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT,
    "STORE_ID" INTEGER,
    "SCCJOBREFNUM" BIGINT,
    "FILEPATH" VARCHAR(254 OCTETS) NOT NULL,
    "FILENAME" VARCHAR(254 OCTETS),
    "FILESIZE" BIGINT,
    "FILETYPE" CHAR(50 OCTETS),
    "FILEENCODING" VARCHAR(128 OCTETS),
    "UPLOADTIME" TIMESTAMP,
    "HOSTNAME" CHAR(50 OCTETS),
    "VERSION" INTEGER NOT NULL,
    "STATUS" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FILEUPLOAD"
ALTER TABLE "DB2ADMIN"."FILEUPLOAD"
ADD PRIMARY KEY ("FILEUPLOAD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FILEUPLOAD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000295" ON "DB2ADMIN"."FILEUPLOAD" ("FILEPATH" ASC, "VERSION" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FILEUPLOAD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000296" ON "DB2ADMIN"."FILEUPLOAD" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FILEUPLOAD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000571" ON "DB2ADMIN"."FILEUPLOAD" ("SCCJOBREFNUM" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FILEUPLOAD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000572" ON "DB2ADMIN"."FILEUPLOAD" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLCOMPOSE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLCOMPOSE" (
    "COMPOSITEFLOW_ID" BIGINT NOT NULL,
    "SINGLEFLOW_ID" BIGINT NOT NULL,
    "SEQUENCE" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLCOMPOSE"
ALTER TABLE "DB2ADMIN"."FLCOMPOSE"
ADD PRIMARY KEY (
        "COMPOSITEFLOW_ID",
        "SINGLEFLOW_ID",
        "SEQUENCE"
    );
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLDOMNDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLDOMNDESC" (
    "FLOWDOMAIN_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(128 OCTETS),
    "LONGDESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLDOMNDESC"
ALTER TABLE "DB2ADMIN"."FLDOMNDESC"
ADD PRIMARY KEY ("FLOWDOMAIN_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLINSTANCE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLINSTANCE" (
    "FLOW_ID" BIGINT NOT NULL,
    "FLOWTYPE_ID" BIGINT NOT NULL,
    "ENTITY_ID" BIGINT NOT NULL,
    "CURSTATEIDENTIFIER" INTEGER NOT NULL,
    "FLOWSTAGES" VARCHAR(254 OCTETS),
    "CURRSTAGEINDEX" INTEGER,
    "LASTUPDATETIME" TIMESTAMP,
    "FLOWCONTEXT" VARCHAR(3600 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLINSTANCE"
ALTER TABLE "DB2ADMIN"."FLINSTANCE"
ADD PRIMARY KEY ("FLOWTYPE_ID", "ENTITY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FLINSTANCE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000102" ON "DB2ADMIN"."FLINSTANCE" ("FLOW_ID" ASC, "ENTITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLOW"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLOW" (
    "FLOW_ID" BIGINT NOT NULL,
    "FLOWTYPE_ID" BIGINT NOT NULL,
    "COMPOSITEFLOW" INTEGER,
    "ATTRIBUTE" VARCHAR(254 OCTETS),
    "IDENTIFIER" VARCHAR(64 OCTETS) NOT NULL,
    "PRIORITY" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLOW"
ALTER TABLE "DB2ADMIN"."FLOW"
ADD PRIMARY KEY ("FLOW_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FLOW"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000103" ON "DB2ADMIN"."FLOW" ("FLOWTYPE_ID" ASC, "IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLOWADMIN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLOWADMIN" (
    "FLOWADMIN_ID" BIGINT NOT NULL,
    "FLOW_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "ORGENTITY_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLOWADMIN"
ALTER TABLE "DB2ADMIN"."FLOWADMIN"
ADD PRIMARY KEY ("FLOWADMIN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FLOWADMIN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000104" ON "DB2ADMIN"."FLOWADMIN" ("FLOW_ID" ASC, "ORGENTITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FLOWADMIN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000573" ON "DB2ADMIN"."FLOWADMIN" ("ORGENTITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FLOWADMIN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000574" ON "DB2ADMIN"."FLOWADMIN" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLOWDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLOWDESC" (
    "FLOW_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(128 OCTETS),
    "LONGDESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLOWDESC"
ALTER TABLE "DB2ADMIN"."FLOWDESC"
ADD PRIMARY KEY ("FLOW_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLOWDOMAIN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLOWDOMAIN" (
    "FLOWDOMAIN_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(64 OCTETS) NOT NULL,
    "PRIORITY" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLOWDOMAIN"
ALTER TABLE "DB2ADMIN"."FLOWDOMAIN"
ADD PRIMARY KEY ("FLOWDOMAIN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FLOWDOMAIN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000105" ON "DB2ADMIN"."FLOWDOMAIN" ("IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLOWTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLOWTYPE" (
    "FLOWTYPE_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(54 OCTETS) NOT NULL,
    "FLOWDOMAIN_ID" BIGINT NOT NULL,
    "BIZFLOWBEANCLASS" VARCHAR(254 OCTETS),
    "ATTRIBUTE" VARCHAR(254 OCTETS),
    "PRIORITY" INTEGER,
    "VIEWNAME" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLOWTYPE"
ALTER TABLE "DB2ADMIN"."FLOWTYPE"
ADD PRIMARY KEY ("FLOWTYPE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FLOWTYPE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000106" ON "DB2ADMIN"."FLOWTYPE" ("IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLSTATEDCT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLSTATEDCT" (
    "FLSTATEDCT_ID" BIGINT NOT NULL,
    "IDENTIFIER" INTEGER NOT NULL,
    "STATENAME" VARCHAR(32 OCTETS) NOT NULL,
    "FLOWTYPE_ID" BIGINT NOT NULL,
    "FLSTATEGP_ID" BIGINT,
    "APPROVERMBRGRPNAME" VARCHAR(254 OCTETS),
    "STATETYPE" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLSTATEDCT"
ALTER TABLE "DB2ADMIN"."FLSTATEDCT"
ADD PRIMARY KEY ("FLSTATEDCT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FLSTATEDCT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000107" ON "DB2ADMIN"."FLSTATEDCT" ("IDENTIFIER" ASC, "FLOWTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FLSTATEDCT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000108" ON "DB2ADMIN"."FLSTATEDCT" ("STATENAME" ASC, "FLOWTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FLSTATEDCT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000575" ON "DB2ADMIN"."FLSTATEDCT" ("FLSTATEGP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLSTATEGP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLSTATEGP" (
    "FLSTATEGP_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(32 OCTETS) NOT NULL,
    "FLOWTYPE_ID" BIGINT NOT NULL,
    "MANDATORYSTATEGP" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLSTATEGP"
ALTER TABLE "DB2ADMIN"."FLSTATEGP"
ADD PRIMARY KEY ("FLSTATEGP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FLSTATEGP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000109" ON "DB2ADMIN"."FLSTATEGP" ("IDENTIFIER" ASC, "FLOWTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLSTATEREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLSTATEREL" (
    "FLSTATEDCT_ID" BIGINT NOT NULL,
    "FLOW_ID" BIGINT NOT NULL,
    "ENTRYACTNINTERFACE" VARCHAR(254 OCTETS),
    "EXITACTNINTERFACE" VARCHAR(254 OCTETS),
    "RESPONSEVIEWNAME" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLSTATEREL"
ALTER TABLE "DB2ADMIN"."FLSTATEREL"
ADD PRIMARY KEY ("FLSTATEDCT_ID", "FLOW_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLSTDCTDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLSTDCTDSC" (
    "FLSTATEDCT_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLSTDCTDSC"
ALTER TABLE "DB2ADMIN"."FLSTDCTDSC"
ADD PRIMARY KEY ("FLSTATEDCT_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLSTGPDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLSTGPDSC" (
    "FLSTATEGP_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLSTGPDSC"
ALTER TABLE "DB2ADMIN"."FLSTGPDSC"
ADD PRIMARY KEY ("FLSTATEGP_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLTRANSDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLTRANSDSC" (
    "FLTRANSITN_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "TRANSITIONDESC" VARCHAR(254 OCTETS),
    "EVENTDESC" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLTRANSDSC"
ALTER TABLE "DB2ADMIN"."FLTRANSDSC"
ADD PRIMARY KEY ("FLTRANSITN_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLTRANSITN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLTRANSITN" (
    "FLTRANSITN_ID" BIGINT NOT NULL,
    "FLOW_ID" BIGINT NOT NULL,
    "SOURCESTATE_ID" BIGINT NOT NULL,
    "TARGETSTATE_ID" BIGINT NOT NULL,
    "PRIORITY" INTEGER,
    "EVENTIDENTIFIER" VARCHAR(64 OCTETS) NOT NULL,
    "APPROVAL" INTEGER NOT NULL,
    "ACTIONINTERFACE" VARCHAR(254 OCTETS),
    "ACCESSCTRLGUARD" VARCHAR(254 OCTETS) NOT NULL,
    "BUSINESSLOGICGUARD" VARCHAR(254 OCTETS),
    "SPAWNFLWTYPE_ID" BIGINT,
    "SPAWNTYPE" INTEGER,
    "RESPONSEVIEWNAME" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLTRANSITN"
ALTER TABLE "DB2ADMIN"."FLTRANSITN"
ADD PRIMARY KEY ("FLTRANSITN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FLTRANSITN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000110" ON "DB2ADMIN"."FLTRANSITN" (
    "FLOW_ID" ASC,
    "EVENTIDENTIFIER" ASC,
    "SOURCESTATE_ID" ASC,
    "TARGETSTATE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FLTYPEDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FLTYPEDESC" (
    "FLOWTYPE_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(128 OCTETS),
    "LONGDESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FLTYPEDESC"
ALTER TABLE "DB2ADMIN"."FLTYPEDESC"
ADD PRIMARY KEY ("FLOWTYPE_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FORUM"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FORUM" (
    "FORUM_ID" BIGINT NOT NULL,
    "OWNER_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(254 OCTETS),
    "MBRGRP_ID" BIGINT,
    "DESCRIPTION" VARCHAR(4000 OCTETS),
    "CREATETIME" TIMESTAMP,
    "SUBJTYPE" CHAR(32 OCTETS),
    "BANNERURL" CHAR(254 OCTETS),
    "STATUS" CHAR(4 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FORUM"
ALTER TABLE "DB2ADMIN"."FORUM"
ADD PRIMARY KEY ("FORUM_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FORUM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000576" ON "DB2ADMIN"."FORUM" ("OWNER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FORUM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000577" ON "DB2ADMIN"."FORUM" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FORUMMSG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FORUMMSG" (
    "MSG_ID" BIGINT NOT NULL,
    "FORUM_ID" BIGINT NOT NULL,
    "POSTER_ID" BIGINT NOT NULL,
    "ROOTMSG_ID" BIGINT,
    "PARENTMSG_ID" BIGINT,
    "POSTTIME" TIMESTAMP,
    "TARGET_ID" BIGINT,
    "MSGSTATUS" CHAR(4 OCTETS),
    "VIEWSTATUS" CHAR(4 OCTETS),
    "MSGSUBJ" VARCHAR(254 OCTETS),
    "MSGBODY" VARCHAR(4000 OCTETS),
    "ACTION" CHAR(4 OCTETS),
    "ACTREMARK" VARCHAR(4000 OCTETS),
    "FIELD1" BIGINT,
    "FIELD2" BIGINT,
    "FIELD3" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "TAB16K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FORUMMSG"
ALTER TABLE "DB2ADMIN"."FORUMMSG"
ADD PRIMARY KEY ("MSG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FORUMMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000111" ON "DB2ADMIN"."FORUMMSG" ("POSTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FORUMMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000112" ON "DB2ADMIN"."FORUMMSG" ("TARGET_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FORUMMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000113" ON "DB2ADMIN"."FORUMMSG" ("MSGSTATUS" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FORUMMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000114" ON "DB2ADMIN"."FORUMMSG" ("VIEWSTATUS" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FORUMMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001258" ON "DB2ADMIN"."FORUMMSG" ("FORUM_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FORUMMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001294" ON "DB2ADMIN"."FORUMMSG" ("PARENTMSG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FORUMMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001295" ON "DB2ADMIN"."FORUMMSG" ("ROOTMSG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
---