-----------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTR" (
    "ATTR_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(254 OCTETS) NOT NULL,
    "ATTRTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "ATTRDICT_ID" BIGINT,
    "STOREENT_ID" INTEGER NOT NULL,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "DISPLAYABLE" INTEGER,
    "SEARCHABLE" INTEGER,
    "COMPARABLE" INTEGER,
    "FIELD1" INTEGER,
    "FIELD2" INTEGER,
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "ATTRUSAGE" INTEGER,
    "STOREDISPLAY" SMALLINT,
    "FACETABLE" SMALLINT NOT NULL WITH DEFAULT 0,
    "MERCHANDISABLE" INTEGER,
    "SWATCHABLE" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTR"
ALTER TABLE "DB2ADMIN"."ATTR"
ADD PRIMARY KEY ("ATTR_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001203" ON "DB2ADMIN"."ATTR" ("IDENTIFIER" ASC, "ATTRDICT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001204" ON "DB2ADMIN"."ATTR" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IDXTESTATTR1" ON "DB2ADMIN"."ATTR" ("IDENTIFIER" ASC, "ATTR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001464" ON "DB2ADMIN"."ATTR" ("FACETABLE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTRDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTRDESC" (
    "ATTR_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "ATTRTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "DESCRIPTION2" VARCHAR(254 OCTETS),
    "FIELD1" VARCHAR(254 OCTETS),
    "GROUPNAME" VARCHAR(64 OCTETS),
    "QTYUNIT_ID" CHAR(16 OCTETS),
    "NOTEINFO" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTRDESC"
ALTER TABLE "DB2ADMIN"."ATTRDESC"
ADD PRIMARY KEY ("ATTR_ID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001466" ON "DB2ADMIN"."ATTRDESC" ("ATTRTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001467" ON "DB2ADMIN"."ATTRDESC" ("QTYUNIT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001465" ON "DB2ADMIN"."ATTRDESC" ("LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTRDICT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTRDICT" (
    "ATTRDICT_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER,
    "FIELD1" INTEGER,
    "FIELD2" INTEGER,
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTRDICT"
ALTER TABLE "DB2ADMIN"."ATTRDICT"
ADD PRIMARY KEY ("ATTRDICT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRDICT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001133" ON "DB2ADMIN"."ATTRDICT" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTRDICTGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTRDICTGRP" (
    "ATTRDICTGRP_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(254 OCTETS) NOT NULL,
    "ATTRDICT_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" INTEGER,
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTRDICTGRP"
ALTER TABLE "DB2ADMIN"."ATTRDICTGRP"
ADD PRIMARY KEY ("ATTRDICTGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRDICTGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001135" ON "DB2ADMIN"."ATTRDICTGRP" ("IDENTIFIER" ASC, "ATTRDICT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRDICTGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001187" ON "DB2ADMIN"."ATTRDICTGRP" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRDICTGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001188" ON "DB2ADMIN"."ATTRDICTGRP" ("ATTRDICT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTRDICTGRPATTRREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTRDICTGRPATTRREL" (
    "ATTRDICTGRP_ID" BIGINT NOT NULL,
    "ATTR_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTRDICTGRPATTRREL"
ALTER TABLE "DB2ADMIN"."ATTRDICTGRPATTRREL"
ADD PRIMARY KEY ("ATTRDICTGRP_ID", "ATTR_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRDICTGRPATTRREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IATTRDICTGRP01" ON "DB2ADMIN"."ATTRDICTGRPATTRREL" ("ATTR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTRDICTGRPDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTRDICTGRPDESC" (
    "ATTRDICTGRP_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "SHORTDESCRIPTION" VARCHAR(254 OCTETS),
    "FIELD1" INTEGER,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTRDICTGRPDESC"
ALTER TABLE "DB2ADMIN"."ATTRDICTGRPDESC"
ADD PRIMARY KEY ("ATTRDICTGRP_ID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRDICTGRPDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001136" ON "DB2ADMIN"."ATTRDICTGRPDESC" ("NAME" ASC, "LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTRDICTGRPREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTRDICTGRPREL" (
    "ATTRDICTGRP_PARENT" BIGINT NOT NULL,
    "ATTRDICTGRP_CHILD" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTRDICTGRPREL"
ALTER TABLE "DB2ADMIN"."ATTRDICTGRPREL"
ADD PRIMARY KEY ("ATTRDICTGRP_PARENT", "ATTRDICTGRP_CHILD");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRDICTGRPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001137" ON "DB2ADMIN"."ATTRDICTGRPREL" ("ATTRDICTGRP_CHILD" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTRIBUTE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTRIBUTE" (
    "ATTRIBUTE_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "ATTRTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "NAME" VARCHAR(254 OCTETS),
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "CATENTRY_ID" BIGINT,
    "DESCRIPTION2" VARCHAR(254 OCTETS),
    "FIELD1" VARCHAR(254 OCTETS),
    "OID" VARCHAR(64 OCTETS),
    "USAGE" CHAR(1 OCTETS) WITH DEFAULT '1',
    "QTYUNIT_ID" CHAR(16 OCTETS),
    "GROUPNAME" VARCHAR(64 OCTETS),
    "NOTEINFO" VARCHAR(64 OCTETS),
    "MULTITYPE" CHAR(1 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTRIBUTE"
ALTER TABLE "DB2ADMIN"."ATTRIBUTE"
ADD PRIMARY KEY ("ATTRIBUTE_ID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRIBUTE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000019" ON "DB2ADMIN"."ATTRIBUTE" (
    "CATENTRY_ID" ASC,
    "LANGUAGE_ID" ASC,
    "NAME" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRIBUTE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000298" ON "DB2ADMIN"."ATTRIBUTE" ("GROUPNAME" ASC, "SEQUENCE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTRTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTRTYPE" (
    "ATTRTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTRTYPE"
ALTER TABLE "DB2ADMIN"."ATTRTYPE"
ADD PRIMARY KEY ("ATTRTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTRVAL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTRVAL" (
    "ATTRVAL_ID" BIGINT NOT NULL,
    "ATTR_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(254 OCTETS),
    "VALUSAGE" INTEGER,
    "STOREENT_ID" INTEGER NOT NULL,
    "FIELD1" INTEGER,
    "FIELD2" INTEGER,
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTRVAL"
ALTER TABLE "DB2ADMIN"."ATTRVAL"
ADD PRIMARY KEY ("ATTRVAL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001205" ON "DB2ADMIN"."ATTRVAL" ("ATTR_ID" ASC, "IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001206" ON "DB2ADMIN"."ATTRVAL" (
    "ATTR_ID" ASC,
    "STOREENT_ID" ASC,
    "VALUSAGE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTRVALDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTRVALDESC" (
    "ATTRVAL_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "ATTR_ID" BIGINT NOT NULL,
    "VALUE" VARCHAR(254 OCTETS),
    "VALUSAGE" INTEGER,
    "SEQUENCE" DOUBLE,
    "STRINGVALUE" VARCHAR(2000 OCTETS),
    "INTEGERVALUE" INTEGER,
    "FLOATVALUE" DOUBLE,
    "QTYUNIT_ID" CHAR(16 OCTETS),
    "IMAGE1" VARCHAR(254 OCTETS),
    "IMAGE2" VARCHAR(254 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTRVALDESC"
ALTER TABLE "DB2ADMIN"."ATTRVALDESC"
ADD PRIMARY KEY ("ATTRVAL_ID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVALDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IDX1211192347290" ON "DB2ADMIN"."ATTRVALDESC" ("ATTR_ID" ASC, "ATTRVAL_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVALDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001468" ON "DB2ADMIN"."ATTRVALDESC" ("LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVALDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001470" ON "DB2ADMIN"."ATTRVALDESC" ("QTYUNIT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVALDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IDXTESTATTRVALDS1" ON "DB2ADMIN"."ATTRVALDESC" (
    "ATTR_ID" ASC,
    "VALUE" ASC,
    "ATTRVAL_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVALDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001469" ON "DB2ADMIN"."ATTRVALDESC" ("ATTR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ATTRVALUE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ATTRVALUE" (
    "ATTRVALUE_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "ATTRIBUTE_ID" BIGINT NOT NULL,
    "ATTRTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "STRINGVALUE" CHAR(254 OCTETS),
    "OPERATOR_ID" INTEGER,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "INTEGERVALUE" INTEGER,
    "FLOATVALUE" DOUBLE,
    "CATENTRY_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(254 OCTETS),
    "FIELD1" INTEGER,
    "IMAGE1" VARCHAR(254 OCTETS),
    "IMAGE2" VARCHAR(254 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS),
    "OID" VARCHAR(64 OCTETS),
    "QTYUNIT_ID" CHAR(16 OCTETS),
    "ATTACHMENT_ID" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ATTRVALUE"
ALTER TABLE "DB2ADMIN"."ATTRVALUE"
ADD PRIMARY KEY ("ATTRVALUE_ID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000021" ON "DB2ADMIN"."ATTRVALUE" (
    "ATTRIBUTE_ID" ASC,
    "CATENTRY_ID" ASC,
    "STRINGVALUE" ASC,
    "LANGUAGE_ID" ASC,
    "INTEGERVALUE" ASC,
    "FLOATVALUE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000020" ON "DB2ADMIN"."ATTRVALUE" (
    "ATTRIBUTE_ID" ASC,
    "CATENTRY_ID" ASC,
    "LANGUAGE_ID" ASC,
    "NAME" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I194153" ON "DB2ADMIN"."ATTRVALUE" (
    "ATTRTYPE_ID" ASC,
    "CATENTRY_ID" ASC,
    "LANGUAGE_ID" ASC,
    "SEQUENCE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000453" ON "DB2ADMIN"."ATTRVALUE" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001235" ON "DB2ADMIN"."ATTRVALUE" ("ATTACHMENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001236" ON "DB2ADMIN"."ATTRVALUE" ("ATTRIBUTE_ID" ASC, "LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."AUCPAYINFO"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."AUCPAYINFO" (
    "AUCPAYINFO_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "NAME" CHAR(32 OCTETS),
    "PAYMETHOD" CHAR(64 OCTETS),
    "DEVICE" CHAR(64 OCTETS),
    "EXPDATE" TIMESTAMP,
    "ENCRYPT" INTEGER WITH DEFAULT 1,
    "BANKINFO" VARCHAR(254 OCTETS),
    "DESCR" VARCHAR(254 OCTETS),
    "BILLADDR" BIGINT,
    "COMMENTS" VARCHAR(254 OCTETS),
    "CAUSE" CHAR(12 OCTETS),
    "CAUSEID" BIGINT,
    "STATUS" CHAR(4 OCTETS),
    "CREATETIME" TIMESTAMP,
    "FIELD1" BIGINT,
    "FIELD2" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."AUCPAYINFO"
ALTER TABLE "DB2ADMIN"."AUCPAYINFO"
ADD PRIMARY KEY ("AUCPAYINFO_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCPAYINFO"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000454" ON "DB2ADMIN"."AUCPAYINFO" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."AUCTDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."AUCTDESC" (
    "AUCT_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "AUSDESC" VARCHAR(254 OCTETS),
    "AULDESC" VARCHAR(2048 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."AUCTDESC"
ALTER TABLE "DB2ADMIN"."AUCTDESC"
ADD PRIMARY KEY ("AUCT_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."AUCTION"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."AUCTION" (
    "AUCT_ID" BIGINT NOT NULL,
    "REFCODE" CHAR(36 OCTETS) NOT NULL,
    "AUCPAYINFO_ID" BIGINT,
    "OWNER_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "ADMIN_ID" BIGINT,
    "FFMCENTER_ID" INTEGER,
    "AUTYPE" CHAR(4 OCTETS) NOT NULL,
    "AUSTATUS" CHAR(4 OCTETS) NOT NULL,
    "AUQUANT" DOUBLE NOT NULL,
    "BIDRULE_ID" BIGINT,
    "QUANTSCALE" INTEGER,
    "RESRVPRICE" DECIMAL(20, 5),
    "OPENPRICE" DECIMAL(20, 5),
    "CURRPRICE" DECIMAL(20, 5),
    "CURRQUANT" DOUBLE,
    "CLOSEPR" CHAR(4 OCTETS),
    "CURRENCY" CHAR(4 OCTETS),
    "PAYMETHODS" CHAR(254 OCTETS),
    "CLOSETYPE" INTEGER,
    "RULEPAGE" VARCHAR(254 OCTETS),
    "STARTTIME" TIMESTAMP,
    "ENDTIME" TIMESTAMP,
    "REALENDTIME" TIMESTAMP,
    "DURATION" TIMESTAMP,
    "DEPOSIT" DECIMAL(20, 5),
    "BESTBID_ID" BIGINT,
    "HIGHBID_ID" BIGINT,
    "LOCKFLAG" INTEGER,
    "UPDATETIME" TIMESTAMP,
    "LASTBKTIME" TIMESTAMP,
    "PRECEDENCE" INTEGER,
    "FIELD1" BIGINT,
    "FIELD2" BIGINT,
    "RETRACT_BID" INTEGER,
    "FIELD3" DECIMAL(20, 5),
    "FIELD4" DECIMAL(20, 5),
    "FIELD5" VARCHAR(254 OCTETS),
    "MBRGRP_ID" BIGINT,
    "FIELD6" VARCHAR(254 OCTETS),
    "SUPPLIER_ID" BIGINT,
    "DURDAYS" INTEGER,
    "REFPRICE" DECIMAL(20, 5),
    "STATE" INTEGER,
    "INVRSRVID" BIGINT,
    "AUCMODE" CHAR(4 OCTETS),
    "PRICELIMIT" DECIMAL(20, 5),
    "QUANTLIMIT" DOUBLE,
    "DURLENGTH" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."AUCTION"
ALTER TABLE "DB2ADMIN"."AUCTION"
ADD PRIMARY KEY ("AUCT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000022" ON "DB2ADMIN"."AUCTION" ("REFCODE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000023" ON "DB2ADMIN"."AUCTION" ("ENDTIME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000024" ON "DB2ADMIN"."AUCTION" ("REFPRICE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000025" ON "DB2ADMIN"."AUCTION" ("STATE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000455" ON "DB2ADMIN"."AUCTION" ("BIDRULE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000456" ON "DB2ADMIN"."AUCTION" ("ADMIN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000457" ON "DB2ADMIN"."AUCTION" ("OWNER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000458" ON "DB2ADMIN"."AUCTION" ("FFMCENTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000459" ON "DB2ADMIN"."AUCTION" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000460" ON "DB2ADMIN"."AUCTION" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001237" ON "DB2ADMIN"."AUCTION" ("AUCPAYINFO_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000026" ON "DB2ADMIN"."AUCTION" ("AUTYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000027" ON "DB2ADMIN"."AUCTION" ("AUSTATUS" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000028" ON "DB2ADMIN"."AUCTION" ("LOCKFLAG" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000029" ON "DB2ADMIN"."AUCTION" ("UPDATETIME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000030" ON "DB2ADMIN"."AUCTION" ("LASTBKTIME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000031" ON "DB2ADMIN"."AUCTION" ("STARTTIME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."AUCTIONLOG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."AUCTIONLOG" (
    "AUCT_ID" BIGINT NOT NULL,
    "ACTIONTIME" TIMESTAMP NOT NULL,
    "ACTIONTYPE" INTEGER,
    "AUCPAYINFO_ID" BIGINT,
    "OWNER_ID" BIGINT,
    "ADMIN_ID" BIGINT,
    "MBRGRP_ID" BIGINT,
    "FFMCENTER_ID" INTEGER,
    "ACTIONMSG" VARCHAR(254 OCTETS),
    "REFCODE" CHAR(36 OCTETS),
    "CATENTRY_ID" BIGINT,
    "AUTYPE" CHAR(4 OCTETS),
    "AUSTATUS" CHAR(4 OCTETS),
    "AUQUANT" DOUBLE,
    "BIDRULE_ID" BIGINT,
    "QUANTSCALE" INTEGER,
    "RESRVPRICE" DECIMAL(20, 5),
    "OPENPRICE" DECIMAL(20, 5),
    "CURRPRICE" DECIMAL(20, 5),
    "CURRQUANT" DOUBLE,
    "CLOSEPR" CHAR(4 OCTETS),
    "CURRENCY" CHAR(4 OCTETS),
    "PAYMETHODS" CHAR(254 OCTETS),
    "CLOSETYPE" INTEGER,
    "RULEPAGE" VARCHAR(254 OCTETS),
    "STARTTIME" TIMESTAMP,
    "ENDTIME" TIMESTAMP,
    "DURATION" TIMESTAMP,
    "DEPOSIT" DECIMAL(20, 5),
    "BESTBID_ID" BIGINT,
    "LOCKFLAG" INTEGER,
    "HIGHBID_ID" BIGINT,
    "UPDATETIME" TIMESTAMP,
    "LASTBKTIME" TIMESTAMP,
    "REALENDTIME" TIMESTAMP,
    "PRECEDENCE" INTEGER,
    "FIELD1" BIGINT,
    "RETRACT_BID" INTEGER,
    "FIELD2" BIGINT,
    "FIELD3" DECIMAL(20, 5),
    "FIELD4" DECIMAL(20, 5),
    "FIELD5" VARCHAR(254 OCTETS),
    "FIELD6" VARCHAR(254 OCTETS),
    "SUPPLIER_ID" BIGINT,
    "DURDAYS" INTEGER,
    "REFPRICE" DECIMAL(20, 5),
    "STATE" INTEGER,
    "INVRSRVID" BIGINT,
    "AUCMODE" CHAR(4 OCTETS),
    "PRICELIMIT" DECIMAL(20, 5),
    "QUANTLIMIT" DOUBLE,
    "DURLENGTH" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."AUCTIONLOG"
ALTER TABLE "DB2ADMIN"."AUCTIONLOG"
ADD PRIMARY KEY ("AUCT_ID", "ACTIONTIME");
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTIONLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000461" ON "DB2ADMIN"."AUCTIONLOG" ("ADMIN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTIONLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000462" ON "DB2ADMIN"."AUCTIONLOG" ("FFMCENTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTIONLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000463" ON "DB2ADMIN"."AUCTIONLOG" ("OWNER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTIONLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000464" ON "DB2ADMIN"."AUCTIONLOG" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTIONLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001238" ON "DB2ADMIN"."AUCTIONLOG" ("AUCPAYINFO_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."AUCTSTRREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."AUCTSTRREL" (
    "AUCT_ID" BIGINT NOT NULL,
    "STORE_ID" INTEGER NOT NULL,
    "ITEMPAGE" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."AUCTSTRREL"
ALTER TABLE "DB2ADMIN"."AUCTSTRREL"
ADD PRIMARY KEY ("STORE_ID", "AUCT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTSTRREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001239" ON "DB2ADMIN"."AUCTSTRREL" ("AUCT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."AUCTSTYLE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."AUCTSTYLE" (
    "ASNAME" CHAR(38 OCTETS) NOT NULL,
    "OWNER_ID" BIGINT NOT NULL,
    "ASTYPE" CHAR(4 OCTETS) NOT NULL,
    "ADMIN_ID" BIGINT,
    "AUQUANT" DOUBLE NOT NULL,
    "OPENPRICE" DECIMAL(20, 5),
    "RESERVPRICE" DECIMAL(20, 5),
    "RULE_ID" BIGINT,
    "CLOSEPR" CHAR(4 OCTETS),
    "DEPOSIT" DECIMAL(20, 5),
    "CLOSETYPE" INTEGER,
    "STARTDAYS" INTEGER,
    "ENDDAYS" INTEGER,
    "STARTTIME" TIMESTAMP,
    "ENDTIME" TIMESTAMP,
    "ASDURATION" TIMESTAMP,
    "ASCUR" CHAR(4 OCTETS),
    "RULEPAGE" VARCHAR(254 OCTETS),
    "ITEMPAGE" VARCHAR(254 OCTETS),
    "DURDAYS" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."AUCTSTYLE"
ALTER TABLE "DB2ADMIN"."AUCTSTYLE"
ADD PRIMARY KEY ("OWNER_ID", "ASNAME");
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTSTYLE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000033" ON "DB2ADMIN"."AUCTSTYLE" ("ASTYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTSTYLE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000465" ON "DB2ADMIN"."AUCTSTYLE" ("ADMIN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUCTSTYLE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000466" ON "DB2ADMIN"."AUCTSTYLE" ("RULE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."AUTOBID"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."AUTOBID" (
    "AUTOBID_ID" BIGINT NOT NULL,
    "REFCODE" CHAR(36 OCTETS) NOT NULL,
    "AUCPAYINFO_ID" BIGINT,
    "OWNER_ID" BIGINT NOT NULL,
    "STORE_ID" INTEGER,
    "ADMIN_ID" BIGINT,
    "AUCT_ID" BIGINT NOT NULL,
    "ABQUANT" DOUBLE NOT NULL,
    "PAYTYPE" CHAR(64 OCTETS) NOT NULL,
    "ENCRYPT" INTEGER NOT NULL,
    "DEVICE" VARCHAR(64 OCTETS) NOT NULL,
    "EXPDATE" TIMESTAMP NOT NULL,
    "QUANTSCALE" INTEGER,
    "MAXBIDLIMIT" DECIMAL(20, 5),
    "ABSTATUS" CHAR(4 OCTETS),
    "WINOPT" CHAR(4 OCTETS),
    "ABTIME" TIMESTAMP,
    "LASTBID_ID" BIGINT,
    "BID_ID" BIGINT,
    "BKNAME" VARCHAR(254 OCTETS),
    "SHIPTO_ID" BIGINT,
    "SHIPMODE" INTEGER,
    "BIDMSG" VARCHAR(254 OCTETS),
    "MSGFLAG" INTEGER,
    "STARTTIME" TIMESTAMP,
    "ENDTIME" TIMESTAMP,
    "ABFIELD1" BIGINT,
    "ABFIELD2" DECIMAL(20, 5),
    "ABFIELD3" VARCHAR(254 OCTETS),
    "BILLADDR" BIGINT,
    "INITBIDVAL" DECIMAL(20, 5),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."AUTOBID"
ALTER TABLE "DB2ADMIN"."AUTOBID"
ADD PRIMARY KEY ("AUTOBID_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBID"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000034" ON "DB2ADMIN"."AUTOBID" ("REFCODE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBID"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000468" ON "DB2ADMIN"."AUTOBID" ("ADMIN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBID"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000469" ON "DB2ADMIN"."AUTOBID" ("OWNER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBID"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001240" ON "DB2ADMIN"."AUTOBID" ("AUCT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBID"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001241" ON "DB2ADMIN"."AUTOBID" ("AUCPAYINFO_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBID"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000035" ON "DB2ADMIN"."AUTOBID" ("BID_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBID"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000036" ON "DB2ADMIN"."AUTOBID" ("ABQUANT" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBID"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000037" ON "DB2ADMIN"."AUTOBID" ("MAXBIDLIMIT" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBID"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000038" ON "DB2ADMIN"."AUTOBID" ("ABSTATUS" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBID"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000467" ON "DB2ADMIN"."AUTOBID" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."AUTOBIDLOG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."AUTOBIDLOG" (
    "AUTOBID_ID" BIGINT NOT NULL,
    "ACTIONTIME" TIMESTAMP NOT NULL,
    "ACTIONTYPE" INTEGER,
    "AUCPAYINFO_ID" BIGINT,
    "OWNER_ID" BIGINT,
    "STORE_ID" INTEGER,
    "ADMIN_ID" BIGINT,
    "ACTIONMSG" VARCHAR(254 OCTETS),
    "REFCODE" CHAR(36 OCTETS),
    "AUCT_ID" BIGINT,
    "ABQUANT" DOUBLE,
    "PAYTYPE" CHAR(64 OCTETS),
    "ENCRYPT" INTEGER,
    "DEVICE" VARCHAR(64 OCTETS),
    "EXPDATE" TIMESTAMP,
    "QUANTSCALE" INTEGER,
    "MAXBIDLIMIT" DECIMAL(20, 5),
    "ABSTATUS" CHAR(4 OCTETS),
    "WINOPT" CHAR(4 OCTETS),
    "ABTIME" TIMESTAMP,
    "LASTBID_ID" BIGINT,
    "BID_ID" BIGINT,
    "BKNAME" VARCHAR(254 OCTETS),
    "SHIPTO_ID" BIGINT,
    "SHIPMODE" INTEGER,
    "BIDMSG" VARCHAR(254 OCTETS),
    "MSGFLAG" INTEGER,
    "STARTTIME" TIMESTAMP,
    "ENDTIME" TIMESTAMP,
    "ABFIELD1" BIGINT,
    "ABFIELD2" DECIMAL(20, 5),
    "ABFIELD3" VARCHAR(254 OCTETS),
    "BILLADDR" BIGINT,
    "INITBIDVAL" DECIMAL(20, 5),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."AUTOBIDLOG"
ALTER TABLE "DB2ADMIN"."AUTOBIDLOG"
ADD PRIMARY KEY ("AUTOBID_ID", "ACTIONTIME");
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBIDLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000470" ON "DB2ADMIN"."AUTOBIDLOG" ("ADMIN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBIDLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000471" ON "DB2ADMIN"."AUTOBIDLOG" ("OWNER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBIDLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000472" ON "DB2ADMIN"."AUTOBIDLOG" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."AUTOBIDLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001242" ON "DB2ADMIN"."AUTOBIDLOG" ("AUCPAYINFO_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
---