------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DAEMON"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DAEMON" (
    "HOSTNAME" CHAR(254 OCTETS),
    "LASTUPDATE" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DAEMON"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000084" ON "DB2ADMIN"."DAEMON" ("HOSTNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DBDELIVERY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DBDELIVERY" (
    "DBMENBR" INTEGER,
    "DBQTBEGIN" CHAR(50 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DBDELIVERY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000085" ON "DB2ADMIN"."DBDELIVERY" ("DBMENBR" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DBDTFREQ"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DBDTFREQ" (
    "DBDTREF" INTEGER,
    "DBDTNAME" CHAR(100 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DBDTFREQ"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000086" ON "DB2ADMIN"."DBDTFREQ" ("DBDTREF" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DBMEAS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DBMEAS" (
    "DBMREF" INTEGER,
    "DBMMFREF" INTEGER,
    "DBMVIEW" INTEGER,
    "DBMENABLE" INTEGER,
    "DBMNAME" CHAR(50 OCTETS),
    "DBMKEYCOL" CHAR(100 OCTETS),
    "DBMKEYLEN" INTEGER,
    "DBMVALCOL" CHAR(100 OCTETS),
    "DBMTBLLST" CHAR(100 OCTETS),
    "DBMNULLST" CHAR(100 OCTETS),
    "DBMDTCOL" CHAR(100 OCTETS),
    "DBMDTLEN" INTEGER,
    "DBMWHERE" VARCHAR(500 OCTETS),
    "DBMGRPBY" CHAR(100 OCTETS),
    "DBMFORMAT" CHAR(250 OCTETS),
    "DBMCMPNT" CHAR(100 OCTETS),
    "DBMFEXTS" VARCHAR(500 OCTETS),
    "DBMEEXTS" VARCHAR(1800 OCTETS),
    "DBMCMDIMG" CHAR(100 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DBMEAS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000087" ON "DB2ADMIN"."DBMEAS" (
    "DBMREF" ASC,
    "DBMMFREF" ASC,
    "DBMVIEW" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DBMEASFM"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DBMEASFM" (
    "DBMFREF" INTEGER,
    "DBMFVIEW" INTEGER,
    "DBMFNAME" CHAR(50 OCTETS),
    "DBMFTEMP" INTEGER,
    "DBMFKEYCOL" CHAR(100 OCTETS),
    "DBMFKEYLEN" INTEGER,
    "DBMFTBLLST" CHAR(100 OCTETS),
    "DBMFDTCOL" CHAR(100 OCTETS),
    "DBMFDTLEN" INTEGER,
    "DBMFWHMER" CHAR(100 OCTETS),
    "DBMFWHERE" VARCHAR(500 OCTETS),
    "DBMFGRPBY" CHAR(100 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DBMEASFM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000088" ON "DB2ADMIN"."DBMEASFM" ("DBMFREF" ASC, "DBMFVIEW" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DBTEMPLATE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DBTEMPLATE" (
    "DBTEMPREF" INTEGER,
    "DBTEMPTYPE" CHAR(100 OCTETS),
    "DBTEMPFREQ" INTEGER,
    "DBTEMPSQL" VARCHAR(1000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DBTEMPLATE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000089" ON "DB2ADMIN"."DBTEMPLATE" ("DBTEMPREF" ASC, "DBTEMPFREQ" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DBVIEW"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DBVIEW" (
    "DBVWREF" INTEGER,
    "DBVWNAME" CHAR(100 OCTETS),
    "DBVWCLASS" CHAR(100 OCTETS),
    "DBVWTYPE" INTEGER,
    "DBVWSQL" VARCHAR(2000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DBVIEW"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000090" ON "DB2ADMIN"."DBVIEW" ("DBVWREF" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DEVICEFMT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DEVICEFMT" (
    "DEVICETYPE_ID" CHAR(64 OCTETS) NOT NULL,
    "DEVICEFMT_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DEVICEFMT"
ALTER TABLE "DB2ADMIN"."DEVICEFMT"
ADD PRIMARY KEY ("DEVICEFMT_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DISPCGPREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DISPCGPREL" (
    "CATGROUP_ID" BIGINT NOT NULL,
    "DISPCGPREL_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER,
    "DEVICEFMT_ID" INTEGER NOT NULL,
    "PAGENAME" VARCHAR(254 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "MBRGRP_ID" BIGINT NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "RANK" DOUBLE,
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "OID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DISPCGPREL"
ALTER TABLE "DB2ADMIN"."DISPCGPREL"
ADD PRIMARY KEY ("DISPCGPREL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISPCGPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000091" ON "DB2ADMIN"."DISPCGPREL" (
    "DEVICEFMT_ID" ASC,
    "STOREENT_ID" ASC,
    "CATGROUP_ID" ASC,
    "MBRGRP_ID" ASC,
    "RANK" ASC,
    "LANGUAGE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISPCGPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000554" ON "DB2ADMIN"."DISPCGPREL" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISPCGPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000555" ON "DB2ADMIN"."DISPCGPREL" ("CATGROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISPCGPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000556" ON "DB2ADMIN"."DISPCGPREL" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DISPENTREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DISPENTREL" (
    "CATENTRY_ID" BIGINT NOT NULL,
    "DISPENTREL_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER,
    "DEVICEFMT_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "PAGENAME" VARCHAR(254 OCTETS) NOT NULL,
    "CATENTTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "AUCTIONSTATE" INTEGER NOT NULL WITH DEFAULT 0,
    "MBRGRP_ID" BIGINT NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "FIELD1" VARCHAR(254 OCTETS),
    "RANK" DOUBLE,
    "FIELD2" VARCHAR(254 OCTETS),
    "OID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DISPENTREL"
ALTER TABLE "DB2ADMIN"."DISPENTREL"
ADD PRIMARY KEY ("DISPENTREL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISPENTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000092" ON "DB2ADMIN"."DISPENTREL" (
    "DEVICEFMT_ID" ASC,
    "STOREENT_ID" ASC,
    "CATENTRY_ID" ASC,
    "CATENTTYPE_ID" ASC,
    "MBRGRP_ID" ASC,
    "AUCTIONSTATE" ASC,
    "RANK" ASC,
    "LANGUAGE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISPENTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000093" ON "DB2ADMIN"."DISPENTREL" (
    "AUCTIONSTATE" ASC,
    "MBRGRP_ID" ASC,
    "CATENTRY_ID" ASC,
    "STOREENT_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISPENTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000094" ON "DB2ADMIN"."DISPENTREL" (
    "CATENTRY_ID" ASC,
    "CATENTTYPE_ID" ASC,
    "STOREENT_ID" ASC,
    "MBRGRP_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISPENTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000557" ON "DB2ADMIN"."DISPENTREL" ("CATENTTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISPENTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000558" ON "DB2ADMIN"."DISPENTREL" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISPENTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000559" ON "DB2ADMIN"."DISPENTREL" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DISTARRANG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DISTARRANG" (
    "DISTARRANG_ID" BIGINT NOT NULL,
    "MERCHANTSTORE_ID" INTEGER NOT NULL,
    "PICKINGMETHOD" CHAR(1 OCTETS),
    "STARTDATE" TIMESTAMP NOT NULL,
    "ENDDATE" TIMESTAMP NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS),
    "WHOLESALESTORE_ID" INTEGER NOT NULL,
    "BASEITEM_ID" BIGINT NOT NULL,
    "LASTUPDATE" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DISTARRANG"
ALTER TABLE "DB2ADMIN"."DISTARRANG"
ADD PRIMARY KEY ("DISTARRANG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISTARRANG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000095" ON "DB2ADMIN"."DISTARRANG" (
    "BASEITEM_ID" ASC,
    "MERCHANTSTORE_ID" ASC,
    "WHOLESALESTORE_ID" ASC,
    "STARTDATE" ASC,
    "ENDDATE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISTARRANG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000347" ON "DB2ADMIN"."DISTARRANG" ("DISTARRANG_ID" ASC, "MERCHANTSTORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISTARRANG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000560" ON "DB2ADMIN"."DISTARRANG" ("MERCHANTSTORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DISTARRANG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000561" ON "DB2ADMIN"."DISTARRANG" ("WHOLESALESTORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DKADJMNT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DKADJMNT" (
    "TERMCOND_ID" BIGINT NOT NULL,
    "KIT_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "ADJUSTMENT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "ADJTYPE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DKADJMNT"
ALTER TABLE "DB2ADMIN"."DKADJMNT"
ADD PRIMARY KEY ("TERMCOND_ID", "KIT_ID", "CATENTRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKADJMNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000906" ON "DB2ADMIN"."DKADJMNT" ("KIT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKADJMNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000907" ON "DB2ADMIN"."DKADJMNT" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DKOFFER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DKOFFER" (
    "DKOFFER_ID" BIGINT NOT NULL,
    "TRADEPOSCN_ID" BIGINT NOT NULL,
    "KIT_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "CURRENCY" CHAR(3 OCTETS) NOT NULL,
    "IDENTIFIER" BIGINT,
    "PRICE" DECIMAL(20, 5) NOT NULL,
    "STARTDATE" TIMESTAMP,
    "ENDDATE" TIMESTAMP,
    "MINIMUMQUANTITY" DOUBLE,
    "MAXIMUMQUANTITY" DOUBLE,
    "PRECEDENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "PUBLISHED" INTEGER NOT NULL WITH DEFAULT 1,
    "FIELD1" CHAR(30 OCTETS),
    "FIELD2" CHAR(1 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DKOFFER"
ALTER TABLE "DB2ADMIN"."DKOFFER"
ADD PRIMARY KEY ("DKOFFER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKOFFER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000932" ON "DB2ADMIN"."DKOFFER" (
    "TRADEPOSCN_ID" ASC,
    "KIT_ID" ASC,
    "CATENTRY_ID" ASC,
    "CURRENCY" ASC,
    "IDENTIFIER" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKOFFER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000903" ON "DB2ADMIN"."DKOFFER" ("KIT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKOFFER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000904" ON "DB2ADMIN"."DKOFFER" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKOFFER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000905" ON "DB2ADMIN"."DKOFFER" ("CURRENCY" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DKPDCCATENTREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DKPDCCATENTREL" (
    "DKPREDEFCONF_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "SEQUENCE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DKPDCCATENTREL"
ALTER TABLE "DB2ADMIN"."DKPDCCATENTREL"
ADD PRIMARY KEY ("DKPREDEFCONF_ID", "CATENTRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKPDCCATENTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001255" ON "DB2ADMIN"."DKPDCCATENTREL" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DKPDCCOMPLIST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DKPDCCOMPLIST" (
    "DKPDCCOMPLIST_ID" BIGINT NOT NULL,
    "DKPREDEFCONF_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "GROUPNAME" VARCHAR(254 OCTETS),
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "QUANTITY" DOUBLE NOT NULL,
    "QTYUNIT_ID" CHAR(16 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "DKPDCREL_ID" BIGINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DKPDCCOMPLIST"
ALTER TABLE "DB2ADMIN"."DKPDCCOMPLIST"
ADD PRIMARY KEY ("DKPDCCOMPLIST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKPDCCOMPLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000414" ON "DB2ADMIN"."DKPDCCOMPLIST" ("DKPREDEFCONF_ID" ASC, "CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKPDCCOMPLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000908" ON "DB2ADMIN"."DKPDCCOMPLIST" ("QTYUNIT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKPDCCOMPLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000413" ON "DB2ADMIN"."DKPDCCOMPLIST" ("DKPDCREL_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKPDCCOMPLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001256" ON "DB2ADMIN"."DKPDCCOMPLIST" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DKPDCDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DKPDCDESC" (
    "DKPREDEFCONF_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "NAME" CHAR(128 OCTETS) NOT NULL,
    "SHORTDESCRIPTION" VARCHAR(254 OCTETS),
    "LONGDESCRIPTION" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DKPDCDESC"
ALTER TABLE "DB2ADMIN"."DKPDCDESC"
ADD PRIMARY KEY ("DKPREDEFCONF_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DKPDCOFFERREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DKPDCOFFERREL" (
    "DKPREDEFCONF_ID" BIGINT NOT NULL,
    "OFFER_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DKPDCOFFERREL"
ALTER TABLE "DB2ADMIN"."DKPDCOFFERREL"
ADD PRIMARY KEY ("DKPREDEFCONF_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKPDCOFFERREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000917" ON "DB2ADMIN"."DKPDCOFFERREL" ("OFFER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DKPDCREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DKPDCREL" (
    "DKPDCREL_ID" BIGINT NOT NULL,
    "DKPREDEFCONF_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "PARENT_ID" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DKPDCREL"
ALTER TABLE "DB2ADMIN"."DKPDCREL"
ADD PRIMARY KEY ("DKPDCREL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKPDCREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000543" ON "DB2ADMIN"."DKPDCREL" ("DKPREDEFCONF_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKPDCREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000544" ON "DB2ADMIN"."DKPDCREL" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DKPDCREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000412" ON "DB2ADMIN"."DKPDCREL" ("PARENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DKPREDEFCONF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DKPREDEFCONF" (
    "DKPREDEFCONF_ID" BIGINT NOT NULL,
    "CONFIGURATION_ID" VARCHAR(256 OCTETS),
    "COMPLETE" SMALLINT NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DKPREDEFCONF"
ALTER TABLE "DB2ADMIN"."DKPREDEFCONF"
ADD PRIMARY KEY ("DKPREDEFCONF_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMACTATTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMACTATTR" (
    "DMACTIVITY_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL WITH DEFAULT 0,
    "PROCESSED" TIMESTAMP,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMACTATTR"
ALTER TABLE "DB2ADMIN"."DMACTATTR"
ADD PRIMARY KEY ("DMACTIVITY_ID", "STOREENT_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMACTIVITY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMACTIVITY" (
    "DMACTIVITY_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(64 OCTETS) NOT NULL,
    "VERSION" INTEGER NOT NULL WITH DEFAULT 1,
    "PUBLISHED" INTEGER NOT NULL WITH DEFAULT 0,
    "STATE" SMALLINT NOT NULL WITH DEFAULT 0,
    "STARTDATE" TIMESTAMP,
    "ENDDATE" TIMESTAMP,
    "PRIORITY" SMALLINT NOT NULL WITH DEFAULT 0,
    "DMCAMPAIGN_ID" INTEGER,
    "DMACTTYPE_ID" SMALLINT NOT NULL WITH DEFAULT 0,
    "DMTEMPLATETYPE_ID" SMALLINT,
    "DMEXPTYPE_ID" SMALLINT,
    "REPEATABLE" SMALLINT NOT NULL WITH DEFAULT 1,
    "CREATED" TIMESTAMP,
    "LASTUPDATE" TIMESTAMP,
    "LASTUPDATEDBY" VARCHAR(254 OCTETS),
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "FLOWXML" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "FIELD1" INTEGER,
    "FIELD2" BIGINT,
    "FIELD3" DECIMAL(20, 5),
    "FIELD4" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "UP_NAME" VARCHAR(64 OCTETS) GENERATED ALWAYS AS (UPPER(NAME)),
    "UP_DESCRIPTION" VARCHAR(254 OCTETS) GENERATED ALWAYS AS (UPPER(DESCRIPTION)),
    "BEHAVIOR" SMALLINT NOT NULL WITH DEFAULT 1,
    "UIDISPLAYABLE" SMALLINT,
    "MANAGINGTOOL" SMALLINT
) IN "TAB16K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMACTIVITY"
ALTER TABLE "DB2ADMIN"."DMACTIVITY"
ADD PRIMARY KEY ("DMACTIVITY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMACTIVITY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001141" ON "DB2ADMIN"."DMACTIVITY" ("NAME" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMACTIVITY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001142" ON "DB2ADMIN"."DMACTIVITY" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMACTIVITY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001143" ON "DB2ADMIN"."DMACTIVITY" ("DMCAMPAIGN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMACTIVITY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001144" ON "DB2ADMIN"."DMACTIVITY" ("DMACTTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMACTIVITY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001145" ON "DB2ADMIN"."DMACTIVITY" ("DMTEMPLATETYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMACTIVITY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001146" ON "DB2ADMIN"."DMACTIVITY" ("DMEXPTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMACTIVITY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001193" ON "DB2ADMIN"."DMACTIVITY" ("STARTDATE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMACTIVITY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00012" ON "DB2ADMIN"."DMACTIVITY" ("UP_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMACTIVITY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00013" ON "DB2ADMIN"."DMACTIVITY" ("UP_DESCRIPTION" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMACTTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMACTTYPE" (
    "DMACTTYPE_ID" SMALLINT NOT NULL,
    "TYPE" VARCHAR(64 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMACTTYPE"
ALTER TABLE "DB2ADMIN"."DMACTTYPE"
ADD PRIMARY KEY ("DMACTTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMCAMPAIGN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMCAMPAIGN" (
    "DMCAMPAIGN_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(64 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "STATE" SMALLINT NOT NULL WITH DEFAULT 0,
    "SEASON" VARCHAR(254 OCTETS),
    "TYPE" INTEGER,
    "STARTDATE" TIMESTAMP,
    "ENDDATE" TIMESTAMP,
    "CREATED" TIMESTAMP,
    "LASTUPDATE" TIMESTAMP,
    "LASTUPDATEDBY" VARCHAR(254 OCTETS),
    "OWNER" VARCHAR(64 OCTETS),
    "OBJECTIVE" VARCHAR(254 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" BIGINT,
    "FIELD3" DECIMAL(20, 5),
    "FIELD4" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "UP_NAME" VARCHAR(64 OCTETS) GENERATED ALWAYS AS (UPPER(NAME)),
    "UP_DESCRIPTION" VARCHAR(254 OCTETS) GENERATED ALWAYS AS (UPPER(DESCRIPTION))
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMCAMPAIGN"
ALTER TABLE "DB2ADMIN"."DMCAMPAIGN"
ADD PRIMARY KEY ("DMCAMPAIGN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMCAMPAIGN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001139" ON "DB2ADMIN"."DMCAMPAIGN" ("NAME" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMCAMPAIGN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001140" ON "DB2ADMIN"."DMCAMPAIGN" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMCAMPAIGN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00014" ON "DB2ADMIN"."DMCAMPAIGN" ("UP_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMCAMPAIGN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00015" ON "DB2ADMIN"."DMCAMPAIGN" ("UP_DESCRIPTION" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMELEMENT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMELEMENT" (
    "DMELEMENT_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(64 OCTETS) NOT NULL,
    "DMELETEMPLATE_ID" INTEGER NOT NULL,
    "DMACTIVITY_ID" INTEGER NOT NULL,
    "RELATED_ID" INTEGER,
    "PRIORITY" SMALLINT,
    "PARENT" VARCHAR(64 OCTETS),
    "SEQUENCE" DOUBLE,
    "FIELD1" INTEGER,
    "FIELD2" BIGINT,
    "FIELD3" DECIMAL(20, 5),
    "FIELD4" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMELEMENT"
ALTER TABLE "DB2ADMIN"."DMELEMENT"
ADD PRIMARY KEY ("DMELEMENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMELEMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001149" ON "DB2ADMIN"."DMELEMENT" ("NAME" ASC, "DMACTIVITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMELEMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001150" ON "DB2ADMIN"."DMELEMENT" ("DMELETEMPLATE_ID" ASC, "DMACTIVITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMELEMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001151" ON "DB2ADMIN"."DMELEMENT" ("DMACTIVITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMELEMENTNVP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMELEMENTNVP" (
    "DMELEMENT_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "VALUE" VARCHAR(254 OCTETS) NOT NULL,
    "TRIGGERMATCH" SMALLINT NOT NULL WITH DEFAULT 0,
    "PROPERTIES" VARCHAR(254 OCTETS),
    "SEQUENCE" DOUBLE,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMELEMENTNVP"
ALTER TABLE "DB2ADMIN"."DMELEMENTNVP"
ADD PRIMARY KEY ("DMELEMENT_ID", "NAME", "VALUE");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMELEMENTNVP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001194" ON "DB2ADMIN"."DMELEMENTNVP" ("NAME" ASC, "VALUE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMELEMENTTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMELEMENTTYPE" (
    "DMELEMENTTYPE_ID" INTEGER NOT NULL,
    "TYPE" VARCHAR(64 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMELEMENTTYPE"
ALTER TABLE "DB2ADMIN"."DMELEMENTTYPE"
ADD PRIMARY KEY ("DMELEMENTTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMELESTATS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMELESTATS" (
    "DMELEMENT_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL WITH DEFAULT 0,
    "COUNTER" INTEGER NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" BIGINT,
    "FIELD3" DECIMAL(20, 5),
    "FIELD4" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMELESTATS"
ALTER TABLE "DB2ADMIN"."DMELESTATS"
ADD PRIMARY KEY ("DMELEMENT_ID", "STOREENT_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMELETEMPLATE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMELETEMPLATE" (
    "DMELETEMPLATE_ID" INTEGER NOT NULL,
    "DMELEMENTTYPE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(64 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "DISPLAYXML" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "IMPLXML" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "BEHAVIORXML" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "RELATEDXML" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "FIELD1" INTEGER,
    "FIELD2" BIGINT,
    "FIELD3" DECIMAL(20, 5),
    "FIELD4" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "TAB16K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMELETEMPLATE"
ALTER TABLE "DB2ADMIN"."DMELETEMPLATE"
ADD PRIMARY KEY ("DMELETEMPLATE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMELETEMPLATE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001147" ON "DB2ADMIN"."DMELETEMPLATE" (
    "DMELEMENTTYPE_ID" ASC,
    "NAME" ASC,
    "STOREENT_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMELETEMPLATE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001148" ON "DB2ADMIN"."DMELETEMPLATE" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMEMSPOTCMD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMEMSPOTCMD" (
    "DMEMSPOTCMD_ID" INTEGER NOT NULL,
    "CONTENTTYPE" VARCHAR(254 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "EMSPOT_ID" INTEGER,
    "DMEMSPOTORD_ID" INTEGER,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMEMSPOTCMD"
ALTER TABLE "DB2ADMIN"."DMEMSPOTCMD"
ADD PRIMARY KEY ("DMEMSPOTCMD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEMSPOTCMD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001160" ON "DB2ADMIN"."DMEMSPOTCMD" (
    "CONTENTTYPE" ASC,
    "STOREENT_ID" ASC,
    "EMSPOT_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEMSPOTCMD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001161" ON "DB2ADMIN"."DMEMSPOTCMD" ("EMSPOT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEMSPOTCMD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001162" ON "DB2ADMIN"."DMEMSPOTCMD" ("DMEMSPOTORD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMEMSPOTDEF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMEMSPOTDEF" (
    "DMEMSPOTDEF_ID" INTEGER NOT NULL,
    "EMSPOT_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "CONTENTTYPE" VARCHAR(254 OCTETS) NOT NULL,
    "CONTENT" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMEMSPOTDEF"
ALTER TABLE "DB2ADMIN"."DMEMSPOTDEF"
ADD PRIMARY KEY ("DMEMSPOTDEF_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEMSPOTDEF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001163" ON "DB2ADMIN"."DMEMSPOTDEF" (
    "EMSPOT_ID" ASC,
    "STOREENT_ID" ASC,
    "CONTENTTYPE" ASC,
    "CONTENT" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEMSPOTDEF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001164" ON "DB2ADMIN"."DMEMSPOTDEF" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMEMSPOTORD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMEMSPOTORD" (
    "DMEMSPOTORD_ID" INTEGER NOT NULL,
    "CONTENTTYPE" VARCHAR(254 OCTETS) NOT NULL,
    "ORDERINGNAME" VARCHAR(254 OCTETS) NOT NULL,
    "INTERFACENAME" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMEMSPOTORD"
ALTER TABLE "DB2ADMIN"."DMEMSPOTORD"
ADD PRIMARY KEY ("DMEMSPOTORD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEMSPOTORD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001159" ON "DB2ADMIN"."DMEMSPOTORD" ("CONTENTTYPE" ASC, "ORDERINGNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMEMSPOTPAGE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMEMSPOTPAGE" (
    "EMSPOT_ID" INTEGER NOT NULL,
    "DMPAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMEMSPOTPAGE"
ALTER TABLE "DB2ADMIN"."DMEMSPOTPAGE"
ADD PRIMARY KEY ("EMSPOT_ID", "DMPAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEMSPOTPAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001158" ON "DB2ADMIN"."DMEMSPOTPAGE" ("DMPAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMEMSPOTSTATS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMEMSPOTSTATS" (
    "DMACTIVITY_ID" INTEGER NOT NULL,
    "EMSPOT_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL WITH DEFAULT 0,
    "VIEWS" INTEGER WITH DEFAULT 0,
    "CLICKS" INTEGER WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMEMSPOTSTATS"
ALTER TABLE "DB2ADMIN"."DMEMSPOTSTATS"
ADD PRIMARY KEY (
        "DMACTIVITY_ID",
        "EMSPOT_ID",
        "STOREENT_ID"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEMSPOTSTATS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001155" ON "DB2ADMIN"."DMEMSPOTSTATS" ("EMSPOT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMEXPFAMILY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMEXPFAMILY" (
    "DMACTIVITY_ID" INTEGER NOT NULL,
    "FAMILY_ID" INTEGER NOT NULL,
    "SEQUENCE" SMALLINT NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMEXPFAMILY"
ALTER TABLE "DB2ADMIN"."DMEXPFAMILY"
ADD PRIMARY KEY ("DMACTIVITY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEXPFAMILY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001200" ON "DB2ADMIN"."DMEXPFAMILY" ("FAMILY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMEXPLOG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMEXPLOG" (
    "DMEXPLOG_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "EXPERIMENT_ID" INTEGER NOT NULL,
    "TESTELEMENT_ID" INTEGER NOT NULL,
    "PERSONALIZATIONID" VARCHAR(30 OCTETS) NOT NULL,
    "CREATED" TIMESTAMP NOT NULL,
    "CLICKED" SMALLINT NOT NULL WITH DEFAULT 0,
    "VALUE" VARCHAR(254 OCTETS) NOT NULL,
    "CONTENTTYPE" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMEXPLOG"
ALTER TABLE "DB2ADMIN"."DMEXPLOG"
ADD PRIMARY KEY ("DMEXPLOG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEXPLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001198" ON "DB2ADMIN"."DMEXPLOG" (
    "STOREENT_ID" ASC,
    "PERSONALIZATIONID" ASC,
    "CREATED" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEXPLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001199" ON "DB2ADMIN"."DMEXPLOG" (
    "STOREENT_ID" ASC,
    "EXPERIMENT_ID" ASC,
    "TESTELEMENT_ID" ASC,
    "CREATED" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMEXPSTATS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMEXPSTATS" (
    "EXPERIMENT_ID" INTEGER NOT NULL,
    "TESTELEMENT_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL WITH DEFAULT 0,
    "VIEWS" INTEGER WITH DEFAULT 0,
    "VIEWORDERS" INTEGER WITH DEFAULT 0,
    "VIEWREVENUE" DECIMAL(20, 5) WITH DEFAULT 0,
    "CLICKS" INTEGER WITH DEFAULT 0,
    "CLICKORDERS" INTEGER WITH DEFAULT 0,
    "CLICKREVENUE" DECIMAL(20, 5) WITH DEFAULT 0,
    "CURRENCY" CHAR(3 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" BIGINT,
    "FIELD3" DECIMAL(20, 5),
    "FIELD4" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMEXPSTATS"
ALTER TABLE "DB2ADMIN"."DMEXPSTATS"
ADD PRIMARY KEY (
        "EXPERIMENT_ID",
        "TESTELEMENT_ID",
        "STOREENT_ID"
    );
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMEXPTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMEXPTYPE" (
    "DMEXPTYPE_ID" SMALLINT NOT NULL,
    "TYPE" VARCHAR(64 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMEXPTYPE"
ALTER TABLE "DB2ADMIN"."DMEXPTYPE"
ADD PRIMARY KEY ("DMEXPTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMMBRGRPPZN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMMBRGRPPZN" (
    "MBRGRP_ID" BIGINT NOT NULL,
    "PERSONALIZATIONID" VARCHAR(30 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMMBRGRPPZN"
ALTER TABLE "DB2ADMIN"."DMMBRGRPPZN"
ADD PRIMARY KEY ("MBRGRP_ID", "PERSONALIZATIONID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMMBRGRPPZN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001233" ON "DB2ADMIN"."DMMBRGRPPZN" ("PERSONALIZATIONID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMPAGE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMPAGE" (
    "DMPAGE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "PATH" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMPAGE"
ALTER TABLE "DB2ADMIN"."DMPAGE"
ADD PRIMARY KEY ("DMPAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMPAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001156" ON "DB2ADMIN"."DMPAGE" ("NAME" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMPAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001157" ON "DB2ADMIN"."DMPAGE" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMTEMPLATETYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMTEMPLATETYPE" (
    "DMTEMPLATETYPE_ID" SMALLINT NOT NULL,
    "TYPE" VARCHAR(64 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMTEMPLATETYPE"
ALTER TABLE "DB2ADMIN"."DMTEMPLATETYPE"
ADD PRIMARY KEY ("DMTEMPLATETYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMTRIGLSTN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMTRIGLSTN" (
    "DMELEMENT_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(64 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "DMACTIVITY_ID" INTEGER NOT NULL,
    "ALLUSERS" SMALLINT,
    "FIELD1" INTEGER,
    "FIELD2" BIGINT,
    "FIELD3" DECIMAL(20, 5),
    "FIELD4" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMTRIGLSTN"
ALTER TABLE "DB2ADMIN"."DMTRIGLSTN"
ADD PRIMARY KEY ("DMELEMENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMTRIGLSTN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001152" ON "DB2ADMIN"."DMTRIGLSTN" ("NAME" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMTRIGLSTN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001153" ON "DB2ADMIN"."DMTRIGLSTN" ("DMACTIVITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMTRIGLSTN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001154" ON "DB2ADMIN"."DMTRIGLSTN" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMTRIGSND"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMTRIGSND" (
    "DMELEMENT_ID" INTEGER NOT NULL,
    "PERSONALIZATIONID" VARCHAR(64 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL WITH DEFAULT 0,
    "TIMETOSEND" TIMESTAMP NOT NULL,
    "PARAMETERS" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "TAB16K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMTRIGSND"
ALTER TABLE "DB2ADMIN"."DMTRIGSND"
ADD PRIMARY KEY (
        "DMELEMENT_ID",
        "PERSONALIZATIONID",
        "STOREENT_ID"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMTRIGSND"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001195" ON "DB2ADMIN"."DMTRIGSND" ("TIMETOSEND" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMUSERBHVR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMUSERBHVR" (
    "PERSONALIZATIONID" VARCHAR(30 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL WITH DEFAULT 0,
    "BEHAVIOR" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "ACTION" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "EVENT" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "LASTUPDATED" TIMESTAMP,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "TAB16K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMUSERBHVR"
ALTER TABLE "DB2ADMIN"."DMUSERBHVR"
ADD PRIMARY KEY ("PERSONALIZATIONID", "STOREENT_ID");
---