------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GEONDDS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GEONDDS" (
    "GEONDDS_ID" INTEGER NOT NULL,
    "GEONODE_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(128 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GEONDDS"
ALTER TABLE "DB2ADMIN"."GEONDDS"
ADD PRIMARY KEY ("GEONDDS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."GEONDDS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001216" ON "DB2ADMIN"."GEONDDS" ("GEONODE_ID" ASC, "LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GEONODE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GEONODE" (
    "GEONODE_ID" INTEGER NOT NULL,
    "IDENTIFIER" VARCHAR(64 OCTETS) NOT NULL,
    "TYPE" CHAR(4 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "STOREENT_ID" INTEGER NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GEONODE"
ALTER TABLE "DB2ADMIN"."GEONODE"
ADD PRIMARY KEY ("GEONODE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."GEONODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001459" ON "DB2ADMIN"."GEONODE" ("STOREENT_ID" ASC, "IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GEOTREE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GEOTREE" (
    "GEOTREE_ID" INTEGER NOT NULL,
    "CHILD_GEONODE_ID" INTEGER NOT NULL,
    "PARENT_GEONODE_ID" INTEGER,
    "SEQUENCE" DOUBLE,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GEOTREE"
ALTER TABLE "DB2ADMIN"."GEOTREE"
ADD PRIMARY KEY ("GEOTREE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."GEOTREE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001217" ON "DB2ADMIN"."GEOTREE" (
    "CHILD_GEONODE_ID" ASC,
    "PARENT_GEONODE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."GEOTREE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001218" ON "DB2ADMIN"."GEOTREE" ("PARENT_GEONODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GRADDR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GRADDR" (
    "ADDRESS_ID" BIGINT NOT NULL,
    "FIELD1" INTEGER,
    "FIELD2" INTEGER,
    "LASTNAME" VARCHAR(128 OCTETS),
    "FIRSTNAME" VARCHAR(128 OCTETS),
    "MIDDLENAME" VARCHAR(128 OCTETS),
    "ADDRESS1" VARCHAR(128 OCTETS),
    "ADDRESS2" VARCHAR(64 OCTETS),
    "ADDRESS3" VARCHAR(50 OCTETS),
    "CITY" VARCHAR(128 OCTETS),
    "STATE" VARCHAR(128 OCTETS),
    "COUNTRY" VARCHAR(128 OCTETS),
    "ZIPCODE" VARCHAR(40 OCTETS),
    "EMAIL1" VARCHAR(254 OCTETS),
    "EMAIL2" VARCHAR(254 OCTETS),
    "TITLE" VARCHAR(50 OCTETS),
    "PHONE1" VARCHAR(32 OCTETS),
    "PHONE2" VARCHAR(32 OCTETS),
    "PHONE3" VARCHAR(32 OCTETS),
    "SUFFIX" VARCHAR(50 OCTETS),
    "FAX" VARCHAR(32 OCTETS),
    "FIELD3" VARCHAR(64 OCTETS),
    "FIELD4" VARCHAR(64 OCTETS),
    "FIELD5" VARCHAR(64 OCTETS),
    "SEARCHKEYLASTNAME" VARCHAR(128 OCTETS),
    "SEARCHKEYFIRSTNAME" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "UP_FIRSTNAME" VARCHAR(128 OCTETS) GENERATED ALWAYS AS (UPPER(FIRSTNAME)),
    "UP_LASTNAME" VARCHAR(128 OCTETS) GENERATED ALWAYS AS (UPPER(LASTNAME))
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GRADDR"
ALTER TABLE "DB2ADMIN"."GRADDR"
ADD PRIMARY KEY ("ADDRESS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRADDR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."GRADDR_INDEX2" ON "DB2ADMIN"."GRADDR" (
    "LASTNAME" ASC,
    "FIRSTNAME" ASC,
    "STATE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRADDR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001300" ON "DB2ADMIN"."GRADDR" ("SEARCHKEYLASTNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRADDR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001301" ON "DB2ADMIN"."GRADDR" ("SEARCHKEYFIRSTNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRADDR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00028" ON "DB2ADMIN"."GRADDR" ("UP_FIRSTNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRADDR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00029" ON "DB2ADMIN"."GRADDR" ("UP_LASTNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GRANNHIST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GRANNHIST" (
    "ANNHISTORY_ID" BIGINT NOT NULL,
    "GIFTREGISTRY_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "SENTDATE" DATE NOT NULL,
    "SENDEREMAIL" VARCHAR(254 OCTETS) NOT NULL,
    "MESSAGE" VARCHAR(254 OCTETS) NOT NULL,
    "SENDERNAME" VARCHAR(32 OCTETS) NOT NULL,
    "FIELD1" VARCHAR(64 OCTETS),
    "FIELD2" VARCHAR(64 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GRANNHIST"
ALTER TABLE "DB2ADMIN"."GRANNHIST"
ADD PRIMARY KEY ("ANNHISTORY_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GRANNTMPLT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GRANNTMPLT" (
    "TEMPLATE_ID" BIGINT NOT NULL,
    "EVENTTYPE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "DEFAULTTEMPLATE" SMALLINT NOT NULL,
    "TEMPLATENAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "THUMBNAILPATH" VARCHAR(254 OCTETS),
    "PATH" VARCHAR(254 OCTETS) NOT NULL,
    "FIELD1" VARCHAR(64 OCTETS),
    "FIELD2" VARCHAR(64 OCTETS),
    "FIELD3" VARCHAR(64 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GRANNTMPLT"
ALTER TABLE "DB2ADMIN"."GRANNTMPLT"
ADD PRIMARY KEY ("TEMPLATE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GREMLLIST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GREMLLIST" (
    "EMAILLIST_ID" BIGINT NOT NULL,
    "ANNHISTORY_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "EMLTYPE" INTEGER NOT NULL,
    "NAME" VARCHAR(32 OCTETS),
    "EMAIL" VARCHAR(254 OCTETS) NOT NULL
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GREMLLIST"
ALTER TABLE "DB2ADMIN"."GREMLLIST"
ADD PRIMARY KEY ("EMAILLIST_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GRETDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GRETDESC" (
    "EVENTTYPE_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "DESCRIPTION" VARCHAR(256 OCTETS) NOT NULL WITH DEFAULT ''
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GRETDESC"
ALTER TABLE "DB2ADMIN"."GRETDESC"
ADD PRIMARY KEY ("EVENTTYPE_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GREVNTTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GREVNTTYPE" (
    "EVENTTYPE_ID" INTEGER NOT NULL,
    "SORTORDER" BIGINT NOT NULL,
    "STATUS" INTEGER NOT NULL WITH DEFAULT 1,
    "STOREID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "FIELD1" VARCHAR(64 OCTETS),
    "FIELD2" VARCHAR(64 OCTETS),
    "FIELD3" VARCHAR(64 OCTETS),
    "EVENTTYPENAME" VARCHAR(32 OCTETS) NOT NULL
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GREVNTTYPE"
ALTER TABLE "DB2ADMIN"."GREVNTTYPE"
ADD PRIMARY KEY ("EVENTTYPE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."GREVNTTYPE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."GRE_INDEX1" ON "DB2ADMIN"."GREVNTTYPE" ("EVENTTYPENAME" ASC, "STOREID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GREVTRMDLG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GREVTRMDLG" (
    "EVTRMDLG_ID" BIGINT NOT NULL,
    "GIFTREGISTRY_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "SENTDATE" DATE NOT NULL,
    "REMINDERTYPE" VARCHAR(32 OCTETS) NOT NULL
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GREVTRMDLG"
ALTER TABLE "DB2ADMIN"."GREVTRMDLG"
ADD PRIMARY KEY ("EVTRMDLG_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GRGFTITM"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GRGFTITM" (
    "GIFTITEM_ID" BIGINT NOT NULL,
    "GIFTREGISTRY_ID" BIGINT NOT NULL,
    "QUANTITYREQUESTED" INTEGER NOT NULL,
    "QUANTITYBOUGHT" INTEGER NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" INTEGER,
    "OPTCOUNTER" SMALLINT,
    "CREATETIME" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    "LASTUPDATE" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    "LOCATION" VARCHAR(32 OCTETS) NOT NULL,
    "PARTNUMBER" VARCHAR(64 OCTETS) NOT NULL,
    "PARTAUXKEY" VARCHAR(64 OCTETS) NOT NULL WITH DEFAULT '',
    "FIELD3" VARCHAR(64 OCTETS),
    "FIELD4" VARCHAR(64 OCTETS),
    "FIELD5" VARCHAR(64 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GRGFTITM"
ALTER TABLE "DB2ADMIN"."GRGFTITM"
ADD PRIMARY KEY ("GIFTITEM_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRGFTITM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."GIFTITEM_UINDEX1" ON "DB2ADMIN"."GRGFTITM" (
    "GIFTREGISTRY_ID" ASC,
    "PARTNUMBER" ASC,
    "PARTAUXKEY" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRGFTITM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."GIFTITEM_INDEX2" ON "DB2ADMIN"."GRGFTITM" ("GIFTREGISTRY_ID" ASC, "PARTNUMBER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GRGFTREG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GRGFTREG" (
    "GIFTREGISTRY_ID" BIGINT NOT NULL,
    "EVENTTYPE_ID" INTEGER NOT NULL,
    "GUESTACCESSOPTION" INTEGER NOT NULL WITH DEFAULT 0,
    "PREEVENTADDRESS_ID" BIGINT NOT NULL,
    "POSTEVENTADDRESS_ID" BIGINT NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "ACCEPTGIFTCARD" INTEGER NOT NULL,
    "STOREID" INTEGER NOT NULL,
    "OPTFOREMAIL" INTEGER NOT NULL,
    "REGTYPE" INTEGER NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" INTEGER,
    "OPTCOUNTER" SMALLINT,
    "CREATEDTIME" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    "LASTUPDATE" TIMESTAMP NOT NULL,
    "EVENTDATE" DATE NOT NULL,
    "LOCATION" VARCHAR(32 OCTETS) NOT NULL,
    "EXTERNALID" VARCHAR(64 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "MESSAGEFORGUEST" VARCHAR(512 OCTETS),
    "NAME" VARCHAR(64 OCTETS),
    "GUESTACCESSKEY" VARCHAR(64 OCTETS),
    "REGACCESSKEY" VARCHAR(64 OCTETS),
    "FIELD3" VARCHAR(64 OCTETS),
    "FIELD4" VARCHAR(64 OCTETS),
    "FIELD5" VARCHAR(64 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GRGFTREG"
ALTER TABLE "DB2ADMIN"."GRGFTREG"
ADD PRIMARY KEY ("GIFTREGISTRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRGFTREG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."GR_INDEX1" ON "DB2ADMIN"."GRGFTREG" ("EXTERNALID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRGFTREG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."GRG_CONSTRAINT1" ON "DB2ADMIN"."GRGFTREG" ("STOREID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRGFTREG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."GR_INDEX2" ON "DB2ADMIN"."GRGFTREG" ("POSTEVENTADDRESS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRGFTREG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."GR_INDEX3" ON "DB2ADMIN"."GRGFTREG" ("PREEVENTADDRESS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GRPERATTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GRPERATTR" (
    "PERATTR_ID" VARCHAR(64 OCTETS) NOT NULL,
    "GIFTITEM_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "VALUE" VARCHAR(64 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GRPERATTR"
ALTER TABLE "DB2ADMIN"."GRPERATTR"
ADD PRIMARY KEY ("GIFTITEM_ID", "PERATTR_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GRPURREC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GRPURREC" (
    "PURCHASERECORD_ID" BIGINT NOT NULL,
    "GIFTREGISTRY_ID" BIGINT NOT NULL,
    "ADDRESS_ID" BIGINT,
    "ORDERITEMID" BIGINT,
    "GIFTITEM_ID" BIGINT,
    "CREATETIME" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    "UPDATETIME" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    "PURCHASEDATE" DATE NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "ISNOTESENT" SMALLINT NOT NULL,
    "PURCHASEQUANTITY" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "TRANSACTIONID" VARCHAR(32 OCTETS),
    "REGISTRANTMEMO" VARCHAR(254 OCTETS),
    "PURCHASELOCATION" VARCHAR(32 OCTETS) NOT NULL,
    "PARTNUMBER" VARCHAR(64 OCTETS) NOT NULL,
    "PARTAUXKEY" VARCHAR(64 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GRPURREC"
ALTER TABLE "DB2ADMIN"."GRPURREC"
ADD PRIMARY KEY ("PURCHASERECORD_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GRREGRULE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GRREGRULE" (
    "GRREGRULE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "STOREID" INTEGER NOT NULL,
    "NAME" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "EVENTTYPENAME" VARCHAR(32 OCTETS),
    "GRRULEVAL" VARCHAR(254 OCTETS) NOT NULL
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GRREGRULE"
ALTER TABLE "DB2ADMIN"."GRREGRULE"
ADD PRIMARY KEY ("GRREGRULE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GRRGSTRNT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GRRGSTRNT" (
    "REGISTRANT_ID" BIGINT NOT NULL,
    "ADDRESS_ID" BIGINT NOT NULL,
    "GIFTREGISTRY_ID" BIGINT NOT NULL,
    "RGSTRNTTYPE" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "USERID" VARCHAR(32 OCTETS),
    "RELATION" VARCHAR(64 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GRRGSTRNT"
ALTER TABLE "DB2ADMIN"."GRRGSTRNT"
ADD PRIMARY KEY ("REGISTRANT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRRGSTRNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."GRR_CONSTRAINT3" ON "DB2ADMIN"."GRRGSTRNT" ("GIFTREGISTRY_ID" ASC, "ADDRESS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."GRRGSTRNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IDXGRRGSTU1" ON "DB2ADMIN"."GRRGSTRNT" (
    "USERID" ASC,
    "RGSTRNTTYPE" ASC,
    "GIFTREGISTRY_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."GRUSERAUTH"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."GRUSERAUTH" (
    "GIFTREGISTRY_ID" BIGINT NOT NULL,
    "PASSWORD" CHAR(128 OCTETS) FOR BIT DATA NOT NULL,
    "OPTCOUNTER" SMALLINT,
    "ACCESSTYPE" INTEGER NOT NULL,
    "STATUS" INTEGER NOT NULL WITH DEFAULT 1,
    "PASSWORDCREATION" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    "SALT" VARCHAR(254 OCTETS) NOT NULL
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."GRUSERAUTH"
ALTER TABLE "DB2ADMIN"."GRUSERAUTH"
ADD PRIMARY KEY ("GIFTREGISTRY_ID", "ACCESSTYPE");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."HISTOATTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."HISTOATTR" (
    "ATTRIBUTEID" VARCHAR(200 OCTETS) NOT NULL,
    "HISTOID" BIGINT NOT NULL,
    "HISTOTYPE" INTEGER NOT NULL,
    "BUCKETCOUNT" INTEGER,
    "MAXVALUE" DOUBLE,
    "MINVALUE" DOUBLE,
    "RANGEARR" VARCHAR(3200 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."HISTOATTR"
ALTER TABLE "DB2ADMIN"."HISTOATTR"
ADD PRIMARY KEY ("HISTOID", "HISTOTYPE", "ATTRIBUTEID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."HISTOFREQ"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."HISTOFREQ" (
    "HISTOID" BIGINT NOT NULL,
    "FREQ" VARCHAR(3200 OCTETS),
    "HISTOTYPE" INTEGER NOT NULL,
    "SEQNUM" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."HISTOFREQ"
ALTER TABLE "DB2ADMIN"."HISTOFREQ"
ADD PRIMARY KEY ("HISTOID", "HISTOTYPE", "SEQNUM");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."HISTONVP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."HISTONVP" (
    "FIELDNAME" VARCHAR(200 OCTETS) NOT NULL,
    "HISTOID" BIGINT NOT NULL,
    "FIELDVALUE" VARCHAR(32 OCTETS),
    "HISTOTYPE" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."HISTONVP"
ALTER TABLE "DB2ADMIN"."HISTONVP"
ADD PRIMARY KEY ("HISTOID", "HISTOTYPE", "FIELDNAME");
-- DDL Statements for Indexes on Table "DB2ADMIN"."HISTONVP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000332" ON "DB2ADMIN"."HISTONVP" ("HISTOID" ASC, "HISTOTYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."HMBITEMS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."HMBITEMS" (
    "HBMRFNBR" INTEGER NOT NULL,
    "HBTRFNBR" INTEGER NOT NULL,
    "HBINTVALUE" INTEGER,
    "HBCURVALUE" DECIMAL(20, 5),
    "HBCUR" CHAR(10 OCTETS),
    "HBFROMSTMP" TIMESTAMP,
    "HBTOSTMP" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."HMBITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000115" ON "DB2ADMIN"."HMBITEMS" (
    "HBMRFNBR" ASC,
    "HBTRFNBR" ASC,
    "HBFROMSTMP" ASC,
    "HBTOSTMP" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICCNCPTLNK"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICCNCPTLNK" (
    "CONCEPTID" INTEGER NOT NULL,
    "METAPHORID" INTEGER NOT NULL,
    "PASSCONSTLIST" INTEGER NOT NULL WITH DEFAULT 1,
    "TEMPLATEUSAGE" INTEGER NOT NULL WITH DEFAULT 1,
    "TEMPLATENAME" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICCNCPTLNK"
ALTER TABLE "DB2ADMIN"."ICCNCPTLNK"
ADD PRIMARY KEY ("CONCEPTID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICCNCPTLNK"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000333" ON "DB2ADMIN"."ICCNCPTLNK" ("METAPHORID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICCONSTRNT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICCONSTRNT" (
    "CONSTRAINTID" INTEGER NOT NULL,
    "CONCEPTID" INTEGER NOT NULL,
    "FEATUREID" INTEGER NOT NULL,
    "FEATURENAME" CHAR(18 OCTETS) NOT NULL,
    "OPERATION" VARCHAR(5 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICCONSTRNT"
ALTER TABLE "DB2ADMIN"."ICCONSTRNT"
ADD PRIMARY KEY ("CONSTRAINTID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICCONSTRNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000334" ON "DB2ADMIN"."ICCONSTRNT" ("FEATUREID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICCONSTRNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000335" ON "DB2ADMIN"."ICCONSTRNT" ("CONCEPTID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICCONSTVAL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICCONSTVAL" (
    "CONSTRAINTID" INTEGER NOT NULL,
    "VALUE" VARCHAR(254 OCTETS) NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICCONSTVAL"
ALTER TABLE "DB2ADMIN"."ICCONSTVAL"
ADD PRIMARY KEY ("CONSTRAINTID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICDATAREG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICDATAREG" (
    "REFID" INTEGER NOT NULL,
    "CLASSNAME" CHAR(100 OCTETS) NOT NULL,
    "BASETYPE" CHAR(100 OCTETS) NOT NULL,
    "DISPLAYNAME" CHAR(80 OCTETS) NOT NULL,
    "DEFAULTTYPE" INTEGER NOT NULL WITH DEFAULT 0,
    "ORDERSEQ" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICDATAREG"
ALTER TABLE "DB2ADMIN"."ICDATAREG"
ADD PRIMARY KEY ("REFID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICDATAREG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000116" ON "DB2ADMIN"."ICDATAREG" ("CLASSNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICDEWIDREG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICDEWIDREG" (
    "CLASSNAME" CHAR(100 OCTETS) NOT NULL,
    "DISPLAYNAME" CHAR(100 OCTETS) NOT NULL,
    "ORDERSEQ" INTEGER NOT NULL WITH DEFAULT 1,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICDEWIDREG"
ALTER TABLE "DB2ADMIN"."ICDEWIDREG"
ADD PRIMARY KEY ("CLASSNAME");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICEXPLDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICEXPLDESC" (
    "FEATUREID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "UNITOFMEASURE" VARCHAR(20 OCTETS),
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "ELABORATION" VARCHAR(254 OCTETS),
    "SCALE" INTEGER,
    "PRECISION" INTEGER,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICEXPLDESC"
ALTER TABLE "DB2ADMIN"."ICEXPLDESC"
ADD PRIMARY KEY ("FEATUREID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICEXPLDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000117" ON "DB2ADMIN"."ICEXPLDESC" ("NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICEXPLFEAT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICEXPLFEAT" (
    "FEATUREID" INTEGER NOT NULL,
    "COLUMNNAME" VARCHAR(254 OCTETS) NOT NULL,
    "LENGTH" INTEGER NOT NULL WITH DEFAULT 0,
    "DATATYPE" CHAR(100 OCTETS),
    "KEYSEQUENCE" INTEGER NOT NULL WITH DEFAULT 0,
    "NULLABLE" INTEGER NOT NULL WITH DEFAULT 1,
    "LOCATION" INTEGER NOT NULL WITH DEFAULT 2,
    "INCLUDED" INTEGER NOT NULL WITH DEFAULT 1,
    "RELEVANCE" INTEGER NOT NULL WITH DEFAULT 1,
    "CATGROUP_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICEXPLFEAT"
ALTER TABLE "DB2ADMIN"."ICEXPLFEAT"
ADD PRIMARY KEY ("FEATUREID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICEXPLFEAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000118" ON "DB2ADMIN"."ICEXPLFEAT" ("CATGROUP_ID" ASC, "COLUMNNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICEXPLFEAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000119" ON "DB2ADMIN"."ICEXPLFEAT" ("COLUMNNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICFEATPROP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICFEATPROP" (
    "FEATUREID" INTEGER NOT NULL,
    "METAPHORID" INTEGER NOT NULL,
    "PROPERTYNAME" VARCHAR(64 OCTETS) NOT NULL,
    "PROPERTYTYPE" INTEGER NOT NULL,
    "PROPERTYVALUE" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICFEATPROP"
ALTER TABLE "DB2ADMIN"."ICFEATPROP"
ADD PRIMARY KEY ("FEATUREID", "METAPHORID", "PROPERTYNAME");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICFEATPROP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000331" ON "DB2ADMIN"."ICFEATPROP" ("METAPHORID" ASC, "FEATUREID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICKNOWDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICKNOWDESC" (
    "CONCEPTID" INTEGER NOT NULL,
    "CONCEPTNAME" VARCHAR(512 OCTETS) NOT NULL,
    "DESCRIPTOR" VARCHAR(512 OCTETS),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICKNOWDESC"
ALTER TABLE "DB2ADMIN"."ICKNOWDESC"
ADD PRIMARY KEY ("CONCEPTID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICKNOWLEDG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICKNOWLEDG" (
    "TREEID" INTEGER NOT NULL,
    "CONCEPTID" INTEGER NOT NULL,
    "PARENTCONCEPTID" INTEGER,
    "STOREID" INTEGER,
    "CLASSNAME" CHAR(100 OCTETS) NOT NULL,
    "METAPHORLINKID" INTEGER,
    "ORDERSEQUENCE" INTEGER NOT NULL WITH DEFAULT 0,
    "RANKING" DOUBLE NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICKNOWLEDG"
ALTER TABLE "DB2ADMIN"."ICKNOWLEDG"
ADD PRIMARY KEY ("CONCEPTID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICKNOWLEDG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000120" ON "DB2ADMIN"."ICKNOWLEDG" (
    "TREEID" ASC,
    "PARENTCONCEPTID" ASC,
    "CLASSNAME" ASC,
    "ORDERSEQUENCE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICKNOWLEDG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000121" ON "DB2ADMIN"."ICKNOWLEDG" ("STOREID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICKNOWLEDG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001296" ON "DB2ADMIN"."ICKNOWLEDG" ("PARENTCONCEPTID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICMERDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICMERDESC" (
    "TREEID" INTEGER NOT NULL,
    "DESCRIPTOR" VARCHAR(254 OCTETS),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICMERDESC"
ALTER TABLE "DB2ADMIN"."ICMERDESC"
ADD PRIMARY KEY ("LANGUAGE_ID", "TREEID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICMERDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000578" ON "DB2ADMIN"."ICMERDESC" ("TREEID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICMERTREE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICMERTREE" (
    "STOREID" INTEGER NOT NULL,
    "TREEID" INTEGER NOT NULL,
    "METAPHORID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICMERTREE"
ALTER TABLE "DB2ADMIN"."ICMERTREE"
ADD PRIMARY KEY ("TREEID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICMERTREE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000122" ON "DB2ADMIN"."ICMERTREE" ("METAPHORID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICMERTREE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000579" ON "DB2ADMIN"."ICMERTREE" ("STOREID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICMETAFEAT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICMETAFEAT" (
    "FEATUREID" INTEGER NOT NULL,
    "STOREID" INTEGER NOT NULL,
    "METAPHORID" INTEGER NOT NULL,
    "DISPLAYABLE" INTEGER NOT NULL,
    "ORDERSEQ" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICMETAFEAT"
ALTER TABLE "DB2ADMIN"."ICMETAFEAT"
ADD PRIMARY KEY ("FEATUREID", "METAPHORID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICMETAFEAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000123" ON "DB2ADMIN"."ICMETAFEAT" ("STOREID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICMETAFEAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000124" ON "DB2ADMIN"."ICMETAFEAT" ("ORDERSEQ" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICMETAFEAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001259" ON "DB2ADMIN"."ICMETAFEAT" ("METAPHORID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICMETAPHOR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICMETAPHOR" (
    "METAPHORID" INTEGER NOT NULL,
    "CATEGORYID" BIGINT NOT NULL,
    "STOREID" INTEGER NOT NULL,
    "TREEID" INTEGER,
    "EXPLREQ" INTEGER,
    "METAPHORNAME" VARCHAR(128 OCTETS) NOT NULL,
    "PUBLISH" INTEGER NOT NULL WITH DEFAULT 0,
    "SYNC" INTEGER NOT NULL WITH DEFAULT 1,
    "TEMPLATENAME" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICMETAPHOR"
ALTER TABLE "DB2ADMIN"."ICMETAPHOR"
ADD PRIMARY KEY ("METAPHORID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICMETAPHOR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000125" ON "DB2ADMIN"."ICMETAPHOR" (
    "METAPHORNAME" ASC,
    "CATEGORYID" ASC,
    "STOREID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICMETAPHOR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000127" ON "DB2ADMIN"."ICMETAPHOR" ("STOREID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICMETAPHOR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000580" ON "DB2ADMIN"."ICMETAPHOR" ("CATEGORYID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICMETAPHOR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000581" ON "DB2ADMIN"."ICMETAPHOR" ("TREEID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICMETAPROP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICMETAPROP" (
    "METAPHORID" INTEGER NOT NULL,
    "PROPERTYNAME" VARCHAR(64 OCTETS) NOT NULL,
    "PROPERTYTYPE" INTEGER NOT NULL,
    "PROPERTYVALUE" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICMETAPROP"
ALTER TABLE "DB2ADMIN"."ICMETAPROP"
ADD PRIMARY KEY ("METAPHORID", "PROPERTYNAME");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICMETAREG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICMETAREG" (
    "METAPHORTYPEID" INTEGER NOT NULL,
    "CLASSNAME" CHAR(100 OCTETS) NOT NULL,
    "BUILDERNAME" CHAR(100 OCTETS) NOT NULL,
    "EXPLSPCREQ" INTEGER NOT NULL WITH DEFAULT 1,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICMETAREG"
ALTER TABLE "DB2ADMIN"."ICMETAREG"
ADD PRIMARY KEY ("METAPHORTYPEID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICMREGDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICMREGDESC" (
    "METAPHORTYPEID" INTEGER NOT NULL,
    "TITLE" CHAR(128 OCTETS) NOT NULL,
    "ICONNAME" CHAR(128 OCTETS) NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICMREGDESC"
ALTER TABLE "DB2ADMIN"."ICMREGDESC"
ADD PRIMARY KEY ("METAPHORTYPEID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICROOTCAT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICROOTCAT" (
    "ROOTCATEGORYID" BIGINT NOT NULL,
    "CATGROUP_ID" BIGINT,
    "PFPASYNC" INTEGER NOT NULL WITH DEFAULT 0,
    "PFREQ" INTEGER NOT NULL WITH DEFAULT 1,
    "TABLENAME" VARCHAR(64 OCTETS) NOT NULL,
    "LASTMODIFIED" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ICROOTCAT"
ALTER TABLE "DB2ADMIN"."ICROOTCAT"
ADD PRIMARY KEY ("ROOTCATEGORYID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICROOTCAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000128" ON "DB2ADMIN"."ICROOTCAT" ("ROOTCATEGORYID" ASC, "PFREQ" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICROOTCAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000129" ON "DB2ADMIN"."ICROOTCAT" ("LASTMODIFIED" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICROOTCAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000582" ON "DB2ADMIN"."ICROOTCAT" ("CATGROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ICTPRICES"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ICTPRICES" (
    "STOREID" INTEGER NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "IPSGNBR" INTEGER,
    "PPPRC" DECIMAL(20, 5),
    "SETCCURR" CHAR(3 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICTPRICES"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000130" ON "DB2ADMIN"."ICTPRICES" ("IPSGNBR" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICTPRICES"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000131" ON "DB2ADMIN"."ICTPRICES" ("PPPRC" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ICTPRICES"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000583" ON "DB2ADMIN"."ICTPRICES" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."IITEM"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."IITEM" (
    "CATENTRY_ID" BIGINT NOT NULL,
    "IITEMLIST_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "LASTUPDATE" TIMESTAMP,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" DECIMAL(20, 5),
    "QUANTITY" DOUBLE,
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."IITEM"
ALTER TABLE "DB2ADMIN"."IITEM"
ADD PRIMARY KEY ("IITEMLIST_ID", "CATENTRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."IITEM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000584" ON "DB2ADMIN"."IITEM" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."IITEM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000585" ON "DB2ADMIN"."IITEM" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."IITEM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000586" ON "DB2ADMIN"."IITEM" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."IITEMLIST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."IITEMLIST" (
    "IITEMLIST_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS) NOT NULL WITH DEFAULT '',
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "LASTUPDATE" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."IITEMLIST"
ALTER TABLE "DB2ADMIN"."IITEMLIST"
ADD PRIMARY KEY ("IITEMLIST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."IITEMLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000132" ON "DB2ADMIN"."IITEMLIST" (
    "IITEMLIST_ID" ASC,
    "SEQUENCE" ASC,
    "MEMBER_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."IITEMLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000133" ON "DB2ADMIN"."IITEMLIST" ("IITEMLIST_ID" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."IITEMLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000587" ON "DB2ADMIN"."IITEMLIST" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INIRULEVAL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INIRULEVAL" (
    "INIRULEVAL_ID" INTEGER NOT NULL,
    "PATH" VARCHAR(1024 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INIRULEVAL"
ALTER TABLE "DB2ADMIN"."INIRULEVAL"
ADD PRIMARY KEY ("INIRULEVAL_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INITIATIVE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INITIATIVE" (
    "INITIATIVE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(64 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "CAMPAIGN_ID" INTEGER,
    "TYPE" INTEGER,
    "STATUS" CHAR(1 OCTETS),
    "FIELD1" VARCHAR(254 OCTETS),
    "LASTUPDATE" TIMESTAMP NOT NULL,
    "LASTUPDATEDBY" VARCHAR(254 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "RULE" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "RESULTTYPE" CHAR(1 OCTETS),
    "SELLTYPE" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INITIATIVE"
ALTER TABLE "DB2ADMIN"."INITIATIVE"
ADD PRIMARY KEY ("INITIATIVE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."INITIATIVE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000134" ON "DB2ADMIN"."INITIATIVE" ("NAME" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."INITIATIVE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000588" ON "DB2ADMIN"."INITIATIVE" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."INITIATIVE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000589" ON "DB2ADMIN"."INITIATIVE" ("CAMPAIGN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INTVSCHED"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INTVSCHED" (
    "INTVSCHED_ID" INTEGER NOT NULL,
    "INITIATIVE_ID" INTEGER NOT NULL,
    "EMSPOT_ID" INTEGER NOT NULL,
    "STARTDATE" TIMESTAMP NOT NULL,
    "ENDDATE" TIMESTAMP NOT NULL,
    "PRIORITY" INTEGER,
    "STOREENT_ID" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INTVSCHED"
ALTER TABLE "DB2ADMIN"."INTVSCHED"
ADD PRIMARY KEY ("INTVSCHED_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."INTVSCHED"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000313" ON "DB2ADMIN"."INTVSCHED" ("EMSPOT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."INTVSCHED"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000314" ON "DB2ADMIN"."INTVSCHED" ("INITIATIVE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."INTVSCHED"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000590" ON "DB2ADMIN"."INTVSCHED" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INVADJCODE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INVADJCODE" (
    "INVADJCODE_ID" BIGINT NOT NULL,
    "ADJUSTCODE" CHAR(4 OCTETS) NOT NULL,
    "LASTUPDATE" TIMESTAMP,
    "STOREENT_ID" INTEGER NOT NULL,
    "MARKFORDELETE" INTEGER WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INVADJCODE"
ALTER TABLE "DB2ADMIN"."INVADJCODE"
ADD PRIMARY KEY ("INVADJCODE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVADJCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000135" ON "DB2ADMIN"."INVADJCODE" ("ADJUSTCODE" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVADJCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000591" ON "DB2ADMIN"."INVADJCODE" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INVADJDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INVADJDESC" (
    "INVADJCODE_ID" BIGINT NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "LASTUPDATE" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INVADJDESC"
ALTER TABLE "DB2ADMIN"."INVADJDESC"
ADD PRIMARY KEY ("INVADJCODE_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INVADJUST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INVADJUST" (
    "INVADJUST_ID" BIGINT NOT NULL,
    "INVADJUSTNUM" INTEGER NOT NULL,
    "INVADJCODE_ID" BIGINT NOT NULL,
    "RECEIPT_ID" BIGINT NOT NULL,
    "ADJUSTMENTDATE" TIMESTAMP,
    "QUANTITY" INTEGER,
    "ADJUSTMENTCOMMENT" VARCHAR(254 OCTETS),
    "LASTUPDATE" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INVADJUST"
ALTER TABLE "DB2ADMIN"."INVADJUST"
ADD PRIMARY KEY ("INVADJUST_ID", "INVADJUSTNUM");
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVADJUST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000136" ON "DB2ADMIN"."INVADJUST" (
    "INVADJUST_ID" ASC,
    "INVADJCODE_ID" ASC,
    "ADJUSTMENTDATE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVADJUST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000592" ON "DB2ADMIN"."INVADJUST" ("RECEIPT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVADJUST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000593" ON "DB2ADMIN"."INVADJUST" ("INVADJCODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INVAVL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INVAVL" (
    "INVAVL_ID" BIGINT NOT NULL,
    "AVAILQUANTITY" DOUBLE,
    "AVAILTIME" TIMESTAMP,
    "AVAILOFFSET" INTEGER,
    "LASTUPDATE" TIMESTAMP,
    "FIELD1" INTEGER,
    "FIELD2" DECIMAL(20, 5),
    "FIELD3" VARCHAR(254 OCTETS),
    "CATENTRY_ID" BIGINT NOT NULL,
    "STORE_ID" INTEGER,
    "STLOC_ID" INTEGER,
    "QUANTITYMEASURE" CHAR(16 OCTETS) NOT NULL WITH DEFAULT 'C62',
    "INVENTORYSTATUS" CHAR(4 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INVAVL"
ALTER TABLE "DB2ADMIN"."INVAVL"
ADD PRIMARY KEY ("INVAVL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVAVL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001223" ON "DB2ADMIN"."INVAVL" (
    "CATENTRY_ID" ASC,
    "STORE_ID" ASC,
    "STLOC_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVAVL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001224" ON "DB2ADMIN"."INVAVL" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVAVL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001225" ON "DB2ADMIN"."INVAVL" ("STLOC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INVCNF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INVCNF" (
    "INVCNF_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(64 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "PRECEDENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "FLAGS" INTEGER NOT NULL WITH DEFAULT 0,
    "THRESHOLDQUANTITY" DOUBLE,
    "CHEXPABOVETHRES" INTEGER,
    "CHEXPBELOWTHRES" INTEGER,
    "CACHEPRIORITY" INTEGER NOT NULL WITH DEFAULT 0,
    "FALLBACKINVSTAT" CHAR(4 OCTETS),
    "FALLBACKAVAILTIME" TIMESTAMP,
    "FALLBACKINVOFFSET" INTEGER,
    "FIELD1" INTEGER,
    "FIELD2" DECIMAL(20, 5),
    "FIELD3" VARCHAR(254 OCTETS),
    "QUANTITYMEASURE" CHAR(16 OCTETS) NOT NULL WITH DEFAULT 'C62',
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INVCNF"
ALTER TABLE "DB2ADMIN"."INVCNF"
ADD PRIMARY KEY ("INVCNF_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVCNF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001226" ON "DB2ADMIN"."INVCNF" ("IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INVCNFREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INVCNFREL" (
    "INVCNFREL_ID" BIGINT NOT NULL,
    "INVCNF_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT,
    "STORE_ID" INTEGER,
    "STLOC_ID" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INVCNFREL"
ALTER TABLE "DB2ADMIN"."INVCNFREL"
ADD PRIMARY KEY ("INVCNFREL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVCNFREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001227" ON "DB2ADMIN"."INVCNFREL" (
    "CATENTRY_ID" ASC,
    "STORE_ID" ASC,
    "STLOC_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVCNFREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001228" ON "DB2ADMIN"."INVCNFREL" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVCNFREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001229" ON "DB2ADMIN"."INVCNFREL" ("STLOC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INVENTORY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INVENTORY" (
    "CATENTRY_ID" BIGINT NOT NULL,
    "QUANTITY" DOUBLE NOT NULL WITH DEFAULT 0,
    "FFMCENTER_ID" INTEGER NOT NULL,
    "STORE_ID" INTEGER NOT NULL,
    "QUANTITYMEASURE" CHAR(16 OCTETS) NOT NULL WITH DEFAULT 'C62',
    "INVENTORYFLAGS" INTEGER NOT NULL WITH DEFAULT 1,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INVENTORY"
ALTER TABLE "DB2ADMIN"."INVENTORY"
ADD PRIMARY KEY ("CATENTRY_ID", "FFMCENTER_ID", "STORE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVENTORY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000595" ON "DB2ADMIN"."INVENTORY" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVENTORY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000594X" ON "DB2ADMIN"."INVENTORY" (
    "FFMCENTER_ID" ASC,
    "QUANTITY" ASC,
    "CATENTRY_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
COMMENT ON INDEX "DB2ADMIN"."I0000594X" IS 'index to support Inventory lookup for OrderItems at COLES';
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INVOICE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INVOICE" (
    "INVOICE_ID" BIGINT NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "ORDRELEASENUM" INTEGER NOT NULL,
    "INVOICEXML" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "STATUS" CHAR(4 OCTETS),
    "TIMECREATED" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INVOICE"
ALTER TABLE "DB2ADMIN"."INVOICE"
ADD PRIMARY KEY ("INVOICE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVOICE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000596" ON "DB2ADMIN"."INVOICE" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INVRESERVE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INVRESERVE" (
    "INVRESERVE_ID" BIGINT NOT NULL,
    "INVRSRVTYP_ID" BIGINT NOT NULL,
    "QUANTITY" INTEGER,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "EXPIRATION" TIMESTAMP,
    "ITEMSPC_ID" BIGINT,
    "LASTUPDATE" TIMESTAMP,
    "STORE_ID" INTEGER,
    "FFMCENTER_ID" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INVRESERVE"
ALTER TABLE "DB2ADMIN"."INVRESERVE"
ADD PRIMARY KEY ("INVRESERVE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."INVRESERVE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001260" ON "DB2ADMIN"."INVRESERVE" (
    "ITEMSPC_ID" ASC,
    "STORE_ID" ASC,
    "FFMCENTER_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INVRSRVDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INVRSRVDSC" (
    "INVRSRVTYP_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS),
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INVRSRVDSC"
ALTER TABLE "DB2ADMIN"."INVRSRVDSC"
ADD PRIMARY KEY ("INVRSRVTYP_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."INVRSRVTYP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."INVRSRVTYP" (
    "INVRSRVTYP_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."INVRSRVTYP"
ALTER TABLE "DB2ADMIN"."INVRSRVTYP"
ADD PRIMARY KEY ("INVRSRVTYP_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ISEDITATT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ISEDITATT" (
    "ISEDITATT_ID" INTEGER NOT NULL,
    "PROFILE_ID" INTEGER NOT NULL,
    "CUSTOMIZABLE" INTEGER NOT NULL,
    "INTERSPECATTNAME" VARCHAR(254 OCTETS) NOT NULL,
    "INTERSPECATTVALUE" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ISEDITATT"
ALTER TABLE "DB2ADMIN"."ISEDITATT"
ADD PRIMARY KEY ("ISEDITATT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ISEDITATT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000137" ON "DB2ADMIN"."ISEDITATT" ("PROFILE_ID" ASC, "INTERSPECATTNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ITEMFFMCTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ITEMFFMCTR" (
    "ITEMSPC_ID" BIGINT NOT NULL,
    "STORE_ID" INTEGER NOT NULL,
    "FFMCENTER_ID" INTEGER NOT NULL,
    "QTYBACKORDERED" INTEGER NOT NULL WITH DEFAULT 0,
    "QTYALLOCBACKORDER" INTEGER NOT NULL WITH DEFAULT 0,
    "LASTUPDATE" TIMESTAMP,
    "QTYRESERVED" INTEGER NOT NULL WITH DEFAULT 0,
    "RESTOCKTIME" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ITEMFFMCTR"
ALTER TABLE "DB2ADMIN"."ITEMFFMCTR"
ADD PRIMARY KEY ("ITEMSPC_ID", "STORE_ID", "FFMCENTER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ITEMFFMCTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000597" ON "DB2ADMIN"."ITEMFFMCTR" ("FFMCENTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ITEMFFMCTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000598" ON "DB2ADMIN"."ITEMFFMCTR" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ITEMSPC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ITEMSPC" (
    "ITEMSPC_ID" BIGINT NOT NULL,
    "LASTUPDATE" TIMESTAMP,
    "MEMBER_ID" BIGINT NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "BASEITEM_ID" BIGINT NOT NULL,
    "DISCONTINUED" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N',
    "PARTNUMBER" VARCHAR(64 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ITEMSPC"
ALTER TABLE "DB2ADMIN"."ITEMSPC"
ADD PRIMARY KEY ("ITEMSPC_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ITEMSPC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000138" ON "DB2ADMIN"."ITEMSPC" ("PARTNUMBER" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ITEMSPC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000139" ON "DB2ADMIN"."ITEMSPC" ("BASEITEM_ID" ASC, "ITEMSPC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ITEMSPC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I800140" ON "DB2ADMIN"."ITEMSPC" ("DISCONTINUED" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ITEMSPC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000361" ON "DB2ADMIN"."ITEMSPC" (
    "ITEMSPC_ID" ASC,
    "BASEITEM_ID" ASC,
    "PARTNUMBER" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ITEMSPC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000599" ON "DB2ADMIN"."ITEMSPC" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ITEMTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ITEMTYPE" (
    "ITEMTYPE_ID" CHAR(4 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ITEMTYPE"
ALTER TABLE "DB2ADMIN"."ITEMTYPE"
ADD PRIMARY KEY ("ITEMTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ITEMVERSN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ITEMVERSN" (
    "ITEMVERSN_ID" BIGINT NOT NULL,
    "LASTUPDATE" TIMESTAMP,
    "BASEITEM_ID" BIGINT NOT NULL,
    "EXPIRATIONDATE" TIMESTAMP NOT NULL,
    "VERSIONNAME" CHAR(30 OCTETS) NOT NULL WITH DEFAULT 'Version 1',
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ITEMVERSN"
ALTER TABLE "DB2ADMIN"."ITEMVERSN"
ADD PRIMARY KEY ("ITEMVERSN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ITEMVERSN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000140" ON "DB2ADMIN"."ITEMVERSN" ("BASEITEM_ID" ASC, "EXPIRATIONDATE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ITEMVERSN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000141" ON "DB2ADMIN"."ITEMVERSN" ("BASEITEM_ID" ASC, "VERSIONNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."JURST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."JURST" (
    "JURST_ID" INTEGER NOT NULL,
    "COUNTRY" VARCHAR(128 OCTETS),
    "STOREENT_ID" INTEGER NOT NULL,
    "CODE" CHAR(30 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "SUBCLASS" INTEGER NOT NULL,
    "CITY" VARCHAR(128 OCTETS),
    "STATE" VARCHAR(128 OCTETS),
    "STATEABBR" VARCHAR(10 OCTETS),
    "COUNTRYABBR" VARCHAR(10 OCTETS),
    "DISTRICT" VARCHAR(30 OCTETS),
    "COUNTY" VARCHAR(30 OCTETS),
    "ZIPCODESTART" VARCHAR(40 OCTETS),
    "ZIPCODEEND" VARCHAR(40 OCTETS),
    "GEOCODE" VARCHAR(254 OCTETS),
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."JURST"
ALTER TABLE "DB2ADMIN"."JURST"
ADD PRIMARY KEY ("JURST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."JURST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000142" ON "DB2ADMIN"."JURST" (
    "CODE" ASC,
    "STOREENT_ID" ASC,
    "SUBCLASS" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."JURST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000600" ON "DB2ADMIN"."JURST" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."JURSTGPREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."JURSTGPREL" (
    "JURST_ID" INTEGER NOT NULL,
    "JURSTGROUP_ID" INTEGER NOT NULL,
    "SUBCLASS" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."JURSTGPREL"
ALTER TABLE "DB2ADMIN"."JURSTGPREL"
ADD PRIMARY KEY ("JURST_ID", "JURSTGROUP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."JURSTGPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000601" ON "DB2ADMIN"."JURSTGPREL" ("JURSTGROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."JURSTGROUP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."JURSTGROUP" (
    "JURSTGROUP_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "SUBCLASS" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "CODE" CHAR(30 OCTETS) NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."JURSTGROUP"
ALTER TABLE "DB2ADMIN"."JURSTGROUP"
ADD PRIMARY KEY ("JURSTGROUP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."JURSTGROUP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000143" ON "DB2ADMIN"."JURSTGROUP" (
    "CODE" ASC,
    "STOREENT_ID" ASC,
    "SUBCLASS" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."JURSTGROUP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000602" ON "DB2ADMIN"."JURSTGROUP" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."KEYS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."KEYS" (
    "KEYS_ID" INTEGER NOT NULL,
    "TABLENAME" VARCHAR(30 OCTETS) NOT NULL,
    "COLUMNNAME" VARCHAR(30 OCTETS) NOT NULL,
    "COUNTER" BIGINT NOT NULL,
    "PREFETCHSIZE" BIGINT WITH DEFAULT 20,
    "LOWERBOUND" BIGINT WITH DEFAULT 0,
    "UPPERBOUND" BIGINT WITH DEFAULT 2147483648,
    "OPTCOUNTER" SMALLINT,
    "NONSEQUENTIAL" CHAR(1 OCTETS) NOT NULL WITH DEFAULT '0',
    "MULTIPLIER" BIGINT NOT NULL WITH DEFAULT 1048576
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."KEYS"
ALTER TABLE "DB2ADMIN"."KEYS"
ADD PRIMARY KEY ("KEYS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."KEYS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000144" ON "DB2ADMIN"."KEYS" ("TABLENAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
---