------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."OFFER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."OFFER" (
    "OFFER_ID" BIGINT NOT NULL,
    "STARTDATE" TIMESTAMP,
    "TRADEPOSCN_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "ENDDATE" TIMESTAMP,
    "PRECEDENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "PUBLISHED" INTEGER NOT NULL WITH DEFAULT 0,
    "LASTUPDATE" TIMESTAMP,
    "MINIMUMQUANTITY" DOUBLE,
    "QTYUNIT_ID" CHAR(16 OCTETS),
    "MAXIMUMQUANTITY" DOUBLE,
    "FIELD1" CHAR(30 OCTETS),
    "FIELD2" CHAR(32 OCTETS),
    "FLAGS" INTEGER NOT NULL WITH DEFAULT 1,
    "IDENTIFIER" BIGINT,
    "OID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."OFFER"
ALTER TABLE "DB2ADMIN"."OFFER"
ADD PRIMARY KEY ("OFFER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."OFFER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000165" ON "DB2ADMIN"."OFFER" (
    "CATENTRY_ID" ASC,
    "IDENTIFIER" ASC,
    "TRADEPOSCN_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."OFFER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000167" ON "DB2ADMIN"."OFFER" (
    "CATENTRY_ID" ASC,
    "PUBLISHED" ASC,
    "TRADEPOSCN_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."OFFER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000626" ON "DB2ADMIN"."OFFER" ("TRADEPOSCN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."OFFERDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."OFFERDESC" (
    "OFFER_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."OFFERDESC"
ALTER TABLE "DB2ADMIN"."OFFERDESC"
ADD PRIMARY KEY ("OFFER_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."OFFERPRICE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."OFFERPRICE" (
    "OFFER_ID" BIGINT NOT NULL,
    "CURRENCY" CHAR(3 OCTETS) NOT NULL,
    "PRICE" DECIMAL(20, 5) NOT NULL,
    "COMPAREPRICE" DECIMAL(20, 5),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."OFFERPRICE"
ALTER TABLE "DB2ADMIN"."OFFERPRICE"
ADD PRIMARY KEY ("OFFER_ID", "CURRENCY");
-- DDL Statements for Indexes on Table "DB2ADMIN"."OFFERPRICE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000168" ON "DB2ADMIN"."OFFERPRICE" (
    "PRICE" ASC,
    "CURRENCY" ASC,
    "OFFER_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."OIBTB"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."OIBTB" (
    "OIBRFNBR" INTEGER NOT NULL,
    "OIMENBR" VARCHAR(30 OCTETS),
    "OIBUNBR" VARCHAR(30 OCTETS),
    "OIBUPRNBR" VARCHAR(30 OCTETS),
    "OIPRMANAME" VARCHAR(80 OCTETS),
    "OIMAPRNBR" VARCHAR(30 OCTETS),
    "OIPRCMDGRP" VARCHAR(30 OCTETS),
    "OIPRCMNAME" VARCHAR(30 OCTETS),
    "OIPRCMNBR" VARCHAR(30 OCTETS),
    "OIPRDESC" VARCHAR(80 OCTETS),
    "OISCOND" CHAR(2 OCTETS),
    "OISTATUS" VARCHAR(32 OCTETS),
    "OINOTES1" VARCHAR(600 OCTETS),
    "OINOTES2" VARCHAR(600 OCTETS),
    "OIQSHIP" INTEGER,
    "OIRSDATE" TIMESTAMP,
    "OISSDATE" TIMESTAMP,
    "OIASDATE" TIMESTAMP,
    "OIBUAMDATE" TIMESTAMP,
    "OIFIELD1" VARCHAR(30 OCTETS),
    "OIFIELD2" VARCHAR(30 OCTETS),
    "OIFIELD3" VARCHAR(30 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."OIBTB"
ALTER TABLE "DB2ADMIN"."OIBTB"
ADD PRIMARY KEY ("OIBRFNBR");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."OICOMPLIST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."OICOMPLIST" (
    "ITEMSPC_ID" BIGINT,
    "OICOMPLIST_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT,
    "ORDERITEMS_ID" BIGINT,
    "CATALOGQUANTITY" DOUBLE,
    "INVENTORYQUANTITY" INTEGER,
    "REQUIRED" CHAR(1 OCTETS) WITH DEFAULT 'Y',
    "CONFIGURATIONID" VARCHAR(128 OCTETS),
    "UNITPRICE" DECIMAL(20, 5),
    "CURRENCY" CHAR(3 OCTETS),
    "SUPPLIERDATA" VARCHAR(254 OCTETS),
    "SUPPLIERPARTNUMBER" VARCHAR(254 OCTETS),
    "RFQPROD_ID" BIGINT,
    "OPTCOUNTER" SMALLINT,
    "OICOMPREL_ID" BIGINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."OICOMPLIST"
ALTER TABLE "DB2ADMIN"."OICOMPLIST"
ADD PRIMARY KEY ("OICOMPLIST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."OICOMPLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000301" ON "DB2ADMIN"."OICOMPLIST" ("ORDERITEMS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."OICOMPLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000371" ON "DB2ADMIN"."OICOMPLIST" ("RFQPROD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."OICOMPLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000627" ON "DB2ADMIN"."OICOMPLIST" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."OICOMPLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000628" ON "DB2ADMIN"."OICOMPLIST" ("ITEMSPC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."OICOMPLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001100" ON "DB2ADMIN"."OICOMPLIST" ("ORDERITEMS_ID" ASC, "CONFIGURATIONID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."OICOMPLIST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001263" ON "DB2ADMIN"."OICOMPLIST" ("OICOMPREL_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."OICOMPREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."OICOMPREL" (
    "OICOMPREL_ID" BIGINT NOT NULL,
    "ORDERITEMS_ID" BIGINT,
    "ITEMSPC_ID" BIGINT NOT NULL,
    "PARENT_ID" BIGINT,
    "REQUIRED" SMALLINT WITH DEFAULT 1,
    "OPTCOUNTER" SMALLINT,
    "CONFIGURATION_ID" VARCHAR(128 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."OICOMPREL"
ALTER TABLE "DB2ADMIN"."OICOMPREL"
ADD PRIMARY KEY ("OICOMPREL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."OICOMPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000966" ON "DB2ADMIN"."OICOMPREL" ("ORDERITEMS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."OICOMPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000963" ON "DB2ADMIN"."OICOMPREL" ("ITEMSPC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."OICOMPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000964" ON "DB2ADMIN"."OICOMPREL" ("PARENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."OICOMPREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001101" ON "DB2ADMIN"."OICOMPREL" ("CONFIGURATION_ID" ASC, "ORDERITEMS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ONLOG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ONLOG" (
    "ORRFNBR" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "METHRFNBR" INTEGER NOT NULL,
    "TIME" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ONLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000629" ON "DB2ADMIN"."ONLOG" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ONLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000630" ON "DB2ADMIN"."ONLOG" ("ORRFNBR" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ONQUEUE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ONQUEUE" (
    "STOREENT_ID" INTEGER NOT NULL,
    "ORRFNBR" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ONQUEUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000170" ON "DB2ADMIN"."ONQUEUE" ("ORRFNBR" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ONQUEUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000631" ON "DB2ADMIN"."ONQUEUE" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ONSLOG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ONSLOG" (
    "MERFNBR" INTEGER NOT NULL,
    "TIME" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."OPERATOR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."OPERATOR" (
    "OPERATOR_ID" INTEGER NOT NULL,
    "OPERATOR" CHAR(32 OCTETS) NOT NULL,
    "OPERATORTYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT '1',
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."OPERATOR"
ALTER TABLE "DB2ADMIN"."OPERATOR"
ADD PRIMARY KEY ("OPERATOR_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."OPERATRDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."OPERATRDSC" (
    "OPERATOR_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."OPERATRDSC"
ALTER TABLE "DB2ADMIN"."OPERATRDSC"
ADD PRIMARY KEY ("OPERATOR_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."OPSYSTEM"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."OPSYSTEM" (
    "OPSYSTEM_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."OPSYSTEM"
ALTER TABLE "DB2ADMIN"."OPSYSTEM"
ADD PRIMARY KEY ("OPSYSTEM_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORCOMMENT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORCOMMENT" (
    "ORCOMMENT_ID" BIGINT NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "LASTUPDATE" TIMESTAMP,
    "COMMENTS" VARCHAR(3000 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "ORDCHGRSN_ID" INTEGER,
    "SERVICEREP_ID" BIGINT,
    "BUSCHN_ID" INTEGER,
    "ORDERVERSION" SMALLINT,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" TIMESTAMP
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORCOMMENT"
ALTER TABLE "DB2ADMIN"."ORCOMMENT"
ADD PRIMARY KEY ("ORCOMMENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORCOMMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000632" ON "DB2ADMIN"."ORCOMMENT" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORCOMMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001264" ON "DB2ADMIN"."ORCOMMENT" ("ORDCHGRSN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORCOMMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001265" ON "DB2ADMIN"."ORCOMMENT" ("SERVICEREP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORCPMAP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORCPMAP" (
    "ORDERS_ID" BIGINT NOT NULL,
    "CPWALLET_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORCPMAP"
ALTER TABLE "DB2ADMIN"."ORCPMAP"
ADD PRIMARY KEY ("ORDERS_ID", "CPWALLET_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORCPMAP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000285" ON "DB2ADMIN"."ORCPMAP" ("CPWALLET_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDADJDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDADJDSC" (
    "ORDADJUST_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
ALTER TABLE "DB2ADMIN"."ORDADJDSC" VOLATILE CARDINALITY;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDADJDSC"
ALTER TABLE "DB2ADMIN"."ORDADJDSC"
ADD PRIMARY KEY ("ORDADJUST_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDADJTXEX"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDADJTXEX" (
    "ORDADJUST_ID" BIGINT NOT NULL,
    "TAXCGRY_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDADJTXEX"
ALTER TABLE "DB2ADMIN"."ORDADJTXEX"
ADD PRIMARY KEY ("ORDADJUST_ID", "TAXCGRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDADJTXEX"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000633" ON "DB2ADMIN"."ORDADJTXEX" ("TAXCGRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDADJUST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDADJUST" (
    "ORDADJUST_ID" BIGINT NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "CALCODE_ID" INTEGER,
    "CALUSAGE_ID" INTEGER,
    "AMOUNT" DECIMAL(20, 5) WITH DEFAULT 0,
    "DISPLAYLEVEL" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDADJUST"
ALTER TABLE "DB2ADMIN"."ORDADJUST"
ADD PRIMARY KEY ("ORDADJUST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDADJUST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000171" ON "DB2ADMIN"."ORDADJUST" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDADJUST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000634" ON "DB2ADMIN"."ORDADJUST" ("CALUSAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDADJUST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000635" ON "DB2ADMIN"."ORDADJUST" ("CALCODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDBTB"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDBTB" (
    "ORBRFNBR" INTEGER NOT NULL,
    "ORBUNBR" VARCHAR(30 OCTETS),
    "ORBUREQNBR" VARCHAR(30 OCTETS),
    "ORBVERNBR" INTEGER,
    "ORBTYPE" CHAR(2 OCTETS),
    "ORBRLNBR" VARCHAR(30 OCTETS),
    "ORBNOTES1" VARCHAR(600 OCTETS),
    "ORBNOTES2" VARCHAR(600 OCTETS),
    "ORBSCOND" CHAR(2 OCTETS),
    "ORBRSDATE" TIMESTAMP,
    "ORBSSDATE" TIMESTAMP,
    "ORBASDATE" TIMESTAMP,
    "ORBUPDATE" TIMESTAMP,
    "ORBUAMDATE" TIMESTAMP,
    "ORBFLAG" CHAR(2 OCTETS) NOT NULL,
    "ORBFIELD1" VARCHAR(30 OCTETS),
    "ORBFIELD2" VARCHAR(30 OCTETS),
    "ORBFIELD3" VARCHAR(30 OCTETS),
    "ORDERS_ID" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDBTB"
ALTER TABLE "DB2ADMIN"."ORDBTB"
ADD PRIMARY KEY ("ORBRFNBR");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDBTB"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000636" ON "DB2ADMIN"."ORDBTB" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDCALCD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDCALCD" (
    "ORDCALCD_ID" BIGINT NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "CALCODE_ID" INTEGER NOT NULL,
    "CALFLAGS" INTEGER NOT NULL WITH DEFAULT 0,
    "CALPARMTYPE" INTEGER NOT NULL WITH DEFAULT 0,
    "CALPARMAMT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDCALCD"
ALTER TABLE "DB2ADMIN"."ORDCALCD"
ADD PRIMARY KEY ("ORDCALCD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDCALCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000637" ON "DB2ADMIN"."ORDCALCD" ("CALCODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDCALCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000638" ON "DB2ADMIN"."ORDCALCD" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDCHGRSN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDCHGRSN" (
    "ORDCHGRSN_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "REASONCODE" VARCHAR(64 OCTETS) NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" BIGINT,
    "FIELD3" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDCHGRSN"
ALTER TABLE "DB2ADMIN"."ORDCHGRSN"
ADD PRIMARY KEY ("ORDCHGRSN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDCHGRSN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001266" ON "DB2ADMIN"."ORDCHGRSN" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDCHGRSNDS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDCHGRSNDS" (
    "ORDCHGRSN_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(1024 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDCHGRSNDS"
ALTER TABLE "DB2ADMIN"."ORDCHGRSNDS"
ADD PRIMARY KEY ("ORDCHGRSN_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDCHNLTYP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDCHNLTYP" (
    "ORDCHNLTYP_ID" BIGINT NOT NULL,
    "PAYMENTTRANSTYPE" CHAR(4 OCTETS),
    "LASTUPDATE" TIMESTAMP,
    "NAME" VARCHAR(200 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDCHNLTYP"
ALTER TABLE "DB2ADMIN"."ORDCHNLTYP"
ADD PRIMARY KEY ("ORDCHNLTYP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDCHNLTYP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000172" ON "DB2ADMIN"."ORDCHNLTYP" ("NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDERBLK"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDERBLK" (
    "ORDERBLK_ID" BIGINT NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "BLKRSNCODE_ID" INTEGER NOT NULL,
    "TIMEBLOCKED" TIMESTAMP NOT NULL,
    "RESOLVED" SMALLINT NOT NULL WITH DEFAULT 0,
    "BLKCOMMENT" VARCHAR(254 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDERBLK"
ALTER TABLE "DB2ADMIN"."ORDERBLK"
ADD PRIMARY KEY ("ORDERBLK_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERBLK"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000956" ON "DB2ADMIN"."ORDERBLK" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERBLK"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000957" ON "DB2ADMIN"."ORDERBLK" ("BLKRSNCODE_ID" ASC, "RESOLVED" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDERHIST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDERHIST" (
    "ORDERS_ID" BIGINT NOT NULL,
    "ORDERVERSION" SMALLINT NOT NULL,
    "LASTUPDATE" TIMESTAMP,
    "ORDXML" CLOB(10000000 OCTETS) LOGGED NOT COMPACT,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDERHIST"
ALTER TABLE "DB2ADMIN"."ORDERHIST"
ADD PRIMARY KEY ("ORDERS_ID", "ORDERVERSION");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDERITEMGIFT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDERITEMGIFT" (
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "EXTERNAL_ID" VARCHAR(64 OCTETS) NOT NULL,
    "GIFTMESSAGE" VARCHAR(4000 OCTETS),
    "SHIPTORGSTRNT" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDERITEMGIFT"
ALTER TABLE "DB2ADMIN"."ORDERITEMGIFT"
ADD PRIMARY KEY ("ORDERITEMS_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDERITEMS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDERITEMS" (
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "TERMCOND_ID" BIGINT,
    "TRADING_ID" BIGINT,
    "ITEMSPC_ID" BIGINT,
    "CATENTRY_ID" BIGINT,
    "PARTNUM" VARCHAR(64 OCTETS),
    "SHIPMODE_ID" INTEGER,
    "FFMCENTER_ID" INTEGER,
    "MEMBER_ID" BIGINT NOT NULL,
    "ADDRESS_ID" BIGINT,
    "ALLOCADDRESS_ID" BIGINT,
    "PRICE" DECIMAL(20, 5),
    "LINEITEMTYPE" CHAR(4 OCTETS),
    "STATUS" CHAR(1 OCTETS) NOT NULL,
    "OUTPUTQ_ID" BIGINT,
    "INVENTORYSTATUS" CHAR(4 OCTETS) NOT NULL WITH DEFAULT 'NALC',
    "LASTCREATE" TIMESTAMP,
    "LASTUPDATE" TIMESTAMP,
    "FULFILLMENTSTATUS" CHAR(4 OCTETS) NOT NULL WITH DEFAULT 'INT',
    "LASTALLOCUPDATE" TIMESTAMP,
    "OFFER_ID" BIGINT,
    "TIMERELEASED" TIMESTAMP,
    "TIMESHIPPED" TIMESTAMP,
    "CURRENCY" CHAR(10 OCTETS),
    "COMMENTS" VARCHAR(254 OCTETS),
    "TOTALPRODUCT" DECIMAL(20, 5) WITH DEFAULT 0,
    "QUANTITY" DOUBLE NOT NULL,
    "TAXAMOUNT" DECIMAL(20, 5),
    "TOTALADJUSTMENT" DECIMAL(20, 5) WITH DEFAULT 0,
    "SHIPTAXAMOUNT" DECIMAL(20, 5),
    "ESTAVAILTIME" TIMESTAMP,
    "FIELD1" INTEGER,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "ALLOCATIONGROUP" BIGINT,
    "SHIPCHARGE" DECIMAL(20, 5),
    "BASEPRICE" DECIMAL(20, 5),
    "BASECURRENCY" CHAR(3 OCTETS),
    "TRACKNUMBER" VARCHAR(64 OCTETS),
    "TRACKDATE" TIMESTAMP,
    "PREPAREFLAGS" INTEGER NOT NULL WITH DEFAULT 0,
    "CORRELATIONGROUP" BIGINT,
    "PROMISEDAVAILTIME" TIMESTAMP,
    "SHIPPINGOFFSET" INTEGER NOT NULL WITH DEFAULT 0,
    "NEEDEDQUANTITY" INTEGER NOT NULL WITH DEFAULT 0,
    "ALLOCQUANTITY" INTEGER NOT NULL WITH DEFAULT 0,
    "ALLOCFFMC_ID" INTEGER,
    "ORDRELEASENUM" INTEGER,
    "CONFIGURATIONID" VARCHAR(128 OCTETS),
    "SUPPLIERDATA" VARCHAR(254 OCTETS),
    "SUPPLIERPARTNUMBER" VARCHAR(254 OCTETS),
    "AVAILQUANTITY" INTEGER,
    "ISEXPEDITED" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N',
    "OPTCOUNTER" SMALLINT,
    "REQUESTEDSHIPDATE" TIMESTAMP,
    "TIECODE" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDERITEMS"
ALTER TABLE "DB2ADMIN"."ORDERITEMS"
ADD PRIMARY KEY ("ORDERITEMS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000173" ON "DB2ADMIN"."ORDERITEMS" (
    "ORDERITEMS_ID" ASC,
    "TIMERELEASED" ASC,
    "TIMESHIPPED" ASC,
    "INVENTORYSTATUS" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000642" ON "DB2ADMIN"."ORDERITEMS" ("SHIPMODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000643" ON "DB2ADMIN"."ORDERITEMS" ("FFMCENTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000644" ON "DB2ADMIN"."ORDERITEMS" ("OFFER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000645" ON "DB2ADMIN"."ORDERITEMS" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000646" ON "DB2ADMIN"."ORDERITEMS" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000647" ON "DB2ADMIN"."ORDERITEMS" ("ADDRESS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000648" ON "DB2ADMIN"."ORDERITEMS" ("ITEMSPC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000649" ON "DB2ADMIN"."ORDERITEMS" ("ALLOCFFMC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I172138" ON "DB2ADMIN"."ORDERITEMS" (
    "ORDERS_ID" ASC,
    "ORDRELEASENUM" ASC,
    "STOREENT_ID" ASC,
    "FFMCENTER_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000360" ON "DB2ADMIN"."ORDERITEMS" (
    "ORDERITEMS_ID" ASC,
    "ORDRELEASENUM" ASC,
    "ORDERS_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000369" ON "DB2ADMIN"."ORDERITEMS" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000639" ON "DB2ADMIN"."ORDERITEMS" ("ALLOCADDRESS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000640" ON "DB2ADMIN"."ORDERITEMS" ("TRADING_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERITEMS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000641" ON "DB2ADMIN"."ORDERITEMS" ("TERMCOND_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDERMGP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDERMGP" (
    "ORDERS_ID" BIGINT NOT NULL,
    "MBRGRP_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDERMGP"
ALTER TABLE "DB2ADMIN"."ORDERMGP"
ADD PRIMARY KEY ("ORDERS_ID", "MBRGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERMGP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000650" ON "DB2ADMIN"."ORDERMGP" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDERMSG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDERMSG" (
    "OMREFNUM" INTEGER NOT NULL,
    "OMORNBR" BIGINT NOT NULL,
    "OMRECNAME" CHAR(10 OCTETS),
    "OMRECSEQ" INTEGER,
    "OMRECVALUE" VARCHAR(3000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000174" ON "DB2ADMIN"."ORDERMSG" (
    "OMRECNAME" ASC,
    "OMORNBR" ASC,
    "OMRECSEQ" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000175" ON "DB2ADMIN"."ORDERMSG" ("OMREFNUM" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERMSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000651" ON "DB2ADMIN"."ORDERMSG" ("OMORNBR" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDERS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDERS" (
    "ORDERS_ID" BIGINT NOT NULL,
    "ORMORDER" CHAR(30 OCTETS),
    "ORGENTITY_ID" BIGINT,
    "TOTALPRODUCT" DECIMAL(20, 5) WITH DEFAULT 0,
    "TOTALTAX" DECIMAL(20, 5) WITH DEFAULT 0,
    "TOTALSHIPPING" DECIMAL(20, 5) WITH DEFAULT 0,
    "TOTALTAXSHIPPING" DECIMAL(20, 5) WITH DEFAULT 0,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "STOREENT_ID" INTEGER NOT NULL,
    "CURRENCY" CHAR(10 OCTETS),
    "LOCKED" CHAR(1 OCTETS),
    "TIMEPLACED" TIMESTAMP,
    "LASTUPDATE" TIMESTAMP,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "STATUS" VARCHAR(3 OCTETS),
    "MEMBER_ID" BIGINT NOT NULL,
    "FIELD1" INTEGER,
    "ADDRESS_ID" BIGINT,
    "FIELD2" DECIMAL(20, 5),
    "PROVIDERORDERNUM" INTEGER,
    "SHIPASCOMPLETE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'Y',
    "FIELD3" VARCHAR(254 OCTETS),
    "TOTALADJUSTMENT" DECIMAL(20, 5) WITH DEFAULT 0,
    "ORDCHNLTYP_ID" BIGINT,
    "COMMENTS" VARCHAR(254 OCTETS),
    "NOTIFICATIONID" BIGINT,
    "TYPE" CHAR(3 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "EDITOR_ID" BIGINT,
    "BUSCHN_ID" INTEGER,
    "SOURCEID" BIGINT,
    "EXPIREDATE" TIMESTAMP,
    "BLOCKED" SMALLINT WITH DEFAULT 0,
    "OPSYSTEM_ID" INTEGER,
    "TRANSFERSTATUS" SMALLINT,
    "BUYERPO_ID" BIGINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDERS"
ALTER TABLE "DB2ADMIN"."ORDERS"
ADD PRIMARY KEY ("ORDERS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000176" ON "DB2ADMIN"."ORDERS" (
    "MEMBER_ID" ASC,
    "STATUS" ASC,
    "STOREENT_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I173124" ON "DB2ADMIN"."ORDERS" ("TIMEPLACED" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000652" ON "DB2ADMIN"."ORDERS" ("ADDRESS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000653" ON "DB2ADMIN"."ORDERS" ("ORGENTITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000654" ON "DB2ADMIN"."ORDERS" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000892" ON "DB2ADMIN"."ORDERS" ("EDITOR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000933" ON "DB2ADMIN"."ORDERS" ("SOURCEID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001267" ON "DB2ADMIN"."ORDERS" ("BUYERPO_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001508" ON "DB2ADMIN"."ORDERS" ("STATUS" ASC, "LASTUPDATE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDERTMPL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDERTMPL" (
    "ORDERS_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "USAGE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDERTMPL"
ALTER TABLE "DB2ADMIN"."ORDERTMPL"
ADD PRIMARY KEY ("MEMBER_ID", "ORDERS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDERTMPL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000655" ON "DB2ADMIN"."ORDERTMPL" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDIADJUST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDIADJUST" (
    "ORDIADJUST_ID" BIGINT NOT NULL,
    "ORDADJUST_ID" BIGINT NOT NULL,
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "AMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDIADJUST"
ALTER TABLE "DB2ADMIN"."ORDIADJUST"
ADD PRIMARY KEY ("ORDIADJUST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDIADJUST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000177" ON "DB2ADMIN"."ORDIADJUST" ("ORDADJUST_ID" ASC, "ORDERITEMS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDIADJUST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000178" ON "DB2ADMIN"."ORDIADJUST" ("ORDERITEMS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDICALCD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDICALCD" (
    "CALCODE_ID" INTEGER NOT NULL,
    "ORDICALCD_ID" BIGINT NOT NULL,
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "CALFLAGS" INTEGER NOT NULL WITH DEFAULT 0,
    "CALPARMTYPE" INTEGER NOT NULL WITH DEFAULT 0,
    "CALPARMAMT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDICALCD"
ALTER TABLE "DB2ADMIN"."ORDICALCD"
ADD PRIMARY KEY ("ORDICALCD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDICALCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000656" ON "DB2ADMIN"."ORDICALCD" ("ORDERITEMS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDICALCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000657" ON "DB2ADMIN"."ORDICALCD" ("CALCODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDIMEEXTN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDIMEEXTN" (
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "REQUESTEDSHIPTIME" TIMESTAMP,
    "SHIPASCOMPLETE" CHAR(1 OCTETS),
    "COMMENTS1" VARCHAR(1024 OCTETS),
    "COMMENTS2" VARCHAR(1024 OCTETS),
    "FIELD1" VARCHAR(64 OCTETS),
    "FIELD2" VARCHAR(64 OCTETS),
    "FIELD3" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDIMEEXTN"
ALTER TABLE "DB2ADMIN"."ORDIMEEXTN"
ADD PRIMARY KEY ("ORDERITEMS_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDIOFFER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDIOFFER" (
    "OFFER_ID" BIGINT NOT NULL,
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDIOFFER"
ALTER TABLE "DB2ADMIN"."ORDIOFFER"
ADD PRIMARY KEY ("ORDERITEMS_ID", "OFFER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDIOFFER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000658" ON "DB2ADMIN"."ORDIOFFER" ("OFFER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDIPROF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDIPROF" (
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "PROFILENAME" VARCHAR(64 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDIPROF"
ALTER TABLE "DB2ADMIN"."ORDIPROF"
ADD PRIMARY KEY ("ORDERITEMS_ID", "PROFILENAME");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDISTAT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDISTAT" (
    "ORDISTAT_ID" BIGINT NOT NULL,
    "ORDERS_ID" BIGINT,
    "OSMORDER" CHAR(30 OCTETS),
    "ORDERITMES_ID" BIGINT,
    "OIMITEM" CHAR(30 OCTETS),
    "PARTNUMBER" CHAR(64 OCTETS),
    "OIUOFM" CHAR(20 OCTETS),
    "OIQTREQUEST" INTEGER,
    "OIQTCONFIRM" INTEGER,
    "OIQTSHIP" INTEGER,
    "OICPCUR" CHAR(10 OCTETS),
    "OIUNPRC" DECIMAL(20, 5),
    "OIPRTOT" DECIMAL(20, 5),
    "OITXTOT" DECIMAL(20, 5),
    "OISHTOT" DECIMAL(20, 5),
    "OISHTXTOT" DECIMAL(20, 5),
    "OISTATUS" CHAR(32 OCTETS),
    "OIPLTIME" TIMESTAMP,
    "OIRSTIME" TIMESTAMP,
    "OISSTIME" TIMESTAMP,
    "OIASTIME" TIMESTAMP,
    "OIINVTIME" TIMESTAMP,
    "OIINVVAL" DECIMAL(20, 5),
    "OIVERNBR" INTEGER,
    "OISCOND" CHAR(2 OCTETS),
    "OICMNT" VARCHAR(254 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" DECIMAL(20, 5),
    "FIELD3" VARCHAR(254 OCTETS),
    "SUPPLIERDATA" VARCHAR(254 OCTETS),
    "ORDSTAT_ID" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDISTAT"
ALTER TABLE "DB2ADMIN"."ORDISTAT"
ADD PRIMARY KEY ("ORDISTAT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDISTAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000659" ON "DB2ADMIN"."ORDISTAT" ("ORDSTAT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDISTAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000660" ON "DB2ADMIN"."ORDISTAT" ("ORDERITMES_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDISTAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000661" ON "DB2ADMIN"."ORDISTAT" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDITAX"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDITAX" (
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "TAXCGRY_ID" INTEGER NOT NULL,
    "TAXAMOUNT" DECIMAL(20, 5) NOT NULL,
    "TAXCGRY_DSC" VARCHAR(255 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDITAX"
ALTER TABLE "DB2ADMIN"."ORDITAX"
ADD PRIMARY KEY ("ORDERITEMS_ID", "TAXCGRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDITAX"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000662" ON "DB2ADMIN"."ORDITAX" ("TAXCGRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDITEMCONF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDITEMCONF" (
    "ORDITEMCONF_ID" BIGINT NOT NULL,
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "OICOMPLIST_ID" BIGINT,
    "SERIALNUMBER" VARCHAR(128 OCTETS),
    "MANIFEST_ID" BIGINT,
    "ORDRELEASENUM" INTEGER NOT NULL,
    "QUANTITY" DOUBLE NOT NULL,
    "CONFIRMTYPE" SMALLINT NOT NULL,
    "CREATION_TIMESTAMP" TIMESTAMP NOT NULL,
    "LASTUPDATE" TIMESTAMP NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDITEMCONF"
ALTER TABLE "DB2ADMIN"."ORDITEMCONF"
ADD PRIMARY KEY ("ORDITEMCONF_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDITEMCONF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000974" ON "DB2ADMIN"."ORDITEMCONF" ("ORDERITEMS_ID" ASC, "OICOMPLIST_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDITEMCONF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000975" ON "DB2ADMIN"."ORDITEMCONF" ("SERIALNUMBER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDITEMCONF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001268" ON "DB2ADMIN"."ORDITEMCONF" ("OICOMPLIST_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDITEMCONF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001269" ON "DB2ADMIN"."ORDITEMCONF" ("MANIFEST_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDITPROMOCD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDITPROMOCD" (
    "ID" BIGINT NOT NULL,
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "CODE" VARCHAR(128 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDITPROMOCD"
ALTER TABLE "DB2ADMIN"."ORDITPROMOCD"
ADD PRIMARY KEY ("ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDITPROMOCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000419" ON "DB2ADMIN"."ORDITPROMOCD" ("ORDERITEMS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDITRD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDITRD" (
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "TRADING_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDITRD"
ALTER TABLE "DB2ADMIN"."ORDITRD"
ADD PRIMARY KEY ("ORDERITEMS_ID", "TRADING_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDITRD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000663" ON "DB2ADMIN"."ORDITRD" ("TRADING_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDMEEXTN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDMEEXTN" (
    "ORDERS_ID" BIGINT NOT NULL,
    "PAYLOADID" VARCHAR(128 OCTETS),
    "BUYERORDERID" CHAR(32 OCTETS),
    "ORDERTYPE" CHAR(2 OCTETS),
    "REQUESTEDTIME" TIMESTAMP,
    "REQUESTEDSHIPTIME" TIMESTAMP,
    "COMMENTS1" VARCHAR(1024 OCTETS),
    "COMMENTS2" VARCHAR(1024 OCTETS),
    "FIELD1" VARCHAR(64 OCTETS),
    "FIELD2" VARCHAR(64 OCTETS),
    "FIELD3" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDMEEXTN"
ALTER TABLE "DB2ADMIN"."ORDMEEXTN"
ADD PRIMARY KEY ("ORDERS_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDOPTIONS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDOPTIONS" (
    "ORDERS_ID" BIGINT NOT NULL,
    "NOTIFYMERCHANT" INTEGER,
    "NOTIFYSHOPPER" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDOPTIONS"
ALTER TABLE "DB2ADMIN"."ORDOPTIONS"
ADD PRIMARY KEY ("ORDERS_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDPAYINFO"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDPAYINFO" (
    "ORDERS_ID" BIGINT NOT NULL,
    "ORDPAYINFO_ID" BIGINT NOT NULL,
    "NAME" CHAR(64 OCTETS) NOT NULL,
    "VALUE" VARCHAR(512 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDPAYINFO"
ALTER TABLE "DB2ADMIN"."ORDPAYINFO"
ADD PRIMARY KEY ("ORDPAYINFO_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDPAYINFO"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000179" ON "DB2ADMIN"."ORDPAYINFO" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
---