------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDPAYMTHD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDPAYMTHD" (
    "PAYMETHOD" CHAR(5 OCTETS) NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "PAYDEVICE" CHAR(64 OCTETS) FOR BIT DATA NOT NULL,
    "STARTDATE" TIMESTAMP,
    "REFUNDNUMBER" BIGINT NOT NULL WITH DEFAULT 0,
    "TRADING_ID" BIGINT,
    "ACCOUNT_ID" BIGINT,
    "RMA_ID" BIGINT,
    "POLICY_ID" BIGINT,
    "PAYSUMMARY_ID" BIGINT,
    "ENDDATE" TIMESTAMP,
    "BUYERPO_ID" BIGINT,
    "MAXAMOUNT" DECIMAL(20, 5),
    "CREDITLINE_ID" BIGINT,
    "ACTUALAMOUNT" DECIMAL(20, 5),
    "CHARGEAMOUNT" DECIMAL(20, 5),
    "CHARGETIME" TIMESTAMP,
    "CHARGEAMTCURR" CHAR(3 OCTETS),
    "XMLDATA" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "STRINGFIELD1" VARCHAR(254 OCTETS),
    "STRINGFIELD2" VARCHAR(254 OCTETS),
    "STRINGFIELD3" VARCHAR(254 OCTETS),
    "STRINGFIELD4" VARCHAR(254 OCTETS),
    "STATUS" INTEGER WITH DEFAULT 0,
    "BIGINTFIELD1" BIGINT,
    "BIGINTFIELD2" BIGINT,
    "BIGINTFIELD3" BIGINT,
    "DECIMALFIELD1" DECIMAL(20, 5),
    "DECIMALFIELD2" DECIMAL(20, 5),
    "DECIMALFIELD3" DECIMAL(20, 5),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDPAYMTHD"
ALTER TABLE "DB2ADMIN"."ORDPAYMTHD"
ADD PRIMARY KEY (
        "ORDERS_ID",
        "PAYMETHOD",
        "PAYDEVICE",
        "REFUNDNUMBER"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDPAYMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000664" ON "DB2ADMIN"."ORDPAYMTHD" ("CREDITLINE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDPAYMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000665" ON "DB2ADMIN"."ORDPAYMTHD" ("TRADING_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDPAYMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000666" ON "DB2ADMIN"."ORDPAYMTHD" ("BUYERPO_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDPAYMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000667" ON "DB2ADMIN"."ORDPAYMTHD" ("PAYSUMMARY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDPAYMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000668" ON "DB2ADMIN"."ORDPAYMTHD" ("POLICY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDPAYMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000669" ON "DB2ADMIN"."ORDPAYMTHD" ("RMA_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDPAYMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000670" ON "DB2ADMIN"."ORDPAYMTHD" ("ACCOUNT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDPICKHST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDPICKHST" (
    "ORDPICKHSTNUM" INTEGER NOT NULL,
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "VERSIONSPC_ID" BIGINT NOT NULL,
    "RECEIPT_ID" BIGINT,
    "QTYPICKED" INTEGER,
    "DATEPICKED" TIMESTAMP,
    "ORDERPICKINGTYPE" INTEGER,
    "LASTUPDATE" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDPICKHST"
ALTER TABLE "DB2ADMIN"."ORDPICKHST"
ADD PRIMARY KEY ("ORDERITEMS_ID", "ORDPICKHSTNUM");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDPICKHST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000362" ON "DB2ADMIN"."ORDPICKHST" (
    "ORDERITEMS_ID" ASC,
    "VERSIONSPC_ID" ASC,
    "QTYPICKED" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDPICKHST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000671" ON "DB2ADMIN"."ORDPICKHST" ("RECEIPT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDPICKHST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000672" ON "DB2ADMIN"."ORDPICKHST" ("VERSIONSPC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDPROMOCD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDPROMOCD" (
    "ID" BIGINT NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "CODE" VARCHAR(128 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDPROMOCD"
ALTER TABLE "DB2ADMIN"."ORDPROMOCD"
ADD PRIMARY KEY ("ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDPROMOCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000418" ON "DB2ADMIN"."ORDPROMOCD" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDQUOTREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDQUOTREL" (
    "PARENT_ID" BIGINT NOT NULL,
    "CHILD_ID" BIGINT,
    "ORDQUOTREL_ID" BIGINT NOT NULL,
    "CHILDSTORE_ID" INTEGER,
    "TRADING_ID" BIGINT,
    "RELTYPE" CHAR(16 OCTETS) NOT NULL,
    "TIMEOUTTIME" TIMESTAMP,
    "DISPLAYSEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "FLAGS" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDQUOTREL"
ALTER TABLE "DB2ADMIN"."ORDQUOTREL"
ADD PRIMARY KEY ("ORDQUOTREL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDQUOTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000278" ON "DB2ADMIN"."ORDQUOTREL" ("CHILD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDQUOTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000308" ON "DB2ADMIN"."ORDQUOTREL" (
    "PARENT_ID" ASC,
    "RELTYPE" ASC,
    "CHILDSTORE_ID" ASC,
    "CHILD_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDQUOTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000309" ON "DB2ADMIN"."ORDQUOTREL" (
    "CHILDSTORE_ID" ASC,
    "CHILD_ID" ASC,
    "RELTYPE" ASC,
    "PARENT_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDQUOTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000673" ON "DB2ADMIN"."ORDQUOTREL" ("TRADING_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDRELEASE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDRELEASE" (
    "ORDRELEASENUM" INTEGER NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "FFMACKNOWLEDGEMENT" TIMESTAMP,
    "STATUS" CHAR(4 OCTETS),
    "CUSTOMERCONFIRM" TIMESTAMP,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS),
    "PICKBATCH_ID" BIGINT,
    "TIMEPLACED" TIMESTAMP,
    "LASTUPDATE" TIMESTAMP,
    "PACKSLIPXML" CLOB(1000000000 OCTETS) LOGGED NOT COMPACT,
    "CAPTUREDATE" TIMESTAMP,
    "EXTORDNUM" VARCHAR(64 OCTETS),
    "EXTREF" VARCHAR(2048 OCTETS),
    "FFMCENTER_ID" INTEGER,
    "ISEXPEDITED" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N',
    "SHIPMODE_ID" INTEGER,
    "ADDRESS_ID" BIGINT,
    "MEMBER_ID" BIGINT,
    "STOREENT_ID" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDRELEASE"
ALTER TABLE "DB2ADMIN"."ORDRELEASE"
ADD PRIMARY KEY ("ORDERS_ID", "ORDRELEASENUM");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDRELEASE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000180" ON "DB2ADMIN"."ORDRELEASE" (
    "STATUS" ASC,
    "ORDERS_ID" ASC,
    "ORDRELEASENUM" ASC,
    "PICKBATCH_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDRELEASE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I803140" ON "DB2ADMIN"."ORDRELEASE" ("PICKBATCH_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDRELEASE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000836" ON "DB2ADMIN"."ORDRELEASE" ("FFMCENTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDRELEASE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000837" ON "DB2ADMIN"."ORDRELEASE" ("SHIPMODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDRELEASE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000838" ON "DB2ADMIN"."ORDRELEASE" ("ADDRESS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDRELEASE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000839" ON "DB2ADMIN"."ORDRELEASE" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDRELEASE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000840" ON "DB2ADMIN"."ORDRELEASE" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDRLSTTLS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDRLSTTLS" (
    "ORDERS_ID" BIGINT NOT NULL,
    "ORDRELEASENUM" INTEGER NOT NULL,
    "CHARGETYPE" CHAR(70 OCTETS) NOT NULL,
    "AMOUNT" DECIMAL(20, 5),
    "LASTCREATED" TIMESTAMP,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(250 OCTETS),
    "FIELD3" VARCHAR(250 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDRLSTTLS"
ALTER TABLE "DB2ADMIN"."ORDRLSTTLS"
ADD PRIMARY KEY (
        "ORDERS_ID",
        "ORDRELEASENUM",
        "CHARGETYPE"
    );
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDSHIPHST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDSHIPHST" (
    "ORDSHIPHSTNUM" INTEGER NOT NULL,
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "VERSIONSPC_ID" BIGINT NOT NULL,
    "RECEIPT_ID" BIGINT,
    "QTYSHIPPED" INTEGER,
    "DATESHIPPED" TIMESTAMP,
    "LASTUPDATE" TIMESTAMP,
    "QTYRETURNED" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDSHIPHST"
ALTER TABLE "DB2ADMIN"."ORDSHIPHST"
ADD PRIMARY KEY ("ORDERITEMS_ID", "ORDSHIPHSTNUM");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDSHIPHST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000674" ON "DB2ADMIN"."ORDSHIPHST" ("RECEIPT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDSHIPHST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000675" ON "DB2ADMIN"."ORDSHIPHST" ("VERSIONSPC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDSTAT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDSTAT" (
    "ORDSTAT_ID" BIGINT NOT NULL,
    "ORDERS_ID" BIGINT,
    "OSMORDER" CHAR(30 OCTETS),
    "OSCPCUR" CHAR(10 OCTETS),
    "OSPRTOT" DECIMAL(20, 5),
    "OSTXTOT" DECIMAL(20, 5),
    "OSSHTOT" DECIMAL(20, 5),
    "OSSHTXTOT" DECIMAL(20, 5),
    "OSSTATUS" CHAR(32 OCTETS),
    "OSPLTIME" TIMESTAMP,
    "OSRSTIME" TIMESTAMP,
    "OSSSTIME" TIMESTAMP,
    "OSASTIME" TIMESTAMP,
    "OSINVTIME" TIMESTAMP,
    "OSINVVAL" DECIMAL(20, 5),
    "OSSCOND" CHAR(2 OCTETS),
    "OSSMFLAG" CHAR(1 OCTETS),
    "OSVERNBR" INTEGER,
    "OSUPDTIME" TIMESTAMP,
    "OSSEQNUM" VARCHAR(64 OCTETS),
    "OSCMNT" VARCHAR(254 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" DECIMAL(20, 5),
    "FIELD3" VARCHAR(254 OCTETS),
    "OSCODE" CHAR(20 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDSTAT"
ALTER TABLE "DB2ADMIN"."ORDSTAT"
ADD PRIMARY KEY ("ORDSTAT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDSTAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000368" ON "DB2ADMIN"."ORDSTAT" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDTAX"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDTAX" (
    "ORDERS_ID" BIGINT NOT NULL,
    "TAXCGRY_ID" INTEGER NOT NULL,
    "TAXAMOUNT" DECIMAL(20, 5) NOT NULL,
    "LASTUPDATE" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDTAX"
ALTER TABLE "DB2ADMIN"."ORDTAX"
ADD PRIMARY KEY ("ORDERS_ID", "TAXCGRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDTAX"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000676" ON "DB2ADMIN"."ORDTAX" ("TAXCGRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDUSERS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDUSERS" (
    "ORDERS_ID" BIGINT NOT NULL,
    "CREATOR_ID" BIGINT,
    "SUBMITTER_ID" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDUSERS"
ALTER TABLE "DB2ADMIN"."ORDUSERS"
ADD PRIMARY KEY ("ORDERS_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORGCODE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORGCODE" (
    "ORGCODE_ID" BIGINT NOT NULL,
    "ORGENTITY_ID" BIGINT NOT NULL,
    "CODETYPE" VARCHAR(32 OCTETS) NOT NULL,
    "CODE" VARCHAR(128 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORGCODE"
ALTER TABLE "DB2ADMIN"."ORGCODE"
ADD PRIMARY KEY ("ORGCODE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORGCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000181" ON "DB2ADMIN"."ORGCODE" ("CODETYPE" ASC, "CODE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORGCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000182" ON "DB2ADMIN"."ORGCODE" ("ORGENTITY_ID" ASC, "CODETYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORGENTITY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORGENTITY" (
    "ORGENTITY_ID" BIGINT NOT NULL,
    "LEGALID" VARCHAR(128 OCTETS),
    "ORGENTITYTYPE" CHAR(3 OCTETS) NOT NULL,
    "ORGENTITYNAME" VARCHAR(128 OCTETS) NOT NULL,
    "BUSINESSCATEGORY" VARCHAR(128 OCTETS),
    "DESCRIPTION" VARCHAR(512 OCTETS),
    "ADMINFIRSTNAME" VARCHAR(128 OCTETS),
    "ADMINLASTNAME" VARCHAR(128 OCTETS),
    "ADMINMIDDLENAME" VARCHAR(128 OCTETS),
    "PREFERREDDELIVERY" VARCHAR(1000 OCTETS),
    "FIELD1" VARCHAR(64 OCTETS),
    "FIELD2" VARCHAR(64 OCTETS),
    "TAXPAYERID" VARCHAR(254 OCTETS),
    "DN" VARCHAR(1000 OCTETS),
    "FIELD3" VARCHAR(64 OCTETS),
    "STATUS" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORGENTITY"
ALTER TABLE "DB2ADMIN"."ORGENTITY"
ADD PRIMARY KEY ("ORGENTITY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORGENTITY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000970" ON "DB2ADMIN"."ORGENTITY" ("DN" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."OUTPUTQ"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."OUTPUTQ" (
    "OUTPUTQ_ID" BIGINT NOT NULL,
    "OUTPUTQTYPE" CHAR(4 OCTETS),
    "LASTUPDATE" TIMESTAMP,
    "NAME" VARCHAR(60 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."OUTPUTQ"
ALTER TABLE "DB2ADMIN"."OUTPUTQ"
ADD PRIMARY KEY ("OUTPUTQ_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."OUTPUTQ"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000183" ON "DB2ADMIN"."OUTPUTQ" ("NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."OUTPUTQDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."OUTPUTQDSC" (
    "OUTPUTQ_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "LASTUPDATE" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."OUTPUTQDSC"
ALTER TABLE "DB2ADMIN"."OUTPUTQDSC"
ADD PRIMARY KEY ("OUTPUTQ_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PAREQINFO"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PAREQINFO" (
    "XID" CHAR(28 OCTETS) NOT NULL,
    "CREATED" TIMESTAMP,
    "MESSAGEID" CHAR(30 OCTETS),
    "ACQUIRERBIN" CHAR(11 OCTETS),
    "MERCHANTID" CHAR(24 OCTETS),
    "PURCHDATETIME" CHAR(17 OCTETS),
    "PURCHAMOUNT" CHAR(12 OCTETS),
    "PURCHCURR" CHAR(3 OCTETS),
    "CURREXP" CHAR(2 OCTETS),
    "PAN" VARCHAR(100 OCTETS),
    "KEYINFO" VARCHAR(3500 OCTETS),
    "EXT1" CHAR(254 OCTETS),
    "EXT2" CHAR(1 OCTETS),
    "EXT3" CHAR(1 OCTETS),
    "EXT4" CHAR(1 OCTETS),
    "EXT5" CHAR(1 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PAREQINFO"
ALTER TABLE "DB2ADMIN"."PAREQINFO"
ADD PRIMARY KEY ("XID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PARTICIPNT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PARTICIPNT" (
    "PARTICIPNT_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT,
    "PARTROLE_ID" INTEGER NOT NULL,
    "TRADING_ID" BIGINT,
    "TERMCOND_ID" BIGINT,
    "INFORMATION" VARCHAR(4000 OCTETS),
    "TIMECREATED" TIMESTAMP,
    "TIMEUPDATED" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PARTICIPNT"
ALTER TABLE "DB2ADMIN"."PARTICIPNT"
ADD PRIMARY KEY ("PARTICIPNT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PARTICIPNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000184" ON "DB2ADMIN"."PARTICIPNT" (
    "MEMBER_ID" ASC,
    "PARTROLE_ID" ASC,
    "TRADING_ID" ASC,
    "TERMCOND_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PARTICIPNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000678" ON "DB2ADMIN"."PARTICIPNT" ("PARTROLE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PARTICIPNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000679" ON "DB2ADMIN"."PARTICIPNT" ("TRADING_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PARTICIPNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000680" ON "DB2ADMIN"."PARTICIPNT" ("TERMCOND_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PARTROLE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PARTROLE" (
    "PARTROLE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PARTROLE"
ALTER TABLE "DB2ADMIN"."PARTROLE"
ADD PRIMARY KEY ("PARTROLE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PARTROLEDS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PARTROLEDS" (
    "PARTROLE_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(4000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PARTROLEDS"
ALTER TABLE "DB2ADMIN"."PARTROLEDS"
ADD PRIMARY KEY ("PARTROLE_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PASTATS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PASTATS" (
    "STOREENT_ID" INTEGER NOT NULL,
    "CATGROUP_ID" BIGINT NOT NULL,
    "METAPHORTYPE" INTEGER NOT NULL,
    "COUNT" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PASTATS"
ALTER TABLE "DB2ADMIN"."PASTATS"
ADD PRIMARY KEY (
        "STOREENT_ID",
        "CATGROUP_ID",
        "METAPHORTYPE"
    );
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PATTRDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PATTRDESC" (
    "PATTRIBUTE_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(1024 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PATTRDESC"
ALTER TABLE "DB2ADMIN"."PATTRDESC"
ADD PRIMARY KEY ("PATTRIBUTE_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PATTRIBUTE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PATTRIBUTE" (
    "PATTRIBUTE_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "ATTRTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "ACCESSBEANNAME" VARCHAR(254 OCTETS),
    "SEQUENCE" INTEGER,
    "ENCRYPTFLAG" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PATTRIBUTE"
ALTER TABLE "DB2ADMIN"."PATTRIBUTE"
ADD PRIMARY KEY ("PATTRIBUTE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PATTRIBUTE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000185" ON "DB2ADMIN"."PATTRIBUTE" ("NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PATTRPROD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PATTRPROD" (
    "PATTRIBUTE_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PATTRPROD"
ALTER TABLE "DB2ADMIN"."PATTRPROD"
ADD PRIMARY KEY ("PATTRIBUTE_ID", "CATENTRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PATTRPROD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000681" ON "DB2ADMIN"."PATTRPROD" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PATTRVALUE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PATTRVALUE" (
    "PATTRVALUE_ID" BIGINT NOT NULL,
    "PATTRIBUTE_ID" BIGINT NOT NULL,
    "ATTRTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "OPERATOR_ID" INTEGER NOT NULL,
    "TERMCOND_ID" BIGINT,
    "QTYUNIT_ID" CHAR(16 OCTETS),
    "INTEGERVALUE" INTEGER,
    "FLOATVALUE" DOUBLE,
    "STRINGVALUE" VARCHAR(254 OCTETS),
    "DATEVALUE" TIMESTAMP,
    "BIGINTVALUE" BIGINT,
    "SEQUENCE" INTEGER,
    "ENCRYPTFLAG" INTEGER NOT NULL WITH DEFAULT 0,
    "ORDERITEMS_ID" BIGINT,
    "MANDATORY" INTEGER NOT NULL WITH DEFAULT 0,
    "ATTACHMENT_ID" BIGINT,
    "CHANGEABLE" INTEGER NOT NULL WITH DEFAULT 0,
    "RFQPROD_ID" BIGINT,
    "RFQRSPPROD_ID" BIGINT,
    "CORRELATIONGROUP" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PATTRVALUE"
ALTER TABLE "DB2ADMIN"."PATTRVALUE"
ADD PRIMARY KEY ("PATTRVALUE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000354" ON "DB2ADMIN"."PATTRVALUE" ("TERMCOND_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000355" ON "DB2ADMIN"."PATTRVALUE" ("RFQPROD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000356" ON "DB2ADMIN"."PATTRVALUE" ("RFQRSPPROD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000367" ON "DB2ADMIN"."PATTRVALUE" ("CORRELATIONGROUP" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000682" ON "DB2ADMIN"."PATTRVALUE" ("PATTRIBUTE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000683" ON "DB2ADMIN"."PATTRVALUE" ("ORDERITEMS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PATTRVALUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001270" ON "DB2ADMIN"."PATTRVALUE" ("ATTACHMENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PAYMTHD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PAYMTHD" (
    "PAYMTHD_ID" INTEGER NOT NULL,
    "PROFILENAME" VARCHAR(64 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PAYMTHD"
ALTER TABLE "DB2ADMIN"."PAYMTHD"
ADD PRIMARY KEY ("PAYMTHD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PAYMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000186" ON "DB2ADMIN"."PAYMTHD" ("PROFILENAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PAYMTHDDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PAYMTHDDSC" (
    "PAYMTHD_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PAYMTHDDSC"
ALTER TABLE "DB2ADMIN"."PAYMTHDDSC"
ADD PRIMARY KEY ("LANGUAGE_ID", "PAYMTHD_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PAYMTHDSUP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PAYMTHDSUP" (
    "PAYMTHD_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PAYMTHDSUP"
ALTER TABLE "DB2ADMIN"."PAYMTHDSUP"
ADD PRIMARY KEY ("PAYMTHD_ID", "STOREENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PAYMTHDSUP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000684" ON "DB2ADMIN"."PAYMTHDSUP" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PAYSTATUS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PAYSTATUS" (
    "SETSORNBR" BIGINT NOT NULL,
    "STORE_ID" INTEGER NOT NULL,
    "SETSBRANDID" CHAR(40 OCTETS),
    "SETSPREQSTMP" TIMESTAMP,
    "SETSTIMESTMP" TIMESTAMP,
    "SETSSTATCODE" INTEGER,
    "SETSNEXTSTAT" INTEGER,
    "SETSTIMEEXP" INTEGER,
    "SETSFAILTYPE" INTEGER,
    "SETSFAILCODE" INTEGER,
    "SETSCURR" INTEGER,
    "SETSCURREXP" INTEGER,
    "SETSACTAMT" DOUBLE,
    "SETSRESPREASON" INTEGER,
    "SETSAUTHCODE" INTEGER,
    "SETSAUTHCHARIND" INTEGER,
    "SETSAPPROVALCODE" CHAR(6 OCTETS),
    "SETSAUTHRETNUM" INTEGER,
    "SETSLOGREFID" VARCHAR(32 OCTETS),
    "SETSPAN" VARCHAR(19 OCTETS),
    "SETSCARDEXPIRY" CHAR(6 OCTETS),
    "SETSAUTHREVCODE" INTEGER,
    "SETSCAPCODE" INTEGER,
    "SETSCAPREVCODE" INTEGER,
    "SETSCREDCODE" INTEGER,
    "SETSCREDREVCODE" INTEGER,
    "SETSAVSRESULT" INTEGER,
    "SETSAUTHAMT" INTEGER,
    "SETSCAPAMT" INTEGER,
    "SETSSETTLEAMT" INTEGER,
    "SETSCREDAMT" INTEGER,
    "SETSWAKEUPMSG" VARCHAR(4000 OCTETS),
    "SETSFAILCODE2" INTEGER,
    "PENDING" INTEGER,
    "PROFILENAME" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PAYSTATUS"
ALTER TABLE "DB2ADMIN"."PAYSTATUS"
ADD PRIMARY KEY ("SETSORNBR", "STORE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PAYSTATUS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000685" ON "DB2ADMIN"."PAYSTATUS" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PAYSUMMARY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PAYSUMMARY" (
    "PAYSUMMARY_ID" BIGINT NOT NULL,
    "ACCOUNT_ID" BIGINT,
    "SETCCURR" CHAR(3 OCTETS),
    "CREDITLINE_ID" BIGINT,
    "STOREENT_ID" INTEGER NOT NULL,
    "POLICY_ID" BIGINT,
    "PERIODSTARTTIME" TIMESTAMP NOT NULL,
    "PERIODENDTIME" TIMESTAMP NOT NULL,
    "TOTALCHARGE" DECIMAL(20, 5) NOT NULL,
    "PAYSUMMARYXML" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "STATUS" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PAYSUMMARY"
ALTER TABLE "DB2ADMIN"."PAYSUMMARY"
ADD PRIMARY KEY ("PAYSUMMARY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PAYSUMMARY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000686" ON "DB2ADMIN"."PAYSUMMARY" ("ACCOUNT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PAYSUMMARY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000687" ON "DB2ADMIN"."PAYSUMMARY" ("POLICY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PAYSUMMARY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000689" ON "DB2ADMIN"."PAYSUMMARY" ("CREDITLINE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PAYSUMMARY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000690" ON "DB2ADMIN"."PAYSUMMARY" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PAYSYNCH"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PAYSYNCH" (
    "PAYSRFNBR" INTEGER NOT NULL,
    "PAYSSTMP1" TIMESTAMP,
    "PAYSSTMP2" TIMESTAMP,
    "PAYSSTMP3" TIMESTAMP NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PAYSYNCH"
ALTER TABLE "DB2ADMIN"."PAYSYNCH"
ADD PRIMARY KEY ("PAYSRFNBR");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PCSTATS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PCSTATS" (
    "STOREENT_ID" INTEGER NOT NULL,
    "CATGROUP_ID" BIGINT NOT NULL,
    "VIEWS" INTEGER,
    "CLICKS" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PCSTATS"
ALTER TABLE "DB2ADMIN"."PCSTATS"
ADD PRIMARY KEY ("STOREENT_ID", "CATGROUP_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PESTATS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PESTATS" (
    "STOREENT_ID" INTEGER NOT NULL,
    "CATGROUP_ID" BIGINT NOT NULL,
    "FEATURE_ID" INTEGER NOT NULL,
    "FEATURENAME" VARCHAR(64 OCTETS),
    "COUNT" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PESTATS"
ALTER TABLE "DB2ADMIN"."PESTATS"
ADD PRIMARY KEY (
        "STOREENT_ID",
        "CATGROUP_ID",
        "FEATURE_ID"
    );
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PICKBATCH"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PICKBATCH" (
    "PICKBATCH_ID" BIGINT NOT NULL,
    "LASTUPDATE" TIMESTAMP,
    "FFMCENTER_ID" INTEGER NOT NULL,
    "MEMBER_ID" BIGINT,
    "PICKSLIPXML" CLOB(1000000000 OCTETS) LOGGED NOT COMPACT,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS),
    "DATE1" TIMESTAMP,
    "DATE2" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PICKBATCH"
ALTER TABLE "DB2ADMIN"."PICKBATCH"
ADD PRIMARY KEY ("PICKBATCH_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PICKBATCH"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000691" ON "DB2ADMIN"."PICKBATCH" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PICKBATCH"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000692" ON "DB2ADMIN"."PICKBATCH" ("FFMCENTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PKGATTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PKGATTR" (
    "PKGATTR_ID" BIGINT NOT NULL,
    "ATTRIBUTE_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CATENTRY_ID" BIGINT,
    "OID" CHAR(32 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PKGATTR"
ALTER TABLE "DB2ADMIN"."PKGATTR"
ADD PRIMARY KEY ("PKGATTR_ID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PKGATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000187" ON "DB2ADMIN"."PKGATTR" (
    "CATENTRY_ID" ASC,
    "LANGUAGE_ID" ASC,
    "ATTRIBUTE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PKGATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001271" ON "DB2ADMIN"."PKGATTR" ("ATTRIBUTE_ID" ASC, "LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PKGATTRVAL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PKGATTRVAL" (
    "PKGATTRVAL_ID" BIGINT NOT NULL,
    "ATTRVALUE_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "OID" CHAR(32 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PKGATTRVAL"
ALTER TABLE "DB2ADMIN"."PKGATTRVAL"
ADD PRIMARY KEY ("PKGATTRVAL_ID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PKGATTRVAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000188" ON "DB2ADMIN"."PKGATTRVAL" (
    "CATENTRY_ID" ASC,
    "LANGUAGE_ID" ASC,
    "ATTRVALUE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PKGATTRVAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001272" ON "DB2ADMIN"."PKGATTRVAL" ("ATTRVALUE_ID" ASC, "LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PKGITEMREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PKGITEMREL" (
    "CATENTRY_ID_PARENT" BIGINT NOT NULL,
    "CATENTRY_ID_PKG" BIGINT NOT NULL,
    "CATENTRY_ID_ITEM" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PKGITEMREL"
ALTER TABLE "DB2ADMIN"."PKGITEMREL"
ADD PRIMARY KEY (
        "CATENTRY_ID_ITEM",
        "CATENTRY_ID_PKG",
        "CATENTRY_ID_PARENT"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."PKGITEMREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000693" ON "DB2ADMIN"."PKGITEMREL" ("CATENTRY_ID_PARENT" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PKGITEMREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000694" ON "DB2ADMIN"."PKGITEMREL" ("CATENTRY_ID_PKG" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLCYACCDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLCYACCDSC" (
    "PLCYACCT_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLCYACCDSC"
ALTER TABLE "DB2ADMIN"."PLCYACCDSC"
ADD PRIMARY KEY ("PLCYACCT_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLCYACCLCK"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLCYACCLCK" (
    "PLCYACCLCK_ID" BIGINT NOT NULL,
    "LOCKOUTTHRESHOLD" INTEGER WITH DEFAULT 6,
    "WAITTIME" INTEGER WITH DEFAULT 10,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLCYACCLCK"
ALTER TABLE "DB2ADMIN"."PLCYACCLCK"
ADD PRIMARY KEY ("PLCYACCLCK_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLCYACCT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLCYACCT" (
    "PLCYACCT_ID" INTEGER NOT NULL,
    "PLCYACCLCK_ID" BIGINT NOT NULL,
    "PLCYPASSWD_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLCYACCT"
ALTER TABLE "DB2ADMIN"."PLCYACCT"
ADD PRIMARY KEY ("PLCYACCT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLCYACCT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000695" ON "DB2ADMIN"."PLCYACCT" ("PLCYACCLCK_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLCYACCT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000696" ON "DB2ADMIN"."PLCYACCT" ("PLCYPASSWD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLCYLCKDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLCYLCKDSC" (
    "PLCYACCLCK_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLCYLCKDSC"
ALTER TABLE "DB2ADMIN"."PLCYLCKDSC"
ADD PRIMARY KEY ("PLCYACCLCK_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLCYPASSWD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLCYPASSWD" (
    "PLCYPASSWD_ID" BIGINT NOT NULL,
    "MINPASSWDLENGTH" INTEGER WITH DEFAULT 8,
    "MINALPHABETIC" INTEGER WITH DEFAULT 1,
    "MINNUMERIC" INTEGER WITH DEFAULT 1,
    "MAXINSTANCES" INTEGER WITH DEFAULT 3,
    "MAXCONSECUTIVETYPE" INTEGER WITH DEFAULT 4,
    "MAXLIFETIME" INTEGER WITH DEFAULT 90,
    "MATCHUSERID" INTEGER WITH DEFAULT 0,
    "REUSEPASSWORD" INTEGER WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLCYPASSWD"
ALTER TABLE "DB2ADMIN"."PLCYPASSWD"
ADD PRIMARY KEY ("PLCYPASSWD_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLCYPWDDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLCYPWDDSC" (
    "PLCYPASSWD_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLCYPWDDSC"
ALTER TABLE "DB2ADMIN"."PLCYPWDDSC"
ADD PRIMARY KEY ("PLCYPASSWD_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLCYTYCMIF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLCYTYCMIF" (
    "POLICYTYPE_ID" CHAR(64 OCTETS) NOT NULL,
    "BUSINESSCMDIF" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLCYTYCMIF"
ALTER TABLE "DB2ADMIN"."PLCYTYCMIF"
ADD PRIMARY KEY ("BUSINESSCMDIF");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLCYTYPDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLCYTYPDSC" (
    "POLICYTYPE_ID" CHAR(64 OCTETS) NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLCYTYPDSC"
ALTER TABLE "DB2ADMIN"."PLCYTYPDSC"
ADD PRIMARY KEY ("POLICYTYPE_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."POLICY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."POLICY" (
    "POLICY_ID" BIGINT NOT NULL,
    "POLICYNAME" VARCHAR(128 OCTETS) NOT NULL,
    "POLICYTYPE_ID" CHAR(64 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "PROPERTIES" VARCHAR(254 OCTETS),
    "STARTTIME" TIMESTAMP,
    "ENDTIME" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."POLICY"
ALTER TABLE "DB2ADMIN"."POLICY"
ADD PRIMARY KEY ("POLICY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."POLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000189" ON "DB2ADMIN"."POLICY" (
    "POLICYNAME" ASC,
    "POLICYTYPE_ID" ASC,
    "STOREENT_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."POLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000337" ON "DB2ADMIN"."POLICY" ("POLICYTYPE_ID" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."POLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000697" ON "DB2ADMIN"."POLICY" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."POLICYCMD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."POLICYCMD" (
    "POLICY_ID" BIGINT NOT NULL,
    "BUSINESSCMDCLASS" VARCHAR(200 OCTETS) NOT NULL,
    "PROPERTIES" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."POLICYCMD"
ALTER TABLE "DB2ADMIN"."POLICYCMD"
ADD PRIMARY KEY ("POLICY_ID", "BUSINESSCMDCLASS");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."POLICYDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."POLICYDESC" (
    "POLICY_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(508 OCTETS) NOT NULL,
    "LONGDESCRIPTION" VARCHAR(4000 OCTETS),
    "TIMECREATED" TIMESTAMP,
    "TIMEUPDATED" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."POLICYDESC"
ALTER TABLE "DB2ADMIN"."POLICYDESC"
ADD PRIMARY KEY ("POLICY_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."POLICYTC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."POLICYTC" (
    "TERMCOND_ID" BIGINT NOT NULL,
    "POLICY_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."POLICYTC"
ALTER TABLE "DB2ADMIN"."POLICYTC"
ADD PRIMARY KEY ("POLICY_ID", "TERMCOND_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."POLICYTC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000357" ON "DB2ADMIN"."POLICYTC" ("TERMCOND_ID" ASC, "POLICY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."POLICYTC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001273" ON "DB2ADMIN"."POLICYTC" ("POLICY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."POLICYTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."POLICYTYPE" (
    "POLICYTYPE_ID" CHAR(64 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."POLICYTYPE"
ALTER TABLE "DB2ADMIN"."POLICYTYPE"
ADD PRIMARY KEY ("POLICYTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PPCBATCH"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PPCBATCH" (
    "PPCBATCH_ID" BIGINT NOT NULL,
    "MERCHCONF_ID" BIGINT NOT NULL,
    "STATE" SMALLINT NOT NULL WITH DEFAULT 0,
    "TIMECREATED" TIMESTAMP NOT NULL,
    "TIMEUPDATED" TIMESTAMP NOT NULL,
    "TIMECLOSED" TIMESTAMP,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PPCBATCH"
ALTER TABLE "DB2ADMIN"."PPCBATCH"
ADD PRIMARY KEY ("PPCBATCH_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCBATCH"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001107" ON "DB2ADMIN"."PPCBATCH" ("MERCHCONF_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCBATCH"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001108" ON "DB2ADMIN"."PPCBATCH" ("STATE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PPCCREDIT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PPCCREDIT" (
    "PPCCREDIT_ID" BIGINT NOT NULL,
    "PPCPAYINST_ID" BIGINT NOT NULL,
    "PPCPAYMENT_ID" BIGINT,
    "EXPECTEDAMOUNT" DECIMAL(20, 5) NOT NULL,
    "CREDITINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "CREDITEDAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "RVRSNGCRDTEDAMNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "STATE" SMALLINT NOT NULL,
    "TIMECREATED" TIMESTAMP NOT NULL,
    "TIMEUPDATED" TIMESTAMP NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PPCCREDIT"
ALTER TABLE "DB2ADMIN"."PPCCREDIT"
ADD PRIMARY KEY ("PPCCREDIT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCCREDIT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000922" ON "DB2ADMIN"."PPCCREDIT" ("PPCPAYINST_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCCREDIT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000923" ON "DB2ADMIN"."PPCCREDIT" ("PPCPAYMENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PPCEXTDATA"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PPCEXTDATA" (
    "PPCEXTDATA_ID" BIGINT NOT NULL,
    "PPCPAYINST_ID" BIGINT,
    "PPCPAYTRAN_ID" BIGINT,
    "ATTRIBUTETYPE" SMALLINT NOT NULL,
    "ENCRYPTED" SMALLINT NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "ATTRIBUTENAME" VARCHAR(64 OCTETS) NOT NULL,
    "SEARCHVALUE" VARCHAR(64 OCTETS),
    "DATAVALUE" VARCHAR(4000 OCTETS),
    "PPCBATCH_ID" BIGINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PPCEXTDATA"
ALTER TABLE "DB2ADMIN"."PPCEXTDATA"
ADD PRIMARY KEY ("PPCEXTDATA_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCEXTDATA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000926" ON "DB2ADMIN"."PPCEXTDATA" ("PPCPAYINST_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCEXTDATA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000927" ON "DB2ADMIN"."PPCEXTDATA" ("PPCPAYTRAN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCEXTDATA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000962" ON "DB2ADMIN"."PPCEXTDATA" ("SEARCHVALUE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCEXTDATA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001106" ON "DB2ADMIN"."PPCEXTDATA" ("PPCBATCH_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PPCPAYINST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PPCPAYINST" (
    "PPCPAYINST_ID" BIGINT NOT NULL,
    "ORDER_ID" BIGINT,
    "RMA_ID" BIGINT,
    "STORE_ID" INTEGER NOT NULL,
    "AMOUNT" DECIMAL(20, 5) NOT NULL,
    "APPROVINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "APPROVEDAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "CREDITINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "CREDITEDAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "DEPOSITINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "DEPOSITEDAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "RVRSNGAPRVEDAMNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "RVRSNGDPSTEDAMNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "RVRSNGCRDTEDAMNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "TIMECREATED" TIMESTAMP NOT NULL,
    "TIMEUPDATED" TIMESTAMP NOT NULL,
    "CURRENCY" CHAR(3 OCTETS) NOT NULL,
    "STATE" SMALLINT NOT NULL WITH DEFAULT 0,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "PLUGINNAME" VARCHAR(64 OCTETS) NOT NULL,
    "PAYMENTSYSTEMNAME" VARCHAR(64 OCTETS) NOT NULL,
    "ACCOUNTNUMBER" VARCHAR(512 OCTETS),
    "PAYCONFIGID" VARCHAR(64 OCTETS) NOT NULL
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PPCPAYINST"
ALTER TABLE "DB2ADMIN"."PPCPAYINST"
ADD PRIMARY KEY ("PPCPAYINST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCPAYINST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000918" ON "DB2ADMIN"."PPCPAYINST" ("ORDER_ID" ASC, "MARKFORDELETE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCPAYINST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000919" ON "DB2ADMIN"."PPCPAYINST" ("RMA_ID" ASC, "MARKFORDELETE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PPCPAYMENT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PPCPAYMENT" (
    "PPCPAYMENT_ID" BIGINT NOT NULL,
    "PPCPAYINST_ID" BIGINT NOT NULL,
    "PPCPAYTRAN_ID" BIGINT,
    "AVSCOMMONCODE" SMALLINT NOT NULL WITH DEFAULT 0,
    "EXPECTEDAMOUNT" DECIMAL(20, 5) NOT NULL,
    "APPROVINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "APPROVEDAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "DEPOSITINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "DEPOSITEDAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "CREDITINGAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "CREDITEDAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "RVRSNGAPRVEDAMNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "RVRSNGDPSTEDAMNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "RVRSNGCRDTEDAMNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "STATE" SMALLINT NOT NULL,
    "TIMEEXPIRED" TIMESTAMP,
    "TIMECREATED" TIMESTAMP NOT NULL,
    "TIMEUPDATED" TIMESTAMP NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PPCPAYMENT"
ALTER TABLE "DB2ADMIN"."PPCPAYMENT"
ADD PRIMARY KEY ("PPCPAYMENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCPAYMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000920" ON "DB2ADMIN"."PPCPAYMENT" ("PPCPAYINST_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PPCPAYTRAN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PPCPAYTRAN" (
    "PPCPAYTRAN_ID" BIGINT NOT NULL,
    "PPCPAYMENT_ID" BIGINT,
    "PPCCREDIT_ID" BIGINT,
    "TRANSACTIONTYPE" SMALLINT NOT NULL,
    "REQUESTEDAMOUNT" DECIMAL(20, 5) NOT NULL,
    "PROCESSEDAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0.00000,
    "STATE" SMALLINT NOT NULL,
    "TIMECREATED" TIMESTAMP NOT NULL,
    "TIMEUPDATED" TIMESTAMP NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "RESPONSECODE" VARCHAR(25 OCTETS),
    "REASONCODE" VARCHAR(25 OCTETS),
    "REFERENCENUMBER" VARCHAR(64 OCTETS),
    "TRACKINGID" VARCHAR(64 OCTETS),
    "PPCBATCH_ID" BIGINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PPCPAYTRAN"
ALTER TABLE "DB2ADMIN"."PPCPAYTRAN"
ADD PRIMARY KEY ("PPCPAYTRAN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCPAYTRAN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000924" ON "DB2ADMIN"."PPCPAYTRAN" ("PPCPAYMENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCPAYTRAN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000925" ON "DB2ADMIN"."PPCPAYTRAN" ("PPCCREDIT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PPCPAYTRAN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001103" ON "DB2ADMIN"."PPCPAYTRAN" ("PPCBATCH_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PRCORSN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PRCORSN" (
    "PRCORSN_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "CODE" VARCHAR(50 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PRCORSN"
ALTER TABLE "DB2ADMIN"."PRCORSN"
ADD PRIMARY KEY ("PRCORSN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PRCORSN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000968" ON "DB2ADMIN"."PRCORSN" ("STOREENT_ID" ASC, "CODE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PRCORSNDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PRCORSNDSC" (
    "PRCORSN_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PRCORSNDSC"
ALTER TABLE "DB2ADMIN"."PRCORSNDSC"
ADD PRIMARY KEY ("PRCORSN_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PROCBUYPRF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PROCBUYPRF" (
    "PROCPROTCL_ID" INTEGER NOT NULL,
    "ORGENTITY_ID" BIGINT NOT NULL,
    "REQIDPARM" VARCHAR(32 OCTETS) NOT NULL,
    "ORGUNITPARM" VARCHAR(32 OCTETS) NOT NULL,
    "CONTRACTPARM" VARCHAR(32 OCTETS),
    "FIELD1" VARCHAR(32 OCTETS),
    "FIELD2" VARCHAR(32 OCTETS),
    "FIELD3" VARCHAR(32 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PROCBUYPRF"
ALTER TABLE "DB2ADMIN"."PROCBUYPRF"
ADD PRIMARY KEY ("PROCPROTCL_ID", "ORGENTITY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PROCBUYPRF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000698" ON "DB2ADMIN"."PROCBUYPRF" ("ORGENTITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PROCMSGVW"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PROCMSGVW" (
    "ORGENTITY_ID" BIGINT NOT NULL,
    "MSGNAME" VARCHAR(200 OCTETS) NOT NULL,
    "VIEWNAME" VARCHAR(254 OCTETS) NOT NULL,
    "PROCPROTCL_ID" INTEGER NOT NULL,
    "ERRORVIEW" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PROCMSGVW"
ALTER TABLE "DB2ADMIN"."PROCMSGVW"
ADD PRIMARY KEY (
        "PROCPROTCL_ID",
        "ORGENTITY_ID",
        "MSGNAME"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."PROCMSGVW"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000699" ON "DB2ADMIN"."PROCMSGVW" ("ORGENTITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PROCPROTCL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PROCPROTCL" (
    "PROCPROTCL_ID" INTEGER NOT NULL,
    "PROCSYSNAME" CHAR(16 OCTETS),
    "PROTOCOLNAME" VARCHAR(32 OCTETS) NOT NULL,
    "VERSION" VARCHAR(32 OCTETS),
    "AUTHTYPE" INTEGER NOT NULL,
    "TWOSTEPMODE" CHAR(1 OCTETS) NOT NULL,
    "PROCPROTCLCOMMENT" VARCHAR(254 OCTETS),
    "CLASSIFDOMAIN" CHAR(32 OCTETS),
    "UOMSTANDARD" VARCHAR(32 OCTETS),
    "FIELD1" VARCHAR(64 OCTETS),
    "FIELD2" VARCHAR(64 OCTETS),
    "FIELD3" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PROCPROTCL"
ALTER TABLE "DB2ADMIN"."PROCPROTCL"
ADD PRIMARY KEY ("PROCPROTCL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PROCPROTCL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000190" ON "DB2ADMIN"."PROCPROTCL" ("PROTOCOLNAME" ASC, "VERSION" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PROCSYS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PROCSYS" (
    "PROCSYSNAME" CHAR(16 OCTETS) NOT NULL,
    "FIELD1" VARCHAR(64 OCTETS),
    "FIELD2" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PROCSYS"
ALTER TABLE "DB2ADMIN"."PROCSYS"
ADD PRIMARY KEY ("PROCSYSNAME");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PRODSETDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PRODSETDSC" (
    "PRODUCTSET_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PRODSETDSC"
ALTER TABLE "DB2ADMIN"."PRODSETDSC"
ADD PRIMARY KEY ("PRODUCTSET_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PRODUCTSET"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PRODUCTSET" (
    "NAME" VARCHAR(32 OCTETS),
    "PRODUCTSET_ID" INTEGER NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "XMLDEFINITION" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "PUBLISHTIME" TIMESTAMP,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "STATIC" CHAR(1 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PRODUCTSET"
ALTER TABLE "DB2ADMIN"."PRODUCTSET"
ADD PRIMARY KEY ("PRODUCTSET_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PRODUCTSET"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000191" ON "DB2ADMIN"."PRODUCTSET" ("NAME" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PRODUCTSET"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000700" ON "DB2ADMIN"."PRODUCTSET" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PROFILE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PROFILE" (
    "PROFILE_ID" INTEGER NOT NULL,
    "STORE_ID" INTEGER NOT NULL,
    "DEVICEFMT_ID" INTEGER NOT NULL,
    "TRANSPORT_ID" INTEGER NOT NULL,
    "MSGTYPE_ID" INTEGER NOT NULL,
    "USERSVIEW" CHAR(1 OCTETS) NOT NULL,
    "LOWPRIORITY" INTEGER NOT NULL WITH DEFAULT 0,
    "HIGHPRIORITY" INTEGER NOT NULL WITH DEFAULT 0,
    "ARCHIVEMSG" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PROFILE"
ALTER TABLE "DB2ADMIN"."PROFILE"
ADD PRIMARY KEY ("PROFILE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PROFILE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000192" ON "DB2ADMIN"."PROFILE" (
    "STORE_ID" ASC,
    "TRANSPORT_ID" ASC,
    "MSGTYPE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PROFILE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000701" ON "DB2ADMIN"."PROFILE" ("MSGTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PROFNVSTRG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PROFNVSTRG" (
    "PROFNVSTRG_ID" INTEGER NOT NULL,
    "PROFILE_ID" INTEGER NOT NULL,
    "PROFILEATTNAME" VARCHAR(254 OCTETS) NOT NULL,
    "PROFILEATTVALUE" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PROFNVSTRG"
ALTER TABLE "DB2ADMIN"."PROFNVSTRG"
ADD PRIMARY KEY ("PROFNVSTRG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PROFNVSTRG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000193" ON "DB2ADMIN"."PROFNVSTRG" ("PROFILE_ID" ASC, "PROFILEATTNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PRSETCEREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PRSETCEREL" (
    "PRODUCTSET_ID" INTEGER NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PRSETCEREL"
ALTER TABLE "DB2ADMIN"."PRSETCEREL"
ADD PRIMARY KEY ("PRODUCTSET_ID", "CATENTRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PRSETCEREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000702" ON "DB2ADMIN"."PRSETCEREL" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PSETADJMNT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PSETADJMNT" (
    "TERMCOND_ID" BIGINT NOT NULL,
    "PRODUCTSET_ID" INTEGER NOT NULL,
    "TYPE" INTEGER NOT NULL,
    "ADJUSTMENT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "PRECEDENCE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PSETADJMNT"
ALTER TABLE "DB2ADMIN"."PSETADJMNT"
ADD PRIMARY KEY ("TERMCOND_ID", "PRODUCTSET_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PSETADJMNT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000703" ON "DB2ADMIN"."PSETADJMNT" ("PRODUCTSET_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PURCHASELT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PURCHASELT" (
    "PURCHASELT_ID" BIGINT NOT NULL,
    "TERMCOND_ID" BIGINT NOT NULL,
    "TRADEPOSCN_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "LIMITTYPE" CHAR(1 OCTETS) NOT NULL,
    "CURRENCY" CHAR(3 OCTETS),
    "MINAMOUNT" DECIMAL(20, 5),
    "MAXAMOUNT" DECIMAL(20, 5),
    "CURRENTAMOUNT" DECIMAL(20, 5),
    "MINQUANTITY" DOUBLE,
    "MAXQUANTITY" DOUBLE,
    "CURRENTQUANTITY" DOUBLE,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PURCHASELT"
ALTER TABLE "DB2ADMIN"."PURCHASELT"
ADD PRIMARY KEY ("PURCHASELT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PURCHASELT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000194" ON "DB2ADMIN"."PURCHASELT" (
    "TERMCOND_ID" ASC,
    "TRADEPOSCN_ID" ASC,
    "CATENTRY_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PURCHASELT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000704" ON "DB2ADMIN"."PURCHASELT" ("TRADEPOSCN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PURCHASELT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000705" ON "DB2ADMIN"."PURCHASELT" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PVCBINDING"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PVCBINDING" (
    "PVCSESSION_ID" BIGINT NOT NULL,
    "PVCBINDING_ID" BIGINT NOT NULL,
    "USERS_ID" BIGINT NOT NULL,
    "STATUS" CHAR(1 OCTETS) NOT NULL,
    "CREATED" TIMESTAMP NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PVCBINDING"
ALTER TABLE "DB2ADMIN"."PVCBINDING"
ADD PRIMARY KEY ("PVCBINDING_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PVCBINDING"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I758147" ON "DB2ADMIN"."PVCBINDING" (
    "PVCSESSION_ID" ASC,
    "USERS_ID" ASC,
    "CREATED" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PVCBINDING"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000706" ON "DB2ADMIN"."PVCBINDING" ("USERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PVCBUFFER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PVCBUFFER" (
    "USERS_ID" BIGINT NOT NULL,
    "URL" VARCHAR(254 OCTETS) NOT NULL,
    "PARAMETERS" VARCHAR(1024 OCTETS),
    "CREATED" TIMESTAMP,
    "PARAMETERS2K" VARCHAR(2048 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PVCBUFFER"
ALTER TABLE "DB2ADMIN"."PVCBUFFER"
ADD PRIMARY KEY ("USERS_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PVCDEVMDL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PVCDEVMDL" (
    "MODEL_ID" INTEGER NOT NULL,
    "MODELNAME" VARCHAR(40 OCTETS),
    "SESSIONTYPE" VARCHAR(32 OCTETS) NOT NULL,
    "VENDOR" VARCHAR(80 OCTETS),
    "DESCRIPTION" VARCHAR(128 OCTETS),
    "DEVMDLNAME" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PVCDEVMDL"
ALTER TABLE "DB2ADMIN"."PVCDEVMDL"
ADD PRIMARY KEY ("MODEL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PVCDEVMDL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000195" ON "DB2ADMIN"."PVCDEVMDL" ("DEVMDLNAME" ASC, "SESSIONTYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PVCDEVSPEC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PVCDEVSPEC" (
    "SPEC_ID" INTEGER NOT NULL,
    "SPECNAME" VARCHAR(80 OCTETS) NOT NULL,
    "SESSIONTYPE" VARCHAR(32 OCTETS),
    "MAXCONTENTLENGTH" INTEGER,
    "MAXURLLENGTH" INTEGER,
    "LCDWIDTH" INTEGER,
    "LCDHEIGHT" INTEGER,
    "LCDCOLORS" INTEGER,
    "LCDMONOCHROME" CHAR(1 OCTETS),
    "IMAGEFORMAT" VARCHAR(80 OCTETS),
    "SOUNDFORMAT" VARCHAR(80 OCTETS),
    "DOCUMENTFORMAT" VARCHAR(80 OCTETS),
    "DOCUMENTVERSION" VARCHAR(8 OCTETS),
    "CONTENTDIR" VARCHAR(80 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PVCDEVSPEC"
ALTER TABLE "DB2ADMIN"."PVCDEVSPEC"
ADD PRIMARY KEY ("SPEC_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PVCDEVSPEC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I775148" ON "DB2ADMIN"."PVCDEVSPEC" ("SPECNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PVCMDLSPEC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PVCMDLSPEC" (
    "MDLSPC_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "MODEL_ID" INTEGER NOT NULL,
    "SPEC_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PVCMDLSPEC"
ALTER TABLE "DB2ADMIN"."PVCMDLSPEC"
ADD PRIMARY KEY ("MDLSPC_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PVCMDLSPEC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000196" ON "DB2ADMIN"."PVCMDLSPEC" (
    "MODEL_ID" ASC,
    "SPEC_ID" ASC,
    "STOREENT_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PVCMDLSPEC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000707" ON "DB2ADMIN"."PVCMDLSPEC" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PVCSESSION"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PVCSESSION" (
    "PVCSESSION_ID" BIGINT NOT NULL,
    "TERMINAL" VARCHAR(254 OCTETS) NOT NULL,
    "REGISTER_ID" BIGINT,
    "LASTVISITED" TIMESTAMP NOT NULL,
    "STATUS" INTEGER NOT NULL WITH DEFAULT 0,
    "GUEST_ID" BIGINT,
    "SESSIONTYPE" VARCHAR(32 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PVCSESSION"
ALTER TABLE "DB2ADMIN"."PVCSESSION"
ADD PRIMARY KEY ("PVCSESSION_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PVCSESSION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000197" ON "DB2ADMIN"."PVCSESSION" ("TERMINAL" ASC, "SESSIONTYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PVCSESSION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000708" ON "DB2ADMIN"."PVCSESSION" ("REGISTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_COUPON"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_COUPON" (
    "PX_COUPON_ID" BIGINT NOT NULL,
    "USERS_ID" BIGINT,
    "STOREENT_ID" INTEGER NOT NULL,
    "VERSION" INTEGER NOT NULL,
    "EFFECTIVE" TIMESTAMP NOT NULL,
    "EXPIRE" TIMESTAMP NOT NULL,
    "STATUS" INTEGER NOT NULL WITH DEFAULT 0,
    "ORDERS_ID" BIGINT,
    "GUESTID" VARCHAR(64 OCTETS),
    "NAME" VARCHAR(128 OCTETS) NOT NULL,
    "CODE" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_COUPON"
ALTER TABLE "DB2ADMIN"."PX_COUPON"
ADD PRIMARY KEY ("PX_COUPON_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_COUPON"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000389" ON "DB2ADMIN"."PX_COUPON" (
    "STOREENT_ID" ASC,
    "NAME" ASC,
    "VERSION" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_COUPON"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000390" ON "DB2ADMIN"."PX_COUPON" ("ORDERS_ID" ASC, "USERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_COUPON"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000391" ON "DB2ADMIN"."PX_COUPON" ("ORDERS_ID" ASC, "GUESTID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_COUPON"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000404" ON "DB2ADMIN"."PX_COUPON" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_COUPON"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000405" ON "DB2ADMIN"."PX_COUPON" ("USERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_COUPON"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000406" ON "DB2ADMIN"."PX_COUPON" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_DESCRIPTION"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_DESCRIPTION" (
    "PX_PROMOTION_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "ADMINDESC" VARCHAR(254 OCTETS),
    "SHORTDESC" VARCHAR(254 OCTETS),
    "LONGDESC" VARCHAR(4000 OCTETS),
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS),
    "FIELD4" VARCHAR(254 OCTETS),
    "FIELD5" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_DESCRIPTION"
ALTER TABLE "DB2ADMIN"."PX_DESCRIPTION"
ADD PRIMARY KEY ("PX_PROMOTION_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_DYNATTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_DYNATTR" (
    "PX_DYNATTR_ID" INTEGER NOT NULL,
    "TYPENAME" VARCHAR(220 OCTETS) NOT NULL,
    "ATTRNAME" VARCHAR(32 OCTETS) NOT NULL,
    "IMPLCLS" VARCHAR(254 OCTETS) NOT NULL,
    "XMLPARAM" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_DYNATTR"
ALTER TABLE "DB2ADMIN"."PX_DYNATTR"
ADD PRIMARY KEY ("PX_DYNATTR_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_DYNATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000385" ON "DB2ADMIN"."PX_DYNATTR" ("TYPENAME" ASC, "ATTRNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_ELEMENT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_ELEMENT" (
    "PX_ELEMENT_ID" BIGINT NOT NULL,
    "PX_PROMOTION_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "TYPE" VARCHAR(254 OCTETS) NOT NULL,
    "SUBTYPE" VARCHAR(254 OCTETS),
    "PARENT" VARCHAR(254 OCTETS),
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_ELEMENT"
ALTER TABLE "DB2ADMIN"."PX_ELEMENT"
ADD PRIMARY KEY ("PX_ELEMENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_ELEMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001201" ON "DB2ADMIN"."PX_ELEMENT" ("PX_PROMOTION_ID" ASC, "NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_ELEMENTNVP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_ELEMENTNVP" (
    "PX_ELEMENTNVP_ID" BIGINT NOT NULL,
    "PX_ELEMENT_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "VALUE" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_ELEMENTNVP"
ALTER TABLE "DB2ADMIN"."PX_ELEMENTNVP"
ADD PRIMARY KEY ("PX_ELEMENTNVP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_ELEMENTNVP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001197" ON "DB2ADMIN"."PX_ELEMENTNVP" (
    "PX_ELEMENT_ID" ASC,
    "NAME" ASC,
    "VALUE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_GROUP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_GROUP" (
    "PX_GROUP_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "STATUS" SMALLINT NOT NULL WITH DEFAULT 1,
    "GRPNAME" VARCHAR(128 OCTETS) NOT NULL,
    "XMLPARAM" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_GROUP"
ALTER TABLE "DB2ADMIN"."PX_GROUP"
ADD PRIMARY KEY ("PX_GROUP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_GROUP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000386" ON "DB2ADMIN"."PX_GROUP" ("STOREENT_ID" ASC, "GRPNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_GROUP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000394" ON "DB2ADMIN"."PX_GROUP" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_GRPPOLICY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_GRPPOLICY" (
    "PX_GROUP_ID" INTEGER NOT NULL,
    "PX_POLICY_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_GRPPOLICY"
ALTER TABLE "DB2ADMIN"."PX_GRPPOLICY"
ADD PRIMARY KEY ("PX_GROUP_ID", "PX_POLICY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_GRPPOLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000396" ON "DB2ADMIN"."PX_GRPPOLICY" ("PX_GROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_GRPPOLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000397" ON "DB2ADMIN"."PX_GRPPOLICY" ("PX_POLICY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_POLICY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_POLICY" (
    "PX_POLICY_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "STATUS" SMALLINT NOT NULL WITH DEFAULT 0,
    "NAME" VARCHAR(128 OCTETS) NOT NULL,
    "IMPLCLS" VARCHAR(254 OCTETS) NOT NULL,
    "XMLPARAM" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_POLICY"
ALTER TABLE "DB2ADMIN"."PX_POLICY"
ADD PRIMARY KEY ("PX_POLICY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_POLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000387" ON "DB2ADMIN"."PX_POLICY" ("STOREENT_ID" ASC, "NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_POLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000395" ON "DB2ADMIN"."PX_POLICY" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_PROMOARG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_PROMOARG" (
    "ORDERS_ID" BIGINT NOT NULL,
    "DETAIL" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_PROMOARG"
ALTER TABLE "DB2ADMIN"."PX_PROMOARG"
ADD PRIMARY KEY ("ORDERS_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_PROMOAUDIT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_PROMOAUDIT" (
    "PX_PROMOTION_ID" INTEGER NOT NULL,
    "VERSION" INTEGER NOT NULL,
    "REVISION" INTEGER NOT NULL,
    "XMLPARAM" CLOB(3000000 OCTETS) LOGGED NOT COMPACT NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "TAB16K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_PROMOAUDIT"
ALTER TABLE "DB2ADMIN"."PX_PROMOAUDIT"
ADD PRIMARY KEY ("PX_PROMOTION_ID", "VERSION", "REVISION");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_PROMOAUTH"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_PROMOAUTH" (
    "PX_PROMOTION_ID" INTEGER NOT NULL,
    "COMMENTS" VARCHAR(254 OCTETS),
    "PROMOTIONTYPE" VARCHAR(254 OCTETS) NOT NULL,
    "DAILYSTARTTIME" TIMESTAMP,
    "DAILYENDTIME" TIMESTAMP,
    "WEEKDAY_SUN" SMALLINT,
    "WEEKDAY_MON" SMALLINT,
    "WEEKDAY_TUE" SMALLINT,
    "WEEKDAY_WED" SMALLINT,
    "WEEKDAY_THU" SMALLINT,
    "WEEKDAY_FRI" SMALLINT,
    "WEEKDAY_SAT" SMALLINT,
    "CTLPARAM" VARCHAR(32 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "ADMINSTVENAME" VARCHAR(254 OCTETS),
    "UP_ADMINSTVENAME" VARCHAR(254 OCTETS) GENERATED ALWAYS AS (UPPER(ADMINSTVENAME))
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_PROMOAUTH"
ALTER TABLE "DB2ADMIN"."PX_PROMOAUTH"
ADD PRIMARY KEY ("PX_PROMOTION_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMOAUTH"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001219" ON "DB2ADMIN"."PX_PROMOAUTH" ("ADMINSTVENAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMOAUTH"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00025" ON "DB2ADMIN"."PX_PROMOAUTH" ("UP_ADMINSTVENAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_PROMOCD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_PROMOCD" (
    "PX_PROMOCD_ID" BIGINT NOT NULL,
    "PX_PROMOTION_ID" INTEGER NOT NULL,
    "CODE" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "UP_CODE" VARCHAR(128 OCTETS) GENERATED ALWAYS AS (UPPER(CODE))
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_PROMOCD"
ALTER TABLE "DB2ADMIN"."PX_PROMOCD"
ADD PRIMARY KEY ("PX_PROMOCD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMOCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001165" ON "DB2ADMIN"."PX_PROMOCD" ("PX_PROMOTION_ID" ASC, "CODE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMOCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001166" ON "DB2ADMIN"."PX_PROMOCD" ("CODE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMOCD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00016" ON "DB2ADMIN"."PX_PROMOCD" ("UP_CODE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_PROMOPOLICY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_PROMOPOLICY" (
    "PX_PROMOTION_ID" INTEGER NOT NULL,
    "PX_POLICY_ID" INTEGER NOT NULL,
    "RELATION" SMALLINT NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMOPOLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000402" ON "DB2ADMIN"."PX_PROMOPOLICY" ("PX_PROMOTION_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMOPOLICY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000403" ON "DB2ADMIN"."PX_PROMOPOLICY" ("PX_POLICY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_PROMOTION"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_PROMOTION" (
    "PX_PROMOTION_ID" INTEGER NOT NULL,
    "PRIORITY" INTEGER NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "EXCLSVE" INTEGER NOT NULL,
    "TYPE" INTEGER NOT NULL,
    "PERORDLMT" INTEGER NOT NULL WITH DEFAULT -1,
    "PERSHOPPERLMT" INTEGER NOT NULL WITH DEFAULT -1,
    "TOTALLMT" INTEGER NOT NULL WITH DEFAULT -1,
    "RSV_INT" INTEGER,
    "PX_GROUP_ID" INTEGER NOT NULL,
    "CAMPAIGN_ID" INTEGER,
    "STOREENT_ID" INTEGER NOT NULL,
    "VERSION" INTEGER NOT NULL,
    "REVISION" INTEGER NOT NULL,
    "EFFECTIVE" INTEGER,
    "TRANSFER" INTEGER WITH DEFAULT 0,
    "CDREQUIRED" INTEGER NOT NULL WITH DEFAULT 0,
    "EXPIRE" INTEGER,
    "LASTUPDATEBY" BIGINT,
    "LASTUPDATE" TIMESTAMP,
    "STARTDATE" TIMESTAMP NOT NULL,
    "ENDDATE" TIMESTAMP NOT NULL,
    "RSV_TIME" TIMESTAMP,
    "RSV_REAL" DECIMAL(20, 5),
    "TGTSALES" DECIMAL(20, 5),
    "NAME" VARCHAR(128 OCTETS) NOT NULL,
    "CODE" VARCHAR(128 OCTETS),
    "RSV_VCH" VARCHAR(254 OCTETS),
    "XMLPARAM" CLOB(3000000 OCTETS) LOGGED NOT COMPACT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_PROMOTION"
ALTER TABLE "DB2ADMIN"."PX_PROMOTION"
ADD PRIMARY KEY ("PX_PROMOTION_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMOTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000388" ON "DB2ADMIN"."PX_PROMOTION" (
    "STOREENT_ID" ASC,
    "NAME" ASC,
    "VERSION" ASC,
    "STATUS" ASC,
    "REVISION" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMOTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000398" ON "DB2ADMIN"."PX_PROMOTION" ("PX_GROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMOTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000399" ON "DB2ADMIN"."PX_PROMOTION" ("CAMPAIGN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMOTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000400" ON "DB2ADMIN"."PX_PROMOTION" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMOTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."SCDAB001" ON "DB2ADMIN"."PX_PROMOTION" (
    "STATUS" ASC,
    "CDREQUIRED" ASC,
    "TYPE" ASC,
    "STARTDATE" ASC,
    "ENDDATE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_PROMPROM"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_PROMPROM" (
    "PX_PROMO_ID_FROM" INTEGER NOT NULL,
    "PX_PROMO_ID_TO" INTEGER NOT NULL,
    "RELATION" SMALLINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMPROM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000421" ON "DB2ADMIN"."PX_PROMPROM" ("PX_PROMO_ID_FROM" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_PROMPROM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000422" ON "DB2ADMIN"."PX_PROMPROM" ("PX_PROMO_ID_TO" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_RWDOPTION"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_RWDOPTION" (
    "PX_RWDOPTION_ID" BIGINT NOT NULL,
    "PX_PROMOTION_ID" INTEGER NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "RWDCHOICE" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "RWDSPEC" CLOB(1000000 OCTETS) LOGGED NOT COMPACT NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "TAB16K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_RWDOPTION"
ALTER TABLE "DB2ADMIN"."PX_RWDOPTION"
ADD PRIMARY KEY ("PX_RWDOPTION_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_RWDOPTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001297" ON "DB2ADMIN"."PX_RWDOPTION" ("PX_PROMOTION_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_RWDOPTION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001298" ON "DB2ADMIN"."PX_RWDOPTION" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_TEMPLATE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_TEMPLATE" (
    "PX_TEMPLATE_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(64 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_TEMPLATE"
ALTER TABLE "DB2ADMIN"."PX_TEMPLATE"
ADD PRIMARY KEY ("PX_TEMPLATE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_TEMPLATE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000420" ON "DB2ADMIN"."PX_TEMPLATE" ("STOREENT_ID" ASC, "NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_TPLTGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_TPLTGRP" (
    "PX_TEMPLATE_ID" INTEGER NOT NULL,
    "PX_GROUP_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_TPLTGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000423" ON "DB2ADMIN"."PX_TPLTGRP" ("PX_TEMPLATE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_TPLTGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000424" ON "DB2ADMIN"."PX_TPLTGRP" ("PX_GROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PX_USAGE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PX_USAGE" (
    "PX_USAGE_ID" BIGINT NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "USERS_ID" BIGINT,
    "STOREENT_ID" INTEGER NOT NULL,
    "VERSION" INTEGER NOT NULL,
    "GUESTID" VARCHAR(64 OCTETS),
    "NAME" VARCHAR(128 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PX_USAGE"
ALTER TABLE "DB2ADMIN"."PX_USAGE"
ADD PRIMARY KEY ("PX_USAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_USAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000392" ON "DB2ADMIN"."PX_USAGE" (
    "STOREENT_ID" ASC,
    "NAME" ASC,
    "VERSION" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_USAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000393" ON "DB2ADMIN"."PX_USAGE" ("GUESTID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_USAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000407" ON "DB2ADMIN"."PX_USAGE" ("USERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_USAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000408" ON "DB2ADMIN"."PX_USAGE" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PX_USAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000409" ON "DB2ADMIN"."PX_USAGE" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
---