------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."QTYCONVERT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."QTYCONVERT" (
    "QTYUNIT_ID_TO" CHAR(16 OCTETS) NOT NULL,
    "QTYCONVERT_ID" INTEGER NOT NULL,
    "QTYUNIT_ID_FROM" CHAR(16 OCTETS) NOT NULL,
    "FACTOR" DECIMAL(31, 20) NOT NULL,
    "MULTIPLYORDIVIDE" CHAR(1 OCTETS) NOT NULL,
    "UPDATABLE" CHAR(1 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."QTYCONVERT"
ALTER TABLE "DB2ADMIN"."QTYCONVERT"
ADD PRIMARY KEY ("QTYCONVERT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."QTYCONVERT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000198" ON "DB2ADMIN"."QTYCONVERT" ("QTYUNIT_ID_TO" ASC, "QTYUNIT_ID_FROM" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."QTYFMTDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."QTYFMTDESC" (
    "STOREENT_ID" INTEGER NOT NULL,
    "NUMBRUSG_ID" INTEGER NOT NULL WITH DEFAULT -1,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "QTYUNIT_ID" CHAR(16 OCTETS) NOT NULL,
    "UNITSYMBOL" VARCHAR(254 OCTETS),
    "UNITPREFIXPOS" VARCHAR(254 OCTETS),
    "UNITSUFFIXPOS" VARCHAR(254 OCTETS),
    "DISPLAYLOCALE" CHAR(16 OCTETS),
    "CUSTOMIZEDQTYSTR" VARCHAR(254 OCTETS),
    "UNITPREFIXNEG" VARCHAR(254 OCTETS),
    "UNITSUFFIXNEG" VARCHAR(254 OCTETS),
    "RADIXPOINT" CHAR(1 OCTETS),
    "GROUPINGCHAR" CHAR(1 OCTETS),
    "NUMBERPATTERN" VARCHAR(254 OCTETS),
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."QTYFMTDESC"
ALTER TABLE "DB2ADMIN"."QTYFMTDESC"
ADD PRIMARY KEY (
        "NUMBRUSG_ID",
        "STOREENT_ID",
        "QTYUNIT_ID",
        "LANGUAGE_ID"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."QTYFMTDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001274" ON "DB2ADMIN"."QTYFMTDESC" (
    "STOREENT_ID" ASC,
    "QTYUNIT_ID" ASC,
    "NUMBRUSG_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."QTYFORMAT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."QTYFORMAT" (
    "STOREENT_ID" INTEGER NOT NULL,
    "QTYUNIT_ID" CHAR(16 OCTETS) NOT NULL,
    "ROUNDINGMULTIPLE" INTEGER NOT NULL,
    "NUMBRUSG_ID" INTEGER NOT NULL WITH DEFAULT -1,
    "ROUNDINGMETHOD" CHAR(1 OCTETS) NOT NULL,
    "DECIMALPLACES" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."QTYFORMAT"
ALTER TABLE "DB2ADMIN"."QTYFORMAT"
ADD PRIMARY KEY (
        "STOREENT_ID",
        "QTYUNIT_ID",
        "NUMBRUSG_ID"
    );
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."QTYUNIT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."QTYUNIT" (
    "QTYUNIT_ID" CHAR(16 OCTETS) NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."QTYUNIT"
ALTER TABLE "DB2ADMIN"."QTYUNIT"
ADD PRIMARY KEY ("QTYUNIT_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."QTYUNITDSC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."QTYUNITDSC" (
    "QTYUNIT_ID" CHAR(16 OCTETS) NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."QTYUNITDSC"
ALTER TABLE "DB2ADMIN"."QTYUNITDSC"
ADD PRIMARY KEY ("LANGUAGE_ID", "QTYUNIT_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."QTYUNITMAP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."QTYUNITMAP" (
    "UOMSTANDARD" VARCHAR(32 OCTETS) NOT NULL,
    "UOMCODE" VARCHAR(16 OCTETS) NOT NULL,
    "QTYUNIT_ID" CHAR(16 OCTETS) NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."QTYUNITMAP"
ALTER TABLE "DB2ADMIN"."QTYUNITMAP"
ADD PRIMARY KEY ("UOMSTANDARD", "UOMCODE");
-- DDL Statements for Indexes on Table "DB2ADMIN"."QTYUNITMAP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000199" ON "DB2ADMIN"."QTYUNITMAP" ("QTYUNIT_ID" ASC, "UOMSTANDARD" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."QUEUE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."QUEUE" (
    "QUEUE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(50 OCTETS) NOT NULL,
    "ALLCSR" INTEGER NOT NULL WITH DEFAULT 0,
    "STORE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."QUEUE"
ALTER TABLE "DB2ADMIN"."QUEUE"
ADD PRIMARY KEY ("QUEUE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."QUEUE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000273" ON "DB2ADMIN"."QUEUE" ("STORE_ID" ASC, "NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."QUEUECSR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."QUEUECSR" (
    "QUEUE_ID" INTEGER NOT NULL,
    "CSR_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."QUEUECSR"
ALTER TABLE "DB2ADMIN"."QUEUECSR"
ADD PRIMARY KEY ("QUEUE_ID", "CSR_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."QUEUECSR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000709" ON "DB2ADMIN"."QUEUECSR" ("CSR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."QUEUEDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."QUEUEDESC" (
    "QUEUE_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "DISPLAYNAME" VARCHAR(50 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."QUEUEDESC"
ALTER TABLE "DB2ADMIN"."QUEUEDESC"
ADD PRIMARY KEY ("QUEUE_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RA"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RA" (
    "RA_ID" BIGINT NOT NULL,
    "VENDOR_ID" BIGINT NOT NULL,
    "STORE_ID" INTEGER NOT NULL,
    "ORDERDATE" TIMESTAMP NOT NULL,
    "OPENINDICATOR" CHAR(1 OCTETS),
    "DATECLOSED" TIMESTAMP,
    "LASTUPDATE" TIMESTAMP,
    "EXTERNALID" CHAR(20 OCTETS),
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "CREATETIME" TIMESTAMP NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RA"
ALTER TABLE "DB2ADMIN"."RA"
ADD PRIMARY KEY ("RA_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000200" ON "DB2ADMIN"."RA" (
    "STORE_ID" ASC,
    "VENDOR_ID" ASC,
    "CREATETIME" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001275" ON "DB2ADMIN"."RA" ("VENDOR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RABACKALLO"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RABACKALLO" (
    "RABACKALLONUM" INTEGER NOT NULL,
    "RADETAIL_ID" BIGINT NOT NULL,
    "ITEMSPC_ID" BIGINT NOT NULL,
    "ORDERITEMS_ID" BIGINT NOT NULL,
    "QTYALLOCATED" INTEGER,
    "LASTUPDATE" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RABACKALLO"
ALTER TABLE "DB2ADMIN"."RABACKALLO"
ADD PRIMARY KEY ("ORDERITEMS_ID", "RABACKALLONUM");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RABACKALLO"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000710" ON "DB2ADMIN"."RABACKALLO" ("ITEMSPC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RABACKALLO"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000711" ON "DB2ADMIN"."RABACKALLO" ("RADETAIL_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RADETAIL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RADETAIL" (
    "RADETAIL_ID" BIGINT NOT NULL,
    "RA_ID" BIGINT NOT NULL,
    "FFMCENTER_ID" INTEGER,
    "ITEMSPC_ID" BIGINT NOT NULL,
    "QTYORDERED" INTEGER NOT NULL WITH DEFAULT 0,
    "QTYRECEIVED" INTEGER NOT NULL WITH DEFAULT 0,
    "QTYREMAINING" INTEGER NOT NULL WITH DEFAULT 0,
    "QTYALLOCATED" INTEGER NOT NULL WITH DEFAULT 0,
    "EXPECTEDDATE" TIMESTAMP NOT NULL,
    "RADETAILCOMMENT" VARCHAR(254 OCTETS),
    "LASTUPDATE" TIMESTAMP,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RADETAIL"
ALTER TABLE "DB2ADMIN"."RADETAIL"
ADD PRIMARY KEY ("RADETAIL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RADETAIL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000201" ON "DB2ADMIN"."RADETAIL" (
    "RA_ID" ASC,
    "FFMCENTER_ID" ASC,
    "ITEMSPC_ID" ASC,
    "EXPECTEDDATE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RADETAIL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000202" ON "DB2ADMIN"."RADETAIL" (
    "RA_ID" ASC,
    "RADETAIL_ID" ASC,
    "EXPECTEDDATE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RADETAIL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000712" ON "DB2ADMIN"."RADETAIL" ("ITEMSPC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RADETAIL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000713" ON "DB2ADMIN"."RADETAIL" ("FFMCENTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RCPTAVAIL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RCPTAVAIL" (
    "RCPTAVAIL_ID" BIGINT NOT NULL,
    "DISTARRANG_ID" BIGINT NOT NULL,
    "RECEIPT_ID" BIGINT NOT NULL,
    "PRECEDENCE" INTEGER,
    "LASTUPDATE" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RCPTAVAIL"
ALTER TABLE "DB2ADMIN"."RCPTAVAIL"
ADD PRIMARY KEY ("RCPTAVAIL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RCPTAVAIL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000203" ON "DB2ADMIN"."RCPTAVAIL" ("DISTARRANG_ID" ASC, "RECEIPT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RCPTAVAIL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000714" ON "DB2ADMIN"."RCPTAVAIL" ("RECEIPT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RECEIPT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RECEIPT" (
    "RECEIPT_ID" BIGINT NOT NULL,
    "VERSIONSPC_ID" BIGINT NOT NULL,
    "RADETAIL_ID" BIGINT,
    "STORE_ID" INTEGER NOT NULL,
    "SETCCURR" CHAR(3 OCTETS),
    "FFMCENTER_ID" INTEGER NOT NULL,
    "VENDOR_ID" BIGINT,
    "RECEIPTDATE" TIMESTAMP NOT NULL,
    "QTYRECEIVED" INTEGER NOT NULL WITH DEFAULT 0,
    "QTYINPROCESS" INTEGER NOT NULL WITH DEFAULT 0,
    "QTYONHAND" INTEGER NOT NULL WITH DEFAULT 0,
    "QTYINKITS" INTEGER NOT NULL WITH DEFAULT 0,
    "COST" DECIMAL(20, 5),
    "COMMENT1" VARCHAR(254 OCTETS),
    "COMMENT2" VARCHAR(254 OCTETS),
    "LASTUPDATE" TIMESTAMP,
    "CREATETIME" TIMESTAMP NOT NULL,
    "RECEIPTTYPE" CHAR(4 OCTETS) NOT NULL WITH DEFAULT 'ADHC',
    "RTNRCPTDSP_ID" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RECEIPT"
ALTER TABLE "DB2ADMIN"."RECEIPT"
ADD PRIMARY KEY ("RECEIPT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RECEIPT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000204" ON "DB2ADMIN"."RECEIPT" (
    "VERSIONSPC_ID" ASC,
    "FFMCENTER_ID" ASC,
    "STORE_ID" ASC,
    "CREATETIME" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RECEIPT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000205" ON "DB2ADMIN"."RECEIPT" (
    "RECEIPT_ID" ASC,
    "RADETAIL_ID" ASC,
    "RECEIPTDATE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RECEIPT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000715" ON "DB2ADMIN"."RECEIPT" ("RADETAIL_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RECEIPT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000716" ON "DB2ADMIN"."RECEIPT" ("FFMCENTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RECEIPT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000717" ON "DB2ADMIN"."RECEIPT" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RECEIPT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001276" ON "DB2ADMIN"."RECEIPT" ("VENDOR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."REFKEYS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."REFKEYS" (
    "TABLENAME" CHAR(18 OCTETS) NOT NULL,
    "FKTABLE_NAME" CHAR(18 OCTETS) NOT NULL,
    "FKCOLUMN_NAME" CHAR(18 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."REFKEYS"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000300" ON "DB2ADMIN"."REFKEYS" (
    "TABLENAME" ASC,
    "FKTABLE_NAME" ASC,
    "FKCOLUMN_NAME" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."REFUNDMTHD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."REFUNDMTHD" (
    "RMA_ID" BIGINT NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "TRADING_ID" BIGINT,
    "SETCCURR" CHAR(3 OCTETS),
    "ACCOUNT_ID" BIGINT,
    "CREDITLINE_ID" BIGINT,
    "POLICY_ID" BIGINT NOT NULL,
    "PAYSUMMARY_ID" BIGINT,
    "REFUNDAMOUNT" DECIMAL(20, 5) NOT NULL,
    "RETURNXML" VARCHAR(4000 OCTETS),
    "TIMECREATED" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."REFUNDMTHD"
ALTER TABLE "DB2ADMIN"."REFUNDMTHD"
ADD PRIMARY KEY ("RMA_ID", "ORDERS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."REFUNDMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000718" ON "DB2ADMIN"."REFUNDMTHD" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."REFUNDMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000719" ON "DB2ADMIN"."REFUNDMTHD" ("TRADING_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."REFUNDMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000720" ON "DB2ADMIN"."REFUNDMTHD" ("CREDITLINE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."REFUNDMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000721" ON "DB2ADMIN"."REFUNDMTHD" ("POLICY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."REFUNDMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000722" ON "DB2ADMIN"."REFUNDMTHD" ("PAYSUMMARY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."REFUNDMTHD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000723" ON "DB2ADMIN"."REFUNDMTHD" ("ACCOUNT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."REPCUSTREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."REPCUSTREL" (
    "REP_ID" BIGINT NOT NULL,
    "CUST_ID" BIGINT NOT NULL,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."REPCUSTREL"
ALTER TABLE "DB2ADMIN"."REPCUSTREL"
ADD PRIMARY KEY ("REP_ID", "CUST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."REPCUSTREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000965" ON "DB2ADMIN"."REPCUSTREL" ("CUST_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."REPDLVRY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."REPDLVRY" (
    "STOREENT_ID" INTEGER NOT NULL,
    "FISCALYEAR" CHAR(50 OCTETS) NOT NULL WITH DEFAULT '01/01',
    "FORMAT" INTEGER NOT NULL WITH DEFAULT 0,
    "FREQUENCY" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'M',
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."REPDLVRY"
ALTER TABLE "DB2ADMIN"."REPDLVRY"
ADD PRIMARY KEY ("STOREENT_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."REPORT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."REPORT" (
    "RPTRFNBR" INTEGER,
    "RPTTITLE" CHAR(100 OCTETS),
    "RPTDESC" VARCHAR(500 OCTETS),
    "RPTTYPE" CHAR(1 OCTETS),
    "RPTMENBR" INTEGER,
    "RPTSUBRPT" CHAR(100 OCTETS),
    "RPTTMPLT" CHAR(100 OCTETS),
    "RPTCOLUMNS" VARCHAR(500 OCTETS),
    "RPTDELY" CHAR(100 OCTETS),
    "RPTENABLE" INTEGER,
    "RPTVIEW" INTEGER,
    "RPTSQL" VARCHAR(2000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."REPORT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000206" ON "DB2ADMIN"."REPORT" ("RPTRFNBR" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RFQ"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RFQ" (
    "MEMBER_ID" BIGINT NOT NULL,
    "RFQ_ID" BIGINT NOT NULL,
    "ACCESSTYPE" INTEGER,
    "TFTRADENG_ID" BIGINT,
    "STARTTIME" TIMESTAMP,
    "STORE_ID" INTEGER,
    "ENDTIME" TIMESTAMP,
    "DURATION" TIMESTAMP,
    "NUMRESPONSES" INTEGER,
    "CREATETIME" TIMESTAMP,
    "UPDATETIME" TIMESTAMP,
    "CANCELTIME" TIMESTAMP,
    "STATE" INTEGER NOT NULL,
    "PREVOFFID" BIGINT,
    "PREVOFFTYPE" INTEGER,
    "NEXTOFFID" BIGINT,
    "NEXTOFFTYPE" INTEGER,
    "ROUND" INTEGER,
    "STAGE" INTEGER,
    "NAME" VARCHAR(200 OCTETS) NOT NULL,
    "MAJORVERSION" INTEGER NOT NULL,
    "MINORVERSION" INTEGER NOT NULL,
    "ENDRESULT" INTEGER,
    "MARKFORDELETE" INTEGER,
    "ACTIVATETIME" TIMESTAMP,
    "CLOSETIME" TIMESTAMP,
    "COMPLETETIME" TIMESTAMP,
    "RULETYPE" INTEGER NOT NULL WITH DEFAULT 1,
    "TRACKNUMBER" VARCHAR(254 OCTETS),
    "VERSIONFLAGS" INTEGER,
    "EXTRFQNUM" VARCHAR(64 OCTETS),
    "FIELD1" BIGINT,
    "FIELD2" INTEGER,
    "FIELD3" VARCHAR(254 OCTETS),
    "FIELD4" VARCHAR(254 OCTETS),
    "FIELD5" TIMESTAMP,
    "FIELD6" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RFQ"
ALTER TABLE "DB2ADMIN"."RFQ"
ADD PRIMARY KEY ("RFQ_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQ"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000207" ON "DB2ADMIN"."RFQ" (
    "NAME" ASC,
    "MAJORVERSION" ASC,
    "MINORVERSION" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQ"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000348" ON "DB2ADMIN"."RFQ" ("STATE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQ"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000724" ON "DB2ADMIN"."RFQ" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQ"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000725" ON "DB2ADMIN"."RFQ" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQ"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001277" ON "DB2ADMIN"."RFQ" ("TFTRADENG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RFQCATEGRY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RFQCATEGRY" (
    "RFQCATEGRY_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(200 OCTETS) NOT NULL,
    "RFQ_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RFQCATEGRY"
ALTER TABLE "DB2ADMIN"."RFQCATEGRY"
ADD PRIMARY KEY ("RFQCATEGRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQCATEGRY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000297" ON "DB2ADMIN"."RFQCATEGRY" ("RFQ_ID" ASC, "NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RFQPROD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RFQPROD" (
    "RFQ_ID" BIGINT NOT NULL,
    "QUANTITY" DOUBLE,
    "PRICE" DECIMAL(20, 5),
    "CURRENCY" CHAR(3 OCTETS),
    "QTYUNIT_ID" CHAR(16 OCTETS),
    "CATENTRY_ID" BIGINT,
    "RFQPROD_ID" BIGINT NOT NULL,
    "RFQPRODNAME" VARCHAR(128 OCTETS),
    "RFQCATEGRY_ID" BIGINT,
    "CHANGEABLE" INTEGER NOT NULL WITH DEFAULT 0,
    "PRICEADJUSTMENT" DOUBLE,
    "NEGOTIATIONTYPE" INTEGER NOT NULL WITH DEFAULT 1,
    "FIELD1" BIGINT,
    "FIELD2" INTEGER,
    "FIELD3" VARCHAR(254 OCTETS),
    "FIELD4" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RFQPROD"
ALTER TABLE "DB2ADMIN"."RFQPROD"
ADD PRIMARY KEY ("RFQPROD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQPROD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000349" ON "DB2ADMIN"."RFQPROD" ("RFQ_ID" ASC, "CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQPROD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000350" ON "DB2ADMIN"."RFQPROD" ("RFQ_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQPROD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000372" ON "DB2ADMIN"."RFQPROD" ("RFQ_ID" ASC, "NEGOTIATIONTYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQPROD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000726" ON "DB2ADMIN"."RFQPROD" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQPROD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001278" ON "DB2ADMIN"."RFQPROD" ("RFQCATEGRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RFQRSP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RFQRSP" (
    "RFQ_ID" BIGINT NOT NULL,
    "TFTRADENG_ID" BIGINT,
    "MAJORVERSION" INTEGER NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "MINORVERSION" INTEGER NOT NULL,
    "NAME" VARCHAR(200 OCTETS) NOT NULL,
    "STATE" INTEGER NOT NULL,
    "REJECTREASON" VARCHAR(254 OCTETS),
    "REMARKS" VARCHAR(254 OCTETS),
    "CREATETIME" TIMESTAMP,
    "UPDATETIME" TIMESTAMP,
    "CANCELTIME" TIMESTAMP,
    "MARKFORDELETE" INTEGER,
    "RFQRSP_ID" BIGINT NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "VERSIONFLAGS" INTEGER,
    "STORE_ID" INTEGER NOT NULL,
    "PREVRSP" BIGINT,
    "ACCEPTACTION" INTEGER NOT NULL WITH DEFAULT 0,
    "EXTRFQRESPONSENUM" VARCHAR(64 OCTETS),
    "FIELD1" BIGINT,
    "FIELD2" INTEGER,
    "FIELD3" VARCHAR(254 OCTETS),
    "FIELD4" VARCHAR(254 OCTETS),
    "FIELD5" TIMESTAMP,
    "FIELD6" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RFQRSP"
ALTER TABLE "DB2ADMIN"."RFQRSP"
ADD PRIMARY KEY ("RFQRSP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000209" ON "DB2ADMIN"."RFQRSP" (
    "NAME" ASC,
    "MAJORVERSION" ASC,
    "MINORVERSION" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000351" ON "DB2ADMIN"."RFQRSP" ("RFQ_ID" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000352" ON "DB2ADMIN"."RFQRSP" ("NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000727" ON "DB2ADMIN"."RFQRSP" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001279" ON "DB2ADMIN"."RFQRSP" ("TFTRADENG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RFQRSPEVAL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RFQRSPEVAL" (
    "RFQRSPEVAL_ID" BIGINT NOT NULL,
    "EVALRESULT" INTEGER NOT NULL WITH DEFAULT 1,
    "REMARKS" VARCHAR(254 OCTETS),
    "UPDATETIME" TIMESTAMP,
    "RFQ_ID" BIGINT NOT NULL,
    "RFQRSP_ID" BIGINT NOT NULL,
    "RFQRSPPROD_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RFQRSPEVAL"
ALTER TABLE "DB2ADMIN"."RFQRSPEVAL"
ADD PRIMARY KEY ("RFQRSPEVAL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPEVAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000338" ON "DB2ADMIN"."RFQRSPEVAL" ("RFQRSPPROD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPEVAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000728" ON "DB2ADMIN"."RFQRSPEVAL" ("RFQRSP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPEVAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000729" ON "DB2ADMIN"."RFQRSPEVAL" ("RFQ_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RFQRSPPARL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RFQRSPPARL" (
    "RFQRSPPARL_ID" BIGINT NOT NULL,
    "RFQ_ID" BIGINT NOT NULL,
    "RFQRSP_ID" BIGINT NOT NULL,
    "RFQPATTRVALUE_ID" BIGINT NOT NULL,
    "RFQRSPPATTRVAL_ID" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RFQRSPPARL"
ALTER TABLE "DB2ADMIN"."RFQRSPPARL"
ADD PRIMARY KEY ("RFQRSPPARL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPPARL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000359" ON "DB2ADMIN"."RFQRSPPARL" ("RFQPATTRVALUE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPPARL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000730" ON "DB2ADMIN"."RFQRSPPARL" ("RFQ_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPPARL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000731" ON "DB2ADMIN"."RFQRSPPARL" ("RFQRSP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPPARL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000732" ON "DB2ADMIN"."RFQRSPPARL" ("RFQRSPPATTRVAL_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RFQRSPPROD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RFQRSPPROD" (
    "CATENTRY_ID" BIGINT,
    "RFQRSP_ID" BIGINT NOT NULL,
    "QUANTITY" DOUBLE,
    "CURRENCY" CHAR(3 OCTETS),
    "PRICE" DECIMAL(20, 5),
    "QTYUNIT_ID" CHAR(16 OCTETS),
    "RFQCATENTRYID" BIGINT,
    "RFQRSPPROD_ID" BIGINT NOT NULL,
    "RFQPROD_ID" BIGINT,
    "SKUGENFLAG" INTEGER NOT NULL WITH DEFAULT 0,
    "PRICEADJUSTMENT" DOUBLE,
    "FIELD1" BIGINT,
    "FIELD2" INTEGER,
    "FIELD3" VARCHAR(254 OCTETS),
    "FIELD4" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RFQRSPPROD"
ALTER TABLE "DB2ADMIN"."RFQRSPPROD"
ADD PRIMARY KEY ("RFQRSPPROD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPPROD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000353" ON "DB2ADMIN"."RFQRSPPROD" ("RFQRSP_ID" ASC, "RFQPROD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPPROD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000733" ON "DB2ADMIN"."RFQRSPPROD" ("RFQPROD_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPPROD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000734" ON "DB2ADMIN"."RFQRSPPROD" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RFQRSPTCRL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RFQRSPTCRL" (
    "RFQRSPTCRL_ID" BIGINT NOT NULL,
    "RFQ_ID" BIGINT NOT NULL,
    "RFQRSP_ID" BIGINT NOT NULL,
    "RFQTC_ID" BIGINT NOT NULL,
    "RFQRSPTC_ID" BIGINT NOT NULL,
    "CHANGEFLAG" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RFQRSPTCRL"
ALTER TABLE "DB2ADMIN"."RFQRSPTCRL"
ADD PRIMARY KEY ("RFQRSPTCRL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPTCRL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000211" ON "DB2ADMIN"."RFQRSPTCRL" (
    "RFQ_ID" ASC,
    "RFQRSP_ID" ASC,
    "RFQTC_ID" ASC,
    "RFQRSPTC_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPTCRL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000212" ON "DB2ADMIN"."RFQRSPTCRL" ("RFQTC_ID" ASC, "RFQRSPTC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPTCRL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000735" ON "DB2ADMIN"."RFQRSPTCRL" ("RFQRSPTC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQRSPTCRL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000736" ON "DB2ADMIN"."RFQRSPTCRL" ("RFQRSP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RFQTARGET"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RFQTARGET" (
    "STORE_ID" INTEGER NOT NULL,
    "RFQ_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RFQTARGET"
ALTER TABLE "DB2ADMIN"."RFQTARGET"
ADD PRIMARY KEY ("STORE_ID", "RFQ_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RFQTARGET"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000358" ON "DB2ADMIN"."RFQTARGET" ("RFQ_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RLDISCOUNT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RLDISCOUNT" (
    "PRIORITY" INTEGER NOT NULL,
    "RULEXML" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "CALCODE_ID" INTEGER NOT NULL,
    "TARGETSALES" DECIMAL(20, 5),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RLDISCOUNT"
ALTER TABLE "DB2ADMIN"."RLDISCOUNT"
ADD PRIMARY KEY ("CALCODE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RMA"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RMA" (
    "RMA_ID" BIGINT NOT NULL,
    "STORE_ID" INTEGER NOT NULL,
    "ORGENTITY_ID" BIGINT,
    "POLICY_ID" BIGINT,
    "MEMBER_ID" BIGINT NOT NULL,
    "TRADING_ID" BIGINT,
    "FFMCENTER_ID" INTEGER,
    "RMADATE" TIMESTAMP NOT NULL,
    "TOTALCREDIT" DECIMAL(20, 5) WITH DEFAULT 0,
    "STATUS" CHAR(3 OCTETS) NOT NULL WITH DEFAULT 'PRC',
    "COMMENTS" VARCHAR(254 OCTETS),
    "LASTUPDATE" TIMESTAMP NOT NULL,
    "REFUNDAGAINSTORDID" BIGINT,
    "INUSE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N',
    "CURRENCY" CHAR(3 OCTETS),
    "PREPARED" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N',
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RMA"
ALTER TABLE "DB2ADMIN"."RMA"
ADD PRIMARY KEY ("RMA_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000213" ON "DB2ADMIN"."RMA" ("RMA_ID" ASC, "RMADATE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I836116" ON "DB2ADMIN"."RMA" ("RMA_ID" ASC, "STATUS" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000737" ON "DB2ADMIN"."RMA" ("TRADING_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000738" ON "DB2ADMIN"."RMA" ("POLICY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000739" ON "DB2ADMIN"."RMA" ("ORGENTITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000740" ON "DB2ADMIN"."RMA" ("FFMCENTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000741" ON "DB2ADMIN"."RMA" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000742" ON "DB2ADMIN"."RMA" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RMAAUTHLOG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RMAAUTHLOG" (
    "RMAAUTHLOG_ID" BIGINT NOT NULL,
    "AUTHNOTICEDATE" TIMESTAMP NOT NULL,
    "RMA_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RMAAUTHLOG"
ALTER TABLE "DB2ADMIN"."RMAAUTHLOG"
ADD PRIMARY KEY ("RMAAUTHLOG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAAUTHLOG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000743" ON "DB2ADMIN"."RMAAUTHLOG" ("RMA_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RMACHARGE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RMACHARGE" (
    "RMACHARGE_ID" BIGINT NOT NULL,
    "RMAITEM_ID" BIGINT,
    "CHARGETYPE_ID" INTEGER NOT NULL,
    "RMA_ID" BIGINT NOT NULL,
    "AMOUNT" DECIMAL(20, 5) NOT NULL,
    "CURRENCY" CHAR(3 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RMACHARGE"
ALTER TABLE "DB2ADMIN"."RMACHARGE"
ADD PRIMARY KEY ("RMACHARGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMACHARGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000744" ON "DB2ADMIN"."RMACHARGE" ("RMAITEM_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMACHARGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000745" ON "DB2ADMIN"."RMACHARGE" ("RMA_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMACHARGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001280" ON "DB2ADMIN"."RMACHARGE" ("CHARGETYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RMAIADJCRD"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RMAIADJCRD" (
    "RMAIADJCRD_ID" BIGINT NOT NULL,
    "RMAITEM_ID" BIGINT NOT NULL,
    "ORDADJUST_ID" BIGINT NOT NULL,
    "AMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RMAIADJCRD"
ALTER TABLE "DB2ADMIN"."RMAIADJCRD"
ADD PRIMARY KEY ("RMAIADJCRD_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAIADJCRD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000214" ON "DB2ADMIN"."RMAIADJCRD" ("RMAITEM_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAIADJCRD"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000746" ON "DB2ADMIN"."RMAIADJCRD" ("ORDADJUST_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RMAIDNYRSN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RMAIDNYRSN" (
    "RMAITEM_ID" BIGINT NOT NULL,
    "RTNDNYRSN_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RMAIDNYRSN"
ALTER TABLE "DB2ADMIN"."RMAIDNYRSN"
ADD PRIMARY KEY ("RMAITEM_ID", "RTNDNYRSN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAIDNYRSN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001281" ON "DB2ADMIN"."RMAIDNYRSN" ("RTNDNYRSN_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RMAITEM"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RMAITEM" (
    "RMAITEM_ID" BIGINT NOT NULL,
    "RMA_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "ORDERITEMS_ID" BIGINT,
    "ITEMSPC_ID" BIGINT NOT NULL,
    "RTNREASON_ID" INTEGER NOT NULL,
    "REFUNDORREPLACE" CHAR(3 OCTETS) NOT NULL,
    "CREDITAMOUNT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "QUANTITY" DOUBLE NOT NULL,
    "CREDITDATE" TIMESTAMP,
    "STATUS" CHAR(3 OCTETS) WITH DEFAULT 'PND',
    "CURRENCY" CHAR(3 OCTETS) NOT NULL,
    "COMMENTS" VARCHAR(254 OCTETS),
    "TAXAMOUNT" DECIMAL(20, 5),
    "ADJUSTMENTCREDIT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "ADJUSTMENT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "LASTUPDATE" TIMESTAMP,
    "TOTALCREDIT" DECIMAL(20, 5) NOT NULL WITH DEFAULT 0,
    "INVQUANTITY" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RMAITEM"
ALTER TABLE "DB2ADMIN"."RMAITEM"
ADD PRIMARY KEY ("RMAITEM_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAITEM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000215" ON "DB2ADMIN"."RMAITEM" ("RMA_ID" ASC, "RMAITEM_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAITEM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I837116" ON "DB2ADMIN"."RMAITEM" (
    "ORDERITEMS_ID" ASC,
    "RMAITEM_ID" ASC,
    "STATUS" ASC,
    "RMA_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAITEM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000747" ON "DB2ADMIN"."RMAITEM" ("ITEMSPC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAITEM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000748" ON "DB2ADMIN"."RMAITEM" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAITEM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000749" ON "DB2ADMIN"."RMAITEM" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAITEM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001282" ON "DB2ADMIN"."RMAITEM" ("RTNREASON_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RMAITEMCMP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RMAITEMCMP" (
    "RMAITEMCMP_ID" BIGINT NOT NULL,
    "RMAITEM_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT,
    "ITEMSPC_ID" BIGINT NOT NULL,
    "QUANTITY" DOUBLE NOT NULL,
    "SHOULDRECEIVE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'Y',
    "INVQUANTITY" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RMAITEMCMP"
ALTER TABLE "DB2ADMIN"."RMAITEMCMP"
ADD PRIMARY KEY ("RMAITEMCMP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAITEMCMP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000216" ON "DB2ADMIN"."RMAITEMCMP" (
    "RMAITEM_ID" ASC,
    "RMAITEMCMP_ID" ASC,
    "SHOULDRECEIVE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAITEMCMP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I838141" ON "DB2ADMIN"."RMAITEMCMP" (
    "ITEMSPC_ID" ASC,
    "RMAITEM_ID" ASC,
    "INVQUANTITY" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAITEMCMP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000750" ON "DB2ADMIN"."RMAITEMCMP" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RMAITEMSERIAL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RMAITEMSERIAL" (
    "RMAITEMSERIAL_ID" BIGINT NOT NULL,
    "RMAITEM_ID" BIGINT NOT NULL,
    "RMAITEMCMP_ID" BIGINT,
    "SERIALNUMBER" VARCHAR(128 OCTETS),
    "QUANTITY" DOUBLE NOT NULL,
    "RECEIVEDQUANTITY" DOUBLE NOT NULL,
    "CREATION_TIMESTAMP" TIMESTAMP NOT NULL,
    "LASTUPDATE" TIMESTAMP NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RMAITEMSERIAL"
ALTER TABLE "DB2ADMIN"."RMAITEMSERIAL"
ADD PRIMARY KEY ("RMAITEMSERIAL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAITEMSERIAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000976" ON "DB2ADMIN"."RMAITEMSERIAL" ("RMAITEM_ID" ASC, "RMAITEMCMP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAITEMSERIAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000977" ON "DB2ADMIN"."RMAITEMSERIAL" ("SERIALNUMBER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMAITEMSERIAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001283" ON "DB2ADMIN"."RMAITEMSERIAL" ("RMAITEMCMP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RMATAX"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RMATAX" (
    "RMA_ID" BIGINT NOT NULL,
    "TAXCGRY_ID" INTEGER NOT NULL,
    "TAXAMOUNT" DECIMAL(20, 5) NOT NULL,
    "LASTUPDATE" TIMESTAMP NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RMATAX"
ALTER TABLE "DB2ADMIN"."RMATAX"
ADD PRIMARY KEY ("RMA_ID", "TAXCGRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RMATAX"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000751" ON "DB2ADMIN"."RMATAX" ("TAXCGRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ROLE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ROLE" (
    "ROLE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(4000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ROLE"
ALTER TABLE "DB2ADMIN"."ROLE"
ADD PRIMARY KEY ("ROLE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ROLE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000217" ON "DB2ADMIN"."ROLE" ("NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ROLEASNPRM"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ROLEASNPRM" (
    "ROLEASNPRM_ID" INTEGER NOT NULL,
    "ASSIGNING_ROLE_ID" INTEGER NOT NULL,
    "ORGENTITY_ID" BIGINT NOT NULL,
    "ASSIGNABLE_ROLE_ID" INTEGER,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ROLEASNPRM"
ALTER TABLE "DB2ADMIN"."ROLEASNPRM"
ADD PRIMARY KEY ("ROLEASNPRM_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ROLEASNPRM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000967" ON "DB2ADMIN"."ROLEASNPRM" (
    "ASSIGNING_ROLE_ID" ASC,
    "ORGENTITY_ID" ASC,
    "ASSIGNABLE_ROLE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."ROLEASNPRM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001284" ON "DB2ADMIN"."ROLEASNPRM" ("ORGENTITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ROLEDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ROLEDESC" (
    "ROLE_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(4000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ROLEDESC"
ALTER TABLE "DB2ADMIN"."ROLEDESC"
ADD PRIMARY KEY ("ROLE_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RTNDNYDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RTNDNYDESC" (
    "RTNDNYRSN_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(384 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RTNDNYDESC"
ALTER TABLE "DB2ADMIN"."RTNDNYDESC"
ADD PRIMARY KEY ("RTNDNYRSN_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RTNDNYRSN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RTNDNYRSN" (
    "RTNDNYRSN_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "CODE" CHAR(10 OCTETS) NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RTNDNYRSN"
ALTER TABLE "DB2ADMIN"."RTNDNYRSN"
ADD PRIMARY KEY ("RTNDNYRSN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RTNDNYRSN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000218" ON "DB2ADMIN"."RTNDNYRSN" ("STOREENT_ID" ASC, "CODE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RTNDSPCODE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RTNDSPCODE" (
    "RTNDSPCODE_ID" INTEGER NOT NULL,
    "RETURNTOINVENTORY" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'Y',
    "STOREENT_ID" INTEGER NOT NULL,
    "CODE" CHAR(10 OCTETS) NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RTNDSPCODE"
ALTER TABLE "DB2ADMIN"."RTNDSPCODE"
ADD PRIMARY KEY ("RTNDSPCODE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RTNDSPCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000219" ON "DB2ADMIN"."RTNDSPCODE" ("CODE" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RTNDSPCODE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000752" ON "DB2ADMIN"."RTNDSPCODE" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RTNDSPDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RTNDSPDESC" (
    "RTNDSPCODE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "LANGUAGE_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RTNDSPDESC"
ALTER TABLE "DB2ADMIN"."RTNDSPDESC"
ADD PRIMARY KEY ("RTNDSPCODE_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RTNRCPTDSP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RTNRCPTDSP" (
    "RTNDSPCODE_ID" INTEGER NOT NULL,
    "RTNRECEIPT_ID" BIGINT NOT NULL,
    "RTNRCPTDSP_ID" BIGINT NOT NULL,
    "RTNREASON_ID" INTEGER,
    "QUANTITY" INTEGER NOT NULL,
    "DISPOSITIONDATE" TIMESTAMP NOT NULL,
    "COMMENTS" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RTNRCPTDSP"
ALTER TABLE "DB2ADMIN"."RTNRCPTDSP"
ADD PRIMARY KEY ("RTNRCPTDSP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RTNRCPTDSP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000220" ON "DB2ADMIN"."RTNRCPTDSP" ("RTNRECEIPT_ID" ASC, "RTNRCPTDSP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RTNRCPTDSP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001285" ON "DB2ADMIN"."RTNRCPTDSP" ("RTNDSPCODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RTNRCPTDSP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001286" ON "DB2ADMIN"."RTNRCPTDSP" ("RTNREASON_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RTNREASON"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RTNREASON" (
    "REASONTYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'B',
    "RTNREASON_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "MARKFORDELETE" INTEGER NOT NULL WITH DEFAULT 0,
    "CODE" CHAR(30 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RTNREASON"
ALTER TABLE "DB2ADMIN"."RTNREASON"
ADD PRIMARY KEY ("RTNREASON_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RTNREASON"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000221" ON "DB2ADMIN"."RTNREASON" ("CODE" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RTNREASON"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000753" ON "DB2ADMIN"."RTNREASON" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RTNRECEIPT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RTNRECEIPT" (
    "RTNRECEIPT_ID" BIGINT NOT NULL,
    "RMA_ID" BIGINT NOT NULL,
    "VERSIONSPC_ID" BIGINT NOT NULL,
    "RMAITEMCMP_ID" BIGINT NOT NULL,
    "LASTUPDATE" TIMESTAMP NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "DATERECEIVED" TIMESTAMP NOT NULL,
    "DISPOSITIONEDQTY" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RTNRECEIPT"
ALTER TABLE "DB2ADMIN"."RTNRECEIPT"
ADD PRIMARY KEY ("RTNRECEIPT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RTNRECEIPT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000222" ON "DB2ADMIN"."RTNRECEIPT" (
    "RMAITEMCMP_ID" ASC,
    "RTNRECEIPT_ID" ASC,
    "DATERECEIVED" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RTNRECEIPT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000754" ON "DB2ADMIN"."RTNRECEIPT" ("VERSIONSPC_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RTNRECEIPT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000755" ON "DB2ADMIN"."RTNRECEIPT" ("RMA_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RTNRSNDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RTNRSNDESC" (
    "RTNREASON_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RTNRSNDESC"
ALTER TABLE "DB2ADMIN"."RTNRSNDESC"
ADD PRIMARY KEY ("RTNREASON_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RULECLSREG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RULECLSREG" (
    "RULECLASS_ID" BIGINT NOT NULL,
    "RULETYPE" CHAR(4 OCTETS) NOT NULL,
    "OWNER_ID" BIGINT,
    "NAME" VARCHAR(140 OCTETS),
    "CLASSNAME" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RULECLSREG"
ALTER TABLE "DB2ADMIN"."RULECLSREG"
ADD PRIMARY KEY ("RULECLASS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."RULECLSREG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000223" ON "DB2ADMIN"."RULECLSREG" ("RULETYPE" ASC, "OWNER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RULECLSREG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000224" ON "DB2ADMIN"."RULECLSREG" ("NAME" ASC, "OWNER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."RULECLSREG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000756" ON "DB2ADMIN"."RULECLSREG" ("OWNER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."RULEVALUE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."RULEVALUE" (
    "RULEVALUE_ID" INTEGER NOT NULL,
    "WORKINGPUBLISHABLE" INTEGER NOT NULL,
    "COMMITTEDPATH" VARCHAR(1024 OCTETS),
    "WORKINGPATH" VARCHAR(1024 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."RULEVALUE"
ALTER TABLE "DB2ADMIN"."RULEVALUE"
ADD PRIMARY KEY ("RULEVALUE_ID");
---