CREATE TABLE "DB2ADMIN"."XORDERATTR" (
    "XORDERATTR_ID" BIGINT NOT NULL,
    "ORDERS_ID" BIGINT NOT NULL,
    "ATTRTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "VALUE" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."XORDERATTR"
ALTER TABLE "DB2ADMIN"."XORDERATTR"
ADD CONSTRAINT "XORDERATTR_PK" PRIMARY KEY ("XORDERATTR_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."XORDERATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IXORDERATTR01" ON "DB2ADMIN"."XORDERATTR" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."XORDERATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IXORDERATTR02" ON "DB2ADMIN"."XORDERATTR" ("ATTRTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."XORDERATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IXORDERATTR03" ON "DB2ADMIN"."XORDERATTR" ("NAME" ASC, "VALUE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."XSTOREFFMCATREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."XSTOREFFMCATREL" (
    "XSTOREFFMCATREL_ID" INTEGER NOT NULL,
    "STORE_ID" INTEGER NOT NULL,
    "CATALOG_ID" INTEGER NOT NULL,
    "FFMCENTER_ID" INTEGER NOT NULL,
    "FFMCLASS" CHAR(1 OCTETS) NOT NULL,
    "FFMEXTID" VARCHAR(20 OCTETS),
    "MARKFORDELETE" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."XSTOREFFMCATREL"
ALTER TABLE "DB2ADMIN"."XSTOREFFMCATREL"
ADD CONSTRAINT "CC1332372305035" PRIMARY KEY ("XSTOREFFMCATREL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."XSTOREFFMCATREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IXSTOREFFM01" ON "DB2ADMIN"."XSTOREFFMCATREL" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."XSTOREFFMCATREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IXSTOREFFM02" ON "DB2ADMIN"."XSTOREFFMCATREL" ("CATALOG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."XSTOREFFMCATREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IXSTOREFFM03" ON "DB2ADMIN"."XSTOREFFMCATREL" ("FFMCENTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPLAIN_INSTANCE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPLAIN_INSTANCE" (
    "EXPLAIN_REQUESTER" VARCHAR(128 OCTETS) NOT NULL,
    "EXPLAIN_TIME" TIMESTAMP NOT NULL,
    "SOURCE_NAME" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_SCHEMA" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_VERSION" VARCHAR(64 OCTETS) NOT NULL,
    "EXPLAIN_OPTION" CHAR(1 OCTETS) NOT NULL,
    "SNAPSHOT_TAKEN" CHAR(1 OCTETS) NOT NULL,
    "DB2_VERSION" CHAR(7 OCTETS) NOT NULL,
    "SQL_TYPE" CHAR(1 OCTETS) NOT NULL,
    "QUERYOPT" INTEGER NOT NULL,
    "BLOCK" CHAR(1 OCTETS) NOT NULL,
    "ISOLATION" CHAR(2 OCTETS) NOT NULL,
    "BUFFPAGE" INTEGER NOT NULL,
    "AVG_APPLS" INTEGER NOT NULL,
    "SORTHEAP" INTEGER NOT NULL,
    "LOCKLIST" INTEGER NOT NULL,
    "MAXLOCKS" SMALLINT NOT NULL,
    "LOCKS_AVAIL" INTEGER NOT NULL,
    "CPU_SPEED" DOUBLE NOT NULL,
    "REMARKS" VARCHAR(254 OCTETS),
    "DBHEAP" INTEGER NOT NULL,
    "COMM_SPEED" DOUBLE NOT NULL,
    "PARALLELISM" CHAR(2 OCTETS) NOT NULL,
    "DATAJOINER" CHAR(1 OCTETS) NOT NULL
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EXPLAIN_INSTANCE"
ALTER TABLE "DB2ADMIN"."EXPLAIN_INSTANCE"
ADD PRIMARY KEY (
        "EXPLAIN_REQUESTER",
        "EXPLAIN_TIME",
        "SOURCE_NAME",
        "SOURCE_SCHEMA",
        "SOURCE_VERSION"
    );
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPLAIN_STATEMENT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPLAIN_STATEMENT" (
    "EXPLAIN_REQUESTER" VARCHAR(128 OCTETS) NOT NULL,
    "EXPLAIN_TIME" TIMESTAMP NOT NULL,
    "SOURCE_NAME" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_SCHEMA" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_VERSION" VARCHAR(64 OCTETS) NOT NULL,
    "EXPLAIN_LEVEL" CHAR(1 OCTETS) NOT NULL,
    "STMTNO" INTEGER NOT NULL,
    "SECTNO" INTEGER NOT NULL,
    "QUERYNO" INTEGER NOT NULL,
    "QUERYTAG" CHAR(20 OCTETS) NOT NULL,
    "STATEMENT_TYPE" CHAR(2 OCTETS) NOT NULL,
    "UPDATABLE" CHAR(1 OCTETS) NOT NULL,
    "DELETABLE" CHAR(1 OCTETS) NOT NULL,
    "TOTAL_COST" DOUBLE NOT NULL,
    "STATEMENT_TEXT" CLOB(2097152 OCTETS) NOT LOGGED NOT COMPACT NOT NULL,
    "SNAPSHOT" BLOB(10485760) NOT LOGGED NOT COMPACT,
    "QUERY_DEGREE" INTEGER NOT NULL
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EXPLAIN_STATEMENT"
ALTER TABLE "DB2ADMIN"."EXPLAIN_STATEMENT"
ADD PRIMARY KEY (
        "EXPLAIN_REQUESTER",
        "EXPLAIN_TIME",
        "SOURCE_NAME",
        "SOURCE_SCHEMA",
        "SOURCE_VERSION",
        "EXPLAIN_LEVEL",
        "STMTNO",
        "SECTNO"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXPLAIN_STATEMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."STMT_I1" ON "DB2ADMIN"."EXPLAIN_STATEMENT" (
    "EXPLAIN_TIME" ASC,
    "EXPLAIN_LEVEL" ASC,
    "STMTNO" ASC,
    "SECTNO" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPLAIN_ARGUMENT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPLAIN_ARGUMENT" (
    "EXPLAIN_REQUESTER" VARCHAR(128 OCTETS) NOT NULL,
    "EXPLAIN_TIME" TIMESTAMP NOT NULL,
    "SOURCE_NAME" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_SCHEMA" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_VERSION" VARCHAR(64 OCTETS) NOT NULL,
    "EXPLAIN_LEVEL" CHAR(1 OCTETS) NOT NULL,
    "STMTNO" INTEGER NOT NULL,
    "SECTNO" INTEGER NOT NULL,
    "OPERATOR_ID" INTEGER NOT NULL,
    "ARGUMENT_TYPE" CHAR(8 OCTETS) NOT NULL,
    "ARGUMENT_VALUE" VARCHAR(1024 OCTETS),
    "LONG_ARGUMENT_VALUE" CLOB(2097152 OCTETS) NOT LOGGED NOT COMPACT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXPLAIN_ARGUMENT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."ARG_I1" ON "DB2ADMIN"."EXPLAIN_ARGUMENT" (
    "EXPLAIN_TIME" ASC,
    "EXPLAIN_LEVEL" ASC,
    "STMTNO" ASC,
    "SECTNO" ASC,
    "OPERATOR_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPLAIN_OBJECT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPLAIN_OBJECT" (
    "EXPLAIN_REQUESTER" VARCHAR(128 OCTETS) NOT NULL,
    "EXPLAIN_TIME" TIMESTAMP NOT NULL,
    "SOURCE_NAME" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_SCHEMA" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_VERSION" VARCHAR(64 OCTETS) NOT NULL,
    "EXPLAIN_LEVEL" CHAR(1 OCTETS) NOT NULL,
    "STMTNO" INTEGER NOT NULL,
    "SECTNO" INTEGER NOT NULL,
    "OBJECT_SCHEMA" VARCHAR(128 OCTETS) NOT NULL,
    "OBJECT_NAME" VARCHAR(128 OCTETS) NOT NULL,
    "OBJECT_TYPE" CHAR(2 OCTETS) NOT NULL,
    "CREATE_TIME" TIMESTAMP,
    "STATISTICS_TIME" TIMESTAMP,
    "COLUMN_COUNT" SMALLINT NOT NULL,
    "ROW_COUNT" BIGINT NOT NULL,
    "WIDTH" INTEGER NOT NULL,
    "PAGES" BIGINT NOT NULL,
    "DISTINCT" CHAR(1 OCTETS) NOT NULL,
    "TABLESPACE_NAME" VARCHAR(128 OCTETS),
    "OVERHEAD" DOUBLE NOT NULL,
    "TRANSFER_RATE" DOUBLE NOT NULL,
    "PREFETCHSIZE" INTEGER NOT NULL,
    "EXTENTSIZE" INTEGER NOT NULL,
    "CLUSTER" DOUBLE NOT NULL,
    "NLEAF" BIGINT NOT NULL,
    "NLEVELS" INTEGER NOT NULL,
    "FULLKEYCARD" BIGINT NOT NULL,
    "OVERFLOW" BIGINT NOT NULL,
    "FIRSTKEYCARD" BIGINT NOT NULL,
    "FIRST2KEYCARD" BIGINT NOT NULL,
    "FIRST3KEYCARD" BIGINT NOT NULL,
    "FIRST4KEYCARD" BIGINT NOT NULL,
    "SEQUENTIAL_PAGES" BIGINT NOT NULL,
    "DENSITY" INTEGER NOT NULL,
    "STATS_SRC" CHAR(1 OCTETS) NOT NULL,
    "AVERAGE_SEQUENCE_GAP" DOUBLE NOT NULL,
    "AVERAGE_SEQUENCE_FETCH_GAP" DOUBLE NOT NULL,
    "AVERAGE_SEQUENCE_PAGES" DOUBLE NOT NULL,
    "AVERAGE_SEQUENCE_FETCH_PAGES" DOUBLE NOT NULL,
    "AVERAGE_RANDOM_PAGES" DOUBLE NOT NULL,
    "AVERAGE_RANDOM_FETCH_PAGES" DOUBLE NOT NULL,
    "NUMRIDS" BIGINT NOT NULL,
    "NUMRIDS_DELETED" BIGINT NOT NULL,
    "NUM_EMPTY_LEAFS" BIGINT NOT NULL,
    "ACTIVE_BLOCKS" BIGINT NOT NULL,
    "NUM_DATA_PARTS" INTEGER NOT NULL
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXPLAIN_OBJECT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."OBJ_I1" ON "DB2ADMIN"."EXPLAIN_OBJECT" (
    "EXPLAIN_TIME" ASC,
    "EXPLAIN_LEVEL" ASC,
    "STMTNO" ASC,
    "SECTNO" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPLAIN_OPERATOR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPLAIN_OPERATOR" (
    "EXPLAIN_REQUESTER" VARCHAR(128 OCTETS) NOT NULL,
    "EXPLAIN_TIME" TIMESTAMP NOT NULL,
    "SOURCE_NAME" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_SCHEMA" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_VERSION" VARCHAR(64 OCTETS) NOT NULL,
    "EXPLAIN_LEVEL" CHAR(1 OCTETS) NOT NULL,
    "STMTNO" INTEGER NOT NULL,
    "SECTNO" INTEGER NOT NULL,
    "OPERATOR_ID" INTEGER NOT NULL,
    "OPERATOR_TYPE" CHAR(6 OCTETS) NOT NULL,
    "TOTAL_COST" DOUBLE NOT NULL,
    "IO_COST" DOUBLE NOT NULL,
    "CPU_COST" DOUBLE NOT NULL,
    "FIRST_ROW_COST" DOUBLE NOT NULL,
    "RE_TOTAL_COST" DOUBLE NOT NULL,
    "RE_IO_COST" DOUBLE NOT NULL,
    "RE_CPU_COST" DOUBLE NOT NULL,
    "COMM_COST" DOUBLE NOT NULL,
    "FIRST_COMM_COST" DOUBLE NOT NULL,
    "BUFFERS" DOUBLE NOT NULL,
    "REMOTE_TOTAL_COST" DOUBLE NOT NULL,
    "REMOTE_COMM_COST" DOUBLE NOT NULL
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXPLAIN_OPERATOR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."OPR_I1" ON "DB2ADMIN"."EXPLAIN_OPERATOR" (
    "EXPLAIN_TIME" ASC,
    "EXPLAIN_LEVEL" ASC,
    "STMTNO" ASC,
    "SECTNO" ASC,
    "OPERATOR_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPLAIN_PREDICATE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPLAIN_PREDICATE" (
    "EXPLAIN_REQUESTER" VARCHAR(128 OCTETS) NOT NULL,
    "EXPLAIN_TIME" TIMESTAMP NOT NULL,
    "SOURCE_NAME" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_SCHEMA" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_VERSION" VARCHAR(64 OCTETS) NOT NULL,
    "EXPLAIN_LEVEL" CHAR(1 OCTETS) NOT NULL,
    "STMTNO" INTEGER NOT NULL,
    "SECTNO" INTEGER NOT NULL,
    "OPERATOR_ID" INTEGER NOT NULL,
    "PREDICATE_ID" INTEGER NOT NULL,
    "HOW_APPLIED" CHAR(10 OCTETS) NOT NULL,
    "WHEN_EVALUATED" CHAR(3 OCTETS) NOT NULL,
    "RELOP_TYPE" CHAR(2 OCTETS) NOT NULL,
    "SUBQUERY" CHAR(1 OCTETS) NOT NULL,
    "FILTER_FACTOR" DOUBLE NOT NULL,
    "PREDICATE_TEXT" CLOB(2097152 OCTETS) NOT LOGGED NOT COMPACT,
    "RANGE_NUM" INTEGER
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXPLAIN_PREDICATE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."PRD_I1" ON "DB2ADMIN"."EXPLAIN_PREDICATE" (
    "EXPLAIN_TIME" ASC,
    "EXPLAIN_LEVEL" ASC,
    "STMTNO" ASC,
    "SECTNO" ASC,
    "OPERATOR_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPLAIN_STREAM"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPLAIN_STREAM" (
    "EXPLAIN_REQUESTER" VARCHAR(128 OCTETS) NOT NULL,
    "EXPLAIN_TIME" TIMESTAMP NOT NULL,
    "SOURCE_NAME" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_SCHEMA" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_VERSION" VARCHAR(64 OCTETS) NOT NULL,
    "EXPLAIN_LEVEL" CHAR(1 OCTETS) NOT NULL,
    "STMTNO" INTEGER NOT NULL,
    "SECTNO" INTEGER NOT NULL,
    "STREAM_ID" INTEGER NOT NULL,
    "SOURCE_TYPE" CHAR(1 OCTETS) NOT NULL,
    "SOURCE_ID" INTEGER NOT NULL,
    "TARGET_TYPE" CHAR(1 OCTETS) NOT NULL,
    "TARGET_ID" INTEGER NOT NULL,
    "OBJECT_SCHEMA" VARCHAR(128 OCTETS),
    "OBJECT_NAME" VARCHAR(128 OCTETS),
    "STREAM_COUNT" DOUBLE NOT NULL,
    "COLUMN_COUNT" SMALLINT NOT NULL,
    "PREDICATE_ID" INTEGER NOT NULL,
    "COLUMN_NAMES" CLOB(2097152 OCTETS) NOT LOGGED NOT COMPACT,
    "PMID" SMALLINT NOT NULL,
    "SINGLE_NODE" CHAR(5 OCTETS),
    "PARTITION_COLUMNS" CLOB(2097152 OCTETS) NOT LOGGED NOT COMPACT,
    "SEQUENCE_SIZES" CLOB(2097152 OCTETS) NOT LOGGED NOT COMPACT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXPLAIN_STREAM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."STM_I1" ON "DB2ADMIN"."EXPLAIN_STREAM" (
    "EXPLAIN_TIME" ASC,
    "EXPLAIN_LEVEL" ASC,
    "STMTNO" ASC,
    "SECTNO" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPLAIN_DIAGNOSTIC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPLAIN_DIAGNOSTIC" (
    "EXPLAIN_REQUESTER" VARCHAR(128 OCTETS) NOT NULL,
    "EXPLAIN_TIME" TIMESTAMP NOT NULL,
    "SOURCE_NAME" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_SCHEMA" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_VERSION" VARCHAR(64 OCTETS) NOT NULL,
    "EXPLAIN_LEVEL" CHAR(1 OCTETS) NOT NULL,
    "STMTNO" INTEGER NOT NULL,
    "SECTNO" INTEGER NOT NULL,
    "DIAGNOSTIC_ID" INTEGER NOT NULL,
    "CODE" INTEGER NOT NULL
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EXPLAIN_DIAGNOSTIC"
ALTER TABLE "DB2ADMIN"."EXPLAIN_DIAGNOSTIC"
ADD PRIMARY KEY (
        "EXPLAIN_REQUESTER",
        "EXPLAIN_TIME",
        "SOURCE_NAME",
        "SOURCE_SCHEMA",
        "SOURCE_VERSION",
        "EXPLAIN_LEVEL",
        "STMTNO",
        "SECTNO",
        "DIAGNOSTIC_ID"
    );
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPLAIN_DIAGNOSTIC_DATA"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPLAIN_DIAGNOSTIC_DATA" (
    "EXPLAIN_REQUESTER" VARCHAR(128 OCTETS) NOT NULL,
    "EXPLAIN_TIME" TIMESTAMP NOT NULL,
    "SOURCE_NAME" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_SCHEMA" VARCHAR(128 OCTETS) NOT NULL,
    "SOURCE_VERSION" VARCHAR(64 OCTETS) NOT NULL,
    "EXPLAIN_LEVEL" CHAR(1 OCTETS) NOT NULL,
    "STMTNO" INTEGER NOT NULL,
    "SECTNO" INTEGER NOT NULL,
    "DIAGNOSTIC_ID" INTEGER NOT NULL,
    "ORDINAL" INTEGER NOT NULL,
    "TOKEN" VARCHAR(1000 OCTETS),
    "TOKEN_LONG" BLOB(3145728) NOT LOGGED NOT COMPACT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXPLAIN_DIAGNOSTIC_DATA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."EXP_DIAG_DAT_I1" ON "DB2ADMIN"."EXPLAIN_DIAGNOSTIC_DATA" (
    "EXPLAIN_TIME" ASC,
    "EXPLAIN_LEVEL" ASC,
    "STMTNO" ASC,
    "SECTNO" ASC,
    "DIAGNOSTIC_ID" ASC,
    "ORDINAL" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PREVIEWTOKEN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PREVIEWTOKEN" (
    "PREVIEWTOKEN_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "USERS_ID" BIGINT NOT NULL,
    "STARTDATE" TIMESTAMP NOT NULL,
    "ENDDATE" TIMESTAMP NOT NULL,
    "STATUS" CHAR(1 OCTETS) NOT NULL,
    "PASSWORD" VARCHAR(256 OCTETS),
    "SALT" VARCHAR(256 OCTETS),
    "CTXDATA" VARCHAR(4000 OCTETS),
    "PROPERTIES" VARCHAR(1024 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PREVIEWTOKEN"
ALTER TABLE "DB2ADMIN"."PREVIEWTOKEN"
ADD CONSTRAINT "P_0028" PRIMARY KEY ("PREVIEWTOKEN_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PREVIEWTOKEN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001506" ON "DB2ADMIN"."PREVIEWTOKEN" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PREVIEWTOKEN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001507" ON "DB2ADMIN"."PREVIEWTOKEN" ("ENDDATE" ASC, "STATUS" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."ORDAUDIT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."ORDAUDIT" (
    "ORDERS_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "LINECOUNT" BIGINT NOT NULL,
    "TIMEPLACED" TIMESTAMP NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."ORDAUDIT"
ALTER TABLE "DB2ADMIN"."ORDAUDIT"
ADD CONSTRAINT "P_0032" PRIMARY KEY ("ORDERS_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."ORDAUDIT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001522" ON "DB2ADMIN"."ORDAUDIT" ("TIMEPLACED" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."STOREDEFCAT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."STOREDEFCAT" (
    "STOREDEFCAT_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "CATALOG_ID" BIGINT NOT NULL,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(256 OCTETS),
    "FIELD3" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."STOREDEFCAT"
ALTER TABLE "DB2ADMIN"."STOREDEFCAT"
ADD CONSTRAINT "P_0001" PRIMARY KEY ("STOREDEFCAT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."STOREDEFCAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001439" ON "DB2ADMIN"."STOREDEFCAT" ("STOREENT_ID" ASC, "CATALOG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."STOREDEFCAT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001440" ON "DB2ADMIN"."STOREDEFCAT" ("CATALOG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PAGELAYOUTTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PAGELAYOUTTYPE" (
    "PAGELAYOUTTYPE_ID" VARCHAR(32 OCTETS) NOT NULL,
    "ISSTATIC" SMALLINT NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PAGELAYOUTTYPE"
ALTER TABLE "DB2ADMIN"."PAGELAYOUTTYPE"
ADD CONSTRAINT "P_0003" PRIMARY KEY ("PAGELAYOUTTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."STOREPLTYPES"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."STOREPLTYPES" (
    "PAGELAYOUTTYPE_ID" VARCHAR(32 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "VIEWNAME" VARCHAR(256 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."STOREPLTYPES"
ALTER TABLE "DB2ADMIN"."STOREPLTYPES"
ADD CONSTRAINT "P_0004" PRIMARY KEY ("PAGELAYOUTTYPE_ID", "STOREENT_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PAGELAYOUT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PAGELAYOUT" (
    "PAGELAYOUT_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(256 OCTETS) NOT NULL,
    "VIEWNAME" VARCHAR(256 OCTETS),
    "MEMBER_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "PAGELAYOUTTYPE_ID" VARCHAR(32 OCTETS),
    "DESCRIPTION" VARCHAR(1024 OCTETS),
    "THUMBNAIL" VARCHAR(256 OCTETS),
    "FULLIMAGE" VARCHAR(256 OCTETS),
    "MASTERCSS" VARCHAR(256 OCTETS),
    "DEVICETYPE" VARCHAR(64 OCTETS) NOT NULL,
    "STATE" SMALLINT NOT NULL WITH DEFAULT 1,
    "ISTEMPLATE" SMALLINT NOT NULL WITH DEFAULT 0,
    "CREATEDATE" TIMESTAMP,
    "LASTUPDATE" TIMESTAMP,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(256 OCTETS),
    "FIELD3" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "UP_NAME" VARCHAR(256 OCTETS) GENERATED ALWAYS AS (UPPER(NAME)),
    "ISDEFAULT" SMALLINT NOT NULL WITH DEFAULT 0,
    "STARTDATE" TIMESTAMP,
    "ENDDATE" TIMESTAMP,
    "PRIORITY" SMALLINT NOT NULL WITH DEFAULT 0,
    "MANAGINGTOOL" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PAGELAYOUT"
ALTER TABLE "DB2ADMIN"."PAGELAYOUT"
ADD CONSTRAINT "P_0005" PRIMARY KEY ("PAGELAYOUT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PAGELAYOUT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001445" ON "DB2ADMIN"."PAGELAYOUT" ("STOREENT_ID" ASC, "PAGELAYOUTTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PAGELAYOUT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00030" ON "DB2ADMIN"."PAGELAYOUT" ("UP_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PAGELAYOUT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001443" ON "DB2ADMIN"."PAGELAYOUT" (
    "NAME" ASC,
    "MEMBER_ID" ASC,
    "MANAGINGTOOL" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PAGELAYOUT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001444" ON "DB2ADMIN"."PAGELAYOUT" (
    "NAME" ASC,
    "STOREENT_ID" ASC,
    "MANAGINGTOOL" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATENTDESCOVR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATENTDESCOVR" (
    "CATENTDESCOVR_ID" BIGINT NOT NULL,
    "CATENTRY_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "CATOVRGRP_ID" BIGINT NOT NULL,
    "NAME" CHAR(128 OCTETS),
    "SHORTDESCRIPTION" VARCHAR(254 OCTETS),
    "LONGDESCRIPTION" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "THUMBNAIL" VARCHAR(254 OCTETS),
    "AUXDESCRIPTION1" VARCHAR(4000 OCTETS),
    "FULLIMAGE" VARCHAR(254 OCTETS),
    "AUXDESCRIPTION2" VARCHAR(4000 OCTETS),
    "PUBLISHED" INTEGER,
    "KEYWORD" VARCHAR(254 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(254 OCTETS),
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "UP_NAME" VARCHAR(128 OCTETS) GENERATED ALWAYS AS (UPPER(NAME))
) IN "TAB16K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATENTDESCOVR"
ALTER TABLE "DB2ADMIN"."CATENTDESCOVR"
ADD CONSTRAINT "P_0006" PRIMARY KEY ("CATENTDESCOVR_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTDESCOVR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001446" ON "DB2ADMIN"."CATENTDESCOVR" (
    "CATENTRY_ID" ASC,
    "LANGUAGE_ID" ASC,
    "CATOVRGRP_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTDESCOVR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001447" ON "DB2ADMIN"."CATENTDESCOVR" ("LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTDESCOVR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001448" ON "DB2ADMIN"."CATENTDESCOVR" ("CATOVRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTDESCOVR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001449" ON "DB2ADMIN"."CATENTDESCOVR" ("CATENTRY_ID" ASC, "CATOVRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATENTDESCOVR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00031" ON "DB2ADMIN"."CATENTDESCOVR" ("UP_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATOVRGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATOVRGRP" (
    "CATOVRGRP_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(254 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "UP_IDENTIFIER" VARCHAR(254 OCTETS) GENERATED ALWAYS AS (UPPER(IDENTIFIER))
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATOVRGRP"
ALTER TABLE "DB2ADMIN"."CATOVRGRP"
ADD CONSTRAINT "P_0007" PRIMARY KEY ("CATOVRGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATOVRGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001450" ON "DB2ADMIN"."CATOVRGRP" ("IDENTIFIER" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATOVRGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001451" ON "DB2ADMIN"."CATOVRGRP" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATOVRGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00032" ON "DB2ADMIN"."CATOVRGRP" ("UP_IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."STORECATOVRGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."STORECATOVRGRP" (
    "STOREENT_ID" INTEGER NOT NULL,
    "CATOVRGRP_ID" BIGINT NOT NULL,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."STORECATOVRGRP"
ALTER TABLE "DB2ADMIN"."STORECATOVRGRP"
ADD CONSTRAINT "P_0008" PRIMARY KEY ("CATOVRGRP_ID", "STOREENT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."STORECATOVRGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001452" ON "DB2ADMIN"."STORECATOVRGRP" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FOLDER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FOLDER" (
    "FOLDER_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "MEMBER_ID" BIGINT,
    "PARENTFOLDER_ID" BIGINT,
    "IDENTIFIER" VARCHAR(256 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(256 OCTETS),
    "TYPE" VARCHAR(128 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(256 OCTETS),
    "FIELD3" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "UP_IDENTIFIER" VARCHAR(256 OCTETS) GENERATED ALWAYS AS (UPPER(IDENTIFIER))
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FOLDER"
ALTER TABLE "DB2ADMIN"."FOLDER"
ADD CONSTRAINT "P_0009" PRIMARY KEY ("FOLDER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FOLDER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001453" ON "DB2ADMIN"."FOLDER" (
    "PARENTFOLDER_ID" ASC,
    "TYPE" ASC,
    "IDENTIFIER" ASC,
    "STOREENT_ID" ASC,
    "MEMBER_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FOLDER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001454" ON "DB2ADMIN"."FOLDER" ("STOREENT_ID" ASC, "IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FOLDER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00033" ON "DB2ADMIN"."FOLDER" ("UP_IDENTIFIER" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FOLDERITEM"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FOLDERITEM" (
    "FOLDERITEM_ID" BIGINT NOT NULL,
    "FOLDER_ID" BIGINT NOT NULL,
    "REFERENCE_ID" BIGINT NOT NULL,
    "FOLDERITEMTYPE" VARCHAR(128 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(256 OCTETS),
    "FIELD3" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FOLDERITEM"
ALTER TABLE "DB2ADMIN"."FOLDERITEM"
ADD CONSTRAINT "P_0010" PRIMARY KEY ("FOLDERITEM_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FOLDERITEM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001455" ON "DB2ADMIN"."FOLDERITEM" ("FOLDERITEMTYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FOLDERITEM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001461" ON "DB2ADMIN"."FOLDERITEM" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FOLDERITEM"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001456" ON "DB2ADMIN"."FOLDERITEM" (
    "FOLDER_ID" ASC,
    "FOLDERITEMTYPE" ASC,
    "REFERENCE_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FACET"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FACET" (
    "FACET_ID" BIGINT NOT NULL,
    "ATTR_ID" BIGINT,
    "SRCHATTR_ID" BIGINT NOT NULL,
    "SELECTION" SMALLINT NOT NULL WITH DEFAULT 0,
    "SORT_ORDER" SMALLINT NOT NULL WITH DEFAULT 0,
    "KEYWORD_SEARCH" SMALLINT NOT NULL WITH DEFAULT 1,
    "ZERO_DISPLAY" SMALLINT NOT NULL WITH DEFAULT 0,
    "STOREENT_ID" INTEGER NOT NULL,
    "MAX_DISPLAY" INTEGER NOT NULL WITH DEFAULT 20,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(256 OCTETS),
    "FIELD3" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "GROUP_ID" BIGINT WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FACET"
ALTER TABLE "DB2ADMIN"."FACET"
ADD CONSTRAINT "P_0012" PRIMARY KEY ("FACET_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FACET"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001476" ON "DB2ADMIN"."FACET" ("ATTR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FACET"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001477" ON "DB2ADMIN"."FACET" ("SRCHATTR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FACET"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001478" ON "DB2ADMIN"."FACET" ("STOREENT_ID" ASC, "KEYWORD_SEARCH" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FACETCATGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FACETCATGRP" (
    "FACETCATGRP_ID" BIGINT NOT NULL,
    "FACET_ID" BIGINT NOT NULL,
    "SEQUENCE" DOUBLE,
    "STOREENT_ID" INTEGER NOT NULL,
    "CATGROUP_ID" BIGINT NOT NULL,
    "DISPLAYABLE" SMALLINT NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FACETCATGRP"
ALTER TABLE "DB2ADMIN"."FACETCATGRP"
ADD CONSTRAINT "P_0013" PRIMARY KEY ("FACETCATGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FACETCATGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001479" ON "DB2ADMIN"."FACETCATGRP" (
    "FACET_ID" ASC,
    "CATGROUP_ID" ASC,
    "STOREENT_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FACETCATGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001480" ON "DB2ADMIN"."FACETCATGRP" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."FACETCATGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001481" ON "DB2ADMIN"."FACETCATGRP" ("CATGROUP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."FACETDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."FACETDESC" (
    "FACET_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(256 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(256 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(256 OCTETS),
    "FIELD3" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."FACETDESC"
ALTER TABLE "DB2ADMIN"."FACETDESC"
ADD CONSTRAINT "P_0014" PRIMARY KEY ("FACET_ID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."FACETDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001482" ON "DB2ADMIN"."FACETDESC" ("LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."DMEMSPOTCOLLDEF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."DMEMSPOTCOLLDEF" (
    "DMEMSPOTCOLLDEF_ID" INTEGER NOT NULL,
    "EMSPOT_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "COLLATERAL_ID" INTEGER NOT NULL,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."DMEMSPOTCOLLDEF"
ALTER TABLE "DB2ADMIN"."DMEMSPOTCOLLDEF"
ADD CONSTRAINT "P_0015" PRIMARY KEY ("DMEMSPOTCOLLDEF_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEMSPOTCOLLDEF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001483" ON "DB2ADMIN"."DMEMSPOTCOLLDEF" (
    "EMSPOT_ID" ASC,
    "STOREENT_ID" ASC,
    "COLLATERAL_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."DMEMSPOTCOLLDEF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001484" ON "DB2ADMIN"."DMEMSPOTCOLLDEF" ("COLLATERAL_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."COLLIMGMAPAREA"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."COLLIMGMAPAREA" (
    "COLLIMGMAPAREA_ID" BIGINT NOT NULL,
    "COLLATERAL_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "COORDINATES" VARCHAR(1024 OCTETS),
    "TITLE" VARCHAR(256 OCTETS),
    "ALT" VARCHAR(256 OCTETS),
    "SHAPE" VARCHAR(32 OCTETS),
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "TARGET" VARCHAR(128 OCTETS),
    "URL" VARCHAR(1024 OCTETS),
    "HTMLDEF" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "FIELD1" VARCHAR(256 OCTETS),
    "FIELD2" VARCHAR(256 OCTETS),
    "FIELD3" VARCHAR(256 OCTETS),
    "FIELD4" VARCHAR(256 OCTETS),
    "FIELD5" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "TAB16K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."COLLIMGMAPAREA"
ALTER TABLE "DB2ADMIN"."COLLIMGMAPAREA"
ADD CONSTRAINT "P_0016" PRIMARY KEY ("COLLIMGMAPAREA_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."COLLIMGMAPAREA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001485" ON "DB2ADMIN"."COLLIMGMAPAREA" (
    "COLLATERAL_ID" ASC,
    "LANGUAGE_ID" ASC,
    "COORDINATES" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."COLLIMGMAPAREA"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001486" ON "DB2ADMIN"."COLLIMGMAPAREA" ("LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."SRCHATTRDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."SRCHATTRDESC" (
    "SRCHATTR_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(256 OCTETS),
    "DESCRIPTION" VARCHAR(512 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "UP_DISPLAYNAME" VARCHAR(256 OCTETS) GENERATED ALWAYS AS (UPPER(DISPLAYNAME)),
    "UP_DESCRIPTION" VARCHAR(512 OCTETS) GENERATED ALWAYS AS (UPPER(DESCRIPTION))
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."SRCHATTRDESC"
ALTER TABLE "DB2ADMIN"."SRCHATTRDESC"
ADD CONSTRAINT "P_0017" PRIMARY KEY ("SRCHATTR_ID", "LANGUAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."SRCHATTRDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001487" ON "DB2ADMIN"."SRCHATTRDESC" ("LANGUAGE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."SRCHATTRDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00034" ON "DB2ADMIN"."SRCHATTRDESC" ("UP_DISPLAYNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."SRCHATTRDESC"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00035" ON "DB2ADMIN"."SRCHATTRDESC" ("UP_DESCRIPTION" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."SRCHPROPRELV"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."SRCHPROPRELV" (
    "SRCHPROPRELV_ID" BIGINT NOT NULL,
    "CATALOG_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "CATGROUP_ID" BIGINT NOT NULL WITH DEFAULT 0,
    "RELVALUE" DOUBLE NOT NULL WITH DEFAULT 0,
    "INDEXFIELD" VARCHAR(128 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."SRCHPROPRELV"
ALTER TABLE "DB2ADMIN"."SRCHPROPRELV"
ADD CONSTRAINT "P_0027" PRIMARY KEY ("SRCHPROPRELV_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."SRCHPROPRELV"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001498" ON "DB2ADMIN"."SRCHPROPRELV" (
    "INDEXFIELD" ASC,
    "CATGROUP_ID" ASC,
    "STOREENT_ID" ASC,
    "CATALOG_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."SRCHPROPRELV"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001499" ON "DB2ADMIN"."SRCHPROPRELV" ("CATALOG_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."SRCHPROPRELV"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001503" ON "DB2ADMIN"."SRCHPROPRELV" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."SRCHPROPRELV"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001504" ON "DB2ADMIN"."SRCHPROPRELV" (
    "CATGROUP_ID" ASC,
    "STOREENT_ID" ASC,
    "CATALOG_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLWIDGETDEF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLWIDGETDEF" (
    "PLWIDGETDEF_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "IDENTIFIER" VARCHAR(256 OCTETS) NOT NULL,
    "UI_OBJECT_NAME" VARCHAR(128 OCTETS),
    "VENDOR" VARCHAR(128 OCTETS) NOT NULL,
    "WIDGETTYPE" SMALLINT NOT NULL WITH DEFAULT 1,
    "JSPPATH" VARCHAR(512 OCTETS) NOT NULL,
    "DEFINITIONXML" CLOB(1000000 OCTETS) LOGGED NOT COMPACT NOT NULL,
    "STATE" SMALLINT NOT NULL WITH DEFAULT 0,
    "CREATEDATE" TIMESTAMP NOT NULL,
    "LASTUPDATE" TIMESTAMP NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLWIDGETDEF"
ALTER TABLE "DB2ADMIN"."PLWIDGETDEF"
ADD CONSTRAINT "P_0018" PRIMARY KEY ("PLWIDGETDEF_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLWIDGETDEF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001488" ON "DB2ADMIN"."PLWIDGETDEF" ("IDENTIFIER" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLWIDGETDEF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001511" ON "DB2ADMIN"."PLWIDGETDEF" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLWIDGETDEFDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLWIDGETDEFDESC" (
    "PLWIDGETDEF_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(256 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(1024 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLWIDGETDEFDESC"
ALTER TABLE "DB2ADMIN"."PLWIDGETDEFDESC"
ADD CONSTRAINT "P_0019" PRIMARY KEY ("PLWIDGETDEF_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLSTOREWIDGET"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLSTOREWIDGET" (
    "PLSTOREWIDGET_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "PLWIDGETDEF_ID" BIGINT NOT NULL,
    "STATE" SMALLINT NOT NULL WITH DEFAULT 1,
    "DEFINITIONXML" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLSTOREWIDGET"
ALTER TABLE "DB2ADMIN"."PLSTOREWIDGET"
ADD CONSTRAINT "P_0020" PRIMARY KEY ("PLSTOREWIDGET_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLSTOREWIDGET"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001512" ON "DB2ADMIN"."PLSTOREWIDGET" ("PLWIDGETDEF_ID" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLSTOREWIDGET"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001513" ON "DB2ADMIN"."PLSTOREWIDGET" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLWIDGET"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLWIDGET" (
    "PLWIDGET_ID" BIGINT NOT NULL,
    "PAGELAYOUT_ID" BIGINT NOT NULL,
    "PLWIDGETDEF_ID" BIGINT NOT NULL,
    "ADMINNAME" VARCHAR(256 OCTETS) NOT NULL,
    "SLOTID" VARCHAR(64 OCTETS),
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(256 OCTETS),
    "FIELD3" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLWIDGET"
ALTER TABLE "DB2ADMIN"."PLWIDGET"
ADD CONSTRAINT "P_0021" PRIMARY KEY ("PLWIDGET_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLWIDGET"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001489" ON "DB2ADMIN"."PLWIDGET" ("PAGELAYOUT_ID" ASC, "ADMINNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLWIDGET"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001514" ON "DB2ADMIN"."PLWIDGET" ("PLWIDGETDEF_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLWIDGETSLOT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLWIDGETSLOT" (
    "PLWIDGETSLOT_ID" BIGINT NOT NULL,
    "PAGELAYOUT_ID" BIGINT NOT NULL,
    "PLWIDGET_ID" BIGINT NOT NULL,
    "ADMINNAME" VARCHAR(256 OCTETS) NOT NULL,
    "SLOTID" VARCHAR(64 OCTETS) NOT NULL,
    "SLOTTYPE" SMALLINT NOT NULL WITH DEFAULT 1,
    "PROPERTIES" VARCHAR(1024 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLWIDGETSLOT"
ALTER TABLE "DB2ADMIN"."PLWIDGETSLOT"
ADD CONSTRAINT "P_0022" PRIMARY KEY ("PLWIDGETSLOT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLWIDGETSLOT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001490" ON "DB2ADMIN"."PLWIDGETSLOT" ("PAGELAYOUT_ID" ASC, "ADMINNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLWIDGETSLOT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001515" ON "DB2ADMIN"."PLWIDGETSLOT" ("PLWIDGET_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLWIDGETNVP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLWIDGETNVP" (
    "PLWIDGETNVP_ID" BIGINT NOT NULL,
    "PLWIDGET_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(256 OCTETS) NOT NULL,
    "VALUE" VARCHAR(256 OCTETS) NOT NULL,
    "PROPERTIES" VARCHAR(256 OCTETS),
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0.0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLWIDGETNVP"
ALTER TABLE "DB2ADMIN"."PLWIDGETNVP"
ADD CONSTRAINT "P_0023" PRIMARY KEY ("PLWIDGETNVP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLWIDGETNVP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001491" ON "DB2ADMIN"."PLWIDGETNVP" (
    "NAME" ASC,
    "VALUE" ASC,
    "PLWIDGET_ID" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLWIDGETNVP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001519" ON "DB2ADMIN"."PLWIDGETNVP" ("PLWIDGET_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLWIDGETREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLWIDGETREL" (
    "PLWIDGET_ID_PARENT" BIGINT,
    "PLWIDGET_ID_CHILD" BIGINT NOT NULL,
    "SEQUENCE" DOUBLE WITH DEFAULT 0.0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLWIDGETREL"
ALTER TABLE "DB2ADMIN"."PLWIDGETREL"
ADD CONSTRAINT "P_0024" PRIMARY KEY ("PLWIDGET_ID_CHILD");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLWIDGETREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001516" ON "DB2ADMIN"."PLWIDGETREL" ("PLWIDGET_ID_PARENT" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLPAGE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLPAGE" (
    "PLPAGE_ID" INTEGER NOT NULL,
    "ADMINNAME" VARCHAR(256 OCTETS) NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "PAGELAYOUTTYPE_ID" VARCHAR(32 OCTETS) NOT NULL,
    "DELETABLE" SMALLINT NOT NULL WITH DEFAULT 1,
    "ADMINNAMEEDITABLE" SMALLINT NOT NULL WITH DEFAULT 1,
    "URLCONFIGURABLE" SMALLINT NOT NULL WITH DEFAULT 1,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(256 OCTETS),
    "FIELD3" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLPAGE"
ALTER TABLE "DB2ADMIN"."PLPAGE"
ADD CONSTRAINT "P_0025" PRIMARY KEY ("PLPAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLPAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001492" ON "DB2ADMIN"."PLPAGE" ("ADMINNAME" ASC, "MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLPAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001493" ON "DB2ADMIN"."PLPAGE" ("ADMINNAME" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLPAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001494" ON "DB2ADMIN"."PLPAGE" ("STOREENT_ID" ASC, "PAGELAYOUTTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLPAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001495" ON "DB2ADMIN"."PLPAGE" ("PAGELAYOUTTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLLOCATION"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLLOCATION" (
    "PLLOCATION_ID" BIGINT NOT NULL,
    "PAGELAYOUT_ID" BIGINT NOT NULL,
    "DMACTIVITY_ID" INTEGER NOT NULL,
    "GROUPNUMBER" SMALLINT NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLLOCATION"
ALTER TABLE "DB2ADMIN"."PLLOCATION"
ADD CONSTRAINT "P_0026" PRIMARY KEY ("PLLOCATION_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLLOCATION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001496" ON "DB2ADMIN"."PLLOCATION" ("PAGELAYOUT_ID" ASC, "DMACTIVITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLLOCATION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001497" ON "DB2ADMIN"."PLLOCATION" ("DMACTIVITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."PLTEMPLATEREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."PLTEMPLATEREL" (
    "PAGELAYOUT_ID" BIGINT NOT NULL,
    "TEMPLATE_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."PLTEMPLATEREL"
ALTER TABLE "DB2ADMIN"."PLTEMPLATEREL"
ADD CONSTRAINT "P_0029" PRIMARY KEY ("PAGELAYOUT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."PLTEMPLATEREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001509" ON "DB2ADMIN"."PLTEMPLATEREL" ("TEMPLATE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."EXPRESSION"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."EXPRESSION" (
    "EXPRESSION_ID" BIGINT NOT NULL,
    "TRADING_ID" BIGINT,
    "CATFILTER_ID" BIGINT,
    "MEMBER_ID" BIGINT,
    "QUERY" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "FIELD1" BIGINT,
    "FIELD2" VARCHAR(256 OCTETS),
    "FIELD3" VARCHAR(256 OCTETS),
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."EXPRESSION"
ALTER TABLE "DB2ADMIN"."EXPRESSION"
ADD CONSTRAINT "P_0030" PRIMARY KEY ("EXPRESSION_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXPRESSION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001517" ON "DB2ADMIN"."EXPRESSION" ("TRADING_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."EXPRESSION"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001518" ON "DB2ADMIN"."EXPRESSION" ("CATFILTER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."CATGRPRULE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."CATGRPRULE" (
    "CATGROUP_ID" BIGINT NOT NULL,
    "DMACTIVITY_ID" INTEGER NOT NULL,
    "EVALTIME" TIMESTAMP,
    "SHOWAFTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "EVALUATING" SMALLINT NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."CATGRPRULE"
ALTER TABLE "DB2ADMIN"."CATGRPRULE"
ADD CONSTRAINT "P_0031" PRIMARY KEY ("CATGROUP_ID", "DMACTIVITY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."CATGRPRULE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001520" ON "DB2ADMIN"."CATGRPRULE" ("DMACTIVITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
---