---------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."LANGPAIR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."LANGPAIR" (
    "STOREENT_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "LANGUAGE_ID_ALT" INTEGER NOT NULL,
    "SEQUENCE" DOUBLE NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."LANGPAIR"
ALTER TABLE "DB2ADMIN"."LANGPAIR"
ADD PRIMARY KEY (
        "LANGUAGE_ID",
        "LANGUAGE_ID_ALT",
        "STOREENT_ID"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."LANGPAIR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000603" ON "DB2ADMIN"."LANGPAIR" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."LANGUAGE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."LANGUAGE" (
    "LANGUAGE_ID" INTEGER NOT NULL,
    "LOCALENAME" CHAR(16 OCTETS) NOT NULL,
    "LANGUAGE" CHAR(5 OCTETS),
    "COUNTRY" CHAR(5 OCTETS),
    "VARIANT" CHAR(10 OCTETS),
    "ENCODING" VARCHAR(32 OCTETS),
    "MIMECHARSET" VARCHAR(32 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."LANGUAGE"
ALTER TABLE "DB2ADMIN"."LANGUAGE"
ADD PRIMARY KEY ("LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."LANGUAGEDS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."LANGUAGEDS" (
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS) NOT NULL,
    "LANGUAGE_ID_DESC" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."LANGUAGEDS"
ALTER TABLE "DB2ADMIN"."LANGUAGEDS"
ADD PRIMARY KEY ("LANGUAGE_ID_DESC", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."LISTPRICE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."LISTPRICE" (
    "CATENTRY_ID" BIGINT NOT NULL,
    "CURRENCY" CHAR(3 OCTETS) NOT NULL,
    "LISTPRICE" DECIMAL(20, 5) NOT NULL,
    "OID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."LISTPRICE"
ALTER TABLE "DB2ADMIN"."LISTPRICE"
ADD PRIMARY KEY ("CURRENCY", "CATENTRY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."LISTPRICE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000145" ON "DB2ADMIN"."LISTPRICE" (
    "CURRENCY" ASC,
    "CATENTRY_ID" ASC,
    "LISTPRICE" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."LISTPRICE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000604" ON "DB2ADMIN"."LISTPRICE" ("CATENTRY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."LMEVENTMAP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."LMEVENTMAP" (
    "LMEVENTMAP_ID" INTEGER NOT NULL,
    "LMSETNAME" VARCHAR(64 OCTETS) NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "EXTEVENTNAME" VARCHAR(64 OCTETS) NOT NULL,
    "EXTEVENTDESC" VARCHAR(254 OCTETS),
    "LMTXTYPEID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."LMEVENTMAP"
ALTER TABLE "DB2ADMIN"."LMEVENTMAP"
ADD PRIMARY KEY ("LMEVENTMAP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."LMEVENTMAP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000146" ON "DB2ADMIN"."LMEVENTMAP" (
    "LMSETNAME" ASC,
    "STOREENT_ID" ASC,
    "EXTEVENTNAME" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."LMEVENTMAP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000310" ON "DB2ADMIN"."LMEVENTMAP" ("LMSETNAME" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."LMEVENTMAP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000605" ON "DB2ADMIN"."LMEVENTMAP" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."LMSERVER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."LMSERVER" (
    "LMSERVER_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "HOSTNAME" VARCHAR(128 OCTETS) NOT NULL,
    "PORT" INTEGER NOT NULL WITH DEFAULT 2620,
    "LMENGINENAME" VARCHAR(64 OCTETS) NOT NULL,
    "LMENGINETYPE" VARCHAR(64 OCTETS) NOT NULL,
    "LMSETNAME" VARCHAR(64 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."LMSERVER"
ALTER TABLE "DB2ADMIN"."LMSERVER"
ADD PRIMARY KEY ("LMSERVER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."LMSERVER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000147" ON "DB2ADMIN"."LMSERVER" (
    "HOSTNAME" ASC,
    "PORT" ASC,
    "LMENGINENAME" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."LMSERVER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000311" ON "DB2ADMIN"."LMSERVER" ("LMENGINETYPE" ASC, "STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."LMSERVER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000606" ON "DB2ADMIN"."LMSERVER" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."LPOPURAMT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."LPOPURAMT" (
    "ORDERS_ID" BIGINT NOT NULL,
    "SETCCURR" CHAR(3 OCTETS),
    "BUYERPO_ID" BIGINT NOT NULL,
    "AMOUNT" DECIMAL(20, 5) NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."LPOPURAMT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000607" ON "DB2ADMIN"."LPOPURAMT" ("BUYERPO_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."LPOPURAMT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000608" ON "DB2ADMIN"."LPOPURAMT" ("ORDERS_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MANIFEST"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MANIFEST" (
    "MANIFEST_ID" BIGINT NOT NULL,
    "ORDRELEASENUM" INTEGER NOT NULL,
    "WEIGHTMEASURE" CHAR(16 OCTETS),
    "SETCCURR" CHAR(3 OCTETS),
    "SHIPMODE_ID" INTEGER,
    "WEIGHT" DOUBLE,
    "MANIFESTSTATUS" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'S',
    "SHIPPINGCOSTS" DECIMAL(20, 5) NOT NULL,
    "DATESHIPPED" TIMESTAMP NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "LASTUPDATE" TIMESTAMP,
    "PACKAGEID" CHAR(20 OCTETS),
    "TRACKINGID" VARCHAR(40 OCTETS),
    "PICKUPRECORDID" CHAR(20 OCTETS),
    "ORDERS_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MANIFEST"
ALTER TABLE "DB2ADMIN"."MANIFEST"
ADD PRIMARY KEY ("MANIFEST_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MANIFEST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000364" ON "DB2ADMIN"."MANIFEST" (
    "ORDERS_ID" ASC,
    "ORDRELEASENUM" ASC,
    "MANIFESTSTATUS" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MANIFEST"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000609" ON "DB2ADMIN"."MANIFEST" ("SHIPMODE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MASSOC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MASSOC" (
    "MASSOC_ID" CHAR(32 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OID" VARCHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MASSOC"
ALTER TABLE "DB2ADMIN"."MASSOC"
ADD PRIMARY KEY ("MASSOC_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MASSOCCECE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MASSOCCECE" (
    "MASSOCCECE_ID" BIGINT NOT NULL,
    "MASSOCTYPE_ID" CHAR(32 OCTETS) NOT NULL,
    "CATENTRY_ID_FROM" BIGINT NOT NULL,
    "RANK" DECIMAL(20, 5),
    "CATENTRY_ID_TO" BIGINT NOT NULL,
    "MASSOC_ID" CHAR(32 OCTETS) NOT NULL,
    "QUANTITY" DOUBLE,
    "RULE" VARCHAR(254 OCTETS),
    "GROUPNAME" VARCHAR(254 OCTETS),
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" INTEGER,
    "FIELD3" DECIMAL(20, 5),
    "OID" VARCHAR(64 OCTETS),
    "DATE1" TIMESTAMP,
    "STORE_ID" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MASSOCCECE"
ALTER TABLE "DB2ADMIN"."MASSOCCECE"
ADD PRIMARY KEY ("MASSOCCECE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MASSOCCECE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000148" ON "DB2ADMIN"."MASSOCCECE" (
    "STORE_ID" ASC,
    "MASSOCTYPE_ID" ASC,
    "MASSOC_ID" ASC,
    "CATENTRY_ID_FROM" ASC,
    "CATENTRY_ID_TO" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MASSOCCECE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000370" ON "DB2ADMIN"."MASSOCCECE" ("CATENTRY_ID_FROM" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MASSOCCECE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000610" ON "DB2ADMIN"."MASSOCCECE" ("CATENTRY_ID_TO" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MASSOCGPGP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MASSOCGPGP" (
    "MASSOCGPGP_ID" BIGINT NOT NULL,
    "CATGROUP_ID_TO" BIGINT NOT NULL,
    "CATGROUP_ID_FROM" BIGINT NOT NULL,
    "MASSOCTYPE_ID" CHAR(32 OCTETS) NOT NULL,
    "RANK" DECIMAL(20, 5),
    "MASSOC_ID" CHAR(32 OCTETS) NOT NULL,
    "QUANTITY" DOUBLE,
    "RULE" CHAR(254 OCTETS),
    "GROUPNAME" VARCHAR(254 OCTETS),
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" INTEGER,
    "FIELD3" DECIMAL(20, 5),
    "OID" VARCHAR(64 OCTETS),
    "DATE1" TIMESTAMP,
    "STORE_ID" INTEGER NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MASSOCGPGP"
ALTER TABLE "DB2ADMIN"."MASSOCGPGP"
ADD PRIMARY KEY ("MASSOCGPGP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MASSOCGPGP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000149" ON "DB2ADMIN"."MASSOCGPGP" (
    "STORE_ID" ASC,
    "MASSOCTYPE_ID" ASC,
    "MASSOC_ID" ASC,
    "CATGROUP_ID_FROM" ASC,
    "CATGROUP_ID_TO" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MASSOCGPGP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000611" ON "DB2ADMIN"."MASSOCGPGP" ("CATGROUP_ID_FROM" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MASSOCGPGP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000612" ON "DB2ADMIN"."MASSOCGPGP" ("CATGROUP_ID_TO" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MASSOCTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MASSOCTYPE" (
    "MASSOCTYPE_ID" CHAR(32 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "FIELD1" INTEGER,
    "OID" VARCHAR(64 OCTETS),
    "FIELD2" DECIMAL(20, 5),
    "FIELD3" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MASSOCTYPE"
ALTER TABLE "DB2ADMIN"."MASSOCTYPE"
ADD PRIMARY KEY ("MASSOCTYPE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MBINFO"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MBINFO" (
    "MBRFNBR" INTEGER NOT NULL,
    "MBBURFNBR" INTEGER NOT NULL,
    "MBMERFNBR" INTEGER NOT NULL,
    "MBSGRFNBR" INTEGER,
    "MBSGTYPE" CHAR(2 OCTETS),
    "MBFIELD1" VARCHAR(30 OCTETS),
    "MBFIELD2" VARCHAR(30 OCTETS),
    "MBFIELD3" VARCHAR(30 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MBINFO"
ALTER TABLE "DB2ADMIN"."MBINFO"
ADD PRIMARY KEY ("MBRFNBR");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBINFO"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000150" ON "DB2ADMIN"."MBINFO" (
    "MBMERFNBR" ASC,
    "MBBURFNBR" ASC,
    "MBSGRFNBR" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBINFO"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000613" ON "DB2ADMIN"."MBINFO" ("MBBURFNBR" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MBRATTR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MBRATTR" (
    "MBRATTR_ID" BIGINT NOT NULL,
    "ATTRTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MBRATTR"
ALTER TABLE "DB2ADMIN"."MBRATTR"
ADD PRIMARY KEY ("MBRATTR_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRATTR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000151" ON "DB2ADMIN"."MBRATTR" ("NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MBRATTRVAL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MBRATTRVAL" (
    "MBRATTRVAL_ID" BIGINT NOT NULL,
    "STOREENT_ID" INTEGER,
    "MEMBER_ID" BIGINT NOT NULL,
    "ATTRTYPE_ID" CHAR(16 OCTETS) NOT NULL,
    "MBRATTR_ID" BIGINT NOT NULL,
    "FLOATVALUE" DOUBLE,
    "INTEGERVALUE" INTEGER,
    "STRINGVALUE" VARCHAR(4000 OCTETS),
    "DATETIMEVALUE" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MBRATTRVAL"
ALTER TABLE "DB2ADMIN"."MBRATTRVAL"
ADD PRIMARY KEY ("MBRATTRVAL_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRATTRVAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000326" ON "DB2ADMIN"."MBRATTRVAL" ("MEMBER_ID" ASC, "MBRATTR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRATTRVAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000327" ON "DB2ADMIN"."MBRATTRVAL" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRATTRVAL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000614" ON "DB2ADMIN"."MBRATTRVAL" ("MBRATTR_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MBRGRP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MBRGRP" (
    "MBRGRP_ID" BIGINT NOT NULL,
    "OWNER_ID" BIGINT NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "DESCRIPTION" VARCHAR(512 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "DN" VARCHAR(1000 OCTETS),
    "MBRGRPNAME" VARCHAR(254 OCTETS) NOT NULL,
    "FIELD3" VARCHAR(254 OCTETS),
    "OID" VARCHAR(64 OCTETS),
    "LASTUPDATE" TIMESTAMP,
    "LASTUPDATEDBY" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT,
    "UP_MBRGRPNAME" VARCHAR(254 OCTETS) GENERATED ALWAYS AS (UPPER(MBRGRPNAME)),
    "ALLOWEXPORT" SMALLINT NOT NULL WITH DEFAULT 0,
    "EXPORTALL" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MBRGRP"
ALTER TABLE "DB2ADMIN"."MBRGRP"
ADD PRIMARY KEY ("MBRGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000152" ON "DB2ADMIN"."MBRGRP" ("OWNER_ID" ASC, "MBRGRPNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRGRP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."IPF00009" ON "DB2ADMIN"."MBRGRP" ("UP_MBRGRPNAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MBRGRPCOND"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MBRGRPCOND" (
    "MBRGRP_ID" BIGINT NOT NULL,
    "CONDITIONS" CLOB(1048576 OCTETS) LOGGED NOT COMPACT,
    "FIELD1" VARCHAR(254 OCTETS),
    "FIELD2" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MBRGRPCOND"
ALTER TABLE "DB2ADMIN"."MBRGRPCOND"
ADD PRIMARY KEY ("MBRGRP_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MBRGRPDESC"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MBRGRPDESC" (
    "MBRGRP_ID" BIGINT NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DISPLAYNAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(4000 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MBRGRPDESC"
ALTER TABLE "DB2ADMIN"."MBRGRPDESC"
ADD PRIMARY KEY ("MBRGRP_ID", "LANGUAGE_ID");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MBRGRPMBR"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MBRGRPMBR" (
    "MEMBER_ID" BIGINT NOT NULL,
    "MBRGRP_ID" BIGINT NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "CUSTOMERID" VARCHAR(30 OCTETS),
    "EXCLUDE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT '0',
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MBRGRPMBR"
ALTER TABLE "DB2ADMIN"."MBRGRPMBR"
ADD PRIMARY KEY ("MEMBER_ID", "MBRGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRGRPMBR"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000615" ON "DB2ADMIN"."MBRGRPMBR" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MBRGRPTYPE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MBRGRPTYPE" (
    "MBRGRPTYPE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "PROPERTIES" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MBRGRPTYPE"
ALTER TABLE "DB2ADMIN"."MBRGRPTYPE"
ADD PRIMARY KEY ("MBRGRPTYPE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRGRPTYPE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000153" ON "DB2ADMIN"."MBRGRPTYPE" ("NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MBRGRPUSG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MBRGRPUSG" (
    "MBRGRPTYPE_ID" INTEGER NOT NULL,
    "MBRGRP_ID" BIGINT NOT NULL,
    "FIELD1" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MBRGRPUSG"
ALTER TABLE "DB2ADMIN"."MBRGRPUSG"
ADD PRIMARY KEY ("MBRGRPTYPE_ID", "MBRGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRGRPUSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000616" ON "DB2ADMIN"."MBRGRPUSG" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MBRREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MBRREL" (
    "DESCENDANT_ID" BIGINT NOT NULL,
    "ANCESTOR_ID" BIGINT NOT NULL,
    "SEQUENCE" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MBRREL"
ALTER TABLE "DB2ADMIN"."MBRREL"
ADD PRIMARY KEY ("DESCENDANT_ID", "ANCESTOR_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000328" ON "DB2ADMIN"."MBRREL" ("DESCENDANT_ID" ASC, "SEQUENCE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000336" ON "DB2ADMIN"."MBRREL" ("ANCESTOR_ID" ASC, "SEQUENCE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MBRROLE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MBRROLE" (
    "MEMBER_ID" BIGINT NOT NULL,
    "ROLE_ID" INTEGER NOT NULL,
    "ORGENTITY_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MBRROLE"
ALTER TABLE "DB2ADMIN"."MBRROLE"
ADD PRIMARY KEY ("MEMBER_ID", "ROLE_ID", "ORGENTITY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRROLE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000275" ON "DB2ADMIN"."MBRROLE" ("MEMBER_ID" ASC, "ORGENTITY_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRROLE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000329" ON "DB2ADMIN"."MBRROLE" ("ORGENTITY_ID" ASC, "ROLE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRROLE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000617" ON "DB2ADMIN"."MBRROLE" ("ROLE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MBRVIEWPRF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MBRVIEWPRF" (
    "MEMBER_ID" BIGINT NOT NULL,
    "VIEWNAME" VARCHAR(254 OCTETS) NOT NULL,
    "PREFERENCE" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MBRVIEWPRF"
ALTER TABLE "DB2ADMIN"."MBRVIEWPRF"
ADD PRIMARY KEY ("MEMBER_ID", "VIEWNAME");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MBRVIEWPRF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001261" ON "DB2ADMIN"."MBRVIEWPRF" ("PREFERENCE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MEMBER"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MEMBER" (
    "MEMBER_ID" BIGINT NOT NULL,
    "TYPE" CHAR(3 OCTETS) NOT NULL,
    "STATE" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MEMBER"
ALTER TABLE "DB2ADMIN"."MEMBER"
ADD PRIMARY KEY ("MEMBER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MEMBER"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I274130" ON "DB2ADMIN"."MEMBER" ("MEMBER_ID" ASC, "TYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MEMBRAUCT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MEMBRAUCT" (
    "AUCT_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "RELATIONTYPE" CHAR(10 OCTETS) NOT NULL,
    "STATUS" CHAR(4 OCTETS),
    "COMMENTS" VARCHAR(254 OCTETS),
    "FIELD1" BIGINT,
    "FIELD2" BIGINT,
    "FIELD3" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MEMBRAUCT"
ALTER TABLE "DB2ADMIN"."MEMBRAUCT"
ADD PRIMARY KEY ("AUCT_ID", "MEMBER_ID", "RELATIONTYPE");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MEMBRAUCT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000154" ON "DB2ADMIN"."MEMBRAUCT" ("RELATIONTYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MEMBRAUCT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000155" ON "DB2ADMIN"."MEMBRAUCT" ("STATUS" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MEMBRAUCT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000618" ON "DB2ADMIN"."MEMBRAUCT" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MERCHANT"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MERCHANT" (
    "MERCHANT_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(250 OCTETS) NOT NULL,
    "STATE" SMALLINT WITH DEFAULT 1,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(250 OCTETS),
    "FIELD3" VARCHAR(250 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MERCHANT"
ALTER TABLE "DB2ADMIN"."MERCHANT"
ADD PRIMARY KEY ("MERCHANT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MERCHANT"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001262" ON "DB2ADMIN"."MERCHANT" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MERCHCONF"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MERCHCONF" (
    "MERCHCONF_ID" BIGINT NOT NULL,
    "MERCHANT_ID" BIGINT NOT NULL,
    "PAYMENTSYSTEM" VARCHAR(64 OCTETS) NOT NULL,
    "PAYCONFGRP" VARCHAR(64 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0,
    "FIELD1" INTEGER,
    "FIELD2" VARCHAR(250 OCTETS),
    "FIELD3" VARCHAR(250 OCTETS)
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MERCHCONF"
ALTER TABLE "DB2ADMIN"."MERCHCONF"
ADD PRIMARY KEY ("MERCHCONF_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MERCHCONF"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000972" ON "DB2ADMIN"."MERCHCONF" (
    "MERCHANT_ID" ASC,
    "PAYMENTSYSTEM" ASC,
    "PAYCONFGRP" ASC
) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MERCHCONFINFO"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MERCHCONFINFO" (
    "MERCHCONFINFO_ID" BIGINT NOT NULL,
    "MERCHCONF_ID" BIGINT NOT NULL,
    "PROPERTY_NAME" VARCHAR(64 OCTETS) NOT NULL,
    "PROPERTY_VALUE" VARCHAR(4000 OCTETS) NOT NULL,
    "ENCRYPTED" SMALLINT NOT NULL WITH DEFAULT 1,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "TAB8K" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MERCHCONFINFO"
ALTER TABLE "DB2ADMIN"."MERCHCONFINFO"
ADD PRIMARY KEY ("MERCHCONFINFO_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MERCHCONFINFO"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000973" ON "DB2ADMIN"."MERCHCONFINFO" ("MERCHCONF_ID" ASC, "PROPERTY_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MERPROFILE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MERPROFILE" (
    "MPMRFNBR" INTEGER NOT NULL,
    "MPCUR" CHAR(10 OCTETS),
    "MPVERSION" CHAR(10 OCTETS),
    "MPENABLE" CHAR(1 OCTETS),
    "MPCSTMP" TIMESTAMP,
    "MPANIVSTMP" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MERPROFILE"
ALTER TABLE "DB2ADMIN"."MERPROFILE"
ADD PRIMARY KEY ("MPMRFNBR");
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MESSAGE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MESSAGE" (
    "MESSAGE_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "MSGTYPE" INTEGER,
    "SUBJECT" VARCHAR(254 OCTETS),
    "POSTTIME" TIMESTAMP,
    "CONTENT" CLOB(1000000 OCTETS) LOGGED NOT COMPACT,
    "MSGPARAM1" VARCHAR(254 OCTETS),
    "MSGPARAM2" VARCHAR(254 OCTETS),
    "MSGPARAM3" VARCHAR(254 OCTETS),
    "DELAY" TIMESTAMP,
    "BASE" TIMESTAMP,
    "TARGET_ID" BIGINT,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MESSAGE"
ALTER TABLE "DB2ADMIN"."MESSAGE"
ADD PRIMARY KEY ("MESSAGE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MESSAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000156" ON "DB2ADMIN"."MESSAGE" ("MSGTYPE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MESSAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000157" ON "DB2ADMIN"."MESSAGE" ("DELAY" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MESSAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000158" ON "DB2ADMIN"."MESSAGE" ("BASE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MESSAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000159" ON "DB2ADMIN"."MESSAGE" ("TARGET_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MESSAGE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000619" ON "DB2ADMIN"."MESSAGE" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MGPCONDELE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MGPCONDELE" (
    "MGPCONDELE_ID" BIGINT NOT NULL,
    "MBRGRP_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(64 OCTETS) NOT NULL,
    "TYPE" VARCHAR(64 OCTETS) NOT NULL,
    "PARENT" VARCHAR(64 OCTETS),
    "SEQUENCE" DOUBLE,
    "VARIABLE" VARCHAR(254 OCTETS),
    "OPERATOR" VARCHAR(16 OCTETS),
    "VALUE" VARCHAR(254 OCTETS),
    "CONDNAME" VARCHAR(254 OCTETS),
    "NEGATE" SMALLINT NOT NULL WITH DEFAULT 0,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MGPCONDELE"
ALTER TABLE "DB2ADMIN"."MGPCONDELE"
ADD PRIMARY KEY ("MGPCONDELE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MGPCONDELE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0001230" ON "DB2ADMIN"."MGPCONDELE" ("NAME" ASC, "MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MGPCONDELE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001231" ON "DB2ADMIN"."MGPCONDELE" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MGPCONDELENVP"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MGPCONDELENVP" (
    "MGPCONDELENVP_ID" BIGINT NOT NULL,
    "MGPCONDELE_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "VALUE" VARCHAR(254 OCTETS) NOT NULL,
    "OPTCOUNTER" SMALLINT NOT NULL WITH DEFAULT 0
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MGPCONDELENVP"
ALTER TABLE "DB2ADMIN"."MGPCONDELENVP"
ADD PRIMARY KEY ("MGPCONDELENVP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MGPCONDELENVP"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001232" ON "DB2ADMIN"."MGPCONDELENVP" ("MGPCONDELE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MGPTRDPSCN"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MGPTRDPSCN" (
    "MBRGRP_ID" BIGINT NOT NULL,
    "TRADEPOSCN_ID" BIGINT NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MGPTRDPSCN"
ALTER TABLE "DB2ADMIN"."MGPTRDPSCN"
ADD PRIMARY KEY ("TRADEPOSCN_ID", "MBRGRP_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MGPTRDPSCN"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000620" ON "DB2ADMIN"."MGPTRDPSCN" ("MBRGRP_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MLTIME"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MLTIME" (
    "INSTANCEID" BIGINT,
    "MLTIMESTAMP" TIMESTAMP,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MOPICONFIG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MOPICONFIG" (
    "STORE_ID" INTEGER NOT NULL,
    "PAY_INFO_NAME" CHAR(64 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MOPICONFIG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000160" ON "DB2ADMIN"."MOPICONFIG" ("PAY_INFO_NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MOPICONFIG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000621" ON "DB2ADMIN"."MOPICONFIG" ("STORE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MSGARCHIVE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MSGARCHIVE" (
    "TRANSPORT_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "MSGARCHIVE_ID" BIGINT NOT NULL,
    "MESSAGEINDEX" INTEGER NOT NULL,
    "MESSAGE" BLOB(1000000) LOGGED NOT COMPACT,
    "OPTCOUNTER" SMALLINT,
    "MSGLASTUPDATE" TIMESTAMP
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MSGARCHIVE"
ALTER TABLE "DB2ADMIN"."MSGARCHIVE"
ADD PRIMARY KEY (
        "MSGARCHIVE_ID",
        "MESSAGEINDEX",
        "TRANSPORT_ID"
    );
-- DDL Statements for Indexes on Table "DB2ADMIN"."MSGARCHIVE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000622" ON "DB2ADMIN"."MSGARCHIVE" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MSGARCHIVE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0001557" ON "DB2ADMIN"."MSGARCHIVE" ("MSGLASTUPDATE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MSGMEMREL"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MSGMEMREL" (
    "MESSAGE_ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "STATUS" CHAR(4 OCTETS) NOT NULL,
    "SENDSTAT" CHAR(4 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MSGMEMREL"
ALTER TABLE "DB2ADMIN"."MSGMEMREL"
ADD PRIMARY KEY ("MESSAGE_ID", "MEMBER_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MSGMEMREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000161" ON "DB2ADMIN"."MSGMEMREL" ("STATUS" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MSGMEMREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000162" ON "DB2ADMIN"."MSGMEMREL" ("SENDSTAT" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."MSGMEMREL"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000623" ON "DB2ADMIN"."MSGMEMREL" ("MEMBER_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MSGSTORE"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MSGSTORE" (
    "MSGID" BIGINT NOT NULL,
    "MESSAGEINDEX" INTEGER NOT NULL,
    "MESSAGE" BLOB(1000000) LOGGED NOT COMPACT,
    "RETRIES" INTEGER,
    "EXPIRY" TIMESTAMP,
    "TRANSPORT_ID" INTEGER NOT NULL,
    "STOREENT_ID" INTEGER NOT NULL,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MSGSTORE"
ALTER TABLE "DB2ADMIN"."MSGSTORE"
ADD PRIMARY KEY ("MSGID", "MESSAGEINDEX", "TRANSPORT_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MSGSTORE"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000624" ON "DB2ADMIN"."MSGSTORE" ("STOREENT_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."MSGTYPES"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."MSGTYPES" (
    "MSGTYPE_ID" INTEGER NOT NULL,
    "MSGTDIR" INTEGER NOT NULL,
    "NAME" VARCHAR(254 OCTETS) NOT NULL,
    "VIEWNAME" VARCHAR(254 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."MSGTYPES"
ALTER TABLE "DB2ADMIN"."MSGTYPES"
ADD PRIMARY KEY ("MSGTYPE_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."MSGTYPES"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000163" ON "DB2ADMIN"."MSGTYPES" ("NAME" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."NOTIFY"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."NOTIFY" (
    "NOTIFY_ID" BIGINT NOT NULL,
    "NOTIFICATIONID" BIGINT,
    "TRANSPORTATTNAME" VARCHAR(254 OCTETS),
    "TRANSPORTATTVALUE" VARCHAR(254 OCTETS),
    "TRANSPORT_ID" INTEGER,
    "MSGTYPE_ID" INTEGER,
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."NOTIFY"
ALTER TABLE "DB2ADMIN"."NOTIFY"
ADD PRIMARY KEY ("NOTIFY_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."NOTIFY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000307" ON "DB2ADMIN"."NOTIFY" ("NOTIFICATIONID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Indexes on Table "DB2ADMIN"."NOTIFY"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE INDEX "DB2ADMIN"."I0000625" ON "DB2ADMIN"."NOTIFY" ("MSGTYPE_ID" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."NSLOG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."NSLOG" (
    "NLRECID" INTEGER NOT NULL,
    "NLDATE" TIMESTAMP,
    "NLRECCLASS" INTEGER,
    "NLMSGID" INTEGER,
    "NLLOC" INTEGER,
    "NLDATA" VARCHAR(1024 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."NUMBRUSG"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."NUMBRUSG" (
    "NUMBRUSG_ID" INTEGER NOT NULL,
    "CODE" CHAR(60 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."NUMBRUSG"
ALTER TABLE "DB2ADMIN"."NUMBRUSG"
ADD PRIMARY KEY ("NUMBRUSG_ID");
-- DDL Statements for Indexes on Table "DB2ADMIN"."NUMBRUSG"
SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
CREATE UNIQUE INDEX "DB2ADMIN"."I0000164" ON "DB2ADMIN"."NUMBRUSG" ("CODE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "DB2ADMIN"."NUMBRUSGDS"
------------------------------------------------
CREATE TABLE "DB2ADMIN"."NUMBRUSGDS" (
    "NUMBRUSG_ID" INTEGER NOT NULL,
    "LANGUAGE_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(254 OCTETS),
    "OPTCOUNTER" SMALLINT
) IN "USERSPACE1" ORGANIZE BY ROW;
-- DDL Statements for Primary Key on Table "DB2ADMIN"."NUMBRUSGDS"
ALTER TABLE "DB2ADMIN"."NUMBRUSGDS"
ADD PRIMARY KEY ("NUMBRUSG_ID", "LANGUAGE_ID");
---